import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 10: Container Registries ---------------- */
  {
    id: 'registries',
    level: 'intermediate',
    roots: [
      {
        id: 'docker-hub',
        title: 'Docker Hub',
        summary: 'Accounts, repositories, programs and rate limits.',
        children: [
          { id: 'docker-hub-accounts', title: 'Accounts & Organizations' },
          { id: 'docker-hub-repositories', title: 'Repositories (public & private)' },
          { id: 'docker-hub-official-images', title: 'Docker Official Images' },
          { id: 'docker-hub-verified-publisher', title: 'Verified Publisher Program' },
          { id: 'docker-hub-sponsored-oss', title: 'Docker-Sponsored OSS' },
          { id: 'automated-builds-hub', title: 'Automated Builds' },
          { id: 'docker-hub-webhooks', title: 'Webhooks' },
          { id: 'docker-hub-teams-permissions', title: 'Teams & Permissions' },
          { id: 'docker-hub-access-tokens', title: 'Personal Access Tokens (PATs)' },
          { id: 'docker-hub-org-access-tokens', title: 'Organization Access Tokens (OATs)' },
          { id: 'docker-hub-rate-limits', title: 'Pull Rate Limits' },
          { id: 'docker-hub-scout-integration', title: 'Docker Scout on Hub' },
          { id: 'docker-hub-insights', title: 'Insights & Analytics' },
        ],
      },
      {
        id: 'docker-hardened-images',
        title: 'Docker Hardened Images',
        summary: 'Hardened, minimal, signed images from Docker.',
        children: [
          { id: 'dhi-overview', title: 'DHI Overview' },
          { id: 'dhi-vs-official-images', title: 'DHI vs Official Images' },
          { id: 'dhi-base-image-strategy', title: 'Using DHI as Base Images' },
          { id: 'dhi-customization', title: 'Customizing DHI' },
          { id: 'dhi-vulnerability-policies', title: 'DHI Vulnerability SLAs' },
          { id: 'dhi-attestations', title: 'DHI Attestations' },
        ],
      },
      {
        id: 'private-registries',
        title: 'Private Registries',
        summary: 'Self-hosted registry, Harbor and cloud/Git registries (overview).',
        children: [
          {
            id: 'self-hosted-registry-image',
            title: 'Self-Hosted Registry',
            children: [
              { id: 'registry-distribution-project', title: 'distribution/distribution' },
              { id: 'registry-storage-backends', title: 'Storage Backends (filesystem, s3, azure, gcs)' },
              { id: 'registry-tls-setup', title: 'Configuring TLS' },
              { id: 'registry-htpasswd-auth', title: 'Basic htpasswd Auth' },
              { id: 'registry-token-auth', title: 'Token Authentication' },
              { id: 'registry-garbage-collection', title: 'Garbage Collection' },
              { id: 'registry-notifications', title: 'Notifications & Webhooks' },
            ],
          },
          {
            id: 'harbor-registry',
            title: 'Harbor Registry',
            children: [
              { id: 'harbor-architecture', title: 'Harbor Architecture' },
              { id: 'harbor-projects-rbac', title: 'Projects & RBAC' },
              { id: 'harbor-vulnerability-scanning', title: 'Vulnerability Scanning' },
              { id: 'harbor-replication', title: 'Replication Policies' },
              { id: 'harbor-content-trust-signing', title: 'Content Trust & Signing' },
              { id: 'harbor-retention-policies', title: 'Retention Policies' },
              { id: 'harbor-webhooks', title: 'Harbor Webhooks' },
            ],
          },
          {
            id: 'cloud-registries-overview',
            title: 'Cloud Registries (overview)',
            children: [
              { id: 'aws-ecr-overview', title: 'AWS ECR (overview)' },
              { id: 'azure-acr-overview', title: 'Azure Container Registry (overview)' },
              { id: 'gcp-artifact-registry-overview', title: 'GCP Artifact Registry (overview)' },
              { id: 'oracle-cloud-registry-overview', title: 'Oracle Cloud Registry (overview)' },
              { id: 'ibm-cloud-registry-overview', title: 'IBM Cloud Container Registry (overview)' },
            ],
          },
          { id: 'github-container-registry', title: 'GitHub Container Registry (GHCR)' },
          { id: 'gitlab-container-registry', title: 'GitLab Container Registry' },
          { id: 'quay-registry', title: 'Quay.io' },
          { id: 'jfrog-artifactory-registry', title: 'JFrog Artifactory' },
          { id: 'nexus-registry', title: 'Sonatype Nexus' },
          { id: 'zot-registry', title: 'zot (OCI-native)' },
        ],
      },
      {
        id: 'registry-api',
        title: 'Registry API',
        summary: 'OCI distribution API: manifests, blobs, catalog endpoints.',
        children: [
          { id: 'registry-v2-api', title: 'Docker Registry v2 API' },
          { id: 'oci-distribution-api', title: 'OCI Distribution Spec API' },
          { id: 'manifest-endpoints', title: 'Manifest Endpoints (PUT/GET/DELETE)' },
          { id: 'blob-endpoints', title: 'Blob Endpoints (PUT/GET/DELETE)' },
          { id: 'blob-upload-session', title: 'Blob Upload Session (chunked & monolithic)' },
          { id: 'tags-listing-endpoint', title: 'Tags Listing Endpoint' },
          { id: 'catalog-endpoint', title: '_catalog Endpoint' },
          { id: 'referrers-api', title: 'Referrers API (OCI 1.1)' },
          { id: 'cross-repo-mounting', title: 'Cross-Repo Blob Mounting' },
        ],
      },
      {
        id: 'pull-through-cache',
        title: 'Pull-Through Cache',
        summary: 'Caching upstream registries in a local registry.',
        children: [
          { id: 'pull-through-cache-config', title: 'Configuring proxy.remoteurl' },
          { id: 'pull-through-cache-auth', title: 'Auth with Pull-Through Cache' },
          { id: 'pull-through-cache-tls', title: 'TLS for Pull-Through Cache' },
        ],
      },
      {
        id: 'registry-authentication',
        title: 'Registry Authentication',
        summary: 'docker login, credential helpers and tokens.',
        children: [
          { id: 'docker-login-cmd', title: 'docker login' },
          { id: 'docker-logout-cmd', title: 'docker logout' },
          {
            id: 'credential-helpers',
            title: 'Credential Helpers',
            children: [
              { id: 'docker-credential-osxkeychain', title: 'docker-credential-osxkeychain' },
              { id: 'docker-credential-wincred', title: 'docker-credential-wincred' },
              { id: 'docker-credential-secretservice', title: 'docker-credential-secretservice' },
              { id: 'docker-credential-pass', title: 'docker-credential-pass' },
              { id: 'docker-credential-ecr-login', title: 'docker-credential-ecr-login' },
              { id: 'docker-credential-acr-env', title: 'docker-credential-acr-env' },
              { id: 'docker-credential-gcr', title: 'docker-credential-gcr' },
            ],
          },
          { id: 'oauth2-tokens-registry', title: 'OAuth2 Tokens in Registries' },
          { id: 'jwt-tokens-registry', title: 'JWT Tokens in Registries' },
          { id: 'config-json-auths', title: 'config.json auths field' },
          { id: 'identity-tokens', title: 'Identity Tokens & Refresh Tokens' },
        ],
      },
      {
        id: 'registry-mirrors',
        title: 'Registry Mirrors',
        summary: 'Configuring mirrors at the daemon level.',
        children: [
          { id: 'registry-mirrors-daemon-json', title: 'registry-mirrors in daemon.json' },
          { id: 'insecure-registries', title: 'insecure-registries' },
          { id: 'allow-nondistributable-artifacts', title: 'allow-nondistributable-artifacts' },
          { id: 'mirror-failover-behavior', title: 'Mirror Failover Behavior' },
        ],
      },
    ],
  },

  /* ---------------- Stage 11: Image Security & Supply Chain ---------------- */
  {
    id: 'image-security',
    level: 'advanced',
    roots: [
      {
        id: 'docker-scout',
        title: 'Docker Scout',
        summary: 'Scout CLI, policies, recommendations and CVE analysis.',
        children: [
          {
            id: 'scout-cli',
            title: 'Scout CLI',
            children: [
              { id: 'scout-cves-cmd', title: 'docker scout cves' },
              { id: 'scout-quickview', title: 'docker scout quickview' },
              { id: 'scout-recommendations-cmd', title: 'docker scout recommendations' },
              { id: 'scout-compare-cmd', title: 'docker scout compare' },
              { id: 'scout-environment', title: 'docker scout environment' },
              { id: 'scout-policy-cmd', title: 'docker scout policy' },
              { id: 'scout-stream-cmd', title: 'docker scout stream' },
              { id: 'scout-attestation-cmd', title: 'docker scout attestation' },
              { id: 'scout-watch-cmd', title: 'docker scout watch' },
              { id: 'scout-sbom-cmd', title: 'docker scout sbom' },
              { id: 'scout-enroll-cmd', title: 'docker scout enroll' },
              { id: 'scout-config-cmd', title: 'docker scout config' },
            ],
          },
          {
            id: 'scout-policies',
            title: 'Scout Policies',
            children: [
              { id: 'scout-policy-default-rules', title: 'Default Policies' },
              { id: 'scout-policy-custom-rules', title: 'Custom Policies' },
              { id: 'scout-policy-evaluation', title: 'Policy Evaluation' },
              { id: 'scout-policy-exceptions', title: 'Policy Exceptions' },
            ],
          },
          { id: 'scout-recommendations', title: 'Scout Recommendations' },
          { id: 'scout-cves', title: 'Scout CVE Analysis' },
          { id: 'scout-comparison', title: 'Image Comparison' },
          { id: 'scout-image-streams', title: 'Image Streams & Environments' },
          { id: 'scout-vex-statements', title: 'VEX Statements' },
          { id: 'scout-integrations', title: 'Scout Integrations (GitHub/Slack/Jira/Teams)' },
          { id: 'scout-ci-integration', title: 'Scout in CI' },
        ],
      },
      {
        id: 'vulnerability-scanning',
        title: 'Vulnerability Scanning',
        summary: 'Trivy, Grype, Snyk and other scanners.',
        children: [
          { id: 'trivy-integration', title: 'Trivy' },
          { id: 'grype-integration', title: 'Grype' },
          { id: 'snyk-integration', title: 'Snyk' },
          { id: 'clair-integration', title: 'Clair' },
          { id: 'anchore-integration', title: 'Anchore Engine' },
          { id: 'vulnerability-databases', title: 'Vulnerability Databases (NVD, GHSA, OSV)' },
          { id: 'cve-severity-cvss', title: 'CVE Severity & CVSS' },
          { id: 'kev-catalog', title: 'CISA KEV Catalog' },
          { id: 'scan-fail-policies', title: 'Fail-on-Severity Policies' },
        ],
      },
      {
        id: 'sboms',
        title: 'SBOMs',
        summary: 'SBOM formats, Syft, CycloneDX and SPDX.',
        children: [
          { id: 'sbom-overview', title: 'SBOM Overview' },
          { id: 'syft-tool', title: 'Syft' },
          { id: 'cyclonedx-format', title: 'CycloneDX' },
          { id: 'spdx-format', title: 'SPDX' },
          { id: 'sbom-distribution', title: 'SBOM Distribution & Storage' },
          { id: 'sbom-referrers', title: 'SBOMs via OCI Referrers' },
          { id: 'sbom-in-builds-docker', title: 'SBOM Generation in Docker Builds' },
        ],
      },
      {
        id: 'image-signing',
        title: 'Image Signing',
        summary: 'Cosign, Notation, Notary v2 and DCT.',
        children: [
          {
            id: 'cosign-tool',
            title: 'Cosign',
            children: [
              { id: 'cosign-sign-verify', title: 'cosign sign / verify' },
              { id: 'cosign-keyless-fulcio', title: 'Keyless Signing (Fulcio/Rekor)' },
              { id: 'cosign-policies', title: 'Cosign Policies' },
              { id: 'cosign-attest', title: 'cosign attest' },
            ],
          },
          { id: 'notation-tool', title: 'Notation' },
          { id: 'notary-v2', title: 'Notary v2' },
          { id: 'docker-content-trust', title: 'Docker Content Trust (DCT)' },
          { id: 'sigstore-ecosystem', title: 'Sigstore Ecosystem (Fulcio, Rekor)' },
          { id: 'key-management-signing', title: 'Key Management for Signing' },
          { id: 'verify-signatures-runtime', title: 'Verifying Signatures at Runtime' },
        ],
      },
      {
        id: 'attestations',
        title: 'Attestations',
        summary: 'Provenance, SLSA and in-toto attestations.',
        children: [
          { id: 'provenance-attestation', title: 'Provenance Attestation' },
          { id: 'slsa-framework', title: 'SLSA Framework' },
          { id: 'slsa-build-levels', title: 'SLSA Build Levels (L1–L4)' },
          { id: 'in-toto-spec', title: 'in-toto Specification' },
          { id: 'attestation-bundles', title: 'Attestation Bundles' },
          { id: 'oci-referrers-attestations', title: 'Attestations via OCI Referrers' },
          { id: 'vex-and-attestations', title: 'VEX in Attestations' },
        ],
      },
      {
        id: 'base-image-strategy',
        title: 'Base Image Strategy',
        summary: 'Distroless, chiseled, Alpine, scratch and Wolfi base images.',
        children: [
          { id: 'distroless-images', title: 'Distroless Images' },
          { id: 'chiseled-images', title: 'Chiseled .NET Images' },
          { id: 'alpine-images', title: 'Alpine Linux Images' },
          { id: 'scratch-images', title: 'scratch Image' },
          { id: 'wolfi-os', title: 'Wolfi OS / Chainguard Images' },
          { id: 'debian-slim-images', title: 'Debian / Ubuntu slim Images' },
          { id: 'busybox-images', title: 'BusyBox Base' },
          { id: 'static-binary-images', title: 'Static Binary Images' },
          { id: 'base-image-tradeoffs', title: 'Trade-offs (size, glibc/musl, libc, debug)' },
        ],
      },
      {
        id: 'secret-management',
        title: 'Secret Management',
        summary: 'Build-time and runtime secrets and external secret stores.',
        children: [
          { id: 'build-time-secrets', title: 'Build-Time Secrets (--secret)' },
          { id: 'runtime-secrets-files', title: 'Runtime Secrets via Files' },
          { id: 'runtime-secrets-env', title: 'Runtime Secrets via Env (avoid)' },
          {
            id: 'external-secret-stores',
            title: 'External Secret Stores',
            children: [
              { id: 'vault-integration', title: 'HashiCorp Vault' },
              { id: 'aws-secrets-manager-overview', title: 'AWS Secrets Manager (overview)' },
              { id: 'azure-key-vault-overview', title: 'Azure Key Vault (overview)' },
              { id: 'gcp-secret-manager-overview', title: 'GCP Secret Manager (overview)' },
              { id: 'sops-secrets', title: 'SOPS / age' },
            ],
          },
          { id: 'secret-rotation-patterns', title: 'Secret Rotation Patterns' },
          { id: 'avoiding-secret-anti-patterns', title: 'Anti-Patterns to Avoid' },
        ],
      },
    ],
  },

  /* ---------------- Stage 12: Container Runtime Internals ---------------- */
  {
    id: 'runtime-internals',
    level: 'advanced',
    roots: [
      {
        id: 'containerd',
        title: 'containerd',
        summary: 'Architecture, namespaces, ctr CLI and plugins.',
        children: [
          {
            id: 'containerd-architecture',
            title: 'containerd Architecture',
            children: [
              { id: 'containerd-grpc-api', title: 'containerd gRPC API' },
              { id: 'containerd-content-store', title: 'Content Store' },
              { id: 'containerd-metadata-store', title: 'Metadata Store (boltdb)' },
              { id: 'containerd-task-service', title: 'Task Service' },
              { id: 'containerd-image-service', title: 'Image Service' },
            ],
          },
          { id: 'containerd-namespaces', title: 'containerd Namespaces' },
          {
            id: 'ctr-cli',
            title: 'ctr CLI',
            children: [
              { id: 'ctr-images', title: 'ctr images' },
              { id: 'ctr-containers', title: 'ctr containers' },
              { id: 'ctr-tasks', title: 'ctr tasks' },
              { id: 'ctr-snapshots', title: 'ctr snapshots' },
              { id: 'ctr-content', title: 'ctr content' },
              { id: 'ctr-plugins', title: 'ctr plugins' },
              { id: 'ctr-events', title: 'ctr events' },
            ],
          },
          {
            id: 'containerd-plugins',
            title: 'containerd Plugins',
            children: [
              { id: 'containerd-builtin-plugins', title: 'Built-in Plugins' },
              { id: 'containerd-external-plugins', title: 'External Plugins' },
              { id: 'containerd-cri-plugin', title: 'CRI Plugin' },
              { id: 'containerd-snapshotter-plugin', title: 'Snapshotter Plugins' },
              { id: 'containerd-runtime-plugin', title: 'Runtime Plugins' },
            ],
          },
          { id: 'containerd-config-toml', title: 'config.toml' },
          { id: 'containerd-vs-dockerd', title: 'containerd vs dockerd (history)' },
          { id: 'nerdctl-containerd', title: 'nerdctl (Docker-compatible CLI for containerd)' },
        ],
      },
      {
        id: 'runc-internals',
        title: 'runc Internals',
        summary: 'runc config.json and libcontainer.',
        children: [
          {
            id: 'runc-config-json',
            title: 'config.json (OCI Runtime Spec)',
            children: [
              { id: 'config-process', title: 'process' },
              { id: 'config-root', title: 'root' },
              { id: 'config-mounts', title: 'mounts' },
              { id: 'config-hooks', title: 'hooks' },
              { id: 'config-linux', title: 'linux (namespaces, devices, cgroups)' },
              { id: 'config-windows', title: 'windows' },
              { id: 'config-vm', title: 'vm' },
              { id: 'config-annotations', title: 'annotations' },
            ],
          },
          { id: 'libcontainer-library', title: 'libcontainer' },
          { id: 'runc-create-start-flow', title: 'runc create / start Flow' },
          { id: 'runc-cgroup-driver', title: 'cgroup Driver (cgroupfs vs systemd)' },
        ],
      },
      {
        id: 'alternate-runtimes',
        title: 'Alternate Runtimes',
        summary: 'crun, youki, Kata, gVisor, Firecracker and runwasi.',
        children: [
          { id: 'crun-runtime', title: 'crun (C-based, OCI)' },
          { id: 'youki-runtime', title: 'youki (Rust, OCI)' },
          { id: 'kata-containers', title: 'Kata Containers (lightweight VMs)' },
          { id: 'gvisor-runsc', title: 'gVisor (runsc, user-space kernel)' },
          { id: 'firecracker', title: 'Firecracker microVMs' },
          { id: 'containerd-runwasi', title: 'containerd runwasi' },
          { id: 'sysbox-runtime', title: 'Sysbox' },
          { id: 'choosing-a-runtime', title: 'Choosing a Runtime' },
        ],
      },
      {
        id: 'snapshotters',
        title: 'Snapshotters',
        summary: 'overlayfs, native, btrfs, stargz and nydus snapshotters.',
        children: [
          { id: 'overlayfs-snapshotter', title: 'overlayfs Snapshotter' },
          { id: 'native-snapshotter', title: 'native Snapshotter' },
          { id: 'btrfs-snapshotter', title: 'btrfs Snapshotter' },
          { id: 'devmapper-snapshotter', title: 'devmapper Snapshotter' },
          { id: 'stargz-snapshotter', title: 'stargz Snapshotter (lazy pull)' },
          { id: 'nydus-snapshotter', title: 'nydus Snapshotter' },
          { id: 'fuse-overlayfs-snapshotter', title: 'fuse-overlayfs Snapshotter' },
          { id: 'snapshotter-comparison', title: 'Snapshotter Comparison' },
        ],
      },
      {
        id: 'shims',
        title: 'Shims',
        summary: 'Shim protocol and shim runtimes.',
        children: [
          { id: 'shim-protocol-v2', title: 'Shim Protocol v2' },
          { id: 'containerd-shim-runc', title: 'containerd-shim-runc-v2' },
          { id: 'shim-binary-naming', title: 'Shim Binary Naming Convention' },
          { id: 'shim-runtimes-list', title: 'Common Shim Runtimes' },
        ],
      },
      {
        id: 'wasm-containers',
        title: 'WASM Containers',
        summary: 'Running WebAssembly workloads as containers.',
        children: [
          { id: 'wasm-overview', title: 'WASM Overview' },
          { id: 'wasi-overview', title: 'WASI Overview' },
          {
            id: 'wasm-runtimes-list',
            title: 'WASM Runtimes',
            children: [
              { id: 'wasmtime-runtime', title: 'wasmtime' },
              { id: 'wasmedge-runtime', title: 'WasmEdge' },
              { id: 'wasmer-runtime', title: 'wasmer' },
              { id: 'spin-runtime', title: 'Fermyon Spin' },
            ],
          },
          { id: 'runwasi-integration', title: 'runwasi Integration' },
          { id: 'wasm-in-docker-desktop', title: 'WASM in Docker Desktop' },
          { id: 'building-wasm-images', title: 'Building WASM Images' },
          { id: 'wasm-vs-containers-tradeoffs', title: 'WASM vs Containers Trade-offs' },
        ],
      },
      {
        id: 'gpu-runtimes',
        title: 'GPU Runtimes',
        summary: 'NVIDIA Container Toolkit and AMD ROCm in containers.',
        children: [
          {
            id: 'nvidia-container-toolkit',
            title: 'NVIDIA Container Toolkit',
            children: [
              { id: 'nvidia-runtime-hook', title: 'NVIDIA Runtime Hook' },
              { id: 'cdi-spec-nvidia', title: 'CDI Spec' },
              { id: 'cuda-base-images', title: 'CUDA Base Images (overview)' },
              { id: 'nvidia-gpus-flag', title: '--gpus all / specific GPUs' },
            ],
          },
          { id: 'amd-rocm-containers', title: 'AMD ROCm Containers' },
          { id: 'intel-gpu-containers', title: 'Intel GPU Containers' },
          { id: 'gpu-sharing-mig', title: 'GPU Sharing & MIG' },
        ],
      },
      {
        id: 'confidential-containers',
        title: 'Confidential Containers',
        summary: 'Confidential computing and trusted execution for containers.',
        children: [
          { id: 'confidential-computing-overview', title: 'Confidential Computing Overview' },
          { id: 'tee-technologies', title: 'TEE Technologies (SGX, SEV-SNP, TDX)' },
          { id: 'kata-cc-runtime', title: 'Kata Confidential Containers' },
          { id: 'enarx', title: 'Enarx' },
          { id: 'remote-attestation', title: 'Remote Attestation' },
        ],
      },
    ],
  },
])
