import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 16: CI/CD with Docker ---------------- */
  {
    id: 'ci-cd',
    level: 'intermediate',
    roots: [
      {
        id: 'docker-in-ci',
        title: 'Docker in CI',
        summary: 'Building, pushing and testing images in CI pipelines.',
        children: [
          {
            id: 'docker-in-ci-runtimes',
            title: 'CI Runtime Options for Docker',
            children: [
              { id: 'dind-docker-in-docker', title: 'Docker-in-Docker (dind)' },
              { id: 'dood-docker-out-of-docker', title: 'Docker-out-of-Docker (dood)' },
              { id: 'kaniko-builder', title: 'Kaniko' },
              { id: 'buildah-builder', title: 'Buildah in CI' },
              { id: 'img-builder', title: 'img (rootless)' },
              { id: 'remote-buildx-builder-ci', title: 'Remote buildx Builder' },
            ],
          },
          { id: 'building-images-in-ci', title: 'Building Images in CI' },
          { id: 'pushing-images-in-ci', title: 'Pushing Images in CI' },
          { id: 'testing-with-containers-ci', title: 'Testing with Containers (services)' },
          { id: 'rate-limit-handling-ci', title: 'Handling Docker Hub Rate Limits' },
          { id: 'concurrency-and-ephemeral-builders', title: 'Concurrency & Ephemeral Builders' },
        ],
      },
      {
        id: 'github-actions-docker',
        title: 'GitHub Actions',
        summary: 'Buildx and build-push actions, matrix builds and GHA cache.',
        children: [
          {
            id: 'gha-official-actions',
            title: 'Official Docker Actions',
            children: [
              { id: 'gha-setup-buildx-action', title: 'docker/setup-buildx-action' },
              { id: 'gha-setup-qemu-action', title: 'docker/setup-qemu-action' },
              { id: 'gha-build-push-action', title: 'docker/build-push-action' },
              { id: 'gha-bake-action', title: 'docker/bake-action' },
              { id: 'gha-login-action', title: 'docker/login-action' },
              { id: 'gha-metadata-action', title: 'docker/metadata-action' },
              { id: 'gha-scout-action', title: 'docker/scout-action' },
            ],
          },
          { id: 'gha-matrix-builds', title: 'Matrix Builds' },
          { id: 'gha-cache-backend', title: 'GitHub Actions Cache Backend (type=gha)' },
          { id: 'gha-secrets-tokens', title: 'Secrets & OIDC Tokens' },
          { id: 'gha-reusable-workflows', title: 'Reusable Workflows for Docker' },
          { id: 'gha-tag-conventions', title: 'Tag & Version Conventions' },
          { id: 'gha-attestations', title: 'Attestations from GitHub Actions' },
        ],
      },
      {
        id: 'gitlab-ci-docker',
        title: 'GitLab CI',
        summary: 'Docker-in-Docker, Kaniko and other GitLab patterns.',
        children: [
          { id: 'gitlab-dind-service', title: 'dind Service' },
          { id: 'gitlab-shell-executor-docker', title: 'Shell Executor + Docker' },
          { id: 'gitlab-docker-executor', title: 'Docker Executor' },
          { id: 'gitlab-kaniko-pattern', title: 'Kaniko Pattern' },
          { id: 'gitlab-buildkit-pattern', title: 'BuildKit Pattern' },
          { id: 'gitlab-container-registry-integration', title: 'GitLab Container Registry Integration' },
          { id: 'gitlab-ci-cache-images', title: 'CI Cache for Images' },
          { id: 'gitlab-scanning-integration', title: 'Built-in Scanning Integration' },
        ],
      },
      {
        id: 'jenkins-docker',
        title: 'Jenkins',
        summary: 'Jenkins Docker pipelines.',
        children: [
          { id: 'jenkins-docker-pipeline-plugin', title: 'Docker Pipeline Plugin' },
          { id: 'jenkins-docker-agent', title: 'docker.image().inside { }' },
          { id: 'jenkins-docker-build-push', title: 'Building & Pushing Images' },
          { id: 'jenkins-dind-vs-dood', title: 'dind vs dood for Jenkins' },
          { id: 'jenkins-kaniko-pattern', title: 'Kaniko Pattern' },
          { id: 'jenkins-credentials-for-registries', title: 'Credentials for Registries' },
        ],
      },
      {
        id: 'ci-cache-strategies',
        title: 'CI Cache Strategies',
        summary: 'Inline, registry, GHA and S3 cache strategies.',
        children: [
          { id: 'ci-inline-cache-strategy', title: 'Inline Cache Strategy' },
          { id: 'ci-registry-cache-strategy', title: 'Registry Cache Strategy' },
          { id: 'ci-gha-cache-strategy', title: 'GHA Cache Strategy' },
          { id: 'ci-s3-cache-strategy', title: 'S3 Cache Strategy' },
          { id: 'ci-azblob-cache-strategy', title: 'Azure Blob Cache Strategy' },
          { id: 'ci-local-cache-strategy', title: 'Local Cache Strategy' },
          { id: 'ci-cache-warming-jobs', title: 'Cache Warming Jobs' },
          { id: 'ci-cache-invalidation', title: 'Cache Invalidation' },
        ],
      },
      {
        id: 'multi-platform-ci-builds',
        title: 'Multi-Platform CI Builds',
        summary: 'Cross-arch builds and emulation in CI.',
        children: [
          { id: 'mp-ci-qemu-setup', title: 'QEMU Setup in CI' },
          { id: 'mp-ci-native-runners', title: 'Native Runners per Platform' },
          { id: 'mp-ci-multi-job-merge', title: 'Multi-Job + Manifest Merge' },
          { id: 'mp-ci-buildx-bake', title: 'Multi-Platform Bake in CI' },
          { id: 'mp-ci-build-cloud-integration', title: 'Build Cloud in CI' },
        ],
      },
      {
        id: 'image-promotion',
        title: 'Image Promotion',
        summary: 'Promoting images across environments and registries.',
        children: [
          { id: 'tag-promotion-strategies', title: 'Tag Promotion Strategies' },
          { id: 'digest-based-promotion', title: 'Digest-Based Promotion' },
          { id: 'registry-promotion', title: 'Registry-to-Registry Promotion' },
          { id: 'staging-production-promotion', title: 'Staging → Production Pipelines' },
          { id: 'promotion-with-attestations', title: 'Promoting with Attestations & Signatures' },
          { id: 'crane-skopeo-promotion', title: 'crane / skopeo for Promotion' },
        ],
      },
      {
        id: 'automated-scanning',
        title: 'Automated Scanning',
        summary: 'Integrating SBOM, scanning and signing into pipelines.',
        children: [
          { id: 'ci-scout-scanning', title: 'Docker Scout in CI' },
          { id: 'ci-trivy-scanning', title: 'Trivy in CI' },
          { id: 'ci-grype-scanning', title: 'Grype in CI' },
          { id: 'ci-snyk-scanning', title: 'Snyk in CI' },
          { id: 'ci-sbom-generation', title: 'SBOM Generation in CI' },
          { id: 'ci-signing-pipelines', title: 'Signing in Pipelines (Cosign/Notation)' },
          { id: 'ci-policy-gates', title: 'Policy Gates' },
          { id: 'ci-fail-on-severity', title: 'Fail-on-Severity Configuration' },
        ],
      },
      {
        id: 'release-strategies',
        title: 'Release Strategies',
        summary: 'Semantic tagging, immutable tags and channels.',
        children: [
          { id: 'semantic-versioning-images', title: 'Semantic Versioning Images' },
          { id: 'immutable-tags-ci', title: 'Immutable Tags in CI' },
          { id: 'release-channels', title: 'Release Channels (latest, edge, lts)' },
          { id: 'auto-versioned-builds', title: 'Auto-Versioned Builds (commit SHA, date)' },
          { id: 'pre-release-tags', title: 'Pre-release Tags (rc, beta, alpha)' },
          { id: 'release-notes-images', title: 'Release Notes & OCI Annotations' },
        ],
      },
    ],
  },

  /* ---------------- Stage 17: Observability & Operations ---------------- */
  {
    id: 'observability',
    level: 'intermediate',
    roots: [
      {
        id: 'container-logs',
        title: 'Container Logs',
        summary: 'stdout/stderr conventions, docker logs and log rotation.',
        children: [
          { id: 'stdout-stderr-conventions', title: 'stdout / stderr Conventions' },
          { id: 'docker-logs-cli-deep', title: 'docker logs Deep Dive' },
          { id: 'log-rotation-conf', title: 'Log Rotation Configuration' },
          { id: 'log-tail-follow-since', title: 'tail / follow / since / until' },
          { id: 'multiline-logs-handling', title: 'Multi-line Log Handling' },
          { id: 'structured-logs-json', title: 'Structured Logs (JSON)' },
          { id: 'log-redaction-best-practices', title: 'Redaction Best Practices' },
        ],
      },
      {
        id: 'log-drivers',
        title: 'Log Drivers',
        summary: 'json-file, local, journald, syslog, fluentd, gelf and cloud drivers.',
        children: [
          {
            id: 'json-file-driver',
            title: 'json-file',
            children: [
              { id: 'json-file-max-size', title: 'max-size' },
              { id: 'json-file-max-file', title: 'max-file' },
              { id: 'json-file-compress', title: 'compress' },
              { id: 'json-file-labels-env', title: 'labels / env' },
            ],
          },
          { id: 'local-log-driver', title: 'local' },
          { id: 'journald-driver', title: 'journald' },
          { id: 'syslog-driver', title: 'syslog' },
          { id: 'fluentd-driver', title: 'fluentd' },
          { id: 'gelf-driver', title: 'gelf (Graylog)' },
          { id: 'awslogs-driver', title: 'awslogs' },
          { id: 'gcplogs-driver', title: 'gcplogs' },
          { id: 'splunk-driver', title: 'splunk' },
          { id: 'etwlogs-driver', title: 'etwlogs (Windows)' },
          { id: 'none-log-driver', title: 'none' },
          { id: 'log-driver-default-daemon', title: 'Setting Default in daemon.json' },
          { id: 'log-driver-dual-logging', title: 'Dual Logging' },
        ],
      },
      {
        id: 'metrics',
        title: 'Metrics',
        summary: 'docker stats, daemon Prometheus metrics and cAdvisor.',
        children: [
          { id: 'docker-stats-metrics', title: 'docker stats' },
          { id: 'daemon-prometheus-metrics', title: 'Daemon Prometheus Metrics' },
          { id: 'metrics-addr-config', title: 'metrics-addr Configuration' },
          { id: 'cadvisor-metrics', title: 'cAdvisor' },
          { id: 'node-exporter-host-metrics', title: 'Node Exporter (host metrics)' },
          { id: 'metrics-from-buildkit', title: 'Metrics from BuildKit' },
          { id: 'exporting-metrics-otel', title: 'Exporting Metrics with OpenTelemetry' },
        ],
      },
      {
        id: 'events',
        title: 'Events',
        summary: 'Docker engine event stream.',
        children: [
          { id: 'docker-events-cmd', title: 'docker events' },
          { id: 'event-filters', title: 'Event Filters' },
          { id: 'event-types', title: 'Event Types (container, image, network, volume, daemon)' },
          { id: 'consuming-events-api', title: 'Consuming Events via API' },
        ],
      },
      {
        id: 'diagnostics',
        title: 'Diagnostics',
        summary: 'docker debug, Desktop diagnose and daemon debug mode.',
        children: [
          { id: 'docker-debug-cli', title: 'docker debug CLI' },
          { id: 'docker-desktop-diagnose', title: 'Docker Desktop Diagnose' },
          { id: 'daemon-debug-mode', title: 'Daemon Debug Mode' },
          { id: 'goroutine-stack-dumps', title: 'Goroutine Stack Dumps' },
          { id: 'pprof-profiles', title: 'pprof Profiles' },
          { id: 'docker-system-info-diag', title: 'docker system info (diagnostics)' },
        ],
      },
      {
        id: 'alerting',
        title: 'Alerting',
        summary: 'Alerting on container metrics and events.',
        children: [
          { id: 'alerting-restart-loops', title: 'Restart Loops' },
          { id: 'alerting-oom-events', title: 'OOMKilled Events' },
          { id: 'alerting-healthcheck-failures', title: 'Healthcheck Failures' },
          { id: 'alerting-image-pull-failures', title: 'Image Pull Failures' },
          { id: 'alerting-disk-pressure', title: 'Disk Pressure' },
        ],
      },
    ],
  },

  /* ---------------- Stage 18: Performance & Production Deployment ---------------- */
  {
    id: 'performance-production',
    level: 'advanced',
    roots: [
      {
        id: 'image-performance',
        title: 'Image Performance',
        summary: 'Size, layer caching and lazy pulling strategies.',
        children: [
          { id: 'image-size-strategies', title: 'Image Size Strategies' },
          { id: 'layer-caching-strategies-prod', title: 'Layer Caching Strategies' },
          { id: 'lazy-pulling-stargz', title: 'Lazy Pulling (stargz / nydus)' },
          { id: 'image-prefetching', title: 'Image Prefetching' },
          { id: 'parallel-layer-pulls', title: 'Parallel Layer Pulls' },
          { id: 'multi-arch-image-perf', title: 'Multi-Arch Image Performance' },
        ],
      },
      {
        id: 'build-performance',
        title: 'Build Performance',
        summary: 'Parallel builds, cache tuning and remote builders.',
        children: [
          { id: 'parallel-builds-buildx', title: 'Parallel Builds with buildx' },
          { id: 'cache-tuning-buildkit', title: 'Cache Tuning in BuildKit' },
          { id: 'remote-builders-perf', title: 'Remote / Cloud Builders' },
          { id: 'incremental-builds', title: 'Incremental Builds' },
          { id: 'avoiding-cache-busters', title: 'Avoiding Cache Busters' },
          { id: 'bind-mount-source-perf', title: 'Bind Mount Source Performance' },
          { id: 'cross-compilation-perf', title: 'Cross-Compilation vs Emulation' },
        ],
      },
      {
        id: 'runtime-performance',
        title: 'Runtime Performance',
        summary: 'Startup latency, CPU pinning and NUMA.',
        children: [
          { id: 'container-startup-latency', title: 'Container Startup Latency' },
          { id: 'cpu-pinning', title: 'CPU Pinning (cpuset-cpus)' },
          { id: 'numa-awareness', title: 'NUMA Awareness' },
          { id: 'huge-pages-containers', title: 'Huge Pages in Containers' },
          { id: 'realtime-priorities-containers', title: 'Real-Time Priorities' },
          { id: 'kernel-tunables-containers', title: 'Kernel Tunables (sysctls)' },
          { id: 'low-latency-tuning', title: 'Low-Latency Tuning' },
        ],
      },
      {
        id: 'storage-tuning',
        title: 'Storage Tuning',
        summary: 'Storage driver and volume performance.',
        children: [
          { id: 'overlay2-perf-tuning', title: 'overlay2 Performance Tuning' },
          { id: 'btrfs-zfs-perf', title: 'btrfs / zfs Performance' },
          { id: 'volume-fs-choice', title: 'Volume Filesystem Choice (ext4/xfs)' },
          { id: 'block-device-tuning', title: 'Block Device Tuning' },
          { id: 'io-scheduler-tuning', title: 'I/O Scheduler Tuning' },
          { id: 'desktop-mutagen-vs-bind', title: 'Mutagen vs Bind Mounts (Desktop)' },
        ],
      },
      {
        id: 'network-tuning',
        title: 'Network Tuning',
        summary: 'Throughput and latency tuning for container networks.',
        children: [
          { id: 'bridge-throughput-tuning', title: 'Bridge Throughput Tuning' },
          { id: 'host-network-perf', title: 'Host Network Performance' },
          { id: 'overlay-encryption-overhead', title: 'Overlay Encryption Overhead' },
          { id: 'iptables-conntrack-tuning', title: 'iptables & conntrack Tuning' },
          { id: 'mtu-tuning', title: 'MTU Tuning' },
          { id: 'sriov-and-macvlan-perf', title: 'SR-IOV & macvlan Performance' },
        ],
      },
      {
        id: 'production-deployment-patterns',
        title: 'Production Deployment Patterns',
        summary: 'Single host, Compose, Swarm, container platforms and edge.',
        children: [
          { id: 'single-host-deployments', title: 'Single Host Deployments' },
          { id: 'compose-in-production', title: 'Compose in Production' },
          { id: 'swarm-in-production', title: 'Swarm in Production' },
          {
            id: 'container-platforms-overview',
            title: 'Container Platforms (overview)',
            children: [
              { id: 'platform-ecs-overview', title: 'AWS ECS / Fargate (overview)' },
              { id: 'platform-aci-overview', title: 'Azure Container Instances (overview)' },
              { id: 'platform-cloud-run-overview', title: 'Google Cloud Run (overview)' },
              { id: 'platform-fly-io-overview', title: 'Fly.io (overview)' },
              { id: 'platform-render-overview', title: 'Render (overview)' },
              { id: 'platform-railway-overview', title: 'Railway (overview)' },
              { id: 'platform-koyeb-overview', title: 'Koyeb (overview)' },
              { id: 'platform-self-managed-paas', title: 'Self-managed PaaS (Dokku, CapRover, Coolify)' },
            ],
          },
          { id: 'edge-iot-deployment', title: 'Edge & IoT Deployment' },
          { id: 'air-gapped-deployments', title: 'Air-Gapped Deployments' },
          { id: 'systemd-unit-deployments', title: 'systemd Unit Deployments' },
          { id: 'bare-vm-deployments', title: 'Bare-VM Deployments' },
        ],
      },
      {
        id: 'high-availability',
        title: 'High Availability',
        summary: 'Redundancy, load balancing and disaster recovery.',
        children: [
          { id: 'multi-node-redundancy', title: 'Multi-Node Redundancy' },
          { id: 'load-balancing-containers', title: 'Load Balancing Containers' },
          { id: 'health-driven-routing', title: 'Health-Driven Routing' },
          { id: 'backup-disaster-recovery', title: 'Backup & Disaster Recovery' },
          { id: 'zero-downtime-deployments', title: 'Zero-Downtime Deployments' },
          { id: 'blue-green-deployments-docker', title: 'Blue/Green Deployments' },
          { id: 'canary-deployments-docker', title: 'Canary Deployments' },
        ],
      },
    ],
  },
])
