import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 19: Security Hardening & Compliance ---------------- */
  {
    id: 'security-hardening',
    level: 'advanced',
    roots: [
      {
        id: 'least-privilege',
        title: 'Least Privilege',
        summary: 'Non-root users, no-new-privileges and capability dropping.',
        children: [
          { id: 'running-as-non-root', title: 'Running as Non-Root' },
          { id: 'no-new-privileges', title: '--security-opt no-new-privileges' },
          {
            id: 'dropping-capabilities',
            title: 'Dropping Capabilities',
            children: [
              { id: 'cap-drop-all', title: '--cap-drop=ALL' },
              { id: 'cap-add-minimum', title: 'Adding Only Required Caps' },
              { id: 'common-required-caps', title: 'Common Caps Needed (NET_BIND_SERVICE, CHOWN, …)' },
              { id: 'avoiding-cap-sys-admin', title: 'Avoiding CAP_SYS_ADMIN' },
            ],
          },
          { id: 'fs-permissions-volumes', title: 'Filesystem Permissions for Volumes' },
          { id: 'set-uid-gid-images', title: 'Setting UID/GID in Images' },
        ],
      },
      {
        id: 'container-isolation',
        title: 'Container Isolation',
        summary: 'User namespace remapping, rootless and ECI mode.',
        children: [
          {
            id: 'user-namespace-remapping',
            title: 'User Namespace Remapping (userns-remap)',
            children: [
              { id: 'userns-remap-config', title: 'Configuring userns-remap' },
              { id: 'subuid-subgid', title: '/etc/subuid & /etc/subgid' },
              { id: 'userns-remap-limitations', title: 'Limitations of userns-remap' },
            ],
          },
          { id: 'rootless-containers-runtime', title: 'Rootless Containers' },
          { id: 'enhanced-container-isolation-mode', title: 'Enhanced Container Isolation Mode' },
          { id: 'pid-isolation-tighten', title: 'PID Namespace Isolation' },
          { id: 'ipc-isolation-tighten', title: 'IPC Namespace Isolation' },
          { id: 'mount-isolation-tighten', title: 'Mount Namespace Isolation' },
          { id: 'avoiding-privileged-flag', title: 'Avoiding --privileged' },
        ],
      },
      {
        id: 'security-profiles',
        title: 'Security Profiles',
        summary: 'Seccomp, AppArmor and SELinux profiles at runtime.',
        children: [
          {
            id: 'seccomp-profiles-runtime',
            title: 'Seccomp Profiles',
            children: [
              { id: 'default-seccomp-profile', title: 'Default Seccomp Profile' },
              { id: 'custom-seccomp-profiles', title: 'Custom Seccomp Profiles' },
              { id: 'seccomp-syscall-actions', title: 'Syscall Actions (allow, errno, kill)' },
              { id: 'seccomp-arch-considerations', title: 'Architecture Considerations' },
              { id: 'unconfined-seccomp', title: '--security-opt seccomp=unconfined' },
            ],
          },
          {
            id: 'apparmor-profiles-runtime',
            title: 'AppArmor Profiles',
            children: [
              { id: 'docker-default-apparmor', title: 'docker-default Profile' },
              { id: 'custom-apparmor-profiles', title: 'Custom AppArmor Profiles' },
              { id: 'loading-apparmor-profiles', title: 'Loading AppArmor Profiles' },
            ],
          },
          {
            id: 'selinux-profiles-runtime',
            title: 'SELinux Profiles',
            children: [
              { id: 'container-default-selinux-type', title: 'container_t Default Type' },
              { id: 'custom-selinux-policies', title: 'Custom SELinux Policies' },
              { id: 'selinux-volume-relabeling', title: 'Volume Relabeling (:z, :Z)' },
            ],
          },
        ],
      },
      {
        id: 'read-only-filesystems',
        title: 'Read-only Filesystems',
        summary: 'Running containers with read-only root filesystems.',
        children: [
          { id: 'read-only-flag-runtime', title: '--read-only Flag' },
          { id: 'tmpfs-with-readonly', title: 'tmpfs Mounts with Read-only Root' },
          { id: 'writable-paths-strategy', title: 'Carving Out Writable Paths' },
        ],
      },
      {
        id: 'benchmarks-standards',
        title: 'Benchmarks & Standards',
        summary: 'CIS Docker Benchmark, Docker Bench and NIST standards.',
        children: [
          {
            id: 'cis-docker-benchmark',
            title: 'CIS Docker Benchmark',
            children: [
              { id: 'cis-host-configuration', title: 'Host Configuration Section' },
              { id: 'cis-docker-daemon', title: 'Docker Daemon Section' },
              { id: 'cis-daemon-files-directories', title: 'Daemon Configuration Files' },
              { id: 'cis-container-images', title: 'Container Images Section' },
              { id: 'cis-container-runtime', title: 'Container Runtime Section' },
              { id: 'cis-operations', title: 'Docker Operations Section' },
              { id: 'cis-swarm-section', title: 'Swarm Configuration Section' },
            ],
          },
          { id: 'docker-bench-for-security', title: 'Docker Bench for Security' },
          { id: 'nist-sp-800-190', title: 'NIST SP 800-190 (Container Security)' },
          { id: 'pci-dss-containers', title: 'PCI-DSS Considerations' },
          { id: 'hipaa-containers', title: 'HIPAA Considerations' },
          { id: 'fips-mode-containers', title: 'FIPS Mode Considerations' },
        ],
      },
      {
        id: 'runtime-security',
        title: 'Runtime Security',
        summary: 'Falco, Tracee, Sysdig and behavioural detection.',
        children: [
          {
            id: 'falco-tool',
            title: 'Falco',
            children: [
              { id: 'falco-rules', title: 'Falco Rules' },
              { id: 'falco-syscall-source', title: 'Syscall Source' },
              { id: 'falco-ebpf-driver', title: 'eBPF Driver' },
              { id: 'falco-outputs', title: 'Outputs (stdout, file, http, gRPC)' },
            ],
          },
          { id: 'tracee-tool', title: 'Tracee' },
          { id: 'sysdig-secure', title: 'Sysdig Secure' },
          { id: 'tetragon-cilium', title: 'Tetragon (Cilium)' },
          { id: 'aqua-runtime', title: 'Aqua Runtime Protection (overview)' },
          { id: 'behavioural-anomaly-detection', title: 'Behavioural Anomaly Detection' },
        ],
      },
      {
        id: 'secrets-at-runtime',
        title: 'Secrets at Runtime',
        summary: 'Distributing and using secrets in running containers.',
        children: [
          { id: 'secrets-via-files-runtime', title: 'Secrets via Files' },
          { id: 'secrets-via-env-anti-pattern', title: 'Secrets via Env (anti-pattern)' },
          { id: 'docker-secrets-vs-compose', title: 'Docker Secrets vs Compose Secrets' },
          { id: 'external-secret-injectors', title: 'External Secret Injectors' },
          { id: 'rotating-runtime-secrets', title: 'Rotating Runtime Secrets' },
        ],
      },
      {
        id: 'network-security',
        title: 'Network Security',
        summary: 'Network policies, encryption and firewall considerations.',
        children: [
          { id: 'internal-networks-security', title: 'Internal Networks' },
          { id: 'encrypted-overlays-runtime', title: 'Encrypted Overlay Networks' },
          { id: 'firewall-considerations-docker', title: 'Firewall (ufw/firewalld) & Docker' },
          { id: 'docker-iptables-policies', title: 'Docker iptables Policies' },
          { id: 'inter-container-icc', title: 'icc=false (Disable Inter-Container Comms)' },
          { id: 'limit-published-ports', title: 'Limiting Published Ports' },
          { id: 'tls-everywhere-containers', title: 'TLS Everywhere Inside Containers' },
        ],
      },
    ],
  },

  /* ---------------- Stage 20: Administration & Troubleshooting ---------------- */
  {
    id: 'administration',
    level: 'advanced',
    roots: [
      {
        id: 'daemon-configuration',
        title: 'Daemon Configuration',
        summary: 'daemon.json options for storage, logging, DNS and registries.',
        children: [
          { id: 'daemon-json-location', title: 'daemon.json Locations' },
          {
            id: 'daemon-storage-config',
            title: 'Storage Configuration',
            children: [
              { id: 'storage-driver-key', title: 'storage-driver' },
              { id: 'storage-opts-key', title: 'storage-opts' },
              { id: 'data-root-key', title: 'data-root' },
            ],
          },
          {
            id: 'daemon-logging-defaults',
            title: 'Logging Defaults',
            children: [
              { id: 'log-driver-default', title: 'log-driver' },
              { id: 'log-opts-default', title: 'log-opts' },
            ],
          },
          {
            id: 'daemon-network-config',
            title: 'Network Configuration',
            children: [
              { id: 'bip-bridge-ip-key', title: 'bip / fixed-cidr' },
              { id: 'default-address-pools', title: 'default-address-pools' },
              { id: 'mtu-daemon', title: 'mtu' },
              { id: 'ip6tables-key', title: 'ip6tables / ipv6' },
              { id: 'icc-daemon', title: 'icc' },
            ],
          },
          { id: 'registry-mirrors-config-daemon', title: 'registry-mirrors' },
          { id: 'insecure-registries-daemon', title: 'insecure-registries' },
          { id: 'dns-config-daemon', title: 'dns / dns-search / dns-opts' },
          { id: 'features-key-daemon', title: 'features (e.g. containerd-snapshotter)' },
          { id: 'runtimes-key-daemon', title: 'runtimes (alternate runtimes)' },
          { id: 'default-runtime-key', title: 'default-runtime' },
          { id: 'live-restore', title: 'live-restore' },
          { id: 'userland-proxy-key', title: 'userland-proxy' },
          { id: 'experimental-flag-daemon', title: 'experimental' },
          { id: 'debug-flag-daemon', title: 'debug' },
          { id: 'reloading-daemon-config', title: 'Reloading Configuration (SIGHUP)' },
        ],
      },
      {
        id: 'tls-and-remote-api',
        title: 'TLS & Remote API',
        summary: 'Mutual TLS, exposing the daemon safely and remote contexts.',
        children: [
          { id: 'enabling-tcp-listener', title: 'Enabling the TCP Listener' },
          { id: 'tls-mutual-auth', title: 'Mutual TLS Authentication' },
          { id: 'tls-cert-generation', title: 'Generating CA, Server & Client Certs' },
          { id: 'docker-host-env-var', title: 'DOCKER_HOST Environment Variable' },
          { id: 'docker-tls-verify-env', title: 'DOCKER_TLS_VERIFY' },
          { id: 'docker-cert-path-env', title: 'DOCKER_CERT_PATH' },
          { id: 'exposing-daemon-securely', title: 'Exposing Daemon Securely' },
          { id: 'docker-context-remote', title: 'docker context for Remote Hosts' },
          { id: 'ssh-context-tunnels', title: 'SSH Contexts' },
        ],
      },
      {
        id: 'upgrades-maintenance',
        title: 'Upgrades & Maintenance',
        summary: 'Upgrading the engine, migrating storage drivers and cleanup.',
        children: [
          { id: 'upgrading-docker-engine', title: 'Upgrading Docker Engine' },
          { id: 'upgrading-containerd', title: 'Upgrading containerd' },
          { id: 'upgrading-runc', title: 'Upgrading runc' },
          { id: 'migrating-storage-drivers', title: 'Migrating Storage Drivers' },
          { id: 'migrating-to-containerd-snapshotter', title: 'Migrating to containerd Image Store' },
          { id: 'resource-quotas-cleanup', title: 'Resource Quotas & Cleanup' },
          { id: 'rolling-restart-strategy', title: 'Rolling Restart with live-restore' },
        ],
      },
      {
        id: 'common-errors',
        title: 'Common Errors',
        summary: 'Permissions, image-not-found, OOM, port in use and disk full.',
        children: [
          { id: 'permission-denied-issues', title: 'permission denied' },
          { id: 'image-not-found-error', title: 'image not found' },
          { id: 'manifest-unknown-error', title: 'manifest unknown' },
          { id: 'network-unreachable-error', title: 'network unreachable' },
          { id: 'oom-killed-error', title: 'OOMKilled' },
          { id: 'port-already-allocated-error', title: 'port already allocated' },
          { id: 'no-space-left-on-device', title: 'no space left on device' },
          { id: 'docker-daemon-not-running', title: 'cannot connect to the Docker daemon' },
          { id: 'exit-codes-troubleshoot', title: 'Non-zero Exit Codes' },
          { id: 'context-deadline-exceeded', title: 'context deadline exceeded' },
          { id: 'rate-limit-pull-error', title: 'Docker Hub Rate Limit Error' },
        ],
      },
      {
        id: 'troubleshooting-tools',
        title: 'Troubleshooting Tools',
        summary: 'Events, inspect, nsenter, strace, tcpdump and journald.',
        children: [
          { id: 'docker-events-troubleshoot', title: 'docker events' },
          { id: 'docker-inspect-deep-dive', title: 'docker inspect Deep Dive' },
          { id: 'nsenter-tool', title: 'nsenter' },
          { id: 'strace-in-containers', title: 'strace' },
          { id: 'tcpdump-in-containers', title: 'tcpdump' },
          { id: 'lsof-in-containers', title: 'lsof' },
          { id: 'daemon-logs-journald-debug', title: 'Daemon Logs (journald/journalctl)' },
          { id: 'cadvisor-debug', title: 'cAdvisor for Container Metrics' },
          { id: 'docker-debug-troubleshoot', title: 'docker debug for Troubleshooting' },
          { id: 'crictl-troubleshoot', title: 'crictl for containerd' },
        ],
      },
      {
        id: 'network-troubleshooting',
        title: 'Network Troubleshooting',
        summary: 'Debugging container networking issues.',
        children: [
          { id: 'container-cant-reach-internet', title: 'Container Cannot Reach the Internet' },
          { id: 'host-cant-reach-container', title: 'Host Cannot Reach Container' },
          { id: 'container-to-container-dns-fail', title: 'Container-to-Container DNS Failure' },
          { id: 'iptables-debug-network', title: 'Debugging iptables Rules' },
          { id: 'mtu-mismatch-debug', title: 'MTU Mismatch Issues' },
          { id: 'overlay-vxlan-debug', title: 'Overlay / VXLAN Debugging' },
        ],
      },
      {
        id: 'storage-troubleshooting',
        title: 'Storage Troubleshooting',
        summary: 'Debugging volume, mount and driver issues.',
        children: [
          { id: 'mount-permission-issues', title: 'Mount Permission Issues' },
          { id: 'volume-not-persisting-debug', title: 'Volume Not Persisting Data' },
          { id: 'storage-driver-errors', title: 'Storage Driver Errors' },
          { id: 'inode-exhaustion', title: 'Inode Exhaustion' },
          { id: 'layer-corruption', title: 'Layer Corruption' },
          { id: 'fuse-overlayfs-debug', title: 'fuse-overlayfs Debugging (rootless)' },
        ],
      },
      {
        id: 'build-troubleshooting',
        title: 'Build Troubleshooting',
        summary: 'Diagnosing failed builds and cache issues.',
        children: [
          { id: 'context-too-large', title: 'Context Too Large' },
          { id: 'cache-miss-debugging', title: 'Cache Miss Debugging' },
          { id: 'multi-platform-build-errors', title: 'Multi-Platform Build Errors' },
          { id: 'buildkit-internal-errors', title: 'BuildKit Internal Errors' },
          { id: 'failed-secret-mount-debug', title: 'Failed --secret / --ssh Mount' },
          { id: 'build-debug-mode', title: 'docker buildx debug Build' },
        ],
      },
      {
        id: 'dns-troubleshooting',
        title: 'DNS Troubleshooting',
        summary: 'Resolving DNS issues in containers and networks.',
        children: [
          { id: 'embedded-dns-debug', title: 'Embedded DNS Resolution Debugging' },
          { id: 'resolv-conf-issues', title: '/etc/resolv.conf Issues' },
          { id: 'systemd-resolved-collisions', title: 'systemd-resolved Collisions' },
          { id: 'corporate-dns-issues', title: 'Corporate DNS / Split Horizon Issues' },
        ],
      },
    ],
  },

  /* ---------------- Stage 21: Ecosystem, Frontier & Career ---------------- */
  {
    id: 'ecosystem-career',
    level: 'intermediate',
    roots: [
      {
        id: 'docker-alternatives',
        title: 'Docker Alternatives',
        summary: 'Podman, Buildah, Skopeo, nerdctl, Finch, Lima, Colima and Rancher Desktop.',
        children: [
          {
            id: 'podman-alt',
            title: 'Podman',
            children: [
              { id: 'podman-vs-docker', title: 'Podman vs Docker' },
              { id: 'podman-rootless', title: 'Rootless Podman' },
              { id: 'podman-machine', title: 'podman machine' },
              { id: 'podman-pods-quadlet', title: 'Pods & Quadlet' },
              { id: 'podman-compose', title: 'podman-compose' },
              { id: 'podman-desktop', title: 'Podman Desktop' },
            ],
          },
          {
            id: 'buildah-alt',
            title: 'Buildah',
            children: [
              { id: 'buildah-vs-buildx', title: 'Buildah vs buildx' },
              { id: 'buildah-scripts', title: 'Scriptable Builds' },
            ],
          },
          {
            id: 'skopeo-alt',
            title: 'Skopeo',
            children: [
              { id: 'skopeo-copy', title: 'skopeo copy' },
              { id: 'skopeo-inspect', title: 'skopeo inspect' },
              { id: 'skopeo-sync', title: 'skopeo sync' },
              { id: 'skopeo-delete', title: 'skopeo delete' },
            ],
          },
          { id: 'nerdctl-alt', title: 'nerdctl' },
          { id: 'finch-alt', title: 'Finch (AWS)' },
          { id: 'lima-alt', title: 'Lima' },
          { id: 'colima-alt', title: 'Colima' },
          { id: 'rancher-desktop-alt', title: 'Rancher Desktop' },
          { id: 'orbstack-alt', title: 'OrbStack (macOS)' },
          { id: 'lxc-lxd-alt', title: 'LXC / LXD' },
          { id: 'crane-alt', title: 'crane (go-containerregistry)' },
        ],
      },
      {
        id: 'oci-ecosystem',
        title: 'OCI Ecosystem',
        summary: 'Projects, tools and specs across the OCI ecosystem.',
        children: [
          { id: 'oci-runtime-spec-tools', title: 'Runtime Spec Tools' },
          { id: 'oci-image-spec-tools', title: 'Image Spec Tools' },
          { id: 'oci-distribution-spec-tools', title: 'Distribution Spec Tools' },
          { id: 'oras-tool', title: 'ORAS (OCI Registry As Storage)' },
          { id: 'umoci-tool', title: 'umoci' },
          { id: 'go-containerregistry-tools', title: 'go-containerregistry' },
          { id: 'oci-artifacts-ecosystem', title: 'OCI Artifacts (Helm, OPA, WASM, etc.)' },
          { id: 'oci-referrers-ecosystem', title: 'OCI Referrers Ecosystem' },
        ],
      },
      {
        id: 'emerging-trends',
        title: 'Emerging Trends',
        summary: 'WASM containers, confidential containers, AI and frontier sandboxing.',
        children: [
          { id: 'wasm-containers-frontier', title: 'WASM Containers (frontier)' },
          { id: 'confidential-containers-frontier', title: 'Confidential Containers (frontier)' },
          { id: 'sandboxing-tech-trends', title: 'Frontier Sandboxing (gVisor, Kata, Firecracker)' },
          { id: 'docker-ai-frontier', title: 'Docker AI & Agents Frontier' },
          { id: 'docker-mcp-frontier', title: 'Docker & Model Context Protocol' },
          { id: 'cloud-native-evolution', title: 'Cloud-Native Evolution Beyond Containers' },
          { id: 'serverless-containers-trends', title: 'Serverless Container Trends' },
          { id: 'image-format-evolution', title: 'Image Format Evolution (eStargz, Nydus, zstd)' },
          { id: 'cdi-spec-trend', title: 'Container Device Interface (CDI) Adoption' },
          { id: 'sustainability-greenops', title: 'Sustainability & GreenOps for Containers' },
        ],
      },
      {
        id: 'standards-bodies',
        title: 'Standards Bodies',
        summary: 'Open Container Initiative and CNCF.',
        children: [
          {
            id: 'opencontainers-org',
            title: 'Open Container Initiative (OCI)',
            children: [
              { id: 'oci-history', title: 'OCI History' },
              { id: 'oci-governance', title: 'OCI Governance' },
              { id: 'oci-current-specs', title: 'Current Specifications' },
            ],
          },
          {
            id: 'cncf-org',
            title: 'Cloud Native Computing Foundation (CNCF)',
            children: [
              { id: 'cncf-project-tiers', title: 'CNCF Project Tiers (Sandbox/Incubating/Graduated)' },
              { id: 'cncf-graduated-container-projects', title: 'Graduated Container Projects' },
              { id: 'cncf-landscape', title: 'CNCF Landscape' },
            ],
          },
        ],
      },
      {
        id: 'certifications-career',
        title: 'Certifications & Career',
        summary: 'Docker certifications, learning paths and portfolio projects.',
        children: [
          {
            id: 'docker-certifications',
            title: 'Docker Certifications',
            children: [
              { id: 'docker-foundations-pro-cert', title: 'Docker Foundations Professional Certificate' },
              { id: 'docker-dca-history', title: 'Docker Certified Associate (DCA) — history' },
              { id: 'vendor-neutral-container-certs', title: 'Vendor-Neutral Container Certs' },
            ],
          },
          { id: 'learning-path', title: 'Learning Path: Beginner → Expert' },
          { id: 'portfolio-projects', title: 'Portfolio Projects' },
          { id: 'community-resources', title: 'Community Resources' },
          { id: 'staying-current', title: 'Staying Current (Release Notes, Blog, GitHub)' },
          { id: 'open-source-contributions', title: 'Contributing to Docker / Moby / containerd' },
          { id: 'docker-captains-program', title: 'Docker Captains Program' },
          { id: 'related-skill-tracks', title: 'Related Skill Tracks (Kubernetes, DevOps, SRE)' },
        ],
      },
    ],
  },
])
