import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 5: Building Images with Dockerfiles ---------------- */
  {
    id: 'building-images',
    level: 'beginner',
    roots: [
      {
        id: 'dockerfile-basics',
        title: 'Dockerfile Basics',
        summary: 'Dockerfile syntax, parser directives, heredocs and comments.',
        children: [
          { id: 'dockerfile-syntax', title: 'Dockerfile Syntax' },
          { id: 'dockerfile-filename-conventions', title: 'Dockerfile Filename Conventions' },
          {
            id: 'parser-directives',
            title: 'Parser Directives',
            children: [
              { id: 'syntax-directive', title: '# syntax=' },
              { id: 'escape-directive', title: '# escape=' },
              { id: 'check-directive', title: '# check=' },
            ],
          },
          {
            id: 'heredocs-in-dockerfile',
            title: 'Heredocs in Dockerfile',
            children: [
              { id: 'heredoc-run', title: 'Heredoc with RUN' },
              { id: 'heredoc-copy', title: 'Heredoc with COPY' },
              { id: 'heredoc-shells', title: 'Heredoc Shell Selection' },
            ],
          },
          { id: 'comments-line-continuation', title: 'Comments & Line Continuation' },
          { id: 'reserved-build-args', title: 'Reserved Build Args' },
        ],
      },
      {
        id: 'dockerfile-instructions',
        title: 'Dockerfile Instructions',
        summary: 'FROM, RUN, COPY, ADD, CMD, ENTRYPOINT, ENV, ARG, EXPOSE and friends.',
        children: [
          {
            id: 'from-instruction',
            title: 'FROM',
            children: [
              { id: 'from-image-tag', title: 'FROM image:tag' },
              { id: 'from-digest', title: 'FROM image@sha256:digest' },
              { id: 'from-platform', title: 'FROM --platform=' },
              { id: 'from-as-stage', title: 'FROM ... AS <stage>' },
              { id: 'from-scratch', title: 'FROM scratch' },
            ],
          },
          {
            id: 'run-instruction',
            title: 'RUN',
            children: [
              { id: 'run-shell-form', title: 'Shell Form' },
              { id: 'run-exec-form', title: 'Exec Form' },
              { id: 'run-mount-flag', title: 'RUN --mount' },
              { id: 'run-network-flag', title: 'RUN --network' },
              { id: 'run-security-flag', title: 'RUN --security' },
            ],
          },
          {
            id: 'copy-instruction',
            title: 'COPY',
            children: [
              { id: 'copy-from-flag', title: 'COPY --from=' },
              { id: 'copy-chown-flag', title: 'COPY --chown=' },
              { id: 'copy-chmod-flag', title: 'COPY --chmod=' },
              { id: 'copy-link-flag', title: 'COPY --link' },
              { id: 'copy-exclude-flag', title: 'COPY --exclude' },
              { id: 'copy-parents-flag', title: 'COPY --parents' },
            ],
          },
          {
            id: 'add-instruction',
            title: 'ADD',
            children: [
              { id: 'add-url', title: 'ADD URL' },
              { id: 'add-git-repo', title: 'ADD Git Repo' },
              { id: 'add-tar-extract', title: 'ADD Tar Auto-Extract' },
              { id: 'add-checksum-flag', title: 'ADD --checksum' },
              { id: 'add-keep-git-dir-flag', title: 'ADD --keep-git-dir' },
            ],
          },
          {
            id: 'cmd-instruction',
            title: 'CMD',
            children: [
              { id: 'cmd-exec-form', title: 'Exec Form' },
              { id: 'cmd-shell-form', title: 'Shell Form' },
              { id: 'cmd-default-args', title: 'Default Args for ENTRYPOINT' },
            ],
          },
          {
            id: 'entrypoint-instruction',
            title: 'ENTRYPOINT',
            children: [
              { id: 'entrypoint-exec-form', title: 'Exec Form' },
              { id: 'entrypoint-shell-form', title: 'Shell Form' },
              { id: 'entrypoint-vs-cmd', title: 'ENTRYPOINT vs CMD' },
              { id: 'entrypoint-script-pattern', title: 'Entrypoint Script Pattern' },
            ],
          },
          { id: 'env-instruction', title: 'ENV' },
          { id: 'arg-instruction', title: 'ARG' },
          { id: 'expose-instruction', title: 'EXPOSE' },
          { id: 'volume-instruction', title: 'VOLUME' },
          { id: 'workdir-instruction', title: 'WORKDIR' },
          { id: 'user-instruction', title: 'USER' },
          { id: 'label-instruction', title: 'LABEL' },
          { id: 'healthcheck-instruction', title: 'HEALTHCHECK' },
          { id: 'onbuild-instruction', title: 'ONBUILD' },
          { id: 'stopsignal-instruction', title: 'STOPSIGNAL' },
          { id: 'shell-instruction', title: 'SHELL' },
          { id: 'maintainer-deprecated', title: 'MAINTAINER (deprecated)' },
        ],
      },
      {
        id: 'build-context',
        title: 'Build Context',
        summary: 'Local, remote and named build contexts and .dockerignore.',
        children: [
          { id: 'local-build-context', title: 'Local Build Context' },
          { id: 'stdin-dockerfile-context', title: 'Dockerfile from STDIN' },
          {
            id: 'remote-build-contexts',
            title: 'Remote Build Contexts',
            children: [
              { id: 'git-context', title: 'Git URL Context' },
              { id: 'http-tar-context', title: 'HTTP/Tarball Context' },
              { id: 'oci-image-context', title: 'OCI Image Context' },
            ],
          },
          { id: 'named-contexts', title: 'Named Contexts (--build-context)' },
          { id: 'dockerignore-file', title: '.dockerignore' },
          { id: 'context-transfer-performance', title: 'Context Transfer & Performance' },
        ],
      },
      {
        id: 'build-command',
        title: 'Build Command',
        summary: 'docker build options, build-args, tagging and progress output.',
        children: [
          { id: 'docker-build-cmd', title: 'docker build' },
          { id: 'build-file-flag', title: '--file / -f' },
          { id: 'build-tag-flag', title: '--tag / -t' },
          { id: 'build-arg-passing', title: '--build-arg' },
          { id: 'build-target-flag', title: '--target' },
          { id: 'build-progress-output', title: '--progress' },
          { id: 'build-no-cache', title: '--no-cache' },
          { id: 'build-pull-flag', title: '--pull' },
          { id: 'build-platform-flag', title: '--platform' },
          { id: 'build-output-flag', title: '--output / -o' },
          { id: 'build-cache-from-to', title: '--cache-from / --cache-to' },
          { id: 'build-secret-flag', title: '--secret' },
          { id: 'build-ssh-flag', title: '--ssh' },
          { id: 'build-label-flag', title: '--label' },
          { id: 'build-network-flag', title: '--network' },
          { id: 'build-rm-force-rm', title: '--rm / --force-rm' },
          { id: 'build-quiet-flag', title: '--quiet / -q' },
          { id: 'build-iidfile', title: '--iidfile' },
        ],
      },
      {
        id: 'multi-stage-builds',
        title: 'Multi-Stage Builds',
        summary: 'Named stages, COPY --from, target stages and external images.',
        level: 'intermediate',
        children: [
          { id: 'stage-naming', title: 'Naming Stages (AS)' },
          { id: 'copy-from-stage', title: 'COPY --from=<stage>' },
          { id: 'target-stage-build', title: 'Building a Specific --target' },
          { id: 'external-images-as-stages', title: 'External Images as Stages' },
          { id: 'parallel-stage-builds', title: 'Parallel Stage Builds' },
          { id: 'final-stage-pattern', title: 'Final Stage Pattern' },
          { id: 'builder-runtime-split', title: 'Builder vs Runtime Split' },
          { id: 'test-stage-pattern', title: 'Test Stage Pattern' },
        ],
      },
      {
        id: 'arg-vs-env',
        title: 'ARG vs ENV',
        summary: 'Differences and best practices for build-time vs runtime variables.',
        children: [
          { id: 'arg-scope', title: 'ARG Scope' },
          { id: 'env-scope', title: 'ENV Scope' },
          { id: 'global-args-before-from', title: 'Global ARG before FROM' },
          { id: 'arg-from-env-pattern', title: 'ARG → ENV Pattern' },
          { id: 'arg-default-values', title: 'ARG Default Values' },
          { id: 'arg-env-security', title: 'ARG/ENV & Secrets Anti-Pattern' },
        ],
      },
      {
        id: 'dockerfile-best-practices',
        title: 'Dockerfile Best Practices',
        summary: 'Layer ordering, image size, single process and non-root users.',
        children: [
          { id: 'layer-ordering-bp', title: 'Layer Ordering for Cache' },
          { id: 'minimizing-image-size', title: 'Minimizing Image Size' },
          { id: 'single-process-containers', title: 'Single Process per Container' },
          { id: 'non-root-users-in-dockerfile', title: 'Non-root USER in Dockerfile' },
          { id: 'reproducible-builds', title: 'Reproducible Builds' },
          { id: 'cleaning-package-caches', title: 'Cleaning Package Caches' },
          { id: 'pinning-base-images', title: 'Pinning Base Images' },
          { id: 'avoiding-add-vs-copy', title: 'Avoiding ADD where COPY Suffices' },
          { id: 'combining-run-instructions', title: 'Combining RUN Instructions' },
          { id: 'using-buildkit-features', title: 'Leveraging BuildKit Features' },
          { id: 'use-entrypoint-init', title: 'Use ENTRYPOINT with tini/dumb-init' },
          { id: 'dockerfile-lint-hadolint', title: 'Dockerfile Linting (Hadolint)' },
          { id: 'dockerfile-check-builtin', title: 'Built-in Dockerfile Checks' },
        ],
      },
    ],
  },

  /* ---------------- Stage 6: BuildKit, Buildx & Build Cloud ---------------- */
  {
    id: 'buildkit-buildx',
    level: 'intermediate',
    roots: [
      {
        id: 'buildkit',
        title: 'BuildKit',
        summary: 'Architecture, frontends, LLB and workers.',
        children: [
          {
            id: 'buildkit-architecture',
            title: 'BuildKit Architecture',
            children: [
              { id: 'buildkit-daemon-buildkitd', title: 'buildkitd' },
              { id: 'buildkit-client', title: 'BuildKit Client' },
              { id: 'buildkit-snapshotter-integration', title: 'Snapshotter Integration' },
            ],
          },
          {
            id: 'buildkit-frontends',
            title: 'BuildKit Frontends',
            children: [
              { id: 'dockerfile-frontend', title: 'Dockerfile Frontend' },
              { id: 'custom-frontends', title: 'Custom Frontends' },
              { id: 'buildpacks-frontend', title: 'Buildpacks Frontend' },
            ],
          },
          { id: 'buildkit-llb', title: 'LLB (Low-Level Builder Language)' },
          { id: 'buildkit-workers', title: 'BuildKit Workers (oci, containerd)' },
          { id: 'buildkit-config', title: 'BuildKit Configuration (buildkitd.toml)' },
          { id: 'buildkit-gc', title: 'BuildKit Garbage Collection' },
          { id: 'buildkit-debug', title: 'Debugging BuildKit Builds' },
        ],
      },
      {
        id: 'buildx',
        title: 'Buildx',
        summary: 'Builder instances, drivers and switching builders.',
        children: [
          {
            id: 'buildx-builders',
            title: 'Buildx Builders',
            children: [
              { id: 'buildx-create', title: 'docker buildx create' },
              { id: 'buildx-use', title: 'docker buildx use' },
              { id: 'buildx-ls', title: 'docker buildx ls' },
              { id: 'buildx-rm', title: 'docker buildx rm' },
              { id: 'buildx-inspect', title: 'docker buildx inspect' },
              { id: 'buildx-stop', title: 'docker buildx stop' },
              { id: 'buildx-prune', title: 'docker buildx prune' },
              { id: 'buildx-du', title: 'docker buildx du' },
            ],
          },
          {
            id: 'buildx-drivers',
            title: 'Buildx Drivers',
            children: [
              { id: 'docker-driver', title: 'docker driver' },
              { id: 'docker-container-driver', title: 'docker-container driver' },
              { id: 'kubernetes-driver', title: 'kubernetes driver' },
              { id: 'remote-driver', title: 'remote driver' },
              { id: 'cloud-driver', title: 'cloud driver' },
            ],
          },
          { id: 'buildx-build-cmd', title: 'docker buildx build' },
          { id: 'buildx-imagetools', title: 'docker buildx imagetools' },
          { id: 'buildx-debug-cmd', title: 'docker buildx debug' },
          { id: 'buildx-history-cmd', title: 'docker buildx history' },
          { id: 'buildx-version', title: 'docker buildx version' },
        ],
      },
      {
        id: 'build-cache',
        title: 'Build Cache',
        summary: 'Inline, registry, GitHub Actions, S3 and Azure cache backends.',
        children: [
          {
            id: 'inline-cache',
            title: 'Inline Cache',
            children: [
              { id: 'inline-cache-from', title: 'cache-from inline' },
              { id: 'inline-cache-to', title: 'cache-to inline' },
              { id: 'inline-cache-mode-min-max', title: 'mode=min vs mode=max' },
            ],
          },
          {
            id: 'registry-cache',
            title: 'Registry Cache',
            children: [
              { id: 'registry-cache-from', title: 'type=registry,ref=' },
              { id: 'registry-cache-to', title: 'type=registry,mode=max' },
              { id: 'registry-cache-image-manifest', title: 'image-manifest=true' },
            ],
          },
          { id: 'github-actions-cache-backend', title: 'GitHub Actions Cache (type=gha)' },
          { id: 's3-cache-backend', title: 'S3 Cache (type=s3)' },
          { id: 'azure-blob-cache-backend', title: 'Azure Blob Cache (type=azblob)' },
          { id: 'local-cache-backend', title: 'Local Cache (type=local)' },
          { id: 'cache-from-to-flags', title: '--cache-from / --cache-to' },
          { id: 'cache-import-export', title: 'Cache Import / Export' },
        ],
      },
      {
        id: 'mounts-in-builds',
        title: 'Mounts in Builds',
        summary: 'Cache, secret, ssh, bind and tmpfs mounts at build time.',
        children: [
          {
            id: 'cache-mounts',
            title: 'Cache Mounts',
            children: [
              { id: 'cache-mount-id', title: 'id= identifier' },
              { id: 'cache-mount-sharing', title: 'sharing= (shared/private/locked)' },
              { id: 'cache-mount-target', title: 'target=' },
              { id: 'cache-mount-uid-gid', title: 'uid/gid/mode' },
            ],
          },
          {
            id: 'secret-mounts',
            title: 'Secret Mounts',
            children: [
              { id: 'secret-mount-id', title: 'id= for secrets' },
              { id: 'secret-mount-src', title: 'src= source file' },
              { id: 'secret-mount-env', title: 'env= source variable' },
              { id: 'secret-mount-target', title: 'target= in container' },
              { id: 'secret-mount-required', title: 'required=true' },
            ],
          },
          { id: 'ssh-mounts', title: 'SSH Mounts (--mount=type=ssh)' },
          { id: 'bind-mounts-build', title: 'Bind Mounts in Builds' },
          { id: 'tmpfs-mounts-build', title: 'tmpfs Mounts in Builds' },
        ],
      },
      {
        id: 'multi-platform-builds-buildx',
        title: 'Multi-Platform Builds',
        summary: 'Cross-platform images with buildx and emulation.',
        children: [
          { id: 'mp-build-platform-list', title: '--platform list' },
          { id: 'mp-build-emulation', title: 'QEMU Emulation in Builds' },
          { id: 'mp-build-native-nodes', title: 'Native Build Nodes per Platform' },
          { id: 'mp-build-cross-compilation', title: 'Cross-Compilation Patterns' },
          { id: 'mp-build-push-vs-load', title: '--push vs --load for multi-platform' },
          { id: 'mp-build-manifest-output', title: 'Manifest Output for Multi-Platform' },
        ],
      },
      {
        id: 'docker-bake',
        title: 'Docker Bake',
        summary: 'HCL/JSON bake files, groups, targets and inheritance.',
        children: [
          { id: 'bake-files', title: 'Bake Files (docker-bake.hcl/json/yml)' },
          { id: 'bake-targets', title: 'Targets' },
          { id: 'bake-groups', title: 'Groups' },
          { id: 'bake-inheritance', title: 'Inheritance (inherits)' },
          { id: 'bake-hcl-vs-json', title: 'HCL vs JSON vs YAML' },
          { id: 'bake-variables', title: 'Variables & Defaults' },
          { id: 'bake-matrix', title: 'Matrix' },
          { id: 'bake-functions', title: 'HCL Functions' },
          { id: 'bake-overrides', title: 'CLI Overrides' },
          { id: 'bake-print', title: 'docker buildx bake --print' },
          { id: 'bake-call', title: 'docker buildx bake --call' },
          { id: 'bake-compose-integration', title: 'Bake from Compose Files' },
        ],
      },
      {
        id: 'docker-build-cloud',
        title: 'Docker Build Cloud',
        summary: 'Cloud builders, shared cache and team workflows.',
        children: [
          { id: 'build-cloud-overview', title: 'Build Cloud Overview' },
          { id: 'build-cloud-setup', title: 'Setting up Build Cloud' },
          { id: 'build-cloud-shared-cache', title: 'Shared Cache in Build Cloud' },
          { id: 'build-cloud-native-multiarch', title: 'Native Multi-Arch Builders' },
          { id: 'build-cloud-ci-integration', title: 'Build Cloud in CI' },
          { id: 'build-cloud-pricing-limits', title: 'Pricing & Limits' },
        ],
      },
      {
        id: 'sbom-attestations',
        title: 'SBOMs & Attestations',
        summary: 'SBOM, provenance, SLSA and in-toto attestations.',
        children: [
          { id: 'sbom-buildx', title: '--sbom=true (BuildKit SBOM)' },
          { id: 'provenance-attestations', title: '--provenance=mode=max' },
          { id: 'slsa-levels', title: 'SLSA Levels' },
          { id: 'in-toto-attestations', title: 'in-toto Attestations' },
          { id: 'reading-attestations', title: 'Reading Attestations (buildx imagetools)' },
          { id: 'attestation-storage-formats', title: 'Attestation Storage Formats' },
        ],
      },
      {
        id: 'build-outputs',
        title: 'Build Outputs',
        summary: 'OCI, tar, local and registry output formats.',
        children: [
          { id: 'output-type-image', title: 'type=image (docker / registry)' },
          { id: 'output-type-oci', title: 'type=oci' },
          { id: 'output-type-docker', title: 'type=docker' },
          { id: 'output-type-tar', title: 'type=tar' },
          { id: 'output-type-local', title: 'type=local' },
          { id: 'output-type-registry', title: 'type=registry' },
          { id: 'output-push-load', title: '--push / --load shorthands' },
        ],
      },
    ],
  },
])
