import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 13: Docker Swarm Mode ---------------- */
  {
    id: 'swarm',
    level: 'advanced',
    roots: [
      {
        id: 'swarm-architecture',
        title: 'Swarm Architecture',
        summary: 'Managers, workers, Raft consensus and join tokens.',
        children: [
          { id: 'manager-nodes', title: 'Manager Nodes' },
          { id: 'worker-nodes', title: 'Worker Nodes' },
          { id: 'raft-consensus', title: 'Raft Consensus' },
          { id: 'swarm-quorum', title: 'Quorum & Manager Quorum Sizing' },
          { id: 'swarm-tokens', title: 'Join Tokens (manager & worker)' },
          { id: 'swarm-tls-mutual', title: 'Mutual TLS Between Nodes' },
          { id: 'swarm-state-store', title: 'Internal State Store' },
          { id: 'swarm-leader-election', title: 'Leader Election' },
        ],
      },
      {
        id: 'swarm-setup',
        title: 'Swarm Setup',
        summary: 'Initializing, joining and managing nodes.',
        children: [
          { id: 'docker-swarm-init', title: 'docker swarm init' },
          { id: 'docker-swarm-join', title: 'docker swarm join' },
          { id: 'docker-swarm-join-token', title: 'docker swarm join-token' },
          { id: 'docker-swarm-leave', title: 'docker swarm leave' },
          { id: 'docker-swarm-update', title: 'docker swarm update' },
          { id: 'docker-swarm-unlock-key', title: 'docker swarm unlock-key' },
          { id: 'docker-swarm-unlock', title: 'docker swarm unlock (autolock)' },
          { id: 'docker-swarm-ca', title: 'docker swarm ca (rotate CA)' },
          {
            id: 'node-management',
            title: 'Node Management',
            children: [
              { id: 'docker-node-ls', title: 'docker node ls' },
              { id: 'docker-node-inspect', title: 'docker node inspect' },
              { id: 'docker-node-promote', title: 'docker node promote' },
              { id: 'docker-node-demote', title: 'docker node demote' },
              { id: 'docker-node-update', title: 'docker node update' },
              { id: 'docker-node-rm', title: 'docker node rm' },
              { id: 'docker-node-ps', title: 'docker node ps' },
              { id: 'node-availability-states', title: 'Node Availability (active/pause/drain)' },
            ],
          },
        ],
      },
      {
        id: 'swarm-services',
        title: 'Services',
        summary: 'Creating, updating and scaling services.',
        children: [
          {
            id: 'docker-service-create',
            title: 'docker service create',
            children: [
              { id: 'service-create-replicas', title: '--replicas' },
              { id: 'service-create-mode-global', title: '--mode global' },
              { id: 'service-create-mode-replicated-job', title: '--mode replicated-job' },
              { id: 'service-create-mode-global-job', title: '--mode global-job' },
              { id: 'service-create-mounts', title: '--mount' },
              { id: 'service-create-publish', title: '--publish' },
              { id: 'service-create-network', title: '--network' },
              { id: 'service-create-secret', title: '--secret' },
              { id: 'service-create-config', title: '--config' },
              { id: 'service-create-limit-resources', title: '--limit-cpu/memory/pids' },
              { id: 'service-create-reserve-resources', title: '--reserve-cpu/memory' },
              { id: 'service-create-restart-condition', title: '--restart-condition' },
              { id: 'service-create-rollback-config', title: '--rollback-config' },
              { id: 'service-create-update-config', title: '--update-config' },
            ],
          },
          { id: 'docker-service-ls', title: 'docker service ls' },
          { id: 'docker-service-ps', title: 'docker service ps' },
          { id: 'docker-service-inspect', title: 'docker service inspect' },
          {
            id: 'docker-service-update',
            title: 'docker service update',
            children: [
              { id: 'service-update-image', title: '--image' },
              { id: 'service-update-env', title: '--env-add / --env-rm' },
              { id: 'service-update-publish-add', title: '--publish-add / --publish-rm' },
              { id: 'service-update-mount', title: '--mount-add / --mount-rm' },
              { id: 'service-update-replicas', title: '--replicas / --replicas-max-per-node' },
              { id: 'service-update-force', title: '--force' },
            ],
          },
          { id: 'docker-service-rollback', title: 'docker service rollback' },
          { id: 'docker-service-scale', title: 'docker service scale' },
          { id: 'docker-service-logs', title: 'docker service logs' },
          { id: 'docker-service-rm', title: 'docker service rm' },
          { id: 'global-vs-replicated-services', title: 'Global vs Replicated Services' },
          { id: 'service-jobs-vs-services', title: 'Jobs vs Long-Running Services' },
        ],
      },
      {
        id: 'swarm-stacks',
        title: 'Stacks',
        summary: 'docker stack deploy and managing stacks.',
        children: [
          { id: 'docker-stack-deploy', title: 'docker stack deploy' },
          { id: 'docker-stack-ls', title: 'docker stack ls' },
          { id: 'docker-stack-ps', title: 'docker stack ps' },
          { id: 'docker-stack-services', title: 'docker stack services' },
          { id: 'docker-stack-rm', title: 'docker stack rm' },
          { id: 'docker-stack-config', title: 'docker stack config' },
          { id: 'stack-compose-file-support', title: 'Compose File Support in Stacks' },
          { id: 'stack-deploy-resolve-image', title: '--resolve-image (digest pinning)' },
          { id: 'stack-deploy-detach', title: '--detach' },
          { id: 'stack-deploy-with-registry-auth', title: '--with-registry-auth' },
          { id: 'stack-deploy-prune', title: '--prune' },
        ],
      },
      {
        id: 'swarm-networking',
        title: 'Swarm Networking',
        summary: 'Overlay networks, routing mesh and ingress.',
        children: [
          { id: 'swarm-overlay-network', title: 'Overlay Networks in Swarm' },
          { id: 'routing-mesh', title: 'Routing Mesh' },
          { id: 'ingress-network', title: 'ingress Network' },
          { id: 'encrypted-overlay-swarm', title: 'Encrypted Overlay (--opt encrypted)' },
          { id: 'attachable-overlay-swarm', title: 'Attachable Overlay (--attachable)' },
          { id: 'service-discovery-swarm', title: 'Service Discovery in Swarm' },
          { id: 'load-balancing-vip-dnsrr', title: 'Load Balancing (VIP vs dnsrr)' },
          { id: 'host-mode-publish', title: 'mode=host Port Publishing' },
        ],
      },
      {
        id: 'swarm-storage',
        title: 'Swarm Storage',
        summary: 'Volumes and persistent storage in Swarm.',
        children: [
          { id: 'volumes-per-service', title: 'Volumes Per Service Replica' },
          { id: 'shared-storage-considerations', title: 'Shared Storage Considerations' },
          { id: 'cluster-volumes-swarm', title: 'Cluster Volumes in Swarm' },
          { id: 'csi-plugins-swarm', title: 'CSI Plugins in Swarm' },
        ],
      },
      {
        id: 'swarm-secrets-configs',
        title: 'Swarm Secrets & Configs',
        summary: 'Secrets and configs management in Swarm.',
        children: [
          {
            id: 'swarm-secrets',
            title: 'Secrets',
            children: [
              { id: 'docker-secret-create', title: 'docker secret create' },
              { id: 'docker-secret-ls', title: 'docker secret ls' },
              { id: 'docker-secret-inspect', title: 'docker secret inspect' },
              { id: 'docker-secret-rm', title: 'docker secret rm' },
              { id: 'secret-mount-paths', title: '/run/secrets mount paths' },
              { id: 'rotating-swarm-secrets', title: 'Rotating Secrets' },
            ],
          },
          {
            id: 'swarm-configs',
            title: 'Configs',
            children: [
              { id: 'docker-config-create', title: 'docker config create' },
              { id: 'docker-config-ls', title: 'docker config ls' },
              { id: 'docker-config-inspect', title: 'docker config inspect' },
              { id: 'docker-config-rm', title: 'docker config rm' },
              { id: 'config-templating', title: 'Config Templating' },
            ],
          },
        ],
      },
      {
        id: 'node-labels-constraints',
        title: 'Node Labels & Constraints',
        summary: 'Targeting workloads with labels and constraints.',
        children: [
          { id: 'engine-labels', title: 'Engine Labels' },
          { id: 'node-labels', title: 'Node Labels' },
          { id: 'placement-constraints-syntax', title: 'Constraint Syntax (node.labels, node.role, node.id)' },
        ],
      },
      {
        id: 'service-updates',
        title: 'Service Updates',
        summary: 'Rolling updates, rollback and update policies.',
        children: [
          { id: 'rolling-updates', title: 'Rolling Updates' },
          { id: 'update-parallelism', title: 'Parallelism' },
          { id: 'update-delay', title: 'Update Delay' },
          { id: 'update-order', title: 'Order (start-first / stop-first)' },
          { id: 'update-failure-action', title: 'Failure Action (pause/continue/rollback)' },
          { id: 'update-monitor', title: 'Monitor Period' },
          { id: 'rollback-config', title: 'Rollback Config' },
          { id: 'rollback-parallelism', title: 'Rollback Parallelism' },
        ],
      },
      {
        id: 'service-placement',
        title: 'Service Placement',
        summary: 'Placement constraints and preferences.',
        children: [
          { id: 'placement-constraints', title: 'Placement Constraints' },
          { id: 'placement-preferences', title: 'Placement Preferences (spread)' },
          { id: 'replicas-max-per-node', title: '--replicas-max-per-node' },
          { id: 'placement-platforms', title: 'Platform Constraints' },
        ],
      },
      {
        id: 'swarm-vs-kubernetes',
        title: 'Swarm vs Kubernetes',
        summary: 'High-level comparison from a Docker perspective.',
        children: [
          { id: 'swarm-vs-k8s-feature-comparison', title: 'Feature Comparison' },
          { id: 'swarm-vs-k8s-operational-complexity', title: 'Operational Complexity' },
          { id: 'swarm-vs-k8s-when-to-pick', title: 'When to Choose Which' },
        ],
      },
    ],
  },

  /* ---------------- Stage 14: Docker Desktop & Developer Tooling ---------------- */
  {
    id: 'docker-desktop',
    level: 'intermediate',
    roots: [
      {
        id: 'docker-desktop-overview',
        title: 'Docker Desktop Overview',
        summary: 'Docker Desktop on Mac, Windows and Linux and its settings.',
        children: [
          { id: 'docker-desktop-mac', title: 'Docker Desktop on macOS' },
          { id: 'docker-desktop-windows', title: 'Docker Desktop on Windows' },
          { id: 'docker-desktop-linux', title: 'Docker Desktop on Linux' },
          { id: 'docker-desktop-licensing', title: 'Subscription & Licensing' },
          { id: 'docker-desktop-update-process', title: 'Updates & Release Channels' },
          {
            id: 'docker-desktop-settings',
            title: 'Settings',
            children: [
              { id: 'settings-general', title: 'General' },
              { id: 'settings-resources', title: 'Resources (CPU, Memory, Swap, Disk)' },
              { id: 'settings-file-sharing', title: 'File Sharing' },
              { id: 'settings-proxies', title: 'Proxies' },
              { id: 'settings-network', title: 'Network' },
              { id: 'settings-docker-engine', title: 'Docker Engine' },
              { id: 'settings-kubernetes', title: 'Kubernetes' },
              { id: 'settings-software-updates', title: 'Software Updates' },
              { id: 'settings-features-in-development', title: 'Features in Development' },
              { id: 'settings-builders', title: 'Builders' },
              { id: 'settings-extensions', title: 'Extensions' },
              { id: 'settings-mcp-toolkit', title: 'MCP Toolkit' },
            ],
          },
          { id: 'docker-desktop-dashboard', title: 'Desktop Dashboard' },
          { id: 'docker-desktop-volumes-ui', title: 'Volumes UI' },
          { id: 'docker-desktop-images-ui', title: 'Images UI' },
          { id: 'docker-desktop-containers-ui', title: 'Containers UI' },
          { id: 'docker-desktop-builds-ui', title: 'Builds UI' },
        ],
      },
      {
        id: 'docker-desktop-vm',
        title: 'Docker Desktop VM',
        summary: 'Virtualization backends on Mac, Windows and Linux.',
        children: [
          { id: 'virtualization-framework-mac', title: 'Apple Virtualization Framework' },
          { id: 'rosetta-x86-emulation-mac', title: 'Rosetta x86 Emulation (Apple Silicon)' },
          { id: 'wsl2-backend', title: 'WSL2 Backend' },
          { id: 'hyperv-backend', title: 'Hyper-V Backend' },
          { id: 'qemu-fallback-linux', title: 'QEMU Fallback (Linux)' },
          { id: 'vm-disk-image-management', title: 'Virtual Disk Image Management' },
          { id: 'desktop-cpu-arch-handling', title: 'CPU Architecture Handling' },
        ],
      },
      {
        id: 'desktop-extensions',
        title: 'Desktop Extensions',
        summary: 'Marketplace, common extensions and building your own.',
        children: [
          { id: 'extensions-marketplace', title: 'Extensions Marketplace' },
          {
            id: 'building-extensions',
            title: 'Building Extensions',
            children: [
              { id: 'extension-sdk', title: 'Extension SDK' },
              { id: 'extension-metadata', title: 'metadata.json' },
              { id: 'extension-frontend', title: 'Extension Frontend (React, etc.)' },
              { id: 'extension-backend-services', title: 'Backend Services' },
              { id: 'extension-vm-services', title: 'VM Services' },
              { id: 'extension-host-binaries', title: 'Host Binaries' },
              { id: 'publishing-extensions', title: 'Publishing to Marketplace' },
            ],
          },
          {
            id: 'common-extensions',
            title: 'Common Extensions',
            children: [
              { id: 'extension-portainer', title: 'Portainer' },
              { id: 'extension-disk-usage', title: 'Disk Usage' },
              { id: 'extension-logs-explorer', title: 'Logs Explorer' },
              { id: 'extension-resource-usage', title: 'Resource Usage' },
              { id: 'extension-snyk', title: 'Snyk' },
              { id: 'extension-trivy', title: 'Trivy' },
              { id: 'extension-redis-insight', title: 'Redis Insight' },
              { id: 'extension-microcks', title: 'Microcks' },
              { id: 'extension-min-io', title: 'MinIO' },
            ],
          },
        ],
      },
      {
        id: 'docker-desktop-kubernetes',
        title: 'Desktop Kubernetes',
        summary: 'Single-node Kubernetes built into Docker Desktop.',
        children: [
          { id: 'desktop-k8s-enable', title: 'Enabling Kubernetes' },
          { id: 'desktop-k8s-version', title: 'Selecting Kubernetes Version' },
          { id: 'desktop-k8s-reset', title: 'Resetting the Cluster' },
          { id: 'desktop-k8s-kubectl-context', title: 'docker-desktop kubectl Context' },
        ],
      },
      {
        id: 'dev-environments',
        title: 'Dev Environments',
        summary: 'Shareable, containerized development environments.',
        children: [
          { id: 'dev-environment-create', title: 'Creating a Dev Environment' },
          { id: 'dev-environment-from-repo', title: 'From Git Repository' },
          { id: 'dev-environment-share', title: 'Sharing Dev Environments' },
          { id: 'dev-environment-vscode-integration', title: 'VS Code Integration' },
          { id: 'dev-environment-jetbrains-integration', title: 'JetBrains Integration' },
          { id: 'dev-environment-compose-config', title: 'Compose Configuration' },
        ],
      },
      {
        id: 'docker-init',
        title: 'docker init',
        summary: 'Scaffolding Docker assets for new and existing projects.',
        children: [
          { id: 'docker-init-language-templates', title: 'Language Templates' },
          { id: 'docker-init-generated-files', title: 'Generated Files (Dockerfile, compose.yaml, .dockerignore)' },
          { id: 'docker-init-update-existing', title: 'Updating Existing Projects' },
        ],
      },
      {
        id: 'docker-debug',
        title: 'docker debug',
        summary: 'Debugging running or stopped containers without modifying them.',
        children: [
          { id: 'docker-debug-running', title: 'Debugging Running Containers' },
          { id: 'docker-debug-stopped', title: 'Debugging Stopped Containers' },
          { id: 'docker-debug-toolbox', title: 'Built-in Toolbox' },
          { id: 'docker-debug-install-extra', title: 'Installing Extra Tools On the Fly' },
          { id: 'docker-debug-image', title: 'Debugging Specific Images' },
          { id: 'docker-debug-troubleshooting', title: 'Troubleshooting Tips' },
        ],
      },
      {
        id: 'docker-ai-gordon',
        title: 'Docker AI & Gordon',
        summary: 'Docker\'s AI assistant and AI-powered Desktop features.',
        children: [
          { id: 'gordon-overview', title: 'Ask Gordon Overview' },
          { id: 'gordon-cli', title: 'docker ai / Gordon in CLI' },
          { id: 'gordon-desktop-integration', title: 'Gordon in Docker Desktop' },
          { id: 'gordon-tools', title: 'Tools Used by Gordon' },
          { id: 'gordon-context-sources', title: 'Context Sources (files, images, containers)' },
          { id: 'docker-mcp-toolkit', title: 'Docker MCP Toolkit' },
          { id: 'docker-mcp-catalog', title: 'Docker MCP Catalog' },
          { id: 'docker-mcp-gateway', title: 'Docker MCP Gateway' },
          { id: 'docker-mcp-server-builders', title: 'Building MCP Servers with Docker' },
          { id: 'gordon-privacy-data', title: 'Privacy & Data Handling' },
        ],
      },
      {
        id: 'enhanced-container-isolation',
        title: 'Enhanced Container Isolation',
        summary: 'ECI mode for tighter container isolation on Desktop.',
        children: [
          { id: 'eci-overview', title: 'ECI Overview' },
          { id: 'eci-enable', title: 'Enabling ECI' },
          { id: 'eci-sysbox-runtime', title: 'Sysbox Runtime under ECI' },
          { id: 'eci-limitations', title: 'ECI Limitations' },
          { id: 'eci-admin-policy', title: 'Admin Policies for ECI' },
        ],
      },
      {
        id: 'docker-desktop-admin',
        title: 'Docker Desktop Admin',
        summary: 'Admin console, Settings Management and access controls.',
        children: [
          { id: 'admin-console', title: 'Admin Console' },
          { id: 'settings-management', title: 'Settings Management (admin-settings.json)' },
          { id: 'registry-access-management', title: 'Registry Access Management' },
          { id: 'image-access-management', title: 'Image Access Management' },
          { id: 'sign-in-enforcement', title: 'Sign-In Enforcement' },
          { id: 'sso-saml-scim', title: 'SSO, SAML & SCIM' },
          { id: 'desktop-insights', title: 'Desktop Insights' },
          { id: 'audit-logs-desktop', title: 'Audit Logs' },
          { id: 'air-gapped-containers', title: 'Air-Gapped Containers' },
        ],
      },
      {
        id: 'resource-saver',
        title: 'Resource Saver',
        summary: 'Reducing CPU/memory use when Docker Desktop is idle.',
        children: [
          { id: 'resource-saver-overview', title: 'Resource Saver Overview' },
          { id: 'resource-saver-configuration', title: 'Configuration' },
        ],
      },
      {
        id: 'compose-bridge-desktop',
        title: 'Compose Bridge (Desktop)',
        summary: 'Using Compose Bridge from Docker Desktop.',
        children: [
          { id: 'compose-bridge-desktop-ui', title: 'Compose Bridge UI' },
          { id: 'compose-bridge-desktop-templates', title: 'Bridge Templates in Desktop' },
        ],
      },
    ],
  },

  /* ---------------- Stage 15: Developer Workflows & Testing ---------------- */
  {
    id: 'developer-workflows',
    level: 'intermediate',
    roots: [
      {
        id: 'local-dev-with-docker',
        title: 'Local Dev with Docker',
        summary: 'Dev vs prod images, source mounting and hot reload.',
        children: [
          { id: 'dev-vs-prod-images', title: 'Dev vs Prod Images' },
          { id: 'source-code-mounting', title: 'Source Code Mounting' },
          { id: 'hot-reload-patterns', title: 'Hot Reload Patterns' },
          { id: 'persisting-dev-data', title: 'Persisting Dev Data' },
          { id: 'multi-service-local-dev', title: 'Multi-Service Local Dev' },
          { id: 'shared-base-dev-images', title: 'Shared Base Dev Images' },
        ],
      },
      {
        id: 'dev-containers',
        title: 'Dev Containers',
        summary: 'devcontainer.json, features and editor integrations.',
        children: [
          {
            id: 'devcontainer-json',
            title: 'devcontainer.json',
            children: [
              { id: 'devcontainer-image-field', title: 'image' },
              { id: 'devcontainer-build-field', title: 'build' },
              { id: 'devcontainer-docker-compose-field', title: 'dockerComposeFile' },
              { id: 'devcontainer-features-field', title: 'features' },
              { id: 'devcontainer-customizations-field', title: 'customizations' },
              { id: 'devcontainer-mounts-field', title: 'mounts' },
              { id: 'devcontainer-forward-ports-field', title: 'forwardPorts' },
              { id: 'devcontainer-remote-user-field', title: 'remoteUser' },
              { id: 'devcontainer-workspace-folder-field', title: 'workspaceFolder' },
            ],
          },
          {
            id: 'devcontainer-features',
            title: 'Features',
            children: [
              { id: 'feature-installation', title: 'Installing Features' },
              { id: 'feature-development', title: 'Developing Custom Features' },
              { id: 'feature-publishing', title: 'Publishing Features' },
              { id: 'feature-dependencies', title: 'Feature Dependencies' },
            ],
          },
          {
            id: 'devcontainer-lifecycle-commands',
            title: 'Lifecycle Commands',
            children: [
              { id: 'init-command-dev', title: 'initializeCommand' },
              { id: 'on-create-command-dev', title: 'onCreateCommand' },
              { id: 'update-content-command-dev', title: 'updateContentCommand' },
              { id: 'post-create-command-dev', title: 'postCreateCommand' },
              { id: 'post-start-command-dev', title: 'postStartCommand' },
              { id: 'post-attach-command-dev', title: 'postAttachCommand' },
            ],
          },
          {
            id: 'editor-integrations',
            title: 'Editor Integrations',
            children: [
              { id: 'vscode-dev-containers', title: 'VS Code Dev Containers' },
              { id: 'cursor-dev-containers', title: 'Cursor Dev Containers' },
              { id: 'jetbrains-dev-containers', title: 'JetBrains IDEs' },
              { id: 'github-codespaces', title: 'GitHub Codespaces' },
            ],
          },
          { id: 'devcontainer-cli', title: 'devcontainer CLI' },
          { id: 'devcontainer-templates', title: 'Devcontainer Templates' },
        ],
      },
      {
        id: 'compose-watch-dev',
        title: 'Compose Watch for Dev',
        summary: 'Using Compose watch in day-to-day development.',
        children: [
          { id: 'compose-watch-sync-rules', title: 'Sync Rules' },
          { id: 'compose-watch-rebuild-rules', title: 'Rebuild Rules' },
          { id: 'compose-watch-debugging', title: 'Debugging While Watching' },
          { id: 'compose-watch-cross-os-tradeoffs', title: 'Cross-OS Trade-offs' },
        ],
      },
      {
        id: 'testcontainers',
        title: 'Testcontainers',
        summary: 'Programmatic ephemeral containers for tests.',
        children: [
          { id: 'testcontainers-overview', title: 'Testcontainers Overview' },
          {
            id: 'testcontainers-language-modules',
            title: 'Language Modules',
            children: [
              { id: 'testcontainers-java', title: 'Testcontainers Java' },
              { id: 'testcontainers-go', title: 'Testcontainers Go' },
              { id: 'testcontainers-node', title: 'Testcontainers Node.js' },
              { id: 'testcontainers-python', title: 'Testcontainers Python' },
              { id: 'testcontainers-dotnet', title: 'Testcontainers .NET' },
              { id: 'testcontainers-rust', title: 'Testcontainers Rust' },
              { id: 'testcontainers-ruby', title: 'Testcontainers Ruby' },
            ],
          },
          { id: 'testcontainers-cloud', title: 'Testcontainers Cloud' },
          { id: 'reusable-containers', title: 'Reusable Containers' },
          { id: 'testcontainers-modules', title: 'Modules (databases, queues, browsers)' },
          { id: 'testcontainers-ryuk', title: 'Ryuk Reaper' },
          { id: 'testcontainers-ci', title: 'Testcontainers in CI' },
        ],
      },
      {
        id: 'debugging-in-containers',
        title: 'Debugging in Containers',
        summary: 'Remote debugging, debug images and docker debug.',
        children: [
          {
            id: 'remote-debugging-attach',
            title: 'Remote Debugging Attach',
            children: [
              { id: 'remote-debug-node', title: 'Node.js (--inspect)' },
              { id: 'remote-debug-python-debugpy', title: 'Python (debugpy)' },
              { id: 'remote-debug-jvm', title: 'JVM (JDWP)' },
              { id: 'remote-debug-go-delve', title: 'Go (Delve)' },
              { id: 'remote-debug-dotnet-vsdbg', title: '.NET (vsdbg)' },
            ],
          },
          { id: 'debug-images-with-tools', title: 'Debug Images with Tools' },
          { id: 'debugging-with-docker-debug', title: 'Debugging with docker debug' },
          { id: 'exec-into-debugging', title: 'Exec-in Debugging' },
          { id: 'sidecar-debugging', title: 'Sidecar Debugging Containers' },
        ],
      },
      {
        id: 'production-parity',
        title: 'Production Parity',
        summary: 'Twelve-factor, env-driven config and stdout logs.',
        children: [
          { id: 'twelve-factor-app', title: 'Twelve-Factor App Principles' },
          { id: 'config-via-env', title: 'Config via Environment' },
          { id: 'logs-to-stdout', title: 'Logs to stdout/stderr' },
          { id: 'disposability-fast-startup', title: 'Disposability & Fast Startup' },
          { id: 'dev-prod-parity', title: 'Dev/Prod Parity' },
        ],
      },
      {
        id: 'docker-init-scaffolding',
        title: 'Docker Init Scaffolding',
        summary: 'Using docker init to bootstrap projects.',
        children: [
          { id: 'docker-init-node-template', title: 'Node.js Template' },
          { id: 'docker-init-python-template', title: 'Python Template' },
          { id: 'docker-init-go-template', title: 'Go Template' },
          { id: 'docker-init-java-template', title: 'Java Template' },
          { id: 'docker-init-rust-template', title: 'Rust Template' },
          { id: 'docker-init-php-template', title: 'PHP Template' },
          { id: 'docker-init-aspnet-template', title: 'ASP.NET Template' },
          { id: 'docker-init-other-templates', title: 'Other / Custom Templates' },
        ],
      },
    ],
  },
])
