import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 7: Container Networking ---------------- */
  {
    id: 'networking',
    level: 'intermediate',
    roots: [
      {
        id: 'docker-network-drivers',
        title: 'Network Drivers',
        summary: 'bridge, host, none, overlay, macvlan, ipvlan and plugins.',
        children: [
          {
            id: 'bridge-network',
            title: 'bridge Driver',
            children: [
              { id: 'default-bridge-network', title: 'Default bridge Network' },
              { id: 'user-defined-bridge', title: 'User-Defined bridge' },
              { id: 'bridge-options', title: 'bridge Driver Options' },
              { id: 'bridge-icc', title: 'Inter-Container Communication (icc)' },
              { id: 'bridge-ip-masquerade', title: 'IP Masquerade' },
            ],
          },
          { id: 'host-network', title: 'host Driver' },
          { id: 'none-network', title: 'none Driver' },
          {
            id: 'overlay-network',
            title: 'overlay Driver',
            children: [
              { id: 'overlay-vxlan', title: 'VXLAN Transport' },
              { id: 'overlay-encryption', title: 'Overlay Encryption' },
              { id: 'overlay-attachable', title: 'Attachable Overlay Networks' },
            ],
          },
          {
            id: 'macvlan-network',
            title: 'macvlan Driver',
            children: [
              { id: 'macvlan-bridge-mode', title: 'macvlan bridge mode' },
              { id: '802.1q-trunk-bridge-macvlan', title: '802.1q Trunk Bridge' },
            ],
          },
          { id: 'ipvlan-network', title: 'ipvlan Driver' },
          {
            id: 'third-party-network-plugins',
            title: 'Third-Party Network Plugins',
            children: [
              { id: 'weave-net-plugin', title: 'Weave Net' },
              { id: 'calico-plugin', title: 'Calico for Docker' },
              { id: 'cilium-plugin', title: 'Cilium for Docker (limited)' },
            ],
          },
        ],
      },
      {
        id: 'network-commands',
        title: 'Network Commands',
        summary: 'Creating, listing, inspecting and connecting networks.',
        children: [
          { id: 'docker-network-create', title: 'docker network create' },
          { id: 'docker-network-ls', title: 'docker network ls' },
          { id: 'docker-network-inspect', title: 'docker network inspect' },
          { id: 'docker-network-rm', title: 'docker network rm' },
          { id: 'docker-network-connect', title: 'docker network connect' },
          { id: 'docker-network-disconnect', title: 'docker network disconnect' },
          { id: 'docker-network-prune', title: 'docker network prune' },
        ],
      },
      {
        id: 'user-defined-networks',
        title: 'User-Defined Networks',
        summary: 'Default bridge vs user-defined and network aliases.',
        children: [
          { id: 'default-bridge-vs-user-defined', title: 'Default bridge vs User-Defined' },
          { id: 'network-aliases', title: 'Network Aliases (--network-alias)' },
          { id: 'multi-network-attachment', title: 'Multiple Network Attachment' },
          { id: 'internal-networks', title: 'Internal Networks (--internal)' },
        ],
      },
      {
        id: 'container-dns',
        title: 'Container DNS',
        summary: 'Embedded DNS server, DNS options and the hosts file.',
        children: [
          { id: 'embedded-dns-server', title: 'Embedded DNS Server' },
          {
            id: 'dns-options',
            title: 'DNS Options',
            children: [
              { id: 'dns-flag', title: '--dns' },
              { id: 'dns-search-flag', title: '--dns-search' },
              { id: 'dns-option-flag', title: '--dns-option' },
            ],
          },
          { id: 'hosts-file', title: '/etc/hosts & --add-host' },
          { id: 'service-discovery-dns', title: 'Service Discovery via DNS' },
        ],
      },
      {
        id: 'port-publishing',
        title: 'Port Publishing',
        summary: 'Port mapping syntax, random ports and publishing all ports.',
        children: [
          {
            id: 'port-mapping-syntax',
            title: 'Port Mapping Syntax',
            children: [
              { id: 'host-port-container-port', title: 'host:container' },
              { id: 'host-ip-port-binding', title: 'host_ip:host_port:container_port' },
              { id: 'protocol-suffix', title: '/tcp, /udp, /sctp' },
              { id: 'ipv6-port-publish', title: 'IPv6 Port Publishing' },
            ],
          },
          { id: 'random-host-ports', title: 'Random Host Ports' },
          { id: 'publish-all-ports', title: 'Publishing All Ports (-P)' },
          { id: 'expose-vs-publish', title: 'EXPOSE vs --publish' },
          { id: 'port-conflicts', title: 'Port Conflicts' },
        ],
      },
      {
        id: 'ip-addressing',
        title: 'IP Addressing',
        summary: 'IPAM, static IPs and IPv6 support.',
        children: [
          {
            id: 'ipam-config',
            title: 'IPAM Configuration',
            children: [
              { id: 'ipam-subnet', title: '--subnet' },
              { id: 'ipam-ip-range', title: '--ip-range' },
              { id: 'ipam-gateway', title: '--gateway' },
              { id: 'ipam-aux-address', title: '--aux-address' },
              { id: 'ipam-driver', title: '--ipam-driver' },
              { id: 'ipam-opt', title: '--ipam-opt' },
            ],
          },
          { id: 'static-ips', title: 'Static IPs (--ip / --ip6)' },
          { id: 'ipv6-support', title: 'IPv6 Support' },
          { id: 'mac-address-flag', title: 'MAC Address (--mac-address)' },
        ],
      },
      {
        id: 'network-internals',
        title: 'Network Internals',
        summary: 'iptables rules, linux bridges, veth pairs and netns.',
        level: 'advanced',
        children: [
          { id: 'iptables-rules', title: 'iptables Rules Created by Docker' },
          { id: 'linux-bridge-internals', title: 'Linux Bridge (docker0)' },
          { id: 'veth-pairs', title: 'veth Pairs' },
          { id: 'netns-namespaces', title: 'Network Namespaces (netns)' },
          { id: 'nftables-with-docker', title: 'nftables with Docker' },
          { id: 'libnetwork', title: 'libnetwork' },
          { id: 'cnm-architecture', title: 'CNM (Container Network Model)' },
        ],
      },
    ],
  },

  /* ---------------- Stage 8: Storage & Volumes ---------------- */
  {
    id: 'storage-volumes',
    level: 'intermediate',
    roots: [
      {
        id: 'volume-types',
        title: 'Volume Types',
        summary: 'Bind mounts, named volumes, anonymous volumes and tmpfs.',
        children: [
          { id: 'bind-mounts', title: 'Bind Mounts' },
          { id: 'named-volumes', title: 'Named Volumes' },
          { id: 'anonymous-volumes', title: 'Anonymous Volumes' },
          { id: 'tmpfs-mounts-volumes', title: 'tmpfs Mounts' },
          { id: 'image-volume-instruction', title: 'VOLUME-declared Volumes' },
        ],
      },
      {
        id: 'volume-commands',
        title: 'Volume Commands',
        summary: 'Creating, listing, inspecting and pruning volumes.',
        children: [
          { id: 'docker-volume-create', title: 'docker volume create' },
          { id: 'docker-volume-ls', title: 'docker volume ls' },
          { id: 'docker-volume-inspect', title: 'docker volume inspect' },
          { id: 'docker-volume-rm', title: 'docker volume rm' },
          { id: 'docker-volume-prune', title: 'docker volume prune' },
          { id: 'docker-volume-update', title: 'docker volume update (cluster volumes)' },
        ],
      },
      {
        id: 'mount-syntax',
        title: 'Mount Syntax',
        summary: '-v vs --mount and bind propagation.',
        children: [
          { id: 'v-flag-syntax', title: '-v / --volume Syntax' },
          {
            id: 'mount-flag-syntax',
            title: '--mount Syntax',
            children: [
              { id: 'mount-type', title: 'type=bind/volume/tmpfs' },
              { id: 'mount-source-target', title: 'source/target' },
              { id: 'mount-readonly', title: 'readonly' },
              { id: 'mount-volume-driver', title: 'volume-driver' },
              { id: 'mount-volume-opt', title: 'volume-opt' },
              { id: 'mount-consistency', title: 'consistency (Desktop)' },
            ],
          },
          {
            id: 'bind-propagation',
            title: 'Bind Propagation',
            children: [
              { id: 'bind-propagation-shared', title: 'shared' },
              { id: 'bind-propagation-slave', title: 'slave' },
              { id: 'bind-propagation-private', title: 'private' },
              { id: 'bind-propagation-rshared', title: 'rshared / rslave / rprivate' },
            ],
          },
          { id: 'selinux-volume-labels', title: 'SELinux Volume Labels (:z, :Z)' },
          { id: 'docker-desktop-file-sharing', title: 'Docker Desktop File Sharing' },
        ],
      },
      {
        id: 'storage-drivers',
        title: 'Storage Drivers',
        summary: 'overlay2, btrfs, zfs, vfs and choosing a driver.',
        level: 'advanced',
        children: [
          { id: 'overlay2-driver', title: 'overlay2' },
          { id: 'btrfs-driver', title: 'btrfs' },
          { id: 'zfs-driver', title: 'zfs' },
          { id: 'vfs-driver', title: 'vfs' },
          { id: 'devicemapper-deprecated', title: 'devicemapper (deprecated)' },
          { id: 'aufs-deprecated', title: 'aufs (deprecated)' },
          { id: 'fuse-overlayfs-rootless', title: 'fuse-overlayfs (rootless)' },
          { id: 'storage-driver-selection', title: 'Choosing a Storage Driver' },
          { id: 'storage-driver-config', title: 'Configuring Storage Driver' },
        ],
      },
      {
        id: 'volume-drivers',
        title: 'Volume Drivers & Plugins',
        summary: 'Local driver options, NFS, CIFS/SMB and cloud volume plugins.',
        children: [
          {
            id: 'local-driver-options',
            title: 'local Driver Options',
            children: [
              { id: 'local-driver-type', title: 'type=' },
              { id: 'local-driver-device', title: 'device=' },
              { id: 'local-driver-o', title: 'o= mount options' },
            ],
          },
          { id: 'nfs-volume-driver', title: 'NFS Volume Driver' },
          { id: 'cifs-smb-driver', title: 'CIFS/SMB Volume Driver' },
          { id: 'sshfs-volume-plugin', title: 'sshfs Volume Plugin' },
          { id: 'cloud-volume-plugins', title: 'Cloud Volume Plugins (overview)' },
          { id: 'docker-volume-plugin-api', title: 'Docker Volume Plugin API' },
          { id: 'cluster-volumes-csi', title: 'Cluster Volumes & CSI' },
        ],
      },
      {
        id: 'volume-backup-migration',
        title: 'Volume Backup & Migration',
        summary: 'Backing up, restoring and moving volumes between hosts.',
        children: [
          { id: 'volume-backup-tar-pattern', title: 'tar-based Backup Pattern' },
          { id: 'volume-restore-pattern', title: 'Volume Restore' },
          { id: 'volume-migration-hosts', title: 'Migrating Volumes Between Hosts' },
          { id: 'volume-snapshot-strategies', title: 'Snapshot Strategies' },
        ],
      },
      {
        id: 'disk-usage',
        title: 'Disk Usage & Cleanup',
        summary: 'system df, system prune, image and volume cleanup.',
        children: [
          { id: 'docker-system-df', title: 'docker system df' },
          { id: 'docker-system-prune', title: 'docker system prune' },
          { id: 'docker-system-events', title: 'docker system events' },
          { id: 'docker-system-info', title: 'docker system info' },
          { id: 'image-cleanup-strategies', title: 'Image Cleanup Strategies' },
          { id: 'volume-cleanup-strategies', title: 'Volume Cleanup Strategies' },
          { id: 'build-cache-cleanup', title: 'Build Cache Cleanup' },
          { id: 'log-file-rotation-cleanup', title: 'Log File Cleanup' },
        ],
      },
    ],
  },

  /* ---------------- Stage 9: Docker Compose ---------------- */
  {
    id: 'compose',
    level: 'intermediate',
    roots: [
      {
        id: 'compose-overview',
        title: 'Compose Overview',
        summary: 'v1 vs v2, the Compose Specification and where Compose fits.',
        children: [
          { id: 'compose-history-v1-v2', title: 'Compose v1 vs v2' },
          { id: 'compose-vs-swarm-vs-k8s', title: 'Compose vs Swarm vs Kubernetes' },
          { id: 'compose-specification-overview', title: 'Compose Specification' },
          { id: 'compose-plugin-cli', title: 'Compose Plugin (docker compose)' },
        ],
      },
      {
        id: 'compose-file',
        title: 'Compose File',
        summary: 'Top-level elements: services, networks, volumes, configs, secrets and extensions.',
        children: [
          {
            id: 'top-level-elements',
            title: 'Top-Level Elements',
            children: [
              { id: 'top-level-services', title: 'services' },
              { id: 'top-level-networks', title: 'networks' },
              { id: 'top-level-volumes', title: 'volumes' },
              { id: 'top-level-configs', title: 'configs' },
              { id: 'top-level-secrets', title: 'secrets' },
              { id: 'top-level-name', title: 'name' },
              { id: 'top-level-include', title: 'include' },
            ],
          },
          { id: 'version-deprecated', title: 'version (deprecated)' },
          { id: 'x-extensions', title: 'x-* Extension Fields' },
          { id: 'yaml-anchors-aliases', title: 'YAML Anchors & Aliases' },
          { id: 'compose-fragments', title: 'Compose Fragments' },
        ],
      },
      {
        id: 'service-configuration',
        title: 'Service Configuration',
        summary: 'Image, build, env, ports, volumes, depends_on, healthcheck and resources.',
        children: [
          {
            id: 'image-and-build',
            title: 'image & build',
            children: [
              { id: 'build-context-compose', title: 'build.context' },
              { id: 'build-dockerfile-compose', title: 'build.dockerfile' },
              { id: 'build-args-compose', title: 'build.args' },
              { id: 'build-target-compose', title: 'build.target' },
              { id: 'build-platforms-compose', title: 'build.platforms' },
              { id: 'build-cache-from-compose', title: 'build.cache_from / cache_to' },
              { id: 'build-secrets-compose', title: 'build.secrets' },
              { id: 'build-ssh-compose', title: 'build.ssh' },
              { id: 'build-tags-compose', title: 'build.tags' },
              { id: 'build-labels-compose', title: 'build.labels' },
              { id: 'build-no-cache-compose', title: 'build.no_cache' },
              { id: 'pull-policy-compose', title: 'pull_policy' },
            ],
          },
          { id: 'service-command-entrypoint', title: 'command & entrypoint' },
          {
            id: 'service-env',
            title: 'environment & env_file',
            children: [
              { id: 'environment-mapping', title: 'environment (mapping)' },
              { id: 'environment-list', title: 'environment (list)' },
              { id: 'env-file-required', title: 'env_file required:' },
              { id: 'env-file-format', title: 'env_file format' },
            ],
          },
          { id: 'service-ports', title: 'ports' },
          { id: 'service-expose', title: 'expose' },
          { id: 'service-volumes', title: 'volumes' },
          { id: 'service-volumes-from', title: 'volumes_from' },
          { id: 'service-networks', title: 'networks' },
          { id: 'service-network-mode', title: 'network_mode' },
          { id: 'service-hostname', title: 'hostname & domainname' },
          {
            id: 'depends-on',
            title: 'depends_on',
            children: [
              { id: 'depends-on-short', title: 'Short Form' },
              { id: 'depends-on-condition', title: 'condition:' },
              { id: 'depends-on-restart', title: 'restart:' },
              { id: 'depends-on-required', title: 'required:' },
            ],
          },
          { id: 'service-healthcheck', title: 'healthcheck' },
          { id: 'service-restart', title: 'restart' },
          {
            id: 'service-resources-deploy',
            title: 'deploy.resources',
            children: [
              { id: 'deploy-resources-limits', title: 'limits' },
              { id: 'deploy-resources-reservations', title: 'reservations' },
              { id: 'deploy-resources-devices', title: 'devices (GPU)' },
            ],
          },
          { id: 'service-deploy-other', title: 'deploy (mode, replicas, placement, update_config, rollback_config)' },
          { id: 'service-user-group', title: 'user & group_add' },
          { id: 'service-working-dir', title: 'working_dir' },
          { id: 'service-tty-stdin', title: 'tty & stdin_open' },
          { id: 'service-init', title: 'init' },
          { id: 'service-read-only', title: 'read_only' },
          { id: 'service-tmpfs', title: 'tmpfs' },
          { id: 'service-security-opt', title: 'security_opt' },
          { id: 'service-cap-add-drop', title: 'cap_add / cap_drop' },
          { id: 'service-privileged', title: 'privileged' },
          { id: 'service-ulimits-compose', title: 'ulimits' },
          { id: 'service-sysctls-compose', title: 'sysctls' },
          { id: 'service-devices-compose', title: 'devices' },
          { id: 'service-cgroup-compose', title: 'cgroup / cgroup_parent' },
          { id: 'service-isolation', title: 'isolation (Windows)' },
          { id: 'service-platform-compose', title: 'platform' },
          { id: 'service-labels-compose', title: 'labels' },
          { id: 'service-logging-compose', title: 'logging' },
          { id: 'service-secrets-compose', title: 'secrets' },
          { id: 'service-configs-compose', title: 'configs' },
          { id: 'service-stop-signal-grace-period', title: 'stop_signal & stop_grace_period' },
          { id: 'service-attach', title: 'attach' },
          { id: 'service-profiles', title: 'profiles' },
          { id: 'service-scale', title: 'scale' },
        ],
      },
      {
        id: 'compose-commands',
        title: 'Compose Commands',
        summary: 'up, down, build, ps, logs, exec, run and more.',
        children: [
          {
            id: 'compose-up',
            title: 'docker compose up',
            children: [
              { id: 'up-detach', title: '--detach / -d' },
              { id: 'up-build-flag', title: '--build' },
              { id: 'up-no-deps', title: '--no-deps' },
              { id: 'up-wait', title: '--wait / --wait-timeout' },
              { id: 'up-watch', title: '--watch' },
              { id: 'up-force-recreate', title: '--force-recreate' },
              { id: 'up-remove-orphans', title: '--remove-orphans' },
              { id: 'up-scale', title: '--scale' },
            ],
          },
          { id: 'compose-down', title: 'docker compose down' },
          { id: 'compose-build', title: 'docker compose build' },
          { id: 'compose-pull', title: 'docker compose pull' },
          { id: 'compose-push', title: 'docker compose push' },
          { id: 'compose-ps', title: 'docker compose ps' },
          { id: 'compose-logs', title: 'docker compose logs' },
          { id: 'compose-exec', title: 'docker compose exec' },
          { id: 'compose-run', title: 'docker compose run' },
          { id: 'compose-restart', title: 'docker compose restart' },
          { id: 'compose-stop-start', title: 'docker compose stop / start' },
          { id: 'compose-cp', title: 'docker compose cp' },
          { id: 'compose-config', title: 'docker compose config' },
          { id: 'compose-events', title: 'docker compose events' },
          { id: 'compose-images', title: 'docker compose images' },
          { id: 'compose-top', title: 'docker compose top' },
          { id: 'compose-stats', title: 'docker compose stats' },
          { id: 'compose-version-cmd', title: 'docker compose version' },
          { id: 'compose-watch-command', title: 'docker compose watch' },
          { id: 'compose-create', title: 'docker compose create' },
          { id: 'compose-kill', title: 'docker compose kill' },
          { id: 'compose-pause-unpause', title: 'docker compose pause / unpause' },
          { id: 'compose-port', title: 'docker compose port' },
          { id: 'compose-ls', title: 'docker compose ls' },
          { id: 'compose-wait', title: 'docker compose wait' },
          { id: 'compose-attach', title: 'docker compose attach' },
          { id: 'compose-alpha-cmds', title: 'docker compose alpha (preview commands)' },
        ],
      },
      {
        id: 'compose-profiles',
        title: 'Compose Profiles',
        summary: 'Activating service groups conditionally.',
        children: [
          { id: 'profiles-declaration', title: 'Declaring profiles:' },
          { id: 'profile-activation', title: 'Activating Profiles (--profile)' },
          { id: 'profiles-and-depends-on', title: 'Profiles & depends_on' },
        ],
      },
      {
        id: 'compose-include',
        title: 'Compose Include',
        summary: 'Composing files from multiple sources with include.',
        children: [
          { id: 'include-path', title: 'include.path' },
          { id: 'include-project-directory', title: 'include.project_directory' },
          { id: 'include-env-file', title: 'include.env_file' },
        ],
      },
      {
        id: 'compose-extends',
        title: 'Compose Extends',
        summary: 'Sharing configuration between services with extends.',
        children: [
          { id: 'extends-service', title: 'extends.service' },
          { id: 'extends-file', title: 'extends.file' },
          { id: 'extends-vs-include', title: 'extends vs include' },
        ],
      },
      {
        id: 'compose-override-files',
        title: 'Compose Override Files',
        summary: 'Multiple file merging and override precedence.',
        children: [
          { id: 'override-default-file', title: 'docker-compose.override.yml' },
          { id: 'override-multiple-files', title: 'docker compose -f a.yml -f b.yml' },
          { id: 'override-precedence', title: 'Override Precedence' },
          { id: 'merge-semantics', title: 'Merge Semantics (lists vs maps)' },
        ],
      },
      {
        id: 'variable-interpolation',
        title: 'Variable Interpolation',
        summary: 'env files, shell variables and default/required values.',
        children: [
          { id: 'env-file-default', title: '.env File (default)' },
          { id: 'shell-variables-compose', title: 'Shell Variables in Compose' },
          { id: 'interpolation-default-values', title: '${VAR:-default}' },
          { id: 'interpolation-required-values', title: '${VAR:?error}' },
          { id: 'interpolation-empty-default', title: '${VAR-default}' },
          { id: 'interpolation-escaping', title: 'Escaping ($$)' },
        ],
      },
      {
        id: 'compose-watch',
        title: 'Compose Watch',
        summary: 'Live sync and rebuilds with the watch feature.',
        children: [
          { id: 'watch-actions-sync', title: 'action: sync' },
          { id: 'watch-actions-rebuild', title: 'action: rebuild' },
          { id: 'watch-actions-sync-restart', title: 'action: sync+restart' },
          { id: 'watch-actions-sync-exec', title: 'action: sync+exec' },
          { id: 'watch-paths-targets', title: 'path / target' },
          { id: 'watch-ignore', title: 'ignore patterns' },
          { id: 'watch-include-x-develop', title: 'develop.watch top-level' },
        ],
      },
      {
        id: 'lifecycle-hooks',
        title: 'Lifecycle Hooks',
        summary: 'post_start and pre_stop hooks for services.',
        children: [
          { id: 'post-start-hooks', title: 'post_start hooks' },
          { id: 'pre-stop-hooks', title: 'pre_stop hooks' },
          { id: 'lifecycle-hook-options', title: 'Hook command/user/privileged/environment' },
        ],
      },
      {
        id: 'compose-bridge',
        title: 'Compose Bridge',
        summary: 'Converting Compose files to other formats (e.g. Kubernetes).',
        children: [
          { id: 'compose-bridge-convert', title: 'docker compose bridge convert' },
          { id: 'compose-bridge-templates', title: 'Custom Bridge Templates' },
          { id: 'compose-bridge-helm-output', title: 'Helm Output' },
          { id: 'compose-bridge-k8s-output', title: 'Kubernetes Manifest Output' },
        ],
      },
    ],
  },
])
