import { seedStages } from './seed.mjs'

seedStages([
  /* ---------------- Stage 3: Container Lifecycle & Runtime ---------------- */
  {
    id: 'container-lifecycle',
    level: 'beginner',
    roots: [
      {
        id: 'creating-containers',
        title: 'Creating & Running Containers',
        summary: 'docker run, create, start, stop, pause, kill and remove.',
        children: [
          {
            id: 'docker-run',
            title: 'docker run',
            children: [
              { id: 'detached-vs-foreground', title: 'Detached vs Foreground' },
              { id: 'interactive-tty', title: 'Interactive & TTY (-it)' },
              { id: 'name-flag', title: '--name' },
              { id: 'rm-flag', title: '--rm' },
              { id: 'detach-keys', title: 'Detach Keys' },
              { id: 'pull-policy-run', title: '--pull policy' },
            ],
          },
          { id: 'docker-create', title: 'docker create' },
          { id: 'docker-start', title: 'docker start' },
          { id: 'docker-stop', title: 'docker stop' },
          { id: 'docker-restart', title: 'docker restart' },
          { id: 'docker-pause-unpause', title: 'docker pause & unpause' },
          { id: 'docker-kill', title: 'docker kill' },
          { id: 'docker-rm', title: 'docker rm' },
          { id: 'docker-wait', title: 'docker wait' },
          { id: 'docker-update', title: 'docker update' },
        ],
      },
      {
        id: 'inspecting-containers',
        title: 'Inspecting Containers',
        summary: 'ps, inspect, logs, top, stats, port and diff.',
        children: [
          {
            id: 'docker-ps',
            title: 'docker ps',
            children: [
              { id: 'ps-filters', title: 'docker ps filters' },
              { id: 'ps-format', title: 'docker ps --format' },
              { id: 'ps-all-quiet', title: 'docker ps -a / -q' },
            ],
          },
          {
            id: 'docker-inspect',
            title: 'docker inspect',
            children: [
              { id: 'inspect-format-template', title: '--format Go templates' },
              { id: 'inspect-size', title: '--size' },
              { id: 'inspect-types', title: '--type (container/image/...)' },
            ],
          },
          {
            id: 'docker-logs',
            title: 'docker logs',
            children: [
              { id: 'logs-follow', title: '--follow / -f' },
              { id: 'logs-tail', title: '--tail' },
              { id: 'logs-since-until', title: '--since / --until' },
              { id: 'logs-timestamps', title: '--timestamps' },
              { id: 'logs-details', title: '--details' },
            ],
          },
          { id: 'docker-top', title: 'docker top' },
          { id: 'docker-stats', title: 'docker stats' },
          { id: 'docker-port', title: 'docker port' },
          { id: 'docker-diff', title: 'docker diff' },
        ],
      },
      {
        id: 'interacting-with-containers',
        title: 'Interacting with Containers',
        summary: 'exec, attach, cp, commit and rename.',
        children: [
          {
            id: 'docker-exec',
            title: 'docker exec',
            children: [
              { id: 'exec-interactive', title: 'Interactive exec (-it)' },
              { id: 'exec-user', title: '--user in exec' },
              { id: 'exec-workdir', title: '--workdir in exec' },
              { id: 'exec-env', title: 'Environment in exec' },
              { id: 'exec-detach', title: 'Detached exec (-d)' },
            ],
          },
          { id: 'docker-attach', title: 'docker attach' },
          { id: 'docker-cp', title: 'docker cp' },
          { id: 'docker-commit', title: 'docker commit' },
          { id: 'docker-rename', title: 'docker rename' },
        ],
      },
      {
        id: 'resource-constraints',
        title: 'Resource Constraints',
        summary: 'CPU, memory, blkio, pids, swap, ulimits and GPU.',
        level: 'intermediate',
        children: [
          {
            id: 'cpu-limits',
            title: 'CPU Limits',
            children: [
              { id: 'cpus-flag', title: '--cpus' },
              { id: 'cpu-shares', title: '--cpu-shares' },
              { id: 'cpu-period-quota', title: '--cpu-period / --cpu-quota' },
              { id: 'cpuset-cpus', title: '--cpuset-cpus' },
              { id: 'cpuset-mems', title: '--cpuset-mems' },
              { id: 'cpu-rt-options', title: '--cpu-rt-runtime / --cpu-rt-period' },
            ],
          },
          {
            id: 'memory-limits',
            title: 'Memory Limits',
            children: [
              { id: 'memory-flag', title: '--memory / -m' },
              { id: 'memory-reservation', title: '--memory-reservation' },
              { id: 'memory-swap', title: '--memory-swap' },
              { id: 'memory-swappiness', title: '--memory-swappiness' },
              { id: 'oom-kill-disable', title: '--oom-kill-disable' },
              { id: 'oom-score-adj', title: '--oom-score-adj' },
              { id: 'kernel-memory', title: '--kernel-memory (legacy)' },
            ],
          },
          {
            id: 'blkio-limits',
            title: 'Block I/O Limits',
            children: [
              { id: 'blkio-weight', title: '--blkio-weight' },
              { id: 'device-read-bps', title: '--device-read-bps' },
              { id: 'device-write-bps', title: '--device-write-bps' },
              { id: 'device-read-iops', title: '--device-read-iops' },
              { id: 'device-write-iops', title: '--device-write-iops' },
            ],
          },
          { id: 'pids-limits', title: 'PIDs Limit (--pids-limit)' },
          {
            id: 'ulimits',
            title: 'ulimits',
            children: [
              { id: 'ulimit-nofile', title: 'nofile' },
              { id: 'ulimit-nproc', title: 'nproc' },
              { id: 'ulimit-core', title: 'core' },
              { id: 'ulimit-stack', title: 'stack' },
            ],
          },
          {
            id: 'gpu-support',
            title: 'GPU Support',
            children: [
              { id: 'gpus-flag', title: '--gpus flag' },
              { id: 'device-cgroup-rule', title: '--device-cgroup-rule' },
              { id: 'device-flag', title: '--device flag' },
              { id: 'gpu-capabilities', title: 'GPU capabilities' },
            ],
          },
        ],
      },
      {
        id: 'container-runtime-options',
        title: 'Container Runtime Options',
        summary: 'Environment, entrypoint overrides, read-only, tmpfs, init and signals.',
        children: [
          {
            id: 'environment-variables-runtime',
            title: 'Environment Variables',
            children: [
              { id: 'env-flag', title: '--env / -e' },
              { id: 'env-file-flag', title: '--env-file' },
              { id: 'env-from-shell', title: 'Inheriting from the shell' },
            ],
          },
          { id: 'hostname-domain', title: 'Hostname & Domain (--hostname / --domainname)' },
          { id: 'working-directory-flag', title: 'Working Directory (--workdir / -w)' },
          { id: 'user-flag', title: 'User & Group (--user / -u)' },
          { id: 'entrypoint-override', title: 'Entrypoint Override (--entrypoint)' },
          { id: 'command-override', title: 'Command Override (args after image)' },
          { id: 'read-only-rootfs', title: 'Read-only Root Filesystem (--read-only)' },
          { id: 'tmpfs-mounts-run', title: 'tmpfs Mounts (--tmpfs)' },
          { id: 'init-process-flag', title: 'PID 1 Init Process (--init)' },
          {
            id: 'signals-handling',
            title: 'Process Signals',
            children: [
              { id: 'signal-forwarding', title: 'Signal Forwarding' },
              { id: 'sigterm-vs-sigkill', title: 'SIGTERM vs SIGKILL' },
              { id: 'pid1-signal-handling', title: 'PID 1 & Signal Handling' },
            ],
          },
          { id: 'stop-signal', title: 'Stop Signal (--stop-signal)' },
          { id: 'stop-timeout', title: 'Stop Timeout (--stop-timeout)' },
          { id: 'platform-flag-run', title: 'Platform Selection (--platform)' },
          { id: 'attach-stdio', title: '--attach / stdio streams' },
          { id: 'sysctl-flag', title: '--sysctl' },
          { id: 'shm-size', title: '--shm-size' },
          { id: 'security-opt-flag', title: '--security-opt' },
          { id: 'cap-add-drop', title: '--cap-add / --cap-drop' },
          { id: 'privileged-flag', title: '--privileged' },
          { id: 'userns-flag', title: '--userns' },
          { id: 'log-opt-runtime', title: '--log-driver / --log-opt' },
          { id: 'isolation-flag', title: '--isolation (Windows)' },
        ],
      },
      {
        id: 'container-health',
        title: 'Container Health & Restart',
        summary: 'Healthchecks, restart policies and exit codes.',
        children: [
          {
            id: 'healthcheck-flag',
            title: 'Healthcheck Flags',
            children: [
              { id: 'health-cmd', title: '--health-cmd' },
              { id: 'health-interval', title: '--health-interval' },
              { id: 'health-timeout', title: '--health-timeout' },
              { id: 'health-retries', title: '--health-retries' },
              { id: 'health-start-period', title: '--health-start-period' },
              { id: 'health-start-interval', title: '--health-start-interval' },
              { id: 'no-healthcheck', title: '--no-healthcheck' },
            ],
          },
          {
            id: 'restart-policies',
            title: 'Restart Policies',
            children: [
              { id: 'restart-no', title: 'no' },
              { id: 'restart-on-failure', title: 'on-failure' },
              { id: 'restart-always', title: 'always' },
              { id: 'restart-unless-stopped', title: 'unless-stopped' },
              { id: 'restart-max-retries', title: '--restart=on-failure:N' },
            ],
          },
          { id: 'container-exit-codes', title: 'Container Exit Codes' },
          { id: 'oom-killed-state', title: 'OOMKilled State' },
        ],
      },
    ],
  },

  /* ---------------- Stage 4: Working with Images ---------------- */
  {
    id: 'working-with-images',
    level: 'beginner',
    roots: [
      {
        id: 'image-anatomy',
        title: 'Image Anatomy',
        summary: 'Layers, manifests, config blobs, indexes and digests.',
        children: [
          { id: 'image-layers', title: 'Image Layers' },
          { id: 'image-manifests', title: 'Image Manifest' },
          { id: 'image-config-blob', title: 'Image Config Blob' },
          { id: 'image-index-manifest-list', title: 'Image Index / Manifest List' },
          { id: 'image-digests', title: 'Image Digests (content addressability)' },
          { id: 'image-history-rootfs', title: 'Image History & rootfs' },
          { id: 'media-types-oci', title: 'OCI Media Types' },
          { id: 'image-labels-annotations', title: 'Labels & Annotations' },
        ],
      },
      {
        id: 'image-tagging',
        title: 'Image Tagging',
        summary: 'Naming, the latest tag and immutable tag practices.',
        children: [
          { id: 'image-naming-convention', title: 'Image Naming Convention' },
          { id: 'tag-syntax', title: 'Tag Syntax (registry/namespace/repo:tag)' },
          { id: 'docker-tag-command', title: 'docker tag' },
          { id: 'latest-tag-pitfalls', title: '"latest" Tag Pitfalls' },
          { id: 'immutable-tags', title: 'Immutable Tags' },
          { id: 'semantic-version-tags', title: 'Semantic Version Tags' },
          { id: 'rolling-vs-pinned-tags', title: 'Rolling vs Pinned Tags' },
          { id: 'digest-pinning', title: 'Digest Pinning (image@sha256:...)' },
        ],
      },
      {
        id: 'pulling-pushing-images',
        title: 'Pulling & Pushing Images',
        summary: 'docker pull, push and search.',
        children: [
          {
            id: 'docker-pull',
            title: 'docker pull',
            children: [
              { id: 'pull-all-tags', title: '--all-tags / -a' },
              { id: 'pull-platform', title: '--platform' },
              { id: 'pull-disable-content-trust', title: '--disable-content-trust' },
              { id: 'pull-quiet', title: '--quiet / -q' },
            ],
          },
          {
            id: 'docker-push',
            title: 'docker push',
            children: [
              { id: 'push-all-tags', title: '--all-tags / -a' },
              { id: 'push-disable-content-trust-push', title: '--disable-content-trust' },
              { id: 'push-quiet', title: '--quiet / -q' },
            ],
          },
          { id: 'docker-search', title: 'docker search' },
          { id: 'docker-login-images', title: 'docker login (image auth)' },
          { id: 'docker-logout-images', title: 'docker logout' },
        ],
      },
      {
        id: 'image-management',
        title: 'Image Management',
        summary: 'Listing, removing, history, inspect, save, load, export, import.',
        children: [
          {
            id: 'docker-images',
            title: 'docker images',
            children: [
              { id: 'images-filters', title: '--filter' },
              { id: 'images-format', title: '--format' },
              { id: 'images-all-digests', title: '--all / --digests' },
            ],
          },
          { id: 'docker-rmi', title: 'docker rmi' },
          { id: 'docker-image-prune', title: 'docker image prune' },
          { id: 'docker-image-history', title: 'docker image history' },
          { id: 'docker-image-inspect', title: 'docker image inspect' },
          { id: 'docker-save', title: 'docker save' },
          { id: 'docker-load', title: 'docker load' },
          { id: 'docker-export', title: 'docker export' },
          { id: 'docker-import', title: 'docker import' },
          { id: 'docker-image-tag', title: 'docker image tag' },
        ],
      },
      {
        id: 'multi-platform-images',
        title: 'Multi-Platform Images',
        summary: 'Architectures, manifest lists and QEMU/binfmt.',
        level: 'intermediate',
        children: [
          {
            id: 'platform-architectures',
            title: 'Platform Architectures',
            children: [
              { id: 'amd64-arch', title: 'amd64 / x86_64' },
              { id: 'arm64-arch', title: 'arm64 / aarch64' },
              { id: 'armv7-arch', title: 'arm/v7' },
              { id: 'armv6-arch', title: 'arm/v6' },
              { id: 'ppc64le-arch', title: 'ppc64le' },
              { id: 's390x-arch', title: 's390x' },
              { id: 'riscv64-arch', title: 'riscv64' },
              { id: 'windows-platforms', title: 'Windows Platforms' },
            ],
          },
          { id: 'manifest-lists-mp', title: 'Manifest Lists' },
          { id: 'docker-manifest-cli', title: 'docker manifest CLI' },
          {
            id: 'qemu-binfmt',
            title: 'QEMU & binfmt_misc',
            children: [
              { id: 'binfmt-installer', title: 'tonistiigi/binfmt installer' },
              { id: 'qemu-user-static', title: 'qemu-user-static' },
            ],
          },
          { id: 'platform-emulation-vs-native', title: 'Emulation vs Native Build' },
        ],
      },
      {
        id: 'image-caching',
        title: 'Image Caching',
        summary: 'How images are cached locally and how layers are reused.',
        children: [
          { id: 'local-image-cache', title: 'Local Image Cache' },
          { id: 'pull-layer-deduplication', title: 'Pull Layer Deduplication' },
          { id: 'image-store-on-disk', title: 'Image Store on Disk' },
          { id: 'pruning-cache', title: 'Pruning Cached Images' },
        ],
      },
    ],
  },
])
