import { addEnterpriseStages } from '../_shared/enterpriseAdditions.mjs'

addEnterpriseStages({
  subjectId: 'aws',
  stages: [
    {
      id: 'enterprise-delivery',
      title: 'Enterprise Development & Enablement',
      summary: 'Strategy, governance, platform and enablement for delivering AWS workloads at enterprise scale.',
      tag: 'enterprise-delivery',
      nodes: [
        {
          id: 'enterprise-cloud-strategy',
          title: 'Enterprise Cloud Strategy & Operating Model',
          summary: 'Cloud strategy, operating model and cloud center of excellence on AWS.',
          level: 'advanced',
          children: [
            { id: 'cloud-center-of-excellence', title: 'Cloud Center of Excellence (CCoE)' },
            { id: 'cloud-operating-model', title: 'Cloud Target Operating Model' },
            { id: 'cloud-strategy-roadmap', title: 'Cloud Strategy & Roadmap' },
            { id: 'cloud-portfolio-strategy', title: 'Cloud Workload Portfolio Strategy' },
            { id: 'executive-sponsorship', title: 'Executive Sponsorship & Steering' },
            { id: 'cloud-maturity-model', title: 'Cloud Maturity Model & Assessment' },
            { id: 'value-streams-mapping', title: 'Value Streams & Capability Mapping' },
            { id: 'multi-cloud-strategy', title: 'Multi-Cloud / Hybrid Strategy' },
          ],
        },
        {
          id: 'discovery-requirements',
          title: 'Discovery & Requirements Engineering',
          summary: 'Workload discovery, business case and requirements engineering on AWS.',
          level: 'intermediate',
          children: [
            { id: 'workload-discovery', title: 'Workload Discovery & Inventory' },
            { id: 'business-case-roi', title: 'Business Case & ROI Modeling' },
            { id: 'feasibility-assessment', title: 'Feasibility & Risk Assessment' },
            { id: 'stakeholder-management', title: 'Stakeholder Mapping & Management' },
            { id: 'requirements-elicitation', title: 'Requirements Elicitation Techniques' },
            { id: 'success-criteria-kpis', title: 'Success Criteria, OKRs & KPIs' },
            { id: 'cloud-readiness-assessment', title: 'Cloud Readiness Assessment' },
            { id: 'tco-modeling', title: 'TCO Modeling & Sensitivity Analysis' },
          ],
        },
        {
          id: 'solution-architecture-process',
          title: 'Solution Architecture Process',
          summary: 'Architecture decisions, design reviews and reference blueprints on AWS.',
          level: 'advanced',
          children: [
            { id: 'architecture-decision-records', title: 'Architecture Decision Records (ADRs)' },
            { id: 'design-review-board', title: 'Design Review Board (DRB)' },
            { id: 'reference-architectures', title: 'Reference Architectures Catalog' },
            { id: 'solution-blueprints', title: 'Solution Blueprints & Landing Zones' },
            { id: 'non-functional-requirements', title: 'Non-Functional Requirements (NFRs)' },
            { id: 'capacity-planning', title: 'Capacity & Quota Planning' },
            { id: 'threat-modeling-process', title: 'Threat Modeling Process (STRIDE)' },
            { id: 'tech-radar', title: 'Technology Radar Practice' },
            { id: 'architecture-review-cadence', title: 'Architecture Review Cadence' },
          ],
        },
        {
          id: 'engineering-standards',
          title: 'Engineering Standards & Quality',
          summary: 'Coding, IaC and prompt standards, review process, quality gates.',
          level: 'intermediate',
          children: [
            { id: 'iac-coding-standards', title: 'IaC & Coding Standards' },
            { id: 'cloud-naming-conventions', title: 'Cloud Naming & Tagging Conventions' },
            { id: 'peer-review-process', title: 'Peer Review & Code Review Process' },
            { id: 'definition-of-done', title: 'Definition of Done & Ready' },
            { id: 'quality-gates', title: 'Quality Gates & Build Promotion Rules' },
            { id: 'architectural-fitness-functions', title: 'Architectural Fitness Functions' },
            { id: 'dependency-policy', title: 'Dependency & Module Policy' },
            { id: 'engineering-scorecards', title: 'Engineering Scorecards & Health Metrics' },
          ],
        },
        {
          id: 'developer-platform',
          title: 'Developer Platform & Paved Roads',
          summary: 'Internal developer platform, golden paths and shared modules for AWS teams.',
          level: 'advanced',
          children: [
            { id: 'internal-developer-portal', title: 'Internal Developer Portal (IDP)' },
            { id: 'cloud-starter-templates', title: 'Cloud Starter Templates & Scaffolds' },
            { id: 'golden-paths', title: 'Golden Paths for Cloud Teams' },
            { id: 'shared-iac-modules', title: 'Shared IaC Modules & Constructs' },
            { id: 'service-catalog-program', title: 'Service Catalog Program' },
            { id: 'self-service-tooling', title: 'Self-Service Tooling & Provisioning' },
            { id: 'inner-source-program', title: 'Inner-Source Program' },
            { id: 'developer-experience-metrics', title: 'Developer Experience (DevEx) Metrics' },
            { id: 'platform-as-product', title: 'Platform-as-a-Product Mindset' },
          ],
        },
        {
          id: 'procurement-sourcing',
          title: 'Vendor, Marketplace & Procurement',
          summary: 'Sourcing SaaS, partners and marketplace offerings through enterprise procurement.',
          level: 'advanced',
          children: [
            { id: 'vendor-due-diligence', title: 'Vendor Due Diligence' },
            { id: 'aws-marketplace-governance', title: 'AWS Marketplace Governance' },
            { id: 'build-vs-buy', title: 'Build vs Buy vs Partner Analysis' },
            { id: 'enterprise-agreement-management', title: 'Enterprise Agreement Management' },
            { id: 'data-processing-agreements', title: 'Data Processing Agreements (DPAs)' },
            { id: 'contract-sla-negotiation', title: 'Contract & SLA Negotiation' },
            { id: 'partner-network-management', title: 'AWS Partner Network Management' },
          ],
        },
        {
          id: 'enterprise-data-governance',
          title: 'Enterprise Data Governance',
          summary: 'Data classification, residency, stewardship and master data on AWS.',
          level: 'advanced',
          children: [
            { id: 'data-classification', title: 'Data Classification & Sensitivity Tagging' },
            { id: 'data-residency-controls', title: 'Data Residency & Sovereignty Controls' },
            { id: 'data-lineage', title: 'Data Lineage & Provenance' },
            { id: 'data-stewardship', title: 'Data Stewardship & Ownership' },
            { id: 'data-quality-management', title: 'Data Quality Management' },
            { id: 'consent-management', title: 'Consent & Preference Management' },
            { id: 'master-data-management', title: 'Master & Reference Data Management' },
            { id: 'data-contracts', title: 'Data Contracts & Producer-Consumer SLAs' },
          ],
        },
        {
          id: 'risk-compliance-program',
          title: 'Enterprise Risk & Compliance Program',
          summary: 'Risk registers, audit readiness and certification programs for AWS workloads.',
          level: 'advanced',
          children: [
            { id: 'enterprise-risk-register', title: 'Enterprise Cloud Risk Register' },
            { id: 'control-libraries', title: 'Control Libraries & Mappings (NIST/ISO/CIS)' },
            { id: 'third-party-risk-management', title: 'Third-Party Risk Management (TPRM)' },
            { id: 'audit-readiness', title: 'Audit Readiness & Evidence Collection' },
            { id: 'certifications-soc2-iso', title: 'SOC 2 / ISO 27001 / FedRAMP Programs' },
            { id: 'pci-hipaa-program', title: 'PCI-DSS / HIPAA Program for AWS' },
            { id: 'regulatory-reporting', title: 'Regulatory Reporting & Disclosures' },
            { id: 'continuous-compliance-program', title: 'Continuous Compliance Program' },
          ],
        },
        {
          id: 'enterprise-finops-program',
          title: 'Enterprise FinOps Program',
          summary: 'FinOps program: allocation, forecasting, unit economics and governance.',
          level: 'advanced',
          children: [
            { id: 'cost-allocation-chargeback', title: 'Cost Allocation, Showback & Chargeback' },
            { id: 'budget-governance', title: 'Budget Governance & Guardrails' },
            { id: 'cost-forecasting', title: 'Cost Forecasting & Modeling' },
            { id: 'unit-economics', title: 'Unit Economics per Workload / Customer' },
            { id: 'rate-card-management', title: 'Internal Rate Card Management' },
            { id: 'commitments-discounts', title: 'Commitments, RIs, Savings Plans Governance' },
            { id: 'finops-reporting', title: 'FinOps Reporting & Reviews' },
            { id: 'finops-personas-roles', title: 'FinOps Personas & Roles' },
          ],
        },
        {
          id: 'program-portfolio-management',
          title: 'Program & Portfolio Management',
          summary: 'Intake, prioritization and portfolio governance for AWS initiatives.',
          level: 'intermediate',
          children: [
            { id: 'intake-prioritization', title: 'Demand Intake & Prioritization' },
            { id: 'okrs-roadmaps', title: 'OKRs & Roadmaps' },
            { id: 'dependency-mapping', title: 'Cross-Team Dependency Mapping' },
            { id: 'status-reporting', title: 'Status Reporting & Cadences' },
            { id: 'benefits-realization', title: 'Benefits Realization Tracking' },
            { id: 'agile-at-scale', title: 'Agile-at-Scale (SAFe / LeSS / Scrum@Scale)' },
            { id: 'portfolio-rebalancing', title: 'Portfolio Rebalancing & Stage Gates' },
          ],
        },
        {
          id: 'change-enablement',
          title: 'Change Enablement & Culture',
          summary: 'Organizational change, training and adoption of cloud practices.',
          level: 'intermediate',
          children: [
            { id: 'org-change-management', title: 'Organizational Change Management (OCM)' },
            { id: 'communications-strategy', title: 'Communications & Narrative Strategy' },
            { id: 'training-curricula', title: 'Training Curricula & Certifications' },
            { id: 'communities-of-practice', title: 'Communities of Practice (CoPs)' },
            { id: 'cloud-champions-network', title: 'Cloud Champions Network' },
            { id: 'adoption-metrics', title: 'Adoption & Stickiness Metrics' },
            { id: 'workforce-reskilling', title: 'Workforce Reskilling & Job Redesign' },
          ],
        },
        {
          id: 'legal-ethical-governance',
          title: 'Legal & Ethical Governance',
          summary: 'IP, licensing, acceptable use and ethical cloud governance.',
          level: 'advanced',
          children: [
            { id: 'ip-and-licensing', title: 'IP, Copyright & OSS Licensing' },
            { id: 'liability-frameworks', title: 'Liability & Indemnity Frameworks' },
            { id: 'acceptable-use-policy', title: 'Acceptable Use Policy (AUP)' },
            { id: 'responsible-disclosure-policy', title: 'Responsible Disclosure & VDP' },
            { id: 'dpia-process', title: 'Data Protection Impact Assessment (DPIA)' },
            { id: 'open-source-governance', title: 'Open-Source Use Governance' },
            { id: 'sustainability-governance', title: 'Sustainability & Carbon Governance' },
          ],
        },
      ],
    },
    {
      id: 'production-lifecycle',
      title: 'Production-Grade Application Lifecycle',
      summary: 'End-to-end delivery lifecycle for production-grade AWS workloads.',
      tag: 'production-lifecycle',
      nodes: [
        {
          id: 'requirements-design-phase',
          title: 'Requirements & Design Phase',
          summary: 'Discovery, requirements, design and sign-off for new AWS workloads.',
          level: 'intermediate',
          children: [
            { id: 'discovery-workshops', title: 'Discovery Workshops & Event Storming' },
            { id: 'jobs-and-personas', title: 'Personas & Job Stories' },
            { id: 'journey-mapping', title: 'Journey Mapping & Service Blueprinting' },
            { id: 'prd-templates', title: 'PRDs, Spec & Brief Templates' },
            { id: 'lo-fi-prototyping', title: 'Lo-Fi Prototyping for Workloads' },
            { id: 'design-sign-off', title: 'Design Sign-Off & Acceptance' },
            { id: 'risk-impact-assessment', title: 'Risk & Impact Assessment for Workloads' },
          ],
        },
        {
          id: 'implementation-build-phase',
          title: 'Implementation & Build Phase',
          summary: 'Build discipline, branching, code ownership and refactoring practice.',
          level: 'intermediate',
          children: [
            { id: 'pairing-and-mobbing', title: 'Pairing, Mobbing & Ensemble Programming' },
            { id: 'trunk-based-development', title: 'Trunk-Based Development' },
            { id: 'branching-strategy', title: 'Branching Strategy & Release Branches' },
            { id: 'commit-conventions', title: 'Commit Conventions & Conventional Commits' },
            { id: 'code-ownership-codeowners', title: 'Code Ownership & CODEOWNERS' },
            { id: 'refactoring-discipline', title: 'Refactoring Discipline' },
            { id: 'feature-toggling-build', title: 'Feature Toggling During Build' },
          ],
        },
        {
          id: 'testing-validation-phase',
          title: 'Testing & Validation Phase',
          summary: 'End-to-end test strategy, performance, security and acceptance programs.',
          level: 'intermediate',
          children: [
            { id: 'test-strategy-pyramid', title: 'Test Strategy & Pyramid for AWS Workloads' },
            { id: 'iac-testing-program', title: 'IaC Testing Program (Static, Unit, Integration)' },
            { id: 'contract-testing-process', title: 'Contract Testing Process (PACT/CDC)' },
            { id: 'performance-test-program', title: 'Performance & Load Test Program' },
            { id: 'security-test-program', title: 'Security Test Program (SAST/DAST/IAST)' },
            { id: 'compliance-test-program', title: 'Compliance & Policy Test Program' },
            { id: 'uat-process', title: 'User Acceptance Testing (UAT) Process' },
            { id: 'acceptance-criteria-bdd', title: 'Acceptance Criteria & BDD' },
            { id: 'game-day-testing', title: 'Game Days & Resilience Drills' },
          ],
        },
        {
          id: 'cicd-release-engineering',
          title: 'CI/CD & Release Engineering',
          summary: 'Pipelines, environment strategy, feature flags and supply-chain security.',
          level: 'advanced',
          children: [
            { id: 'cicd-pipeline-design', title: 'CI/CD Pipeline Design on AWS' },
            { id: 'build-promotion-stages', title: 'Build Promotion & Environment Stages' },
            { id: 'env-strategy-paths', title: 'Environment Strategy (Dev → Staging → Prod)' },
            { id: 'release-trains', title: 'Release Trains & Cadence' },
            { id: 'feature-flag-management', title: 'Feature Flag Management at Scale' },
            { id: 'secrets-management-process', title: 'Secrets Management Process' },
            { id: 'supply-chain-security-program', title: 'Supply-Chain Security (SLSA/SBOM)' },
            { id: 'artifact-versioning-strategy', title: 'Artifact & Image Versioning Strategy' },
          ],
        },
        {
          id: 'production-readiness',
          title: 'Production Readiness & Launch',
          summary: 'PRR, launch checklists, gradual rollout and rollback strategy.',
          level: 'advanced',
          children: [
            { id: 'production-readiness-review', title: 'Production Readiness Review (PRR)' },
            { id: 'launch-checklist', title: 'Launch Readiness Checklist' },
            { id: 'go-no-go-criteria', title: 'Go / No-Go Decision Criteria' },
            { id: 'dark-launches', title: 'Dark Launches & Shadow Mode' },
            { id: 'gradual-rollout-strategy', title: 'Gradual Rollout (Canary, Ringed)' },
            { id: 'rollback-strategy-process', title: 'Rollback & Recovery Strategy' },
            { id: 'day-1-day-2-operations', title: 'Day-1 vs Day-2 Operations Plan' },
            { id: 'hypercare-period', title: 'Hypercare & Post-Launch Support' },
          ],
        },
        {
          id: 'operations-sre-program',
          title: 'Operations & SRE Program',
          summary: 'SLOs, error budgets, on-call programs and resilience for AWS workloads.',
          level: 'advanced',
          children: [
            { id: 'sli-slo-sla-design', title: 'SLI/SLO/SLA Design for AWS Services' },
            { id: 'error-budget-policy', title: 'Error Budget Policy' },
            { id: 'on-call-program', title: 'On-Call Program & Schedules' },
            { id: 'escalation-paths', title: 'Escalation Paths & Severity Levels' },
            { id: 'capacity-management', title: 'Capacity & Demand Management' },
            { id: 'dr-bcp-planning', title: 'DR & Business Continuity Planning' },
            { id: 'chaos-engineering-program', title: 'Chaos Engineering Program' },
            { id: 'reliability-reviews', title: 'Reliability Reviews & Toil Audits' },
          ],
        },
        {
          id: 'observability-program',
          title: 'Observability Program',
          summary: 'Telemetry standards, dashboards, alerting policy and platform ownership.',
          level: 'advanced',
          children: [
            { id: 'telemetry-standards', title: 'Telemetry Standards & Conventions' },
            { id: 'golden-signals', title: 'Golden Signals for AWS Workloads' },
            { id: 'dashboards-as-code', title: 'Dashboards-as-Code' },
            { id: 'alerting-policy', title: 'Alerting Policy & Symptom-Based Alerts' },
            { id: 'log-management-policy', title: 'Log Management Policy' },
            { id: 'retention-and-sampling', title: 'Retention & Sampling Policy' },
            { id: 'observability-platform-ownership', title: 'Observability Platform Ownership' },
            { id: 'cost-of-telemetry', title: 'Cost of Telemetry & Optimization' },
          ],
        },
        {
          id: 'incident-management-process',
          title: 'Incident Management Process',
          summary: 'Process for declaring, managing and learning from production incidents.',
          level: 'advanced',
          children: [
            { id: 'incident-classification', title: 'Incident Classification & Severity Matrix' },
            { id: 'incident-commander-role', title: 'Incident Commander Role & Roster' },
            { id: 'war-room-protocols', title: 'War Room & Bridge Call Protocols' },
            { id: 'status-page-comms', title: 'Status Page & Customer Communications' },
            { id: 'blameless-postmortems', title: 'Blameless Postmortem Process' },
            { id: 'action-item-tracking', title: 'Action Item Tracking & Closure' },
            { id: 'incident-metrics-mttx', title: 'Incident Metrics (MTTD/MTTA/MTTR)' },
            { id: 'major-incident-review', title: 'Major Incident Reviews' },
          ],
        },
        {
          id: 'support-maintenance-program',
          title: 'Support & Maintenance Program',
          summary: 'Tiered support, bug triage and ongoing maintenance programs.',
          level: 'intermediate',
          children: [
            { id: 'tiered-support-model', title: 'Tiered Support Model (L1/L2/L3)' },
            { id: 'bug-triage-process', title: 'Bug Triage & Backlog Hygiene' },
            { id: 'sla-management', title: 'SLA Management & Reporting' },
            { id: 'patch-management-cadence', title: 'Patch & Vulnerability Management Cadence' },
            { id: 'dependency-upgrade-program', title: 'Dependency Upgrade Program' },
            { id: 'service-version-policy', title: 'Service / Runtime Version Policy' },
            { id: 'decommissioning-sunsetting', title: 'Decommissioning & Sunsetting Process' },
            { id: 'knowledge-base-maintenance', title: 'Knowledge Base Maintenance' },
          ],
        },
        {
          id: 'continuous-improvement-program',
          title: 'Continuous Improvement & Evolution',
          summary: 'Feedback loops, technical debt management and evolutionary architecture practice.',
          level: 'advanced',
          children: [
            { id: 'feedback-loops-program', title: 'User & Operator Feedback Loops' },
            { id: 'post-launch-reviews', title: 'Post-Launch Reviews & Beta Graduations' },
            { id: 'technical-debt-management', title: 'Technical Debt Management Program' },
            { id: 'evolutionary-architecture-practice', title: 'Evolutionary Architecture Practice' },
            { id: 'version-deprecation-policy', title: 'Version Deprecation & Migration Policy' },
            { id: 'retrospectives-cadence', title: 'Retrospectives & Improvement Cadence' },
            { id: 'wa-review-cadence', title: 'Well-Architected Review Cadence' },
          ],
        },
      ],
    },
  ],
})
