/**
 * Seed all top-level (roadmap-anchor) topic.json files for the Software
 * Engineering subject AND regenerate roadmap.json from the same source of
 * truth defined here.
 *
 * Run with: node scripts/software-engineering/seed.mjs
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SUBJECT_DIR = resolve(__dirname, '../../src/content/subjects/software-engineering')
const TOPICS_DIR = resolve(SUBJECT_DIR, 'topics')

/**
 * STAGES is the single source of truth for the subject's roadmap and root
 * topic files. Each node carries id, title, summary and difficulty level.
 * Subtopics + sub-subtopics are added in subsequent partN-stages-*.mjs scripts.
 */
const STAGES = [
  {
    id: 'foundations',
    title: 'Software Engineering Foundations',
    summary: 'What software engineering is, where it came from and how it differs from CS.',
    nodes: [
      { id: 'what-is-software-engineering', title: 'What is Software Engineering?', level: 'beginner', description: 'Definition, goals and scope of the SE discipline.' },
      { id: 'software-engineering-history', title: 'History of Software Engineering', level: 'beginner', description: 'NATO 1968 conference to the modern profession.' },
      { id: 'swebok-overview', title: 'SWEBOK Guide Overview', level: 'beginner', description: 'IEEE Software Engineering Body of Knowledge v4.' },
      { id: 'software-product-types', title: 'Software Products & Systems', level: 'beginner', description: 'Generic, custom, embedded, web, SaaS and AI products.' },
      { id: 'software-characteristics', title: 'Characteristics of Software', level: 'beginner', description: 'Intangibility, complexity, conformity, changeability, invisibility.' },
      { id: 'software-engineering-vs-cs', title: 'Software Engineering vs Computer Science', level: 'beginner', description: 'Engineering discipline vs scientific discipline.' },
      { id: 'engineering-mindset', title: 'The Engineering Mindset', level: 'beginner', description: 'Trade-offs, constraints, evidence and rigor.' },
      { id: 'software-myths', title: 'Software Engineering Myths', level: 'beginner', description: 'Management, customer and practitioner myths.' },
    ],
  },
  {
    id: 'cs-foundations',
    title: 'Computer Science Foundations for Engineers',
    summary: 'Core CS knowledge an engineer relies on every day.',
    nodes: [
      { id: 'discrete-math-for-se', title: 'Discrete Math for Engineers', level: 'beginner', description: 'Logic, sets, relations, induction, combinatorics for SE.' },
      { id: 'algorithms-fundamentals-se', title: 'Algorithms Fundamentals', level: 'beginner', description: 'Sorting, searching, graph and divide-and-conquer basics.' },
      { id: 'data-structures-fundamentals-se', title: 'Data Structures Fundamentals', level: 'beginner', description: 'Arrays, lists, trees, hash tables, heaps and graphs.' },
      { id: 'complexity-and-bigo', title: 'Complexity & Big-O', level: 'beginner', description: 'Time, space and asymptotic analysis.' },
      { id: 'automata-and-computation', title: 'Automata & Theory of Computation', level: 'intermediate', description: 'Languages, grammars, computability and decidability.' },
      { id: 'computer-architecture-basics', title: 'Computer Architecture Basics', level: 'beginner', description: 'CPU, memory hierarchy, caches and ISA basics.' },
      { id: 'operating-systems-basics-se', title: 'Operating Systems Fundamentals', level: 'beginner', description: 'Processes, threads, scheduling, memory and I/O for engineers.' },
      { id: 'networking-basics-se', title: 'Networking Fundamentals', level: 'beginner', description: 'TCP/IP, HTTP, DNS and sockets for engineers.' },
      { id: 'compilers-interpreters-runtimes', title: 'Compilers, Interpreters & Runtimes', level: 'intermediate', description: 'How programs are translated, executed and managed.' },
      { id: 'numerical-computing-basics', title: 'Numerical Computing Basics', level: 'intermediate', description: 'Floating point, precision, rounding and stability.' },
    ],
  },
  {
    id: 'programming-paradigms',
    title: 'Programming Foundations & Paradigms',
    summary: 'Programming concepts and paradigms that shape engineering decisions.',
    nodes: [
      { id: 'programming-paradigms-overview', title: 'Programming Paradigms Overview', level: 'beginner', description: 'Map of paradigms and how to choose between them.' },
      { id: 'imperative-procedural', title: 'Imperative & Procedural Programming', level: 'beginner', description: 'State, statements, procedures and side effects.' },
      { id: 'structured-programming', title: 'Structured Programming', level: 'beginner', description: 'Sequence, selection, iteration and goto-less code.' },
      { id: 'object-oriented-paradigm', title: 'Object-Oriented Paradigm', level: 'beginner', description: 'Encapsulation, inheritance, polymorphism, message passing.' },
      { id: 'functional-paradigm', title: 'Functional Paradigm', level: 'intermediate', description: 'Pure functions, immutability, higher-order and HM types.' },
      { id: 'declarative-paradigm', title: 'Declarative Paradigm', level: 'intermediate', description: 'Describing what, not how (SQL, HTML, regex).' },
      { id: 'logic-programming', title: 'Logic Programming', level: 'advanced', description: 'Facts, rules and inference (Prolog, Datalog).' },
      { id: 'generic-programming', title: 'Generic Programming', level: 'intermediate', description: 'Templates, generics and parametric polymorphism.' },
      { id: 'meta-programming', title: 'Meta-Programming', level: 'advanced', description: 'Macros, reflection, codegen and DSLs.' },
      { id: 'aspect-oriented-programming', title: 'Aspect-Oriented Programming', level: 'advanced', description: 'Cross-cutting concerns, advice and pointcuts.' },
      { id: 'reactive-programming', title: 'Reactive Programming', level: 'intermediate', description: 'Streams, observables and async dataflow.' },
      { id: 'event-driven-programming', title: 'Event-Driven Programming', level: 'intermediate', description: 'Code-level paradigm of events, handlers, callbacks and event loops.' },
      { id: 'dataflow-programming', title: 'Dataflow Programming', level: 'advanced', description: 'Programs as directed graphs of data transformations.' },
      { id: 'concurrent-and-parallel-paradigms', title: 'Concurrent & Parallel Paradigms', level: 'intermediate', description: 'Threads, actors, CSP, async/await and SIMD.' },
      { id: 'type-systems', title: 'Type Systems', level: 'intermediate', description: 'Static, dynamic, strong, weak, structural and nominal.' },
      { id: 'memory-management-models', title: 'Memory Management Models', level: 'intermediate', description: 'Manual, GC, ownership, ARC and arenas.' },
      { id: 'error-handling-paradigms', title: 'Error Handling Paradigms', level: 'intermediate', description: 'Exceptions, return codes, Result/Option, effects.' },
    ],
  },
  {
    id: 'process-models',
    title: 'Software Process Models & Lifecycles',
    summary: 'Plan-driven and iterative SDLC models.',
    nodes: [
      { id: 'sdlc-overview', title: 'SDLC Overview', level: 'beginner', description: 'Phases, activities and lifecycle models.' },
      { id: 'waterfall-model', title: 'Waterfall Model', level: 'beginner', description: 'Phased, sequential development.' },
      { id: 'v-model', title: 'V-Model', level: 'beginner', description: 'Verification and validation aligned with phases.' },
      { id: 'spiral-model', title: 'Spiral Model', level: 'intermediate', description: 'Risk-driven iterative development (Boehm).' },
      { id: 'iterative-incremental', title: 'Iterative & Incremental Models', level: 'beginner', description: 'Repeated cycles delivering increments.' },
      { id: 'prototyping-model', title: 'Prototyping Model', level: 'beginner', description: 'Throwaway and evolutionary prototyping.' },
      { id: 'rad-model', title: 'Rapid Application Development', level: 'intermediate', description: 'Time-boxed RAD and JAD sessions.' },
      { id: 'evolutionary-development', title: 'Evolutionary Development', level: 'intermediate', description: 'Continuous evolution of working systems.' },
      { id: 'formal-methods-development', title: 'Formal Methods Development', level: 'advanced', description: 'Mathematically grounded development models.' },
      { id: 'unified-process-rup', title: 'Unified Process & RUP', level: 'intermediate', description: 'Inception, elaboration, construction, transition.' },
      { id: 'icse-process-12207', title: 'ISO/IEC/IEEE 12207 Process', level: 'intermediate', description: 'International standard for software lifecycle processes.' },
    ],
  },
  {
    id: 'agile-lean',
    title: 'Agile & Lean Software Engineering',
    summary: 'Agile values, methods, scaling and lean engineering.',
    nodes: [
      { id: 'agile-fundamentals', title: 'Agile Fundamentals', level: 'beginner', description: 'Iterative delivery, feedback and adaptation.' },
      { id: 'agile-manifesto', title: 'Agile Manifesto & Principles', level: 'beginner', description: 'Values and 12 principles.' },
      { id: 'scrum-engineering', title: 'Scrum Framework (Engineering View)', level: 'beginner', description: 'Roles, events and artifacts.' },
      { id: 'kanban-engineering', title: 'Kanban Method (Engineering View)', level: 'beginner', description: 'Visualize work, limit WIP, manage flow.' },
      { id: 'extreme-programming', title: 'Extreme Programming (XP)', level: 'intermediate', description: 'Pair programming, TDD, CI and small releases.' },
      { id: 'crystal-methods', title: 'Crystal Family of Methods', level: 'intermediate', description: 'Cockburn-style human-powered methods.' },
      { id: 'feature-driven-development', title: 'Feature-Driven Development', level: 'intermediate', description: 'Model-driven, feature-based agile method.' },
      { id: 'dsdm-method', title: 'DSDM / AgilePM', level: 'intermediate', description: 'Time-boxed, MoSCoW-prioritized framework.' },
      { id: 'lean-software', title: 'Lean Software Development', level: 'intermediate', description: 'Eliminate waste, amplify learning, deliver fast.' },
      { id: 'safe-overview', title: 'SAFe Overview', level: 'advanced', description: 'Scaled Agile Framework for enterprises.' },
      { id: 'less-overview', title: 'LeSS Overview', level: 'advanced', description: 'Large-Scale Scrum.' },
      { id: 'nexus-overview', title: 'Nexus Overview', level: 'advanced', description: 'Scrum.org scaling framework.' },
      { id: 'scrum-at-scale-overview', title: 'Scrum@Scale Overview', level: 'advanced', description: 'Sutherland-style scaled Scrum.' },
      { id: 'disciplined-agile', title: 'Disciplined Agile (DA)', level: 'advanced', description: 'PMI-owned hybrid agile toolkit.' },
      { id: 'agile-anti-patterns', title: 'Agile Anti-Patterns (Engineering)', level: 'intermediate', description: 'Cargo-cult agile, fake agile and recovery.' },
    ],
  },
  {
    id: 'requirements-engineering',
    title: 'Software Requirements Engineering',
    summary: 'Eliciting, analyzing, specifying and managing requirements.',
    nodes: [
      { id: 'requirements-engineering-fundamentals', title: 'Requirements Engineering Fundamentals', level: 'beginner', description: 'Process, stakeholders and artifacts.' },
      { id: 'requirements-elicitation', title: 'Requirements Elicitation', level: 'beginner', description: 'Interviews, workshops, observation and surveys.' },
      { id: 'requirements-analysis', title: 'Requirements Analysis', level: 'beginner', description: 'Classification, negotiation and conflict resolution.' },
      { id: 'requirements-specification', title: 'Requirements Specification', level: 'beginner', description: 'SRS documents, IEEE 830 and ISO/IEC/IEEE 29148.' },
      { id: 'requirements-validation', title: 'Requirements Validation & Verification', level: 'intermediate', description: 'Reviews, prototyping and acceptance criteria.' },
      { id: 'requirements-management', title: 'Requirements Management', level: 'intermediate', description: 'Change control, baselining and tooling.' },
      { id: 'functional-vs-nonfunctional', title: 'Functional vs Non-Functional Requirements', level: 'beginner', description: 'Definitions, examples and -ilities.' },
      { id: 'user-stories-engineering', title: 'User Stories (Engineering View)', level: 'beginner', description: 'INVEST, splitting and acceptance criteria.' },
      { id: 'use-case-modeling-re', title: 'Use Case Modeling', level: 'beginner', description: 'Actors, scenarios and use case diagrams.' },
      { id: 'requirements-traceability', title: 'Requirements Traceability', level: 'intermediate', description: 'Linking requirements to code, tests and changes.' },
      { id: 'requirements-prioritization', title: 'Requirements Prioritization', level: 'beginner', description: 'MoSCoW, RICE, Kano and weighted scoring.' },
      { id: 'babok-overview', title: 'BABOK Overview', level: 'intermediate', description: 'Business analysis body of knowledge.' },
    ],
  },
  {
    id: 'modeling-analysis',
    title: 'Software Modeling & Analysis',
    summary: 'Visual and formal models for understanding software.',
    nodes: [
      { id: 'modeling-fundamentals', title: 'Modeling Fundamentals', level: 'beginner', description: 'Why model, abstraction levels and notations.' },
      { id: 'uml-overview', title: 'UML Overview', level: 'beginner', description: 'UML 2.x diagrams and how they fit together.' },
      { id: 'structural-uml', title: 'Structural UML Diagrams', level: 'beginner', description: 'Class, component, package, deployment and object.' },
      { id: 'behavioral-uml', title: 'Behavioral UML Diagrams', level: 'beginner', description: 'Sequence, activity, state machine, communication and timing.' },
      { id: 'erd-modeling', title: 'Entity-Relationship Modeling', level: 'beginner', description: 'Entities, attributes, relationships and cardinality.' },
      { id: 'bpmn-modeling', title: 'BPMN Modeling', level: 'intermediate', description: 'Business Process Model and Notation.' },
      { id: 'sysml-overview', title: 'SysML Overview', level: 'advanced', description: 'Systems Modeling Language for systems engineering.' },
      { id: 'data-flow-diagrams', title: 'Data Flow Diagrams', level: 'beginner', description: 'Processes, data stores and flows.' },
      { id: 'state-machines-modeling', title: 'State Machines & Statecharts', level: 'intermediate', description: 'Finite state machines and Harel statecharts.' },
      { id: 'petri-nets', title: 'Petri Nets', level: 'advanced', description: 'Concurrency and synchronization modeling.' },
      { id: 'domain-modeling-se', title: 'Domain Modeling', level: 'intermediate', description: 'Capturing the business domain in code-aligned models.' },
      { id: 'modeling-tools', title: 'Modeling Tools', level: 'beginner', description: 'PlantUML, Mermaid, Lucidchart, drawio, Enterprise Architect.' },
    ],
  },
  {
    id: 'design-principles',
    title: 'Software Design Principles (Code-Level)',
    summary: 'Code-level design principles every engineer should master.',
    nodes: [
      { id: 'design-principles-overview', title: 'Design Principles Overview', level: 'beginner', description: 'Why principles, where they apply and trade-offs.' },
      { id: 'abstraction-encapsulation', title: 'Abstraction & Encapsulation', level: 'beginner', description: 'Hiding details and exposing intent.' },
      { id: 'modularity-cohesion-coupling', title: 'Modularity, Cohesion & Coupling', level: 'beginner', description: 'How modules are sized, related and isolated.' },
      { id: 'separation-of-concerns', title: 'Separation of Concerns', level: 'beginner', description: 'One responsibility per construct.' },
      { id: 'single-responsibility', title: 'Single Responsibility Principle', level: 'beginner', description: 'A class should have one reason to change.' },
      { id: 'open-closed-principle', title: 'Open/Closed Principle', level: 'intermediate', description: 'Open for extension, closed for modification.' },
      { id: 'liskov-substitution', title: 'Liskov Substitution Principle', level: 'intermediate', description: 'Subtypes must honor base contracts.' },
      { id: 'interface-segregation', title: 'Interface Segregation Principle', level: 'intermediate', description: 'Many client-specific interfaces beat one general one.' },
      { id: 'dependency-inversion', title: 'Dependency Inversion Principle', level: 'intermediate', description: 'Depend on abstractions, not concretions.' },
      { id: 'dry-principle', title: 'DRY (Don’t Repeat Yourself)', level: 'beginner', description: 'Single source of truth for knowledge.' },
      { id: 'kiss-principle', title: 'KISS (Keep It Simple)', level: 'beginner', description: 'Favor simple, obvious solutions.' },
      { id: 'yagni-principle', title: 'YAGNI (You Aren’t Gonna Need It)', level: 'beginner', description: 'Build only what you need now.' },
      { id: 'law-of-demeter', title: 'Law of Demeter', level: 'intermediate', description: 'Talk only to your immediate friends.' },
      { id: 'composition-over-inheritance', title: 'Composition Over Inheritance', level: 'intermediate', description: 'Prefer has-a over is-a.' },
      { id: 'principle-of-least-astonishment', title: 'Principle of Least Astonishment', level: 'beginner', description: 'Behave the way users expect.' },
      { id: 'design-heuristics-riel', title: 'Design Heuristics (Riel)', level: 'intermediate', description: 'Object-oriented design heuristics.' },
      { id: 'gof-foundations', title: 'GoF Foundations & Vocabulary', level: 'intermediate', description: 'Patterns, forces, intent and vocabulary.' },
    ],
  },
  {
    id: 'ooad',
    title: 'Object-Oriented Analysis & Design',
    summary: 'Identifying objects, responsibilities and collaborations.',
    nodes: [
      { id: 'ooad-fundamentals', title: 'OOAD Fundamentals', level: 'intermediate', description: 'OOA, OOD and OOP relationships.' },
      { id: 'object-oriented-analysis', title: 'Object-Oriented Analysis', level: 'intermediate', description: 'Conceptual model from the problem domain.' },
      { id: 'object-oriented-design', title: 'Object-Oriented Design', level: 'intermediate', description: 'Designing objects, classes and interactions.' },
      { id: 'grasp-patterns', title: 'GRASP Patterns', level: 'intermediate', description: 'Information expert, creator, controller, low coupling and others.' },
      { id: 'responsibility-driven-design', title: 'Responsibility-Driven Design', level: 'intermediate', description: 'Roles, responsibilities and collaborations.' },
      { id: 'crc-cards', title: 'CRC Cards', level: 'beginner', description: 'Class-Responsibility-Collaborator brainstorming.' },
      { id: 'noun-verb-analysis', title: 'Noun-Verb Analysis', level: 'beginner', description: 'Find candidate classes and methods from text.' },
      { id: 'object-oriented-modeling', title: 'Object-Oriented Modeling', level: 'intermediate', description: 'OOAD with UML and domain models.' },
    ],
  },
  {
    id: 'code-level-patterns',
    title: 'Code-Level Design Patterns',
    summary: 'Reusable solutions to recurring code-level problems.',
    nodes: [
      { id: 'gof-patterns-overview', title: 'GoF Patterns Overview', level: 'intermediate', description: 'Origin, classification and applicability.' },
      { id: 'creational-code-patterns', title: 'Creational Patterns', level: 'intermediate', description: 'Factory, builder, prototype, singleton and abstract factory.' },
      { id: 'structural-code-patterns', title: 'Structural Patterns', level: 'intermediate', description: 'Adapter, bridge, composite, decorator, facade, flyweight and proxy.' },
      { id: 'behavioral-code-patterns', title: 'Behavioral Patterns', level: 'intermediate', description: 'Strategy, observer, command, iterator, state and others.' },
      { id: 'concurrency-code-patterns', title: 'Concurrency Patterns', level: 'advanced', description: 'Producer-consumer, monitor, read-write lock, futures.' },
      { id: 'functional-code-patterns', title: 'Functional Patterns', level: 'intermediate', description: 'Functor, monad, lens, transducer and pipelines.' },
      { id: 'code-anti-patterns', title: 'Code Anti-Patterns', level: 'intermediate', description: 'God object, spaghetti, lava flow and golden hammer.' },
    ],
  },
  {
    id: 'construction',
    title: 'Software Construction Practices',
    summary: 'Day-to-day practices that turn design into clean working code.',
    nodes: [
      { id: 'software-construction-fundamentals', title: 'Software Construction Fundamentals', level: 'beginner', description: 'SWEBOK construction KA and Code Complete pillars.' },
      { id: 'coding-standards-and-style', title: 'Coding Standards & Style', level: 'beginner', description: 'Style guides, formatters and conventions.' },
      { id: 'defensive-programming', title: 'Defensive Programming', level: 'intermediate', description: 'Assertions, preconditions, invariants and barricades.' },
      { id: 'error-handling-practices', title: 'Error Handling Practices', level: 'intermediate', description: 'Exception design, logging context and fail-fast.' },
      { id: 'pair-programming', title: 'Pair Programming', level: 'beginner', description: 'Driver/navigator, ping-pong and styles.' },
      { id: 'mob-programming', title: 'Mob Programming', level: 'intermediate', description: 'Whole team on one problem at one computer.' },
      { id: 'ensemble-programming', title: 'Ensemble Programming', level: 'intermediate', description: 'Modern naming and practice for mob programming.' },
      { id: 'test-driven-development', title: 'Test-Driven Development (TDD)', level: 'intermediate', description: 'Red, green, refactor and TDD styles.' },
      { id: 'behavior-driven-development', title: 'Behavior-Driven Development (BDD)', level: 'intermediate', description: 'Given-When-Then and ubiquitous language.' },
      { id: 'acceptance-test-driven-development', title: 'Acceptance Test-Driven Development', level: 'intermediate', description: 'Customer-collaborated acceptance tests upfront.' },
      { id: 'specification-by-example', title: 'Specification by Example', level: 'intermediate', description: 'Living documentation through examples.' },
      { id: 'event-driven-development-process', title: 'Event-Driven Development (Process)', level: 'intermediate', description: 'Engineering discipline of building software events-first: discovery, code-level practices and tests.' },
      { id: 'construction-anti-patterns', title: 'Construction Anti-Patterns', level: 'intermediate', description: 'Premature optimization, copy-paste and wrong abstractions.' },
    ],
  },
  {
    id: 'version-control',
    title: 'Version Control & Source Code Management',
    summary: 'Tracking, branching, reviewing and managing source code.',
    nodes: [
      { id: 'version-control-fundamentals', title: 'Version Control Fundamentals', level: 'beginner', description: 'Why VCS, centralized vs distributed.' },
      { id: 'git-fundamentals-se', title: 'Git Fundamentals (Engineering View)', level: 'beginner', description: 'Repos, commits, branches and remotes.' },
      { id: 'git-advanced-workflows', title: 'Git Advanced Workflows', level: 'intermediate', description: 'Rebase, cherry-pick, bisect, worktrees and submodules.' },
      { id: 'branching-strategies', title: 'Branching Strategies', level: 'intermediate', description: 'Gitflow, GitHub Flow, GitLab Flow, trunk-based.' },
      { id: 'merging-and-rebasing', title: 'Merging & Rebasing', level: 'intermediate', description: 'Merge strategies, conflict resolution and history hygiene.' },
      { id: 'code-review-process-vcs', title: 'Code Review Process', level: 'beginner', description: 'PR/MR flow, expectations and reviewer mindset.' },
      { id: 'pull-request-workflow', title: 'Pull Request Workflow', level: 'beginner', description: 'Drafts, approvals, required reviewers and templates.' },
      { id: 'monorepo-vs-polyrepo', title: 'Monorepo vs Polyrepo', level: 'intermediate', description: 'Trade-offs, tooling and team implications.' },
      { id: 'commit-conventions', title: 'Commit Conventions', level: 'beginner', description: 'Conventional commits, atomic commits and messages.' },
      { id: 'vcs-tools-comparison', title: 'VCS Tools Comparison', level: 'beginner', description: 'Git, Mercurial, SVN, Perforce and others.' },
      { id: 'version-control-anti-patterns', title: 'Version Control Anti-Patterns', level: 'intermediate', description: 'Long-lived branches, mega commits and force pushes.' },
    ],
  },
  {
    id: 'testing',
    title: 'Software Testing',
    summary: 'A complete map of software testing as a discipline.',
    nodes: [
      { id: 'testing-fundamentals', title: 'Testing Fundamentals', level: 'beginner', description: 'Goals, definitions and ISTQB basics.' },
      { id: 'test-levels-overview', title: 'Test Levels Overview', level: 'beginner', description: 'Unit, integration, system and acceptance levels.' },
      { id: 'unit-testing', title: 'Unit Testing', level: 'beginner', description: 'Isolating and testing the smallest behavior.' },
      { id: 'integration-testing', title: 'Integration Testing', level: 'intermediate', description: 'Testing collaborations between components.' },
      { id: 'system-testing', title: 'System Testing', level: 'intermediate', description: 'End-to-end behavior at the system boundary.' },
      { id: 'acceptance-testing', title: 'Acceptance Testing', level: 'intermediate', description: 'UAT, alpha, beta and contract acceptance.' },
      { id: 'regression-testing', title: 'Regression Testing', level: 'intermediate', description: 'Re-testing after changes to detect regressions.' },
      { id: 'smoke-and-sanity-testing', title: 'Smoke & Sanity Testing', level: 'beginner', description: 'Fast checks for basic build/feature health.' },
      { id: 'exploratory-testing', title: 'Exploratory Testing', level: 'intermediate', description: 'Simultaneous learning, design and execution.' },
      { id: 'mutation-testing', title: 'Mutation Testing', level: 'advanced', description: 'Measuring test suite effectiveness.' },
      { id: 'property-based-testing', title: 'Property-Based Testing', level: 'advanced', description: 'Generators and properties (QuickCheck-style).' },
      { id: 'fuzz-testing', title: 'Fuzz Testing', level: 'advanced', description: 'Automated random/structured input testing.' },
      { id: 'contract-testing', title: 'Contract Testing', level: 'intermediate', description: 'Consumer-driven contracts (Pact and friends).' },
      { id: 'snapshot-testing', title: 'Snapshot Testing', level: 'intermediate', description: 'Approval and golden-master tests.' },
      { id: 'ui-and-end-to-end-testing', title: 'UI & End-to-End Testing', level: 'intermediate', description: 'Browser/mobile UI automation and stability.' },
      { id: 'accessibility-testing', title: 'Accessibility Testing', level: 'intermediate', description: 'Automated and manual a11y checks (WCAG).' },
      { id: 'usability-testing', title: 'Usability Testing', level: 'intermediate', description: 'Observing users to evaluate usability.' },
      { id: 'performance-testing', title: 'Performance Testing', level: 'intermediate', description: 'Load, stress, spike, soak and capacity tests.' },
      { id: 'security-testing', title: 'Security Testing', level: 'intermediate', description: 'Vulnerability, penetration and abuse-case testing.' },
      { id: 'testing-pyramid-trophy', title: 'Testing Pyramid & Trophy', level: 'beginner', description: 'Test mix, pyramid, trophy and diamond shapes.' },
      { id: 'test-doubles', title: 'Test Doubles (Mocks, Stubs, Fakes)', level: 'intermediate', description: 'Stubs, spies, mocks, fakes and dummies.' },
      { id: 'coverage-criteria', title: 'Coverage Criteria', level: 'intermediate', description: 'Statement, branch, MC/DC and mutation coverage.' },
      { id: 'test-design-techniques', title: 'Test Design Techniques', level: 'intermediate', description: 'Equivalence, boundary, decision tables, pairwise.' },
      { id: 'test-automation-strategy', title: 'Test Automation Strategy', level: 'intermediate', description: 'What to automate, frameworks and ROI.' },
      { id: 'test-anti-patterns', title: 'Test Anti-Patterns', level: 'intermediate', description: 'Flaky tests, ice-cream cone and slow suites.' },
    ],
  },
  {
    id: 'sqa',
    title: 'Software Quality Assurance',
    summary: 'Reviews, verification, validation and quality enforcement.',
    nodes: [
      { id: 'sqa-fundamentals', title: 'SQA Fundamentals', level: 'beginner', description: 'Quality assurance vs quality control vs testing.' },
      { id: 'verification-and-validation', title: 'Verification & Validation', level: 'beginner', description: 'Building it right vs building the right thing.' },
      { id: 'inspections-walkthroughs', title: 'Inspections & Walkthroughs', level: 'intermediate', description: 'Structured peer reviews of artifacts.' },
      { id: 'formal-reviews-fagan', title: 'Formal Fagan Inspections', level: 'advanced', description: 'Fagan-style structured inspection process.' },
      { id: 'code-review-quality', title: 'Code Review for Quality', level: 'beginner', description: 'Beyond style: defects, design and learning.' },
      { id: 'static-analysis', title: 'Static Analysis', level: 'intermediate', description: 'Linters, type checkers and SAST scanners.' },
      { id: 'dynamic-analysis', title: 'Dynamic Analysis', level: 'intermediate', description: 'Sanitizers, profilers and runtime checkers.' },
      { id: 'continuous-quality', title: 'Continuous Quality', level: 'intermediate', description: 'Quality embedded in every commit.' },
      { id: 'quality-gates', title: 'Quality Gates', level: 'intermediate', description: 'Automated thresholds blocking unsafe changes.' },
    ],
  },
  {
    id: 'code-quality',
    title: 'Code Quality, Refactoring & Technical Debt',
    summary: 'Keeping code clean, readable and maintainable over time.',
    nodes: [
      { id: 'clean-code-principles', title: 'Clean Code Principles', level: 'beginner', description: 'Martin-style readable, expressive code.' },
      { id: 'code-smells-catalog', title: 'Code Smells Catalog', level: 'intermediate', description: 'Long methods, large classes, duplication and others.' },
      { id: 'refactoring-fundamentals', title: 'Refactoring Fundamentals', level: 'intermediate', description: 'Behavior-preserving structural improvement.' },
      { id: 'refactoring-catalog', title: 'Refactoring Catalog', level: 'intermediate', description: 'Fowler-style mechanical refactorings.' },
      { id: 'working-with-legacy-code', title: 'Working With Legacy Code', level: 'intermediate', description: 'Feathers seam-based techniques.' },
      { id: 'characterization-tests', title: 'Characterization Tests', level: 'intermediate', description: 'Pinning down legacy behavior with tests.' },
      { id: 'technical-debt-types', title: 'Types of Technical Debt', level: 'intermediate', description: 'Code, design, test, doc and infra debt.' },
      { id: 'technical-debt-quadrant', title: 'Technical Debt Quadrant', level: 'intermediate', description: 'Reckless/prudent × deliberate/inadvertent.' },
      { id: 'code-readability', title: 'Code Readability', level: 'beginner', description: 'Reading-first code and cognitive load.' },
      { id: 'naming-conventions', title: 'Naming Conventions', level: 'beginner', description: 'Intent-revealing names and consistent vocabularies.' },
      { id: 'complexity-management', title: 'Complexity Management', level: 'intermediate', description: 'Essential vs accidental complexity (Brooks).' },
    ],
  },
  {
    id: 'maintenance-evolution',
    title: 'Software Maintenance & Evolution',
    summary: 'Keeping software valuable across its lifetime.',
    nodes: [
      { id: 'maintenance-fundamentals', title: 'Software Maintenance Fundamentals', level: 'intermediate', description: 'Why maintenance is the bulk of SE effort.' },
      { id: 'maintenance-types', title: 'Types of Maintenance', level: 'beginner', description: 'Corrective, adaptive, perfective, preventive.' },
      { id: 'legacy-modernization', title: 'Legacy Modernization', level: 'advanced', description: 'Strategies to modernize old systems.' },
      { id: 'software-aging', title: 'Software Aging', level: 'intermediate', description: 'Why software degrades over time (Parnas).' },
      { id: 'lehman-laws', title: 'Lehman’s Laws of Evolution', level: 'intermediate', description: 'Continuing change, growing complexity and others.' },
      { id: 'reengineering', title: 'Software Reengineering', level: 'advanced', description: 'Examination, restructuring and reimplementation.' },
      { id: 'reverse-engineering', title: 'Reverse Engineering', level: 'advanced', description: 'Recovering design from existing code.' },
      { id: 'migration-strategies-se', title: 'Migration Strategies (Engineering)', level: 'advanced', description: 'Strangler fig, branch by abstraction, big bang.' },
      { id: 'end-of-life-retirement', title: 'End-of-Life & Retirement', level: 'intermediate', description: 'Sunsetting software responsibly.' },
    ],
  },
  {
    id: 'configuration-management',
    title: 'Software Configuration Management',
    summary: 'Identifying, controlling and tracking artifacts and changes.',
    nodes: [
      { id: 'scm-fundamentals', title: 'SCM Fundamentals', level: 'beginner', description: 'SWEBOK SCM KA: identification, control, status, audit.' },
      { id: 'baseline-management', title: 'Baseline Management', level: 'intermediate', description: 'Functional, allocated and product baselines.' },
      { id: 'change-control', title: 'Change Control', level: 'intermediate', description: 'CCB, RFCs and change impact analysis.' },
      { id: 'release-management-process', title: 'Release Management (Process)', level: 'intermediate', description: 'Planning, building, deploying and tracking releases.' },
      { id: 'environment-management', title: 'Environment Management', level: 'intermediate', description: 'Dev, test, staging, prod and ephemeral envs.' },
      { id: 'build-management', title: 'Build Management', level: 'intermediate', description: 'Reproducible, audited builds.' },
      { id: 'workspace-management', title: 'Workspace Management', level: 'beginner', description: 'Developer environments, devcontainers and dotfiles.' },
      { id: 'scm-standards-iso', title: 'SCM Standards (ISO/IEC/IEEE)', level: 'advanced', description: 'IEEE 828, ISO 10007 and related standards.' },
    ],
  },
  {
    id: 'build-packaging',
    title: 'Build, Packaging & Dependency Management',
    summary: 'Turning source into reproducible, shippable artifacts.',
    nodes: [
      { id: 'build-systems-overview', title: 'Build Systems Overview', level: 'beginner', description: 'Compilers, linkers, build graphs and incrementality.' },
      { id: 'make-cmake', title: 'Make & CMake', level: 'beginner', description: 'Classic and modern C/C++ build tooling.' },
      { id: 'gradle-overview', title: 'Gradle (Build Tool)', level: 'intermediate', description: 'JVM polyglot build tool fundamentals.' },
      { id: 'maven-overview', title: 'Maven (Build Tool)', level: 'beginner', description: 'JVM build, dependency and packaging tool.' },
      { id: 'bazel-overview', title: 'Bazel (Build Tool)', level: 'advanced', description: 'Hermetic, fast monorepo build system.' },
      { id: 'npm-yarn-pnpm', title: 'npm, Yarn & pnpm', level: 'beginner', description: 'JavaScript package managers.' },
      { id: 'pip-poetry-uv', title: 'pip, Poetry & uv', level: 'beginner', description: 'Python package and project managers.' },
      { id: 'nuget', title: 'NuGet', level: 'beginner', description: '.NET package manager.' },
      { id: 'cargo', title: 'Cargo', level: 'beginner', description: 'Rust package manager and build tool.' },
      { id: 'go-modules', title: 'Go Modules', level: 'beginner', description: 'Go dependency and versioning system.' },
      { id: 'artifact-repositories', title: 'Artifact Repositories', level: 'intermediate', description: 'Nexus, Artifactory, GitHub Packages, GHCR.' },
      { id: 'dependency-management', title: 'Dependency Management', level: 'intermediate', description: 'Resolution, locking, audits and updates.' },
      { id: 'semantic-versioning', title: 'Semantic Versioning', level: 'beginner', description: 'SemVer rules and breaking change discipline.' },
      { id: 'reproducible-builds', title: 'Reproducible Builds', level: 'advanced', description: 'Bit-for-bit identical outputs from source.' },
      { id: 'build-caching', title: 'Build Caching', level: 'intermediate', description: 'Local and remote caches for fast builds.' },
      { id: 'monorepo-build-tools', title: 'Monorepo Build Tools', level: 'advanced', description: 'Bazel, Buck2, Nx, Turborepo, Pants and Lerna.' },
    ],
  },
  {
    id: 'documentation',
    title: 'Software Documentation',
    summary: 'Writing documentation that engineers and users actually use.',
    nodes: [
      { id: 'documentation-fundamentals', title: 'Documentation Fundamentals', level: 'beginner', description: 'Audiences, goals and quality attributes.' },
      { id: 'types-of-documentation', title: 'Types of Software Documentation', level: 'beginner', description: 'Reference, tutorial, how-to and explanation.' },
      { id: 'diataxis-framework', title: 'Diátaxis Framework', level: 'beginner', description: 'Four-mode documentation system.' },
      { id: 'readme-best-practices', title: 'README Best Practices', level: 'beginner', description: 'Structure, badges and onboarding-first READMEs.' },
      { id: 'api-documentation', title: 'API Documentation', level: 'intermediate', description: 'OpenAPI, AsyncAPI, JSDoc and reference docs.' },
      { id: 'user-and-admin-docs', title: 'User & Admin Documentation', level: 'beginner', description: 'End-user guides and admin runbooks.' },
      { id: 'internal-developer-docs', title: 'Internal Developer Documentation', level: 'intermediate', description: 'Onboarding, runbooks, RFCs and ADR repos.' },
      { id: 'documentation-as-code', title: 'Documentation as Code', level: 'intermediate', description: 'Docs in repos with the same review and CI.' },
      { id: 'diagrams-as-code', title: 'Diagrams as Code', level: 'intermediate', description: 'Mermaid, PlantUML, D2 and Structurizr.' },
      { id: 'changelog-and-release-notes', title: 'Changelogs & Release Notes', level: 'beginner', description: 'Keep a Changelog, semantic release notes.' },
      { id: 'documentation-anti-patterns', title: 'Documentation Anti-Patterns', level: 'intermediate', description: 'Stale docs, code-as-docs and over-documentation.' },
    ],
  },
  {
    id: 'project-management-engineers',
    title: 'Software Project Management for Engineers',
    summary: 'Engineering-focused project planning and tracking.',
    nodes: [
      { id: 'project-management-overview', title: 'Project Management Overview', level: 'beginner', description: 'PMI process groups and knowledge areas.' },
      { id: 'engineering-project-lifecycle', title: 'Engineering Project Lifecycle', level: 'beginner', description: 'Initiation, planning, execution, monitoring, closing.' },
      { id: 'wbs-decomposition', title: 'Work Breakdown Structure', level: 'beginner', description: 'Decomposing work into manageable items.' },
      { id: 'gantt-and-pert', title: 'Gantt Charts & PERT', level: 'intermediate', description: 'Schedule visualization and three-point estimates.' },
      { id: 'critical-path-method', title: 'Critical Path Method', level: 'intermediate', description: 'Identifying the longest dependent task chain.' },
      { id: 'earned-value-management', title: 'Earned Value Management', level: 'advanced', description: 'PV, EV, AC, SPI, CPI and forecasting.' },
      { id: 'progress-tracking', title: 'Progress Tracking (Engineering)', level: 'beginner', description: 'Burnups, burndowns, CFD and flow tracking.' },
      { id: 'pmbok-overview', title: 'PMBOK Overview', level: 'intermediate', description: 'PMI Project Management Body of Knowledge.' },
      { id: 'prince2-overview', title: 'PRINCE2 Overview', level: 'intermediate', description: 'PRojects IN Controlled Environments method.' },
    ],
  },
  {
    id: 'estimation-planning',
    title: 'Software Estimation & Planning',
    summary: 'Forecasting effort, cost and schedule for software work.',
    nodes: [
      { id: 'estimation-fundamentals', title: 'Estimation Fundamentals', level: 'beginner', description: 'Estimates, targets, commitments and cones of uncertainty.' },
      { id: 'expert-judgment-estimation', title: 'Expert Judgment Estimation', level: 'beginner', description: 'Wideband Delphi and structured expert input.' },
      { id: 'analogy-based-estimation', title: 'Analogy-Based Estimation', level: 'beginner', description: 'Estimating from past similar projects.' },
      { id: 'cocomo-models', title: 'COCOMO Models', level: 'advanced', description: 'COCOMO I, II and parametric estimation.' },
      { id: 'function-point-analysis', title: 'Function Point Analysis', level: 'advanced', description: 'IFPUG and SNAP function-point estimation.' },
      { id: 'use-case-points', title: 'Use Case Points', level: 'intermediate', description: 'Karner-style use-case-based estimation.' },
      { id: 'story-points-velocity', title: 'Story Points & Velocity', level: 'beginner', description: 'Relative sizing and team velocity tracking.' },
      { id: 't-shirt-sizing', title: 'T-Shirt Sizing', level: 'beginner', description: 'XS-XXL coarse-grained estimation.' },
      { id: 'planning-poker', title: 'Planning Poker', level: 'beginner', description: 'Anonymous, consensus-based estimation game.' },
      { id: 'monte-carlo-estimation', title: 'Monte Carlo Estimation', level: 'advanced', description: 'Probabilistic forecasting from historical flow.' },
      { id: 'estimation-pitfalls', title: 'Estimation Pitfalls', level: 'intermediate', description: 'Optimism, anchoring, padding and ranges.' },
    ],
  },
  {
    id: 'risk-management',
    title: 'Risk Management in Software',
    summary: 'Identifying and managing software project risks.',
    nodes: [
      { id: 'risk-management-fundamentals', title: 'Risk Management Fundamentals', level: 'beginner', description: 'What risk is and why we manage it.' },
      { id: 'risk-identification', title: 'Risk Identification Techniques', level: 'beginner', description: 'Brainstorming, checklists and assumption analysis.' },
      { id: 'risk-analysis-qualitative', title: 'Qualitative Risk Analysis', level: 'beginner', description: 'Probability/impact matrices and heat maps.' },
      { id: 'risk-analysis-quantitative', title: 'Quantitative Risk Analysis', level: 'advanced', description: 'EMV, Monte Carlo and decision trees.' },
      { id: 'risk-mitigation-strategies', title: 'Risk Mitigation Strategies', level: 'beginner', description: 'Avoid, transfer, mitigate, accept and exploit.' },
      { id: 'risk-monitoring', title: 'Risk Monitoring', level: 'intermediate', description: 'Tracking, reassessment and triggers.' },
      { id: 'risk-registers', title: 'Risk Registers', level: 'beginner', description: 'Living risk inventory artifacts.' },
      { id: 'common-software-risks', title: 'Common Software Risks', level: 'beginner', description: 'Schedule, requirements, technology, team and product risks.' },
    ],
  },
  {
    id: 'quality-standards',
    title: 'Software Quality Management & Standards',
    summary: 'Standards, models and bodies that define software quality.',
    nodes: [
      { id: 'quality-management-fundamentals', title: 'Quality Management Fundamentals', level: 'intermediate', description: 'QM systems, policies and continuous improvement.' },
      { id: 'iso-25010', title: 'ISO/IEC 25010 Quality Model', level: 'intermediate', description: 'Modern product quality characteristics.' },
      { id: 'iso-9126-legacy', title: 'ISO/IEC 9126 (Legacy)', level: 'intermediate', description: 'Predecessor of 25010 and historical quality model.' },
      { id: 'iso-iec-ieee-12207', title: 'ISO/IEC/IEEE 12207', level: 'intermediate', description: 'Software lifecycle processes standard.' },
      { id: 'iso-iec-ieee-15288', title: 'ISO/IEC/IEEE 15288', level: 'advanced', description: 'Systems lifecycle processes standard.' },
      { id: 'cmmi-overview', title: 'CMMI Overview', level: 'intermediate', description: 'Capability Maturity Model Integration.' },
      { id: 'iso-15504-spice', title: 'ISO/IEC 15504 (SPICE)', level: 'advanced', description: 'Software process improvement and capability determination.' },
      { id: 'six-sigma-software', title: 'Six Sigma in Software', level: 'advanced', description: 'DMAIC and DMADV applied to software.' },
      { id: 'tqm-software', title: 'TQM in Software', level: 'intermediate', description: 'Total Quality Management for software orgs.' },
      { id: 'ieee-software-standards', title: 'IEEE Software Standards', level: 'intermediate', description: 'IEEE 730, 829, 830, 1012, 1016, 1471 and others.' },
    ],
  },
  {
    id: 'metrics-measurement',
    title: 'Software Metrics & Measurement',
    summary: 'Quantifying software products, processes and projects.',
    nodes: [
      { id: 'measurement-fundamentals', title: 'Measurement Fundamentals', level: 'beginner', description: 'Scales, validity and goal-based measurement.' },
      { id: 'product-metrics', title: 'Product Metrics', level: 'intermediate', description: 'Size, complexity, quality and structural metrics.' },
      { id: 'process-metrics', title: 'Process Metrics', level: 'intermediate', description: 'Lead time, cycle time, throughput and efficiency.' },
      { id: 'project-metrics', title: 'Project Metrics', level: 'intermediate', description: 'Effort, cost, schedule and earned value.' },
      { id: 'size-metrics-loc-fp', title: 'Size Metrics (LOC, FP)', level: 'beginner', description: 'Lines of code and function points.' },
      { id: 'complexity-metrics', title: 'Complexity Metrics', level: 'intermediate', description: 'Cyclomatic, cognitive, NPath and structural.' },
      { id: 'cyclomatic-complexity', title: 'Cyclomatic Complexity', level: 'intermediate', description: 'McCabe complexity measure and thresholds.' },
      { id: 'halstead-metrics', title: 'Halstead Metrics', level: 'advanced', description: 'Vocabulary, volume, difficulty and effort.' },
      { id: 'coupling-cohesion-metrics', title: 'Coupling & Cohesion Metrics', level: 'advanced', description: 'CK metrics, LCOM and DIT.' },
      { id: 'defect-metrics', title: 'Defect Metrics', level: 'intermediate', description: 'Defect density, escape rate and DRE.' },
      { id: 'gqm-paradigm', title: 'Goal-Question-Metric (GQM)', level: 'intermediate', description: 'Top-down measurement framework.' },
      { id: 'dora-metrics', title: 'DORA Metrics', level: 'intermediate', description: 'Lead time, deploy frequency, MTTR, change-failure rate.' },
      { id: 'space-framework', title: 'SPACE Framework', level: 'intermediate', description: 'Satisfaction, performance, activity, communication, efficiency.' },
      { id: 'devex-core-metrics', title: 'DevEx Core Metrics', level: 'intermediate', description: 'Flow, friction and cognitive load (Forsgren).' },
      { id: 'flow-metrics', title: 'Flow Metrics', level: 'intermediate', description: 'Flow time, flow load and flow efficiency.' },
    ],
  },
  {
    id: 'security-engineering',
    title: 'Software Security Engineering Process',
    summary: 'Building security into the software development lifecycle.',
    nodes: [
      { id: 'secure-sdlc', title: 'Secure SDLC', level: 'intermediate', description: 'Security activities across SDLC phases.' },
      { id: 'security-requirements-engineering', title: 'Security Requirements Engineering', level: 'intermediate', description: 'Eliciting and specifying security requirements.' },
      { id: 'threat-modeling-process', title: 'Threat Modeling (Process)', level: 'intermediate', description: 'STRIDE, LINDDUN, attack trees and PASTA.' },
      { id: 'secure-design-principles-se', title: 'Secure Design Principles', level: 'intermediate', description: 'Saltzer & Schroeder principles for engineers.' },
      { id: 'secure-coding-practices', title: 'Secure Coding Practices', level: 'intermediate', description: 'CERT, MISRA and OWASP secure coding.' },
      { id: 'owasp-top-10', title: 'OWASP Top 10', level: 'intermediate', description: 'Top web application security risks.' },
      { id: 'owasp-asvs', title: 'OWASP ASVS', level: 'advanced', description: 'Application Security Verification Standard.' },
      { id: 'sast-dast-iast', title: 'SAST, DAST & IAST', level: 'intermediate', description: 'Static, dynamic and interactive security testing.' },
      { id: 'supply-chain-security-process', title: 'Supply Chain Security (Process)', level: 'advanced', description: 'Dependency, build and artifact integrity.' },
      { id: 'sbom-and-slsa', title: 'SBOM & SLSA', level: 'advanced', description: 'Software Bill of Materials and SLSA levels.' },
      { id: 'vulnerability-management-process', title: 'Vulnerability Management Process', level: 'intermediate', description: 'CVE/CVSS, triage and remediation flows.' },
      { id: 'microsoft-sdl', title: 'Microsoft SDL', level: 'intermediate', description: 'Microsoft Security Development Lifecycle.' },
      { id: 'bsimm-and-samm', title: 'BSIMM & OWASP SAMM', level: 'advanced', description: 'Maturity models for software security.' },
    ],
  },
  {
    id: 'tools-ides',
    title: 'Software Engineering Tools & IDEs',
    summary: 'Editors, IDEs and engineering tools that boost productivity.',
    nodes: [
      { id: 'ide-overview', title: 'IDE Overview', level: 'beginner', description: 'What an IDE is and what makes a good one.' },
      { id: 'jetbrains-ides', title: 'JetBrains IDEs', level: 'beginner', description: 'IntelliJ, PyCharm, WebStorm, Rider and others.' },
      { id: 'visual-studio-code', title: 'Visual Studio Code', level: 'beginner', description: 'Microsoft’s cross-platform editor and ecosystem.' },
      { id: 'visual-studio', title: 'Visual Studio', level: 'beginner', description: 'Full-feature Microsoft IDE.' },
      { id: 'eclipse-ide', title: 'Eclipse IDE', level: 'beginner', description: 'Open-source extensible IDE.' },
      { id: 'vim-and-neovim', title: 'Vim & Neovim', level: 'intermediate', description: 'Modal editing, plugins and Lua/Vimscript.' },
      { id: 'emacs-editor', title: 'Emacs', level: 'intermediate', description: 'Extensible Lisp-powered editor.' },
      { id: 'sublime-and-nova', title: 'Sublime Text & Nova', level: 'beginner', description: 'Lightweight commercial editors.' },
      { id: 'code-formatters', title: 'Code Formatters', level: 'beginner', description: 'Prettier, Black, gofmt, rustfmt and clang-format.' },
      { id: 'linters-overview', title: 'Linters Overview', level: 'beginner', description: 'ESLint, Pylint, RuboCop, golangci-lint and others.' },
      { id: 'debugger-tools', title: 'Debugger Tools', level: 'beginner', description: 'gdb, lldb, IDE debuggers and time-travel debuggers.' },
      { id: 'profilers', title: 'Profilers', level: 'intermediate', description: 'CPU, memory and async profilers.' },
      { id: 'shell-and-terminal-tools', title: 'Shell & Terminal Tools', level: 'beginner', description: 'Bash, zsh, fish, tmux and modern terminals.' },
      { id: 'ai-coding-assistants', title: 'AI Coding Assistants', level: 'intermediate', description: 'Inline completion, chat and refactoring assistants.' },
      { id: 'copilot-cursor-cline', title: 'Copilot, Cursor, Cline & Friends', level: 'intermediate', description: '2026 AI-first coding tools.' },
      { id: 'diff-and-merge-tools', title: 'Diff & Merge Tools', level: 'beginner', description: 'Meld, Beyond Compare, KDiff3, IDE diff/merge.' },
      { id: 'code-search-tools', title: 'Code Search Tools', level: 'beginner', description: 'ripgrep, Sourcegraph, Comby and code intel.' },
    ],
  },
  {
    id: 'reuse-components',
    title: 'Software Reuse, Components & Libraries',
    summary: 'Building and consuming reusable software.',
    nodes: [
      { id: 'software-reuse-fundamentals', title: 'Software Reuse Fundamentals', level: 'beginner', description: 'Why and how to reuse code, components and assets.' },
      { id: 'library-vs-framework', title: 'Library vs Framework', level: 'beginner', description: 'Inversion of control and trade-offs.' },
      { id: 'component-based-software-engineering', title: 'Component-Based Software Engineering', level: 'intermediate', description: 'Components, interfaces and composition.' },
      { id: 'product-line-engineering', title: 'Software Product Line Engineering', level: 'advanced', description: 'Feature-based product family engineering.' },
      { id: 'inner-source-reuse', title: 'Inner-Source Reuse', level: 'intermediate', description: 'Open-source practices applied internally.' },
      { id: 'reuse-economics', title: 'Reuse Economics', level: 'intermediate', description: 'Cost, payoff and break-even of reuse programs.' },
    ],
  },
  {
    id: 'open-source',
    title: 'Open Source Software Engineering',
    summary: 'Engineering with and around open source software.',
    nodes: [
      { id: 'oss-fundamentals', title: 'OSS Fundamentals', level: 'beginner', description: 'Definitions, OSI, free software and OSS history.' },
      { id: 'oss-licenses', title: 'OSS Licenses', level: 'beginner', description: 'MIT, Apache, BSD, GPL, MPL and dual licenses.' },
      { id: 'copyleft-vs-permissive', title: 'Copyleft vs Permissive', level: 'beginner', description: 'License families and viral effects.' },
      { id: 'choosing-an-oss-license', title: 'Choosing an OSS License', level: 'beginner', description: 'Picking a license for a project.' },
      { id: 'contributing-to-oss', title: 'Contributing to OSS', level: 'beginner', description: 'Issues, PRs, CLAs and community etiquette.' },
      { id: 'open-source-governance', title: 'Open Source Governance', level: 'intermediate', description: 'BDFL, meritocracy, foundations and councils.' },
      { id: 'foundations-and-stewards', title: 'Foundations & Stewards', level: 'intermediate', description: 'Apache, Linux, CNCF, Eclipse, OpenJS and others.' },
      { id: 'oss-security-supply-chain', title: 'OSS Security & Supply Chain', level: 'advanced', description: 'Sigstore, Scorecard, OSSF and provenance.' },
      { id: 'oss-sustainability', title: 'OSS Sustainability', level: 'intermediate', description: 'Funding, maintainer burnout and stewardship.' },
    ],
  },
  {
    id: 'formal-methods',
    title: 'Formal Methods & Verification',
    summary: 'Mathematically grounded specification and verification.',
    nodes: [
      { id: 'formal-methods-overview', title: 'Formal Methods Overview', level: 'advanced', description: 'When and why to use formal methods.' },
      { id: 'formal-specification', title: 'Formal Specification', level: 'advanced', description: 'Precise, unambiguous behavior descriptions.' },
      { id: 'z-notation', title: 'Z Notation', level: 'advanced', description: 'Set-theoretic specification language.' },
      { id: 'vdm-method', title: 'VDM (Vienna Development Method)', level: 'advanced', description: 'Model-oriented formal method.' },
      { id: 'b-method', title: 'B-Method', level: 'advanced', description: 'Refinement-based formal method.' },
      { id: 'alloy-language', title: 'Alloy', level: 'advanced', description: 'Lightweight first-order relational logic.' },
      { id: 'tla-plus', title: 'TLA+', level: 'advanced', description: 'Lamport’s temporal logic of actions.' },
      { id: 'model-checking', title: 'Model Checking', level: 'advanced', description: 'Exhaustive state-space verification.' },
      { id: 'theorem-proving', title: 'Theorem Proving', level: 'advanced', description: 'Coq, Isabelle, Lean and proof assistants.' },
      { id: 'abstract-interpretation', title: 'Abstract Interpretation', level: 'advanced', description: 'Sound static analysis via abstraction.' },
      { id: 'runtime-verification', title: 'Runtime Verification', level: 'advanced', description: 'Monitoring program behavior at runtime.' },
      { id: 'type-driven-design', title: 'Type-Driven Design', level: 'intermediate', description: 'Using types to enforce invariants by construction.' },
    ],
  },
  {
    id: 'empirical-se',
    title: 'Empirical Software Engineering',
    summary: 'Evidence-based methods for studying software engineering.',
    nodes: [
      { id: 'empirical-se-fundamentals', title: 'Empirical SE Fundamentals', level: 'advanced', description: 'Why and how to study software empirically.' },
      { id: 'evidence-based-se', title: 'Evidence-Based Software Engineering', level: 'advanced', description: 'Decisions backed by evidence.' },
      { id: 'controlled-experiments-se', title: 'Controlled Experiments', level: 'advanced', description: 'Randomized experiments in SE.' },
      { id: 'case-study-research-se', title: 'Case Study Research', level: 'intermediate', description: 'Yin-style and Runeson-style SE case studies.' },
      { id: 'mining-software-repositories', title: 'Mining Software Repositories', level: 'advanced', description: 'Extracting insights from VCS, issues and discussions.' },
      { id: 'systematic-literature-reviews', title: 'Systematic Literature Reviews', level: 'advanced', description: 'Kitchenham-style SLR methodology.' },
      { id: 'meta-analysis-se', title: 'Meta-Analysis in SE', level: 'advanced', description: 'Combining results across studies.' },
      { id: 'se-research-methods', title: 'SE Research Methods', level: 'advanced', description: 'Quantitative, qualitative and mixed methods.' },
    ],
  },
  {
    id: 'economics',
    title: 'Software Engineering Economics',
    summary: 'Cost, value and economic decision-making in software.',
    nodes: [
      { id: 'software-economics-fundamentals', title: 'Software Economics Fundamentals', level: 'intermediate', description: 'Boehm-style software economics.' },
      { id: 'cost-benefit-analysis', title: 'Cost-Benefit Analysis', level: 'beginner', description: 'CBA for engineering decisions.' },
      { id: 'total-cost-of-ownership', title: 'Total Cost of Ownership', level: 'intermediate', description: 'Lifecycle costs of a software solution.' },
      { id: 'build-vs-buy-decisions', title: 'Build vs Buy Decisions', level: 'intermediate', description: 'When to build, when to buy and when to OSS.' },
      { id: 'vendor-evaluation', title: 'Vendor Evaluation', level: 'intermediate', description: 'RFI/RFP, scoring and POC frameworks.' },
      { id: 'saas-vs-self-hosted', title: 'SaaS vs Self-Hosted', level: 'intermediate', description: 'Trade-offs for adopting platforms.' },
      { id: 'pricing-models-engineering', title: 'Pricing Models (Engineering View)', level: 'intermediate', description: 'Per-seat, usage, tiered, freemium economics.' },
      { id: 'value-engineering', title: 'Value Engineering', level: 'intermediate', description: 'Maximizing value vs cost in software.' },
    ],
  },
  {
    id: 'ethics-professionalism',
    title: 'Software Engineering Ethics & Professionalism',
    summary: 'Professional, ethical and societal responsibility.',
    nodes: [
      { id: 'engineering-ethics-fundamentals', title: 'Engineering Ethics Fundamentals', level: 'beginner', description: 'Why ethics matters for software engineers.' },
      { id: 'acm-code-of-ethics', title: 'ACM Code of Ethics', level: 'beginner', description: 'ACM principles and obligations.' },
      { id: 'ieee-cs-code-of-ethics', title: 'IEEE-CS Code of Ethics', level: 'beginner', description: 'IEEE Computer Society code of ethics.' },
      { id: 'professional-responsibility', title: 'Professional Responsibility', level: 'beginner', description: 'Duty to public, employer, profession and self.' },
      { id: 'whistleblowing-in-software', title: 'Whistleblowing in Software', level: 'intermediate', description: 'Reporting unethical software behavior.' },
      { id: 'responsible-ai-engineering', title: 'Responsible AI for Engineers', level: 'intermediate', description: 'Engineering view of responsible AI obligations.' },
      { id: 'privacy-by-design-ethics', title: 'Privacy by Design (Ethics)', level: 'intermediate', description: 'Privacy as a default engineering value.' },
      { id: 'software-engineering-licensing', title: 'Software Engineering Licensing', level: 'intermediate', description: 'P.Eng / PEng / Chartered Engineer routes for SE.' },
    ],
  },
  {
    id: 'specialized-domains',
    title: 'Specialized Software Engineering Domains',
    summary: 'How SE practice adapts in specialized application domains.',
    nodes: [
      { id: 'real-time-software-engineering', title: 'Real-Time Software Engineering', level: 'advanced', description: 'Hard and soft real-time engineering practices.' },
      { id: 'embedded-software-engineering', title: 'Embedded Software Engineering', level: 'advanced', description: 'Engineering for resource-constrained devices.' },
      { id: 'safety-critical-software', title: 'Safety-Critical Software', level: 'advanced', description: 'DO-178C, IEC 61508, ISO 26262 and similar.' },
      { id: 'mission-critical-software', title: 'Mission-Critical Software', level: 'advanced', description: 'Engineering for systems where failures are catastrophic.' },
      { id: 'scientific-software-engineering', title: 'Scientific Software Engineering', level: 'intermediate', description: 'Engineering practices for research code and HPC.' },
      { id: 'hpc-software-engineering', title: 'HPC Software Engineering', level: 'advanced', description: 'High-performance computing engineering practices.' },
      { id: 'mobile-engineering-process', title: 'Mobile Software Engineering Process', level: 'intermediate', description: 'Mobile-specific engineering and release flows.' },
      { id: 'web-engineering-process', title: 'Web Software Engineering Process', level: 'intermediate', description: 'Web-specific engineering and delivery practices.' },
      { id: 'game-engineering-process', title: 'Game Software Engineering Process', level: 'advanced', description: 'Game-specific engineering and content pipelines.' },
      { id: 'ml-engineering-process', title: 'ML Software Engineering Process', level: 'advanced', description: 'MLOps and engineering practices for ML systems.' },
      { id: 'data-engineering-process', title: 'Data Software Engineering Process', level: 'intermediate', description: 'DataOps and engineering practices for data systems.' },
      { id: 'iot-engineering-process', title: 'IoT Software Engineering Process', level: 'advanced', description: 'IoT/edge engineering and OTA update flows.' },
      { id: 'robotics-engineering', title: 'Robotics Software Engineering', level: 'advanced', description: 'ROS-style engineering for robotics systems.' },
    ],
  },
  {
    id: 'education-career',
    title: 'Software Engineering Education, Career & Interviews',
    summary: 'Becoming and staying a strong software engineer.',
    nodes: [
      { id: 'engineering-career-tracks', title: 'Engineering Career Tracks', level: 'beginner', description: 'IC and management tracks in 2026.' },
      { id: 'ic-engineering-ladder', title: 'IC Engineering Ladder', level: 'beginner', description: 'Junior, mid, senior, staff, principal and beyond.' },
      { id: 'continuous-learning-strategies', title: 'Continuous Learning Strategies', level: 'beginner', description: 'How great engineers keep learning.' },
      { id: 'learning-resources-curated', title: 'Curated Learning Resources', level: 'beginner', description: 'Books, courses, podcasts and newsletters.' },
      { id: 'coding-interviews-process', title: 'Coding Interview Process', level: 'beginner', description: 'DS&A, mock interviews and prep strategies.' },
      { id: 'behavioral-interviews-process', title: 'Behavioral Interview Process', level: 'beginner', description: 'STAR, leadership stories and values fit.' },
      { id: 'take-home-and-pair-interviews', title: 'Take-Home & Pair Interviews', level: 'beginner', description: 'Take-home assignments and pair-programming rounds.' },
      { id: 'portfolios-side-projects', title: 'Portfolios & Side Projects', level: 'beginner', description: 'Side projects, OSS contributions and portfolios.' },
      { id: 'engineering-conferences', title: 'Engineering Conferences', level: 'beginner', description: 'Talks, papers and the conference circuit.' },
      { id: 'communities-of-practice', title: 'Communities of Practice', level: 'beginner', description: 'Internal and external CoPs for engineers.' },
      { id: 'engineering-certifications', title: 'Engineering Certifications', level: 'beginner', description: 'ISTQB, AWS, Azure, GCP, K8s and others.' },
    ],
  },
  {
    id: 'devprod-devex',
    title: 'Developer Productivity & Developer Experience',
    summary: 'Engineering effectiveness, flow and DevEx.',
    nodes: [
      { id: 'developer-productivity-fundamentals', title: 'Developer Productivity Fundamentals', level: 'intermediate', description: 'What productivity means and how to think about it.' },
      { id: 'developer-experience-fundamentals', title: 'Developer Experience Fundamentals', level: 'intermediate', description: 'DevEx as a discipline.' },
      { id: 'inner-vs-outer-loop', title: 'Inner vs Outer Loop', level: 'intermediate', description: 'Code-build-test-run vs commit-deploy-observe.' },
      { id: 'flow-and-cognitive-load', title: 'Flow & Cognitive Load', level: 'intermediate', description: 'Reducing cognitive load and protecting flow.' },
      { id: 'focus-time-engineering', title: 'Focus Time Engineering', level: 'intermediate', description: 'Maker schedules, deep work and focus blocks.' },
      { id: 'onboarding-and-paved-paths', title: 'Onboarding & Paved Paths', level: 'intermediate', description: 'Fast, safe defaults for new engineers.' },
      { id: 'internal-developer-platforms-overview', title: 'Internal Developer Platforms (Overview)', level: 'intermediate', description: 'IDPs as a productivity multiplier.' },
      { id: 'toil-and-friction', title: 'Toil & Friction', level: 'intermediate', description: 'Identifying and removing developer friction.' },
      { id: 'engineering-effectiveness', title: 'Engineering Effectiveness', level: 'intermediate', description: 'EE teams, charters and impact measurement.' },
    ],
  },
  {
    id: 'ai-augmented',
    title: 'AI-Augmented Software Engineering (2026)',
    summary: 'How LLMs and agents reshape engineering practice in 2026.',
    nodes: [
      { id: 'ai-augmented-engineering-overview', title: 'AI-Augmented Engineering Overview', level: 'intermediate', description: 'Map of AI-assisted engineering activities.' },
      { id: 'llm-coding-assistants-2026', title: 'LLM Coding Assistants (2026)', level: 'intermediate', description: 'State of inline, chat and agent assistants in 2026.' },
      { id: 'prompt-patterns-for-coding', title: 'Prompt Patterns for Coding', level: 'intermediate', description: 'Effective prompting for engineering tasks.' },
      { id: 'ai-pair-programming', title: 'AI Pair Programming', level: 'intermediate', description: 'Working with an AI as a pair partner.' },
      { id: 'ai-code-review', title: 'AI Code Review', level: 'intermediate', description: 'AI-driven review for quality, security and style.' },
      { id: 'ai-test-generation', title: 'AI Test Generation', level: 'intermediate', description: 'Generating unit, property and integration tests.' },
      { id: 'ai-spec-and-design', title: 'AI Spec & Design', level: 'intermediate', description: 'Spec drafting, ADRs and design exploration with AI.' },
      { id: 'ai-refactoring', title: 'AI Refactoring', level: 'intermediate', description: 'Bulk and surgical refactors with AI help.' },
      { id: 'ai-bug-fixing', title: 'AI Bug Fixing', level: 'intermediate', description: 'Triage, RCA and patch generation with AI.' },
      { id: 'ai-documentation-gen', title: 'AI Documentation Generation', level: 'intermediate', description: 'Generating and maintaining documentation with AI.' },
      { id: 'ai-code-search-navigation', title: 'AI Code Search & Navigation', level: 'intermediate', description: 'Semantic code search and code intelligence with AI.' },
      { id: 'agentic-coding-2026', title: 'Agentic Coding (2026)', level: 'advanced', description: 'Autonomous coding agents in 2026 workflows.' },
      { id: 'background-coding-agents', title: 'Background Coding Agents', level: 'advanced', description: 'Long-running background agents for engineering tasks.' },
      { id: 'evals-for-coding-agents', title: 'Evals for Coding Agents', level: 'advanced', description: 'SWE-bench, HumanEval+ and modern coding evals.' },
      { id: 'ai-code-quality-trust', title: 'AI Code Quality & Trust', level: 'intermediate', description: 'Verifying, attributing and trusting AI-written code.' },
      { id: 'ai-coding-economics', title: 'AI Coding Economics', level: 'intermediate', description: 'Costs, leverage and ROI of AI-assisted engineering.' },
    ],
  },
  {
    id: 'frontier-2026',
    title: 'Frontier Trends in Software Engineering (2026)',
    summary: 'Where the engineering discipline is heading in 2026 and beyond.',
    nodes: [
      { id: 'post-agile-engineering', title: 'Post-Agile Engineering', level: 'advanced', description: 'What comes after agile orthodoxy.' },
      { id: 'spec-driven-development', title: 'Spec-Driven Development', level: 'advanced', description: 'Specs as the unit of programming with AI.' },
      { id: 'product-engineering-mode', title: 'Product Engineering Mode', level: 'advanced', description: 'Engineers owning the full product slice.' },
      { id: 'generative-engineering', title: 'Generative Engineering', level: 'advanced', description: 'Code, tests and infra generated end-to-end.' },
      { id: 'code-as-data', title: 'Code as Data', level: 'advanced', description: 'Treating codebases as queryable, transformable data.' },
      { id: 'software-2-0-paradigm', title: 'Software 2.0 Paradigm', level: 'advanced', description: 'Karpathy-style software defined by data and weights.' },
      { id: 'end-of-traditional-coding-debate', title: 'End-of-Traditional-Coding Debate', level: 'advanced', description: 'Will engineers still hand-write code?' },
      { id: 'programming-by-example', title: 'Programming by Example', level: 'advanced', description: 'Demonstration-driven program synthesis.' },
      { id: 'low-code-no-code-engineering', title: 'Low-Code / No-Code Engineering', level: 'intermediate', description: 'Engineering with citizen developers and platforms.' },
      { id: 'nl-programming', title: 'Natural Language Programming', level: 'advanced', description: 'NL specs as primary engineering input.' },
      { id: 'type-safe-stacks-2026', title: 'Type-Safe Stacks (2026)', level: 'intermediate', description: 'Modern end-to-end type-safe engineering stacks.' },
      { id: 'effect-systems-trends', title: 'Effect Systems Trends', level: 'advanced', description: 'Algebraic effects and capabilities in mainstream langs.' },
      { id: 'wasm-portable-runtimes', title: 'WASM & Portable Runtimes', level: 'advanced', description: 'WebAssembly as universal runtime for engineering.' },
      { id: 'platform-engineering-discipline', title: 'Platform Engineering as a Discipline', level: 'advanced', description: 'Platform engineering as a 2026 SE specialty.' },
      { id: 'internal-ai-platforms-se', title: 'Internal AI Platforms (Engineering)', level: 'advanced', description: 'Internal LLM/agent platforms for engineers.' },
      { id: 'vibe-coding-debate', title: 'Vibe Coding Debate', level: 'intermediate', description: 'Vibe coding vs disciplined engineering in 2026.' },
      { id: 'post-llm-engineering', title: 'Post-LLM Engineering', level: 'advanced', description: 'What if foundation models plateau or shift?' },
      { id: 'formal-methods-renaissance', title: 'Formal Methods Renaissance', level: 'advanced', description: 'AI-driven proofs and verification revival.' },
      { id: 'engineering-and-policy-2026', title: 'Engineering & Policy (2026)', level: 'advanced', description: 'EU AI Act, software liability and SE.' },
      { id: 'sustainable-software-engineering', title: 'Sustainable Software Engineering', level: 'intermediate', description: 'Carbon, energy and green software engineering.' },
    ],
  },
]

let nodeOrder = 0
function emitRoadmap() {
  const roadmap = {
    title: 'Software Engineering Learning Roadmap',
    stages: STAGES.map((s) => ({
      id: s.id,
      title: s.title,
      summary: s.summary,
      nodes: s.nodes.map((n) => ({
        id: n.id,
        title: n.title,
        topicId: n.id,
        status: 'core',
        description: n.description ?? n.title,
      })),
    })),
  }
  writeFileSync(
    resolve(SUBJECT_DIR, 'roadmap.json'),
    JSON.stringify(roadmap, null, 2) + '\n',
  )
}

function emitRootTopics() {
  let created = 0
  let skipped = 0
  let order = 0
  for (const stage of STAGES) {
    for (const node of stage.nodes) {
      order += 1
      const dir = resolve(TOPICS_DIR, node.id)
      const file = resolve(dir, 'topic.json')
      if (existsSync(file)) {
        skipped += 1
        continue
      }
      const meta = {
        id: node.id,
        title: node.title,
        summary: node.description ?? node.title,
        order,
        level: node.level ?? 'beginner',
        tags: [stage.id],
      }
      mkdirSync(dir, { recursive: true })
      writeFileSync(file, JSON.stringify(meta, null, 2) + '\n')
      created += 1
    }
  }
  console.log(`[software-engineering:seed] roadmap stages=${STAGES.length} nodes=${STAGES.reduce((s, x) => s + x.nodes.length, 0)}`)
  console.log(`[software-engineering:seed] root topics: created ${created}, skipped ${skipped}`)
}

emitRoadmap()
emitRootTopics()
nodeOrder // keep eslint happy if unused
