import { addEnterpriseStages } from '../_shared/enterpriseAdditions.mjs'

addEnterpriseStages({
  subjectId: 'claude',
  stages: [
    {
      id: 'enterprise-delivery',
      title: 'Enterprise Development & Enablement',
      summary: 'Strategy, governance, platform and enablement for adopting Claude at enterprise scale.',
      tag: 'enterprise-delivery',
      nodes: [
        {
          id: 'enterprise-claude-strategy',
          title: 'Enterprise Claude Strategy & Operating Model',
          summary: 'Strategy, operating model and Claude center of excellence.',
          level: 'advanced',
          children: [
            { id: 'claude-center-of-excellence', title: 'Claude Center of Excellence (CoE)' },
            { id: 'claude-operating-model', title: 'Claude Target Operating Model' },
            { id: 'claude-strategy-roadmap', title: 'Claude Adoption Strategy & Roadmap' },
            { id: 'claude-portfolio-strategy', title: 'Claude Use-Case Portfolio Strategy' },
            { id: 'executive-sponsorship', title: 'Executive Sponsorship & Steering' },
            { id: 'claude-maturity-model', title: 'Claude Adoption Maturity Model' },
            { id: 'value-streams-mapping', title: 'Value Streams & Capability Mapping' },
          ],
        },
        {
          id: 'discovery-requirements',
          title: 'Discovery & Requirements Engineering',
          summary: 'Use case discovery, business case and requirements engineering for Claude.',
          level: 'intermediate',
          children: [
            { id: 'use-case-discovery', title: 'Claude Use Case Discovery & Ideation' },
            { id: 'business-case-roi', title: 'Business Case & ROI Modeling' },
            { id: 'feasibility-assessment', title: 'Feasibility & Risk Assessment' },
            { id: 'stakeholder-management', title: 'Stakeholder Mapping & Management' },
            { id: 'requirements-elicitation', title: 'Requirements Elicitation Techniques' },
            { id: 'success-criteria-kpis', title: 'Success Criteria, OKRs & KPIs' },
            { id: 'poc-to-production-criteria', title: 'PoC-to-Production Criteria' },
          ],
        },
        {
          id: 'solution-architecture-process',
          title: 'Solution Architecture Process',
          summary: 'Architecture decisions, design reviews and reference blueprints for Claude apps.',
          level: 'advanced',
          children: [
            { id: 'architecture-decision-records', title: 'Architecture Decision Records (ADRs)' },
            { id: 'design-review-board', title: 'Design Review Board (DRB)' },
            { id: 'reference-architectures', title: 'Reference Architectures for Claude' },
            { id: 'solution-blueprints', title: 'Solution Blueprints' },
            { id: 'non-functional-requirements', title: 'Non-Functional Requirements (NFRs)' },
            { id: 'capacity-quota-planning', title: 'Capacity & Quota Planning' },
            { id: 'threat-modeling-process', title: 'Threat Modeling for Claude Apps' },
            { id: 'tech-radar', title: 'Technology Radar Practice' },
          ],
        },
        {
          id: 'engineering-standards',
          title: 'Engineering Standards & Quality',
          summary: 'Coding standards, prompt standards, review process and quality gates.',
          level: 'intermediate',
          children: [
            { id: 'coding-standards', title: 'Engineering Coding Standards' },
            { id: 'prompt-engineering-standards', title: 'Prompt Engineering Standards' },
            { id: 'peer-review-process', title: 'Peer Review & Code Review Process' },
            { id: 'definition-of-done', title: 'Definition of Done & Ready' },
            { id: 'quality-gates', title: 'Quality Gates & Promotion Rules' },
            { id: 'architectural-fitness-functions', title: 'Architectural Fitness Functions' },
            { id: 'engineering-scorecards', title: 'Engineering Scorecards & Health Metrics' },
          ],
        },
        {
          id: 'developer-platform',
          title: 'Developer Platform & Paved Roads',
          summary: 'Internal developer platform, golden paths and shared SDKs for Claude teams.',
          level: 'advanced',
          children: [
            { id: 'internal-developer-portal', title: 'Internal Developer Portal (IDP)' },
            { id: 'claude-starter-templates', title: 'Claude Starter Templates & Scaffolds' },
            { id: 'golden-paths', title: 'Golden Paths for Claude Teams' },
            { id: 'shared-libraries-sdks', title: 'Shared Libraries & Internal SDKs' },
            { id: 'self-service-tooling', title: 'Self-Service Tooling & Provisioning' },
            { id: 'inner-source-program', title: 'Inner-Source Program' },
            { id: 'developer-experience-metrics', title: 'Developer Experience (DevEx) Metrics' },
            { id: 'platform-as-product', title: 'Platform-as-a-Product Mindset' },
          ],
        },
        {
          id: 'procurement-sourcing',
          title: 'Vendor & Model Procurement',
          summary: 'Anthropic contracts, partner sourcing and multi-model strategy.',
          level: 'advanced',
          children: [
            { id: 'vendor-due-diligence', title: 'Vendor Due Diligence (Anthropic & Partners)' },
            { id: 'model-evaluation-framework', title: 'Model Evaluation Framework' },
            { id: 'build-vs-buy', title: 'Build vs Buy vs Partner Analysis' },
            { id: 'multi-vendor-strategy', title: 'Multi-Vendor / Multi-Model Strategy' },
            { id: 'data-processing-agreements', title: 'Data Processing Agreements (DPAs)' },
            { id: 'contract-sla-negotiation', title: 'Contract & SLA Negotiation' },
            { id: 'model-sourcing-policy', title: 'Model Sourcing & Usage Policy' },
          ],
        },
        {
          id: 'enterprise-data-governance',
          title: 'Enterprise Data Governance for Claude',
          summary: 'Data classification, residency and stewardship for Claude inputs/outputs.',
          level: 'advanced',
          children: [
            { id: 'data-classification', title: 'Data Classification & Sensitivity Tagging' },
            { id: 'data-residency-controls', title: 'Data Residency & Sovereignty Controls' },
            { id: 'data-lineage', title: 'Data Lineage & Provenance' },
            { id: 'data-stewardship', title: 'Data Stewardship & Ownership' },
            { id: 'data-quality-management', title: 'Data Quality Management' },
            { id: 'consent-management', title: 'Consent & Preference Management' },
            { id: 'pii-redaction-process', title: 'PII Redaction & Anonymization Process' },
          ],
        },
        {
          id: 'risk-compliance-program',
          title: 'Risk & Compliance Program',
          summary: 'Risk registers, model risk management and audit/certification programs.',
          level: 'advanced',
          children: [
            { id: 'enterprise-risk-register', title: 'Enterprise AI Risk Register' },
            { id: 'control-libraries', title: 'Control Libraries & Mappings' },
            { id: 'model-risk-management', title: 'Model Risk Management (MRM/SR 11-7)' },
            { id: 'third-party-risk-management', title: 'Third-Party Risk Management (TPRM)' },
            { id: 'audit-readiness', title: 'Audit Readiness & Evidence Collection' },
            { id: 'certifications-soc2-iso', title: 'SOC 2 / ISO 27001 / ISO 42001 Programs' },
            { id: 'regulatory-reporting', title: 'Regulatory Reporting & Disclosures' },
            { id: 'model-cards-datasheets', title: 'Model Cards & System Cards' },
            { id: 'algorithmic-impact-assessment', title: 'Algorithmic Impact Assessments' },
          ],
        },
        {
          id: 'enterprise-finops-program',
          title: 'Enterprise FinOps for Claude',
          summary: 'FinOps program: allocation, forecasting, unit economics for Claude usage.',
          level: 'advanced',
          children: [
            { id: 'cost-allocation-chargeback', title: 'Cost Allocation, Showback & Chargeback' },
            { id: 'budget-governance', title: 'Budget Governance & Guardrails' },
            { id: 'cost-forecasting', title: 'Cost Forecasting & Modeling' },
            { id: 'unit-economics-per-conversation', title: 'Unit Economics per Conversation / Task' },
            { id: 'rate-card-management', title: 'Internal Rate Card Management' },
            { id: 'caching-batching-optimization', title: 'Caching & Batching for Cost' },
            { id: 'finops-reporting', title: 'FinOps Reporting & Reviews' },
          ],
        },
        {
          id: 'program-portfolio-management',
          title: 'Program & Portfolio Management',
          summary: 'Intake, prioritization and portfolio governance for Claude initiatives.',
          level: 'intermediate',
          children: [
            { id: 'intake-prioritization', title: 'Demand Intake & Prioritization' },
            { id: 'okrs-roadmaps', title: 'OKRs & Roadmaps' },
            { id: 'dependency-mapping', title: 'Cross-Team Dependency Mapping' },
            { id: 'status-reporting', title: 'Status Reporting & Cadences' },
            { id: 'benefits-realization', title: 'Benefits Realization Tracking' },
            { id: 'agile-at-scale', title: 'Agile-at-Scale (SAFe / LeSS / Scrum@Scale)' },
            { id: 'portfolio-rebalancing', title: 'Portfolio Rebalancing & Stage Gates' },
          ],
        },
        {
          id: 'change-enablement',
          title: 'Change Enablement & Culture',
          summary: 'Organizational change, training and adoption of Claude.',
          level: 'intermediate',
          children: [
            { id: 'org-change-management', title: 'Organizational Change Management (OCM)' },
            { id: 'communications-strategy', title: 'Communications & Narrative Strategy' },
            { id: 'training-curricula', title: 'Training Curricula & Certifications' },
            { id: 'communities-of-practice', title: 'Communities of Practice (CoPs)' },
            { id: 'champions-network', title: 'Claude Champions Network' },
            { id: 'adoption-metrics', title: 'Adoption & Stickiness Metrics' },
            { id: 'workforce-reskilling', title: 'Workforce Reskilling & Job Redesign' },
          ],
        },
        {
          id: 'legal-ethical-governance',
          title: 'Legal & Ethical Governance',
          summary: 'AI ethics, IP, liability and acceptable use governance for Claude.',
          level: 'advanced',
          children: [
            { id: 'ai-ethics-board', title: 'AI Ethics Board / Review Council' },
            { id: 'ip-and-licensing', title: 'IP, Copyright & Licensing for AI Outputs' },
            { id: 'liability-frameworks', title: 'Liability & Indemnity Frameworks' },
            { id: 'acceptable-use-policy', title: 'Acceptable Use Policy (AUP)' },
            { id: 'responsible-disclosure-policy', title: 'Responsible Disclosure & VDP' },
            { id: 'dpia-process', title: 'Data Protection Impact Assessment (DPIA)' },
            { id: 'open-source-governance', title: 'Open-Source Model & Code Governance' },
          ],
        },
      ],
    },
    {
      id: 'production-lifecycle',
      title: 'Production-Grade Application Lifecycle',
      summary: 'End-to-end delivery lifecycle for production-grade Claude applications.',
      tag: 'production-lifecycle',
      nodes: [
        {
          id: 'requirements-design-phase',
          title: 'Requirements & Design Phase',
          summary: 'Discovery, requirements, design and sign-off for new Claude features.',
          level: 'intermediate',
          children: [
            { id: 'discovery-workshops', title: 'Discovery Workshops & Event Storming' },
            { id: 'jobs-and-personas', title: 'Personas & Job Stories' },
            { id: 'journey-mapping', title: 'Journey Mapping & Service Blueprinting' },
            { id: 'prd-templates', title: 'PRDs, Spec & Brief Templates' },
            { id: 'lo-fi-prototyping', title: 'Lo-Fi Prototyping for Conversational Flows' },
            { id: 'design-sign-off', title: 'Design Sign-Off & Acceptance' },
            { id: 'risk-impact-assessment', title: 'Risk & Impact Assessment for Features' },
          ],
        },
        {
          id: 'implementation-build-phase',
          title: 'Implementation & Build Phase',
          summary: 'Build discipline, branching, code ownership and refactoring practice.',
          level: 'intermediate',
          children: [
            { id: 'pairing-and-mobbing', title: 'Pairing, Mobbing & Ensemble Programming' },
            { id: 'trunk-based-development', title: 'Trunk-Based Development' },
            { id: 'branching-strategy', title: 'Branching Strategy & Release Branches' },
            { id: 'commit-conventions', title: 'Commit Conventions & Conventional Commits' },
            { id: 'code-ownership-codeowners', title: 'Code Ownership & CODEOWNERS' },
            { id: 'refactoring-discipline', title: 'Refactoring Discipline' },
            { id: 'feature-toggling-build', title: 'Feature Toggling During Build' },
          ],
        },
        {
          id: 'testing-validation-phase',
          title: 'Testing & Validation Phase',
          summary: 'End-to-end test strategy, performance, security and acceptance testing.',
          level: 'intermediate',
          children: [
            { id: 'test-strategy-pyramid', title: 'Test Strategy & Pyramid for Claude Apps' },
            { id: 'eval-as-tests', title: 'Claude Evals as Tests in CI' },
            { id: 'contract-testing-process', title: 'Contract Testing Process (PACT/CDC)' },
            { id: 'performance-test-program', title: 'Performance & Load Test Program' },
            { id: 'security-test-program', title: 'Security Test Program (SAST/DAST)' },
            { id: 'uat-process', title: 'User Acceptance Testing (UAT) Process' },
            { id: 'acceptance-criteria-bdd', title: 'Acceptance Criteria & BDD' },
            { id: 'red-team-test-program', title: 'Red-Team Testing Program' },
          ],
        },
        {
          id: 'cicd-release-engineering',
          title: 'CI/CD & Release Engineering',
          summary: 'Pipelines, environment strategy, feature flags and supply-chain security.',
          level: 'advanced',
          children: [
            { id: 'cicd-pipeline-design', title: 'CI/CD Pipeline Design' },
            { id: 'build-promotion-stages', title: 'Build Promotion & Environment Stages' },
            { id: 'env-strategy-paths', title: 'Environment Strategy (Dev → Staging → Prod)' },
            { id: 'release-trains', title: 'Release Trains & Cadence' },
            { id: 'feature-flag-management', title: 'Feature Flag Management at Scale' },
            { id: 'secrets-management-process', title: 'Secrets Management Process' },
            { id: 'supply-chain-security-program', title: 'Supply-Chain Security (SLSA/SBOM)' },
            { id: 'prompt-versioning-strategy', title: 'Prompt & Artifact Versioning Strategy' },
          ],
        },
        {
          id: 'production-readiness',
          title: 'Production Readiness & Launch',
          summary: 'PRR, launch checklists, gradual rollout and rollback strategy.',
          level: 'advanced',
          children: [
            { id: 'production-readiness-review', title: 'Production Readiness Review (PRR)' },
            { id: 'launch-checklist', title: 'Launch Readiness Checklist' },
            { id: 'go-no-go-criteria', title: 'Go / No-Go Decision Criteria' },
            { id: 'dark-launches', title: 'Dark Launches & Shadow Mode' },
            { id: 'gradual-rollout-strategy', title: 'Gradual Rollout (Canary, Ringed, Blue-Green)' },
            { id: 'rollback-strategy', title: 'Rollback & Recovery Strategy' },
            { id: 'day-1-day-2-operations', title: 'Day-1 vs Day-2 Operations Plan' },
            { id: 'hypercare-period', title: 'Hypercare & Post-Launch Support' },
          ],
        },
        {
          id: 'operations-sre-program',
          title: 'Operations & SRE Program',
          summary: 'SLOs, error budgets, on-call programs and resilience for Claude apps.',
          level: 'advanced',
          children: [
            { id: 'sli-slo-sla-design', title: 'SLI/SLO/SLA Design for Claude Services' },
            { id: 'error-budget-policy', title: 'Error Budget Policy' },
            { id: 'on-call-program', title: 'On-Call Program & Schedules' },
            { id: 'escalation-paths', title: 'Escalation Paths & Severity Levels' },
            { id: 'capacity-management', title: 'Capacity & Demand Management' },
            { id: 'dr-bcp-planning', title: 'DR & Business Continuity Planning' },
            { id: 'chaos-engineering-program', title: 'Chaos Engineering Program' },
            { id: 'reliability-reviews', title: 'Reliability Reviews & Toil Audits' },
          ],
        },
        {
          id: 'observability-program',
          title: 'Observability Program',
          summary: 'Telemetry standards, dashboards, alerting policy and platform ownership.',
          level: 'advanced',
          children: [
            { id: 'telemetry-standards', title: 'Telemetry Standards & Conventions' },
            { id: 'golden-signals', title: 'Golden Signals for Claude Services' },
            { id: 'dashboards-as-code', title: 'Dashboards-as-Code' },
            { id: 'alerting-policy', title: 'Alerting Policy & Symptom-Based Alerts' },
            { id: 'log-management-policy', title: 'Log Management & PII Scrubbing' },
            { id: 'retention-and-sampling', title: 'Retention & Sampling Policy' },
            { id: 'conversation-trace-governance', title: 'Conversation Trace Governance' },
          ],
        },
        {
          id: 'incident-management-process',
          title: 'Incident Management Process',
          summary: 'Process for declaring, managing and learning from production incidents.',
          level: 'advanced',
          children: [
            { id: 'incident-classification', title: 'Incident Classification & Severity Matrix' },
            { id: 'incident-commander-role', title: 'Incident Commander Role & Roster' },
            { id: 'war-room-protocols', title: 'War Room & Bridge Call Protocols' },
            { id: 'status-page-comms', title: 'Status Page & Customer Communications' },
            { id: 'blameless-postmortems', title: 'Blameless Postmortem Process' },
            { id: 'action-item-tracking', title: 'Action Item Tracking & Closure' },
            { id: 'incident-metrics-mttx', title: 'Incident Metrics (MTTD/MTTA/MTTR)' },
            { id: 'major-incident-review', title: 'Major Incident Reviews' },
          ],
        },
        {
          id: 'support-maintenance-program',
          title: 'Support & Maintenance Program',
          summary: 'Tiered support, bug triage and ongoing maintenance programs.',
          level: 'intermediate',
          children: [
            { id: 'tiered-support-model', title: 'Tiered Support Model (L1/L2/L3)' },
            { id: 'bug-triage-process', title: 'Bug Triage & Backlog Hygiene' },
            { id: 'sla-management', title: 'SLA Management & Reporting' },
            { id: 'patch-management-cadence', title: 'Patch & Vulnerability Management Cadence' },
            { id: 'dependency-upgrade-program', title: 'Dependency Upgrade Program' },
            { id: 'model-version-policy', title: 'Claude Model Version Policy' },
            { id: 'decommissioning-sunsetting', title: 'Decommissioning & Sunsetting Process' },
          ],
        },
        {
          id: 'continuous-improvement-program',
          title: 'Continuous Improvement & Evolution',
          summary: 'Feedback loops, technical debt management and evolutionary architecture practice.',
          level: 'advanced',
          children: [
            { id: 'feedback-loops-program', title: 'User & Operator Feedback Loops' },
            { id: 'post-launch-reviews', title: 'Post-Launch Reviews & Beta Graduations' },
            { id: 'technical-debt-management', title: 'Technical Debt Management Program' },
            { id: 'evolutionary-architecture-practice', title: 'Evolutionary Architecture Practice' },
            { id: 'prompt-deprecation-policy', title: 'Prompt / Model Deprecation Policy' },
            { id: 'retrospectives-cadence', title: 'Retrospectives & Improvement Cadence' },
            { id: 'continuous-eval-loops', title: 'Continuous Evaluation Loops' },
          ],
        },
      ],
    },
  ],
})
