import { addEnterpriseStages } from '../_shared/enterpriseAdditions.mjs'

addEnterpriseStages({
  subjectId: 'angular',
  stages: [
    {
      id: 'enterprise-delivery',
      title: 'Enterprise Development & Enablement',
      summary: 'Strategy, governance, platform and enablement for delivering Angular at enterprise scale.',
      tag: 'enterprise-delivery',
      nodes: [
        {
          id: 'enterprise-frontend-strategy',
          title: 'Enterprise Frontend Strategy & Operating Model',
          summary: 'Strategy, operating model and frontend center of excellence for Angular.',
          level: 'advanced',
          children: [
            { id: 'frontend-center-of-excellence', title: 'Frontend Center of Excellence (CoE)' },
            { id: 'frontend-operating-model', title: 'Frontend Target Operating Model' },
            { id: 'frontend-roadmap-strategy', title: 'Frontend Strategy & Roadmap' },
            { id: 'frontend-portfolio-strategy', title: 'Frontend Portfolio Strategy' },
            { id: 'executive-sponsorship', title: 'Executive Sponsorship & Steering' },
            { id: 'frontend-maturity-model', title: 'Frontend Maturity Model & Assessment' },
            { id: 'value-streams-mapping', title: 'Frontend Value Streams & Capability Mapping' },
          ],
        },
        {
          id: 'discovery-requirements',
          title: 'Discovery & Requirements Engineering',
          summary: 'Use case discovery, business case and requirements engineering for Angular apps.',
          level: 'intermediate',
          children: [
            { id: 'frontend-use-case-discovery', title: 'Frontend Use Case Discovery' },
            { id: 'business-case-roi', title: 'Business Case & ROI Modeling' },
            { id: 'feasibility-assessment', title: 'Feasibility & Risk Assessment' },
            { id: 'stakeholder-management', title: 'Stakeholder Mapping & Management' },
            { id: 'requirements-elicitation', title: 'Requirements Elicitation Techniques' },
            { id: 'success-criteria-kpis', title: 'Success Criteria, OKRs & KPIs' },
            { id: 'user-research-discovery', title: 'User Research & Jobs-to-be-Done' },
            { id: 'design-thinking-workshops', title: 'Design Thinking Workshops' },
          ],
        },
        {
          id: 'solution-architecture-process',
          title: 'Solution Architecture Process',
          summary: 'Architecture decisions, design reviews and reference blueprints for Angular apps.',
          level: 'advanced',
          children: [
            { id: 'architecture-decision-records', title: 'Architecture Decision Records (ADRs)' },
            { id: 'design-review-board', title: 'Design Review Board (DRB)' },
            { id: 'reference-architectures', title: 'Reference Architectures & Patterns Catalog' },
            { id: 'solution-blueprints', title: 'Solution Blueprints' },
            { id: 'non-functional-requirements', title: 'Non-Functional Requirements (NFRs)' },
            { id: 'capacity-planning', title: 'Capacity & Traffic Planning' },
            { id: 'threat-modeling-process', title: 'Threat Modeling Process (STRIDE)' },
            { id: 'tech-radar', title: 'Technology Radar Practice' },
          ],
        },
        {
          id: 'engineering-standards',
          title: 'Engineering Standards & Quality',
          summary: 'Coding standards, peer review, definition of done and quality gates.',
          level: 'intermediate',
          children: [
            { id: 'angular-coding-standards', title: 'Angular Coding Standards & Style Guide' },
            { id: 'eslint-config-standards', title: 'ESLint & Prettier Standards' },
            { id: 'peer-review-process', title: 'Peer Review & Code Review Process' },
            { id: 'definition-of-done', title: 'Definition of Done & Ready' },
            { id: 'quality-gates', title: 'Quality Gates & Build Promotion Rules' },
            { id: 'architectural-fitness-functions', title: 'Architectural Fitness Functions' },
            { id: 'dependency-policy', title: 'Dependency & License Policy' },
            { id: 'engineering-scorecards', title: 'Engineering Scorecards & Health Metrics' },
            { id: 'cyclomatic-complexity-limits', title: 'Complexity & Coverage Limits' },
          ],
        },
        {
          id: 'developer-platform',
          title: 'Developer Platform & Paved Roads',
          summary: 'Internal developer platform, golden paths and shared libraries for Angular teams.',
          level: 'advanced',
          children: [
            { id: 'internal-developer-portal', title: 'Internal Developer Portal (IDP)' },
            { id: 'angular-starter-templates', title: 'Angular Starter Templates & Scaffolds' },
            { id: 'golden-paths', title: 'Golden Paths for Angular Teams' },
            { id: 'shared-angular-libraries', title: 'Shared Angular Libraries & SDKs' },
            { id: 'design-system-program', title: 'Enterprise Design System Program' },
            { id: 'self-service-tooling', title: 'Self-Service Tooling & Provisioning' },
            { id: 'inner-source-program', title: 'Inner-Source Program' },
            { id: 'developer-experience-metrics', title: 'Developer Experience (DevEx) Metrics' },
            { id: 'platform-as-product', title: 'Platform-as-a-Product Mindset' },
          ],
        },
        {
          id: 'enterprise-data-governance',
          title: 'Enterprise Data Governance for Frontend',
          summary: 'Data classification, privacy and PII handling in Angular apps.',
          level: 'advanced',
          children: [
            { id: 'data-classification-frontend', title: 'Data Classification in the Frontend' },
            { id: 'pii-handling-policies', title: 'PII Handling & Masking Policies' },
            { id: 'data-residency-controls', title: 'Data Residency & Sovereignty Controls' },
            { id: 'analytics-data-governance', title: 'Analytics & Telemetry Data Governance' },
            { id: 'consent-management', title: 'Consent & Preference Management' },
            { id: 'cookie-tracker-governance', title: 'Cookie & Tracker Governance' },
            { id: 'data-retention-frontend', title: 'Local Storage & Client Retention Policy' },
          ],
        },
        {
          id: 'risk-compliance-program',
          title: 'Risk & Compliance Program',
          summary: 'Risk registers, third-party risk and audit programs for frontend apps.',
          level: 'advanced',
          children: [
            { id: 'enterprise-risk-register', title: 'Enterprise Frontend Risk Register' },
            { id: 'control-libraries', title: 'Control Libraries & Mappings' },
            { id: 'third-party-risk-management', title: 'Third-Party Risk Management (TPRM)' },
            { id: 'audit-readiness', title: 'Audit Readiness & Evidence Collection' },
            { id: 'certifications-soc2-iso', title: 'SOC 2 / ISO 27001 Programs' },
            { id: 'wcag-compliance-program', title: 'WCAG / ADA Accessibility Compliance' },
            { id: 'gdpr-ccpa-compliance', title: 'GDPR / CCPA Compliance Program' },
            { id: 'regulatory-reporting', title: 'Regulatory Reporting & Disclosures' },
          ],
        },
        {
          id: 'enterprise-finops',
          title: 'Financial Management & FinOps',
          summary: 'FinOps for hosting, CDN, monitoring and developer tooling costs.',
          level: 'advanced',
          children: [
            { id: 'cost-allocation-chargeback', title: 'Cost Allocation, Showback & Chargeback' },
            { id: 'budget-governance', title: 'Budget Governance & Guardrails' },
            { id: 'cost-forecasting', title: 'Cost Forecasting & Modeling' },
            { id: 'cdn-cost-optimization', title: 'CDN & Edge Cost Optimization' },
            { id: 'tooling-license-management', title: 'Tooling & License Management' },
            { id: 'finops-reporting', title: 'FinOps Reporting & Reviews' },
          ],
        },
        {
          id: 'program-portfolio-management',
          title: 'Program & Portfolio Management',
          summary: 'Intake, prioritization and portfolio governance for frontend initiatives.',
          level: 'intermediate',
          children: [
            { id: 'intake-prioritization', title: 'Demand Intake & Prioritization' },
            { id: 'okrs-roadmaps', title: 'OKRs & Roadmaps' },
            { id: 'dependency-mapping', title: 'Cross-Team Dependency Mapping' },
            { id: 'status-reporting', title: 'Status Reporting & Cadences' },
            { id: 'benefits-realization', title: 'Benefits Realization Tracking' },
            { id: 'agile-at-scale', title: 'Agile-at-Scale (SAFe / LeSS / Scrum@Scale)' },
            { id: 'portfolio-rebalancing', title: 'Portfolio Rebalancing & Stage Gates' },
          ],
        },
        {
          id: 'change-enablement',
          title: 'Change Enablement & Culture',
          summary: 'Organizational change, training and adoption of modern Angular practices.',
          level: 'intermediate',
          children: [
            { id: 'org-change-management', title: 'Organizational Change Management (OCM)' },
            { id: 'communications-strategy', title: 'Communications & Narrative Strategy' },
            { id: 'training-curricula', title: 'Training Curricula & Certifications' },
            { id: 'communities-of-practice', title: 'Communities of Practice (CoPs)' },
            { id: 'angular-champions-network', title: 'Angular Champions Network' },
            { id: 'adoption-metrics', title: 'Adoption & Stickiness Metrics' },
            { id: 'frontend-guild', title: 'Frontend Guild & Chapter Model' },
          ],
        },
        {
          id: 'legal-ethical-governance',
          title: 'Legal & Ethical Governance',
          summary: 'IP, licensing, acceptable use and ethical UX governance.',
          level: 'advanced',
          children: [
            { id: 'ip-and-licensing', title: 'IP, Copyright & OSS Licensing' },
            { id: 'liability-frameworks', title: 'Liability & Indemnity Frameworks' },
            { id: 'acceptable-use-policy', title: 'Acceptable Use Policy (AUP)' },
            { id: 'responsible-disclosure-policy', title: 'Responsible Disclosure Policy' },
            { id: 'dark-patterns-policy', title: 'Anti Dark-Patterns Policy' },
            { id: 'oss-contribution-policy', title: 'Open-Source Contribution Policy' },
            { id: 'dpia-process', title: 'Data Protection Impact Assessment (DPIA)' },
          ],
        },
      ],
    },
    {
      id: 'production-lifecycle',
      title: 'Production-Grade Application Lifecycle',
      summary: 'End-to-end delivery lifecycle for production-grade Angular applications.',
      tag: 'production-lifecycle',
      nodes: [
        {
          id: 'requirements-design-phase',
          title: 'Requirements & Design Phase',
          summary: 'Discovery, requirements, design and sign-off for new Angular features.',
          level: 'intermediate',
          children: [
            { id: 'discovery-workshops', title: 'Discovery Workshops & Event Storming' },
            { id: 'jobs-and-personas', title: 'Personas & Job Stories' },
            { id: 'journey-mapping', title: 'Journey Mapping & Service Blueprinting' },
            { id: 'prd-templates', title: 'PRDs, Spec & Brief Templates' },
            { id: 'lo-fi-prototyping', title: 'Lo-Fi Prototyping & Wireframes' },
            { id: 'design-sign-off', title: 'Design Sign-Off & Acceptance' },
            { id: 'risk-impact-assessment', title: 'Risk & Impact Assessment for Features' },
            { id: 'accessibility-design-review', title: 'Accessibility Design Review' },
          ],
        },
        {
          id: 'implementation-build-phase',
          title: 'Implementation & Build Phase',
          summary: 'Build discipline, branching, code ownership and refactoring practice.',
          level: 'intermediate',
          children: [
            { id: 'pairing-and-mobbing', title: 'Pairing, Mobbing & Ensemble Programming' },
            { id: 'trunk-based-development', title: 'Trunk-Based Development' },
            { id: 'branching-strategy', title: 'Branching Strategy & Release Branches' },
            { id: 'commit-conventions', title: 'Commit Conventions & Conventional Commits' },
            { id: 'code-ownership-codeowners', title: 'Code Ownership & CODEOWNERS' },
            { id: 'refactoring-discipline', title: 'Refactoring Discipline' },
            { id: 'feature-toggling-build', title: 'Feature Toggling During Build' },
          ],
        },
        {
          id: 'testing-validation-phase',
          title: 'Testing & Validation Phase',
          summary: 'End-to-end test strategy, performance, security and acceptance testing programs.',
          level: 'intermediate',
          children: [
            { id: 'test-strategy-pyramid', title: 'Test Strategy & Pyramid for Angular' },
            { id: 'contract-testing-process', title: 'Contract Testing Process (PACT/CDC)' },
            { id: 'visual-regression-program', title: 'Visual Regression Testing Program' },
            { id: 'performance-test-program', title: 'Performance & Load Test Program' },
            { id: 'security-test-program', title: 'Security Test Program (SAST/DAST)' },
            { id: 'accessibility-testing-program', title: 'Accessibility Testing Program' },
            { id: 'uat-process', title: 'User Acceptance Testing (UAT) Process' },
            { id: 'acceptance-criteria-bdd', title: 'Acceptance Criteria & BDD' },
            { id: 'mutation-testing-program', title: 'Mutation Testing Program' },
          ],
        },
        {
          id: 'cicd-release-engineering',
          title: 'CI/CD & Release Engineering',
          summary: 'Pipelines, environment strategy, feature flags and supply-chain security.',
          level: 'advanced',
          children: [
            { id: 'cicd-pipeline-design', title: 'CI/CD Pipeline Design for Angular' },
            { id: 'build-promotion-stages', title: 'Build Promotion & Environment Stages' },
            { id: 'env-strategy-paths', title: 'Environment Strategy (Dev → Staging → Prod)' },
            { id: 'release-trains', title: 'Release Trains & Cadence' },
            { id: 'feature-flag-management', title: 'Feature Flag Management at Scale' },
            { id: 'secrets-management-process', title: 'Secrets Management Process' },
            { id: 'supply-chain-security-program', title: 'Supply-Chain Security (SLSA/SBOM)' },
            { id: 'artifact-versioning-strategy', title: 'Artifact & Asset Versioning Strategy' },
            { id: 'preview-environments', title: 'Preview / PR Environments' },
          ],
        },
        {
          id: 'production-readiness',
          title: 'Production Readiness & Launch',
          summary: 'PRR, launch checklists, gradual rollout and rollback strategy.',
          level: 'advanced',
          children: [
            { id: 'production-readiness-review', title: 'Production Readiness Review (PRR)' },
            { id: 'launch-checklist', title: 'Launch Readiness Checklist' },
            { id: 'go-no-go-criteria', title: 'Go / No-Go Decision Criteria' },
            { id: 'dark-launches', title: 'Dark Launches & Shadow Releases' },
            { id: 'gradual-rollout-strategy', title: 'Gradual Rollout (Canary, Ringed, Blue-Green)' },
            { id: 'rollback-strategy', title: 'Rollback & Recovery Strategy' },
            { id: 'day-1-day-2-operations', title: 'Day-1 vs Day-2 Operations Plan' },
            { id: 'hypercare-period', title: 'Hypercare & Post-Launch Support' },
          ],
        },
        {
          id: 'operations-sre-frontend',
          title: 'Operations & SRE for Frontend',
          summary: 'SLOs, error budgets, on-call programs and resilience for Angular apps.',
          level: 'advanced',
          children: [
            { id: 'sli-slo-sla-design', title: 'SLI/SLO/SLA Design for Frontend' },
            { id: 'error-budget-policy', title: 'Error Budget Policy' },
            { id: 'on-call-program', title: 'On-Call Program & Schedules' },
            { id: 'escalation-paths', title: 'Escalation Paths & Severity Levels' },
            { id: 'capacity-management', title: 'Capacity & Demand Management' },
            { id: 'dr-bcp-planning', title: 'DR & Business Continuity Planning' },
            { id: 'chaos-engineering-program', title: 'Chaos Engineering Program' },
            { id: 'reliability-reviews', title: 'Reliability Reviews & Toil Audits' },
            { id: 'core-web-vitals-slos', title: 'Core Web Vitals as SLOs' },
          ],
        },
        {
          id: 'observability-program',
          title: 'Observability Program',
          summary: 'Telemetry, RUM, dashboards and alerting policy for Angular apps.',
          level: 'advanced',
          children: [
            { id: 'telemetry-standards', title: 'Telemetry Standards & Conventions' },
            { id: 'real-user-monitoring', title: 'Real User Monitoring (RUM)' },
            { id: 'synthetic-monitoring', title: 'Synthetic Monitoring Program' },
            { id: 'frontend-error-tracking', title: 'Frontend Error Tracking Program' },
            { id: 'dashboards-as-code', title: 'Dashboards-as-Code' },
            { id: 'alerting-policy', title: 'Alerting Policy & Symptom-Based Alerts' },
            { id: 'log-management-policy', title: 'Log Management Policy' },
            { id: 'retention-and-sampling', title: 'Retention & Sampling Policy' },
          ],
        },
        {
          id: 'incident-management-process',
          title: 'Incident Management Process',
          summary: 'Process for declaring, managing and learning from production incidents.',
          level: 'advanced',
          children: [
            { id: 'incident-classification', title: 'Incident Classification & Severity Matrix' },
            { id: 'incident-commander-role', title: 'Incident Commander Role & Roster' },
            { id: 'war-room-protocols', title: 'War Room & Bridge Call Protocols' },
            { id: 'status-page-comms', title: 'Status Page & Customer Communications' },
            { id: 'blameless-postmortems', title: 'Blameless Postmortem Process' },
            { id: 'action-item-tracking', title: 'Action Item Tracking & Closure' },
            { id: 'incident-metrics-mttx', title: 'Incident Metrics (MTTD/MTTA/MTTR)' },
            { id: 'major-incident-review', title: 'Major Incident Reviews' },
          ],
        },
        {
          id: 'support-maintenance',
          title: 'Support & Maintenance',
          summary: 'Tiered support, bug triage and ongoing maintenance programs.',
          level: 'intermediate',
          children: [
            { id: 'tiered-support-model', title: 'Tiered Support Model (L1/L2/L3)' },
            { id: 'bug-triage-process', title: 'Bug Triage & Backlog Hygiene' },
            { id: 'sla-management', title: 'SLA Management & Reporting' },
            { id: 'patch-management-cadence', title: 'Patch & Vulnerability Management Cadence' },
            { id: 'dependency-upgrade-program', title: 'Dependency & Angular Upgrade Program' },
            { id: 'browser-support-policy', title: 'Browser & Device Support Policy' },
            { id: 'decommissioning-sunsetting', title: 'Decommissioning & Sunsetting Process' },
            { id: 'knowledge-base-maintenance', title: 'Knowledge Base Maintenance' },
          ],
        },
        {
          id: 'continuous-improvement-program',
          title: 'Continuous Improvement & Evolution',
          summary: 'Feedback loops, technical debt management and evolutionary architecture practice.',
          level: 'advanced',
          children: [
            { id: 'feedback-loops-program', title: 'User & Operator Feedback Loops' },
            { id: 'post-launch-reviews', title: 'Post-Launch Reviews & Beta Graduations' },
            { id: 'technical-debt-management', title: 'Technical Debt Management Program' },
            { id: 'evolutionary-architecture-practice', title: 'Evolutionary Architecture Practice' },
            { id: 'version-deprecation-policy', title: 'Version Deprecation & Migration Policy' },
            { id: 'retrospectives-cadence', title: 'Retrospectives & Improvement Cadence' },
            { id: 'experimentation-program', title: 'A/B Experimentation Program' },
          ],
        },
      ],
    },
  ],
})
