import { addTopics } from './addTopics.mjs'

// Stage 12 — Application Lifecycle & Packaging
// `deployment-strategies` is refocused on native Kubernetes workload rollouts;
// progressive delivery (Argo Rollouts / Flagger / feature flags) lives in the
// `devops` subject.
addTopics([
  /* ---------- helm ---------- */
  {
    id: 'helm-fundamentals',
    title: 'Helm Fundamentals',
    parentId: 'helm',
    children: [
      { id: 'helm-overview', title: 'Helm Overview' },
      { id: 'helm-3-vs-helm-2', title: 'Helm 3 vs Helm 2' },
      { id: 'helm-architecture', title: 'Helm Architecture' },
      { id: 'tiller-removal', title: 'Tiller Removal (Helm 2 → 3)' },
      { id: 'helm-vs-kustomize', title: 'Helm vs Kustomize' },
    ],
  },
  {
    id: 'helm-charts',
    title: 'Helm Charts',
    parentId: 'helm',
    children: [
      { id: 'chart-structure', title: 'Chart Structure' },
      { id: 'chart-yaml-file', title: 'Chart.yaml' },
      { id: 'values-yaml-file', title: 'values.yaml' },
      { id: 'chart-templates-dir', title: 'templates/' },
      { id: 'chart-tests-dir', title: 'tests/' },
      { id: 'chart-readme', title: 'README & NOTES.txt' },
      { id: 'chart-license', title: 'LICENSE' },
      { id: 'chart-icon-and-keywords', title: 'icon & keywords' },
      { id: 'subcharts', title: 'Subcharts' },
      { id: 'chart-dependencies', title: 'Chart Dependencies' },
      { id: 'chart-lock-file', title: 'Chart.lock' },
      { id: 'chart-types-application-vs-library', title: 'Chart Types (application vs library)' },
      { id: 'crds-folder', title: 'crds/ Folder' },
    ],
  },
  {
    id: 'helm-cli',
    title: 'Helm CLI',
    parentId: 'helm',
    children: [
      { id: 'helm-install', title: 'helm install' },
      { id: 'helm-upgrade', title: 'helm upgrade' },
      { id: 'helm-rollback', title: 'helm rollback' },
      { id: 'helm-uninstall', title: 'helm uninstall' },
      { id: 'helm-list', title: 'helm list' },
      { id: 'helm-status', title: 'helm status' },
      { id: 'helm-history', title: 'helm history' },
      { id: 'helm-get', title: 'helm get' },
      { id: 'helm-repo', title: 'helm repo' },
      { id: 'helm-pull', title: 'helm pull' },
      { id: 'helm-search', title: 'helm search' },
      { id: 'helm-package', title: 'helm package' },
      { id: 'helm-lint', title: 'helm lint' },
      { id: 'helm-template', title: 'helm template' },
      { id: 'helm-show', title: 'helm show' },
      { id: 'helm-test', title: 'helm test' },
      { id: 'helm-dependency', title: 'helm dependency' },
      { id: 'helm-plugin', title: 'helm plugin' },
      { id: 'helm-create', title: 'helm create' },
      { id: 'helm-completion', title: 'helm completion' },
    ],
  },
  {
    id: 'helm-templating',
    title: 'Helm Templating',
    parentId: 'helm',
    children: [
      { id: 'go-template-syntax-in-helm', title: 'Go Template Syntax in Helm' },
      { id: 'sprig-functions', title: 'Sprig Functions' },
      { id: 'helm-built-in-objects', title: 'Built-In Objects (.Values, .Release, .Chart, .Files, ...)' },
      { id: 'flow-control-in-templates', title: 'Flow Control (if / range / with)' },
      { id: 'named-templates-and-partials', title: 'Named Templates & Partials' },
      { id: 'include-and-template-actions', title: 'include vs template' },
      { id: 'template-debugging', title: 'Template Debugging' },
      { id: 'whitespace-control', title: 'Whitespace Control ({{- and -}})' },
      { id: 'fail-and-required-functions', title: 'fail & required Functions' },
      { id: 'tpl-function', title: 'tpl Function' },
    ],
  },
  {
    id: 'helm-values',
    title: 'Helm Values',
    parentId: 'helm',
    children: [
      { id: 'default-values', title: 'Default Values' },
      { id: 'values-overrides', title: 'Values Overrides' },
      { id: 'set-vs-values-file', title: '--set vs --values' },
      { id: 'values-schema-json', title: 'values.schema.json' },
      { id: 'values-validation-with-cel', title: 'CEL Validation in values.schema' },
      { id: 'global-values', title: 'global Values' },
      { id: 'values-from-files', title: 'Values from Files (--set-file)' },
      { id: 'values-from-string', title: '--set-string' },
    ],
  },
  {
    id: 'helm-hooks',
    title: 'Helm Hooks',
    parentId: 'helm',
    children: [
      { id: 'pre-install-hook', title: 'pre-install Hook' },
      { id: 'post-install-hook', title: 'post-install Hook' },
      { id: 'pre-upgrade-hook', title: 'pre-upgrade Hook' },
      { id: 'post-upgrade-hook', title: 'post-upgrade Hook' },
      { id: 'pre-delete-hook', title: 'pre-delete Hook' },
      { id: 'post-delete-hook', title: 'post-delete Hook' },
      { id: 'pre-rollback-hook', title: 'pre-rollback Hook' },
      { id: 'post-rollback-hook', title: 'post-rollback Hook' },
      { id: 'test-hook', title: 'test Hook' },
      { id: 'hook-deletion-policies', title: 'Hook Deletion Policies' },
      { id: 'hook-weights', title: 'Hook Weights' },
    ],
  },
  {
    id: 'helm-releases-and-state',
    title: 'Helm Releases & State',
    parentId: 'helm',
    children: [
      { id: 'release-state-storage', title: 'Release State Storage' },
      { id: 'release-secrets', title: 'Release Secrets (sh.helm.release.v1.*)' },
      { id: 'release-revisions', title: 'Release Revisions' },
      { id: 'drift-handling', title: 'Drift Handling' },
      { id: 'three-way-merge-patches', title: 'Three-Way Merge Patches' },
    ],
  },
  {
    id: 'helm-repositories',
    title: 'Helm Repositories',
    parentId: 'helm',
    children: [
      { id: 'helm-repos-classic', title: 'Classic HTTP Repos' },
      { id: 'helm-oci-registries', title: 'OCI-Based Registries' },
      { id: 'chart-museum', title: 'ChartMuseum' },
      { id: 'harbor-as-helm-repo', title: 'Harbor as Helm Repo' },
      { id: 'github-pages-as-repo', title: 'GitHub Pages as Repo' },
      { id: 'signing-charts-with-cosign', title: 'Signing Charts with Cosign' },
      { id: 'provenance-files', title: 'Provenance Files' },
    ],
  },
  {
    id: 'helm-best-practices',
    title: 'Helm Best Practices',
    parentId: 'helm',
    children: [
      { id: 'chart-naming-conventions', title: 'Chart Naming Conventions' },
      { id: 'immutable-chart-versioning', title: 'Immutable Chart Versioning' },
      { id: 'chart-design-principles', title: 'Chart Design Principles' },
      { id: 'readme-and-metadata', title: 'README & Metadata' },
      { id: 'minimal-cluster-perms', title: 'Minimal Cluster Permissions' },
      { id: 'avoiding-template-pitfalls', title: 'Avoiding Template Pitfalls' },
    ],
  },
  {
    id: 'helm-debugging',
    title: 'Helm Debugging',
    parentId: 'helm',
    children: [
      { id: 'helm-template-vs-install', title: 'helm template vs helm install' },
      { id: 'helm-debug-flag', title: '--debug Flag' },
      { id: 'helm-dry-run', title: '--dry-run' },
      { id: 'helm-diff-plugin', title: 'helm-diff Plugin' },
      { id: 'release-rollback-debug', title: 'Release Rollback Debug' },
    ],
  },
  {
    id: 'helm-charts-distribution',
    title: 'Helm Chart Distribution',
    parentId: 'helm',
    children: [
      { id: 'artifact-hub', title: 'Artifact Hub' },
      { id: 'bitnami-charts', title: 'Bitnami Charts' },
      { id: 'community-and-vendor-charts', title: 'Community & Vendor Charts' },
      { id: 'private-chart-distribution', title: 'Private Chart Distribution' },
    ],
  },
  {
    id: 'helmfile-and-helmsman',
    title: 'Helmfile & Helmsman',
    parentId: 'helm',
    children: [
      { id: 'helmfile-overview', title: 'Helmfile Overview' },
      { id: 'helmfile-state', title: 'Helmfile State' },
      { id: 'helmsman-overview', title: 'Helmsman Overview' },
      { id: 'multi-release-orchestration', title: 'Multi-Release Orchestration' },
    ],
  },
  {
    id: 'helm-controllers-pointer',
    title: 'Helm Controllers (Pointer)',
    parentId: 'helm',
    children: [
      { id: 'flux-helm-controller-pointer', title: 'Flux Helm Controller (Pointer)' },
      { id: 'argo-cd-helm-rendering-pointer', title: 'Argo CD Helm Rendering (Pointer)' },
      { id: 'helm-operator-pattern', title: 'Helm Operator Pattern' },
    ],
  },

  /* ---------- kustomize ---------- */
  {
    id: 'kustomize-fundamentals',
    title: 'Kustomize Fundamentals',
    parentId: 'kustomize',
    children: [
      { id: 'kustomize-overview', title: 'Kustomize Overview' },
      { id: 'kustomize-vs-helm', title: 'Kustomize vs Helm' },
      { id: 'kustomize-cli', title: 'kustomize CLI' },
      { id: 'kubectl-k-flag', title: 'kubectl -k Flag' },
      { id: 'kustomization-yaml', title: 'kustomization.yaml' },
    ],
  },
  {
    id: 'bases-and-overlays',
    title: 'Bases & Overlays',
    parentId: 'kustomize',
    children: [
      { id: 'base-directory-structure', title: 'Base Directory Structure' },
      { id: 'overlay-directory-structure', title: 'Overlay Directory Structure' },
      { id: 'composing-bases-and-overlays', title: 'Composing Bases & Overlays' },
      { id: 'remote-bases', title: 'Remote Bases (Git URLs)' },
    ],
  },
  {
    id: 'kustomize-generators',
    title: 'Generators',
    parentId: 'kustomize',
    children: [
      { id: 'configmapgenerator', title: 'configMapGenerator' },
      { id: 'secretgenerator', title: 'secretGenerator' },
      { id: 'generator-options', title: 'generatorOptions' },
      { id: 'disable-name-suffix-hash', title: 'disableNameSuffixHash' },
      { id: 'merge-behavior-generators', title: 'Merge Behavior' },
    ],
  },
  {
    id: 'kustomize-transformers',
    title: 'Transformers',
    parentId: 'kustomize',
    children: [
      { id: 'namespace-transformer', title: 'namespace Transformer' },
      { id: 'common-labels', title: 'commonLabels' },
      { id: 'common-annotations', title: 'commonAnnotations' },
      { id: 'name-prefix-suffix', title: 'namePrefix / nameSuffix' },
      { id: 'image-transformer', title: 'images Transformer' },
      { id: 'replicas-transformer', title: 'replicas Transformer' },
      { id: 'patches-transformer', title: 'patches Transformer' },
      { id: 'replacements-transformer', title: 'replacements Transformer' },
      { id: 'label-transformer-options', title: 'labelTransformer Options' },
    ],
  },
  {
    id: 'kustomize-patches',
    title: 'Patches',
    parentId: 'kustomize',
    children: [
      { id: 'strategic-merge-patches', title: 'Strategic Merge Patches' },
      { id: 'json-6902-patches', title: 'JSON 6902 Patches' },
      { id: 'patch-targets', title: 'Patch Targets (target field)' },
      { id: 'inline-patches', title: 'Inline Patches' },
      { id: 'patches-vs-patchesstrategicmerge-deprecated', title: 'patches vs Deprecated Forms' },
    ],
  },
  {
    id: 'kustomize-components-and-includes',
    title: 'Components & Includes',
    parentId: 'kustomize',
    children: [
      { id: 'kustomize-components', title: 'Components' },
      { id: 'components-vs-bases', title: 'Components vs Bases' },
      { id: 'reusable-feature-toggles', title: 'Reusable Feature Toggles' },
    ],
  },
  {
    id: 'kustomize-replacements',
    title: 'Replacements (Cross-Resource)',
    parentId: 'kustomize',
    children: [
      { id: 'replacement-source-target', title: 'source / targets / rejects' },
      { id: 'field-references', title: 'Field References (fieldPath)' },
      { id: 'cross-resource-references', title: 'Cross-Resource References' },
      { id: 'replacements-vs-vars-deprecated', title: 'replacements vs Deprecated vars' },
    ],
  },
  {
    id: 'kustomize-helmcharts-integration',
    title: 'Helm Charts in Kustomize',
    parentId: 'kustomize',
    children: [
      { id: 'helmcharts-field', title: 'helmCharts Field' },
      { id: 'helm-chart-inflation', title: 'Helm Chart Inflation' },
      { id: 'mixing-helm-and-kustomize', title: 'Mixing Helm + Kustomize' },
    ],
  },
  {
    id: 'kustomize-crds-and-openapi',
    title: 'CRDs & OpenAPI',
    parentId: 'kustomize',
    children: [
      { id: 'openapi-config-field', title: 'openapi Config Field' },
      { id: 'openapi-paths', title: 'openapi paths' },
      { id: 'registering-crd-types', title: 'Registering CRD Types' },
    ],
  },
  {
    id: 'kustomize-best-practices',
    title: 'Kustomize Best Practices',
    parentId: 'kustomize',
    children: [
      { id: 'directory-conventions', title: 'Directory Conventions' },
      { id: 'minimal-overlays', title: 'Minimal Overlays' },
      { id: 'avoid-vars-and-deprecated', title: 'Avoid Deprecated Fields' },
      { id: 'managing-secrets-with-kustomize', title: 'Managing Secrets with Kustomize' },
    ],
  },
  {
    id: 'migrating-helm-kustomize',
    title: 'Migrating Helm ↔ Kustomize',
    parentId: 'kustomize',
    children: [
      { id: 'helm-to-kustomize', title: 'Helm → Kustomize' },
      { id: 'kustomize-to-helm', title: 'Kustomize → Helm' },
      { id: 'rendering-pipelines', title: 'Rendering Pipelines (helm template + kustomize)' },
    ],
  },

  /* ---------- deployment-strategies (REFOCUSED) ---------- */
  {
    id: 'kubernetes-native-rollouts',
    title: 'Kubernetes-Native Rollouts',
    parentId: 'deployment-strategies',
    children: [
      { id: 'rolling-update-deployment', title: 'Deployment RollingUpdate' },
      { id: 'recreate-deployment', title: 'Deployment Recreate' },
      { id: 'statefulset-rollingupdate', title: 'StatefulSet RollingUpdate' },
      { id: 'statefulset-ondelete', title: 'StatefulSet OnDelete' },
      { id: 'daemonset-rollingupdate', title: 'DaemonSet RollingUpdate' },
      { id: 'daemonset-ondelete', title: 'DaemonSet OnDelete' },
      { id: 'job-and-cronjob-update-semantics', title: 'Job / CronJob Update Semantics' },
    ],
  },
  {
    id: 'rollout-mechanics',
    title: 'Rollout Mechanics',
    parentId: 'deployment-strategies',
    children: [
      { id: 'kubectl-rollout-status', title: 'kubectl rollout status' },
      { id: 'kubectl-rollout-pause', title: 'kubectl rollout pause' },
      { id: 'kubectl-rollout-resume', title: 'kubectl rollout resume' },
      { id: 'kubectl-rollout-undo', title: 'kubectl rollout undo' },
      { id: 'rollout-history-revisions', title: 'Rollout History & Revisions' },
      { id: 'revisionhistorylimit-tuning', title: 'revisionHistoryLimit Tuning' },
      { id: 'progressdeadlineseconds-tuning', title: 'progressDeadlineSeconds Tuning' },
      { id: 'minreadyseconds-tuning', title: 'minReadySeconds Tuning' },
    ],
  },
  {
    id: 'max-surge-and-max-unavailable-tuning',
    title: 'maxSurge & maxUnavailable Tuning',
    parentId: 'deployment-strategies',
    children: [
      { id: 'percentage-vs-absolute', title: 'Percentage vs Absolute' },
      { id: 'zero-downtime-tuning', title: 'Zero-Downtime Tuning' },
      { id: 'cost-vs-availability-tradeoffs', title: 'Cost vs Availability Trade-offs' },
      { id: 'large-replica-rollouts', title: 'Large Replica Count Rollouts' },
    ],
  },
  {
    id: 'partition-rolling-update-statefulsets',
    title: 'Partition Rolling Update (StatefulSets)',
    parentId: 'deployment-strategies',
    children: [
      { id: 'partition-field', title: 'partition Field' },
      { id: 'canary-via-partition', title: 'Canary via partition' },
      { id: 'controlled-rollout-with-partition', title: 'Controlled Rollout with partition' },
      { id: 'partition-and-min-replicas', title: 'partition & minReplicasOnUpdate' },
    ],
  },
  {
    id: 'failure-and-rollback',
    title: 'Failure & Rollback',
    parentId: 'deployment-strategies',
    children: [
      { id: 'failed-deployment-conditions', title: 'Failed Deployment Conditions' },
      { id: 'no-auto-rollback-in-k8s', title: 'No Auto-Rollback in Kubernetes' },
      { id: 'manual-rollback-flow', title: 'Manual Rollback Flow' },
      { id: 'rollback-with-revision', title: 'Rollback with --to-revision' },
    ],
  },
  {
    id: 'pods-during-rollout',
    title: 'Pods During Rollout',
    parentId: 'deployment-strategies',
    children: [
      { id: 'graceful-shutdown-during-rollout', title: 'Graceful Shutdown During Rollout' },
      { id: 'readiness-gates-during-rollout', title: 'Readiness Gates During Rollout' },
      { id: 'pdb-during-rollout', title: 'PDB During Rollout' },
      { id: 'pod-eviction-during-update', title: 'Pod Eviction During Update' },
    ],
  },
  {
    id: 'multi-version-coexistence',
    title: 'Multi-Version Coexistence',
    parentId: 'deployment-strategies',
    children: [
      { id: 'service-routing-during-rollout', title: 'Service Routing During Rollout' },
      { id: 'session-affinity-during-rollout', title: 'Session Affinity Considerations' },
      { id: 'schema-migrations-during-rollout', title: 'Schema Migrations During Rollout' },
      { id: 'backward-compatible-apis', title: 'Backward-Compatible APIs Between Versions' },
    ],
  },
  {
    id: 'native-canary-patterns',
    title: 'Native Canary Patterns (No Mesh)',
    parentId: 'deployment-strategies',
    children: [
      { id: 'two-deployments-shared-selector', title: 'Two Deployments + Shared Selector' },
      { id: 'replica-ratio-canary', title: 'Replica-Ratio Canary' },
      { id: 'gateway-api-weighted-canary', title: 'Gateway API Weighted Canary (Native)' },
      { id: 'kubectl-rollout-pause-canary', title: 'kubectl rollout pause Canary' },
    ],
  },
  {
    id: 'progressive-delivery-pointer',
    title: 'Progressive Delivery (Pointer)',
    parentId: 'deployment-strategies',
    children: [
      { id: 'argo-rollouts-pointer-stage12', title: 'Argo Rollouts (Pointer)' },
      { id: 'flagger-pointer-stage12', title: 'Flagger (Pointer)' },
      { id: 'feature-flags-pointer-stage12', title: 'Feature Flags (Pointer to DevOps)' },
    ],
  },
])
