import { addTopics } from './addTopics.mjs'

// Stage 13 — Extending Kubernetes
addTopics([
  /* ---------- custom-resources ---------- */
  {
    id: 'crd-fundamentals',
    title: 'CRD Fundamentals',
    parentId: 'custom-resources',
    children: [
      { id: 'crd-overview', title: 'CRD Overview' },
      { id: 'customresourcedefinition-resource', title: 'CustomResourceDefinition Resource' },
      { id: 'crd-vs-configmap', title: 'CRD vs ConfigMap' },
      { id: 'crd-vs-aggregated-api', title: 'CRD vs Aggregated API' },
      { id: 'crd-storage-limits', title: 'CRD Storage Limits' },
      { id: 'crd-namespace-vs-cluster-scope', title: 'Namespaced vs Cluster-Scoped CRDs' },
    ],
  },
  {
    id: 'crd-spec-and-versions',
    title: 'CRD Spec & Versions',
    parentId: 'custom-resources',
    children: [
      { id: 'crd-versions-list', title: 'versions List' },
      { id: 'served-and-storage-flags', title: 'served & storage Flags' },
      { id: 'multiple-versions-and-conversion', title: 'Multiple Versions & Conversion' },
      { id: 'deprecated-versions', title: 'Deprecated Versions' },
      { id: 'apiapprovedio', title: 'api-approved.kubernetes.io Annotation' },
    ],
  },
  {
    id: 'crd-validation',
    title: 'CRD Validation',
    parentId: 'custom-resources',
    children: [
      { id: 'openapi-v3-schemas', title: 'OpenAPI v3 Schemas' },
      { id: 'structural-schemas', title: 'Structural Schemas' },
      { id: 'crd-cel-validation', title: 'CEL-Based Validation Rules' },
      { id: 'crd-validation-ratcheting', title: 'Validation Ratcheting (KEP-4008)' },
      { id: 'preserveunknownfields-removed', title: 'preserveUnknownFields (Removed)' },
      { id: 'list-type-list-map-keys', title: 'list-type, list-map-keys' },
      { id: 'default-values-via-schema', title: 'Default Values via Schema' },
    ],
  },
  {
    id: 'crd-conversion',
    title: 'CRD Conversion',
    parentId: 'custom-resources',
    children: [
      { id: 'none-conversion-strategy', title: 'None Conversion Strategy' },
      { id: 'webhook-conversion-strategy', title: 'Webhook Conversion Strategy' },
      { id: 'conversion-review-payload', title: 'ConversionReview Payload' },
      { id: 'multi-version-conversion-pitfalls', title: 'Multi-Version Conversion Pitfalls' },
    ],
  },
  {
    id: 'crd-printer-columns',
    title: 'CRD Printer Columns',
    parentId: 'custom-resources',
    children: [
      { id: 'additional-printer-columns', title: 'additionalPrinterColumns' },
      { id: 'jsonpath-for-columns', title: 'JSONPath for Columns' },
      { id: 'priority-and-format', title: 'priority & format Fields' },
    ],
  },
  {
    id: 'crd-categories-and-shortnames',
    title: 'CRD Categories & Short Names',
    parentId: 'custom-resources',
    children: [
      { id: 'categories-field', title: 'categories Field' },
      { id: 'shortnames-field', title: 'shortNames Field' },
      { id: 'singular-and-plural-names', title: 'singular & plural Names' },
      { id: 'kind-and-list-kind', title: 'kind & listKind' },
    ],
  },
  {
    id: 'crd-subresources',
    title: 'CRD Subresources',
    parentId: 'custom-resources',
    children: [
      { id: 'status-subresource', title: 'status Subresource' },
      { id: 'scale-subresource', title: 'scale Subresource' },
      { id: 'spec-vs-status-conventions', title: 'Spec vs Status Conventions' },
      { id: 'enabling-hpa-on-crds', title: 'Enabling HPA on CRDs via scale Subresource' },
    ],
  },
  {
    id: 'crd-server-side-apply-and-managed-fields',
    title: 'Server-Side Apply & Managed Fields on CRDs',
    parentId: 'custom-resources',
    children: [
      { id: 'managed-fields-on-crds', title: 'Managed Fields on CRDs' },
      { id: 'ssa-conflict-resolution', title: 'SSA Conflict Resolution' },
      { id: 'apply-configuration-types', title: 'ApplyConfiguration Types' },
    ],
  },
  {
    id: 'crd-finalizers-deep',
    title: 'CRD Finalizers',
    parentId: 'custom-resources',
    children: [
      { id: 'finalizers-purpose', title: 'Finalizers Purpose' },
      { id: 'adding-removing-finalizers', title: 'Adding / Removing Finalizers' },
      { id: 'finalizer-deletion-flow', title: 'Finalizer Deletion Flow' },
      { id: 'stuck-finalizers-troubleshooting', title: 'Stuck Finalizers Troubleshooting' },
    ],
  },
  {
    id: 'selectable-fields-on-crds',
    title: 'Selectable Fields on CRDs',
    parentId: 'custom-resources',
    children: [
      { id: 'selectable-fields-kep', title: 'Selectable Fields (KEP-4358)' },
      { id: 'field-selectors-on-crds', title: 'Field Selectors on CRDs' },
    ],
  },
  {
    id: 'cel-protected-fields',
    title: 'CEL Protected Fields',
    parentId: 'custom-resources',
    children: [
      { id: 'cel-immutable-fields', title: 'CEL Immutable Fields' },
      { id: 'cel-transition-rules', title: 'CEL Transition Rules' },
      { id: 'cel-message-and-reason', title: 'message & reason Fields' },
    ],
  },
  {
    id: 'crd-best-practices',
    title: 'CRD Best Practices',
    parentId: 'custom-resources',
    children: [
      { id: 'naming-conventions-crd', title: 'Naming Conventions' },
      { id: 'group-and-versioning-strategy', title: 'Group & Versioning Strategy' },
      { id: 'minimal-spec-status-design', title: 'Minimal spec/status Design' },
      { id: 'crd-documentation-via-descriptions', title: 'Documentation via descriptions' },
    ],
  },

  /* ---------- operators-pattern ---------- */
  {
    id: 'controller-pattern',
    title: 'Controller Pattern',
    parentId: 'operators-pattern',
    children: [
      { id: 'controller-loop', title: 'Controller Loop' },
      { id: 'reconciliation-loops-deep', title: 'Reconciliation Loops Deep Dive' },
      { id: 'declarative-vs-imperative-controllers', title: 'Declarative vs Imperative Controllers' },
      { id: 'level-vs-edge-triggered-controllers', title: 'Level vs Edge-Triggered' },
      { id: 'idempotent-reconciliation', title: 'Idempotent Reconciliation' },
      { id: 'optimistic-concurrency-resourceversion', title: 'Optimistic Concurrency & resourceVersion' },
    ],
  },
  {
    id: 'operator-pattern-overview',
    title: 'Operator Pattern Overview',
    parentId: 'operators-pattern',
    children: [
      { id: 'operator-as-domain-knowledge', title: 'Operator as Encoded Domain Knowledge' },
      { id: 'operator-vs-controller', title: 'Operator vs Controller' },
      { id: 'operator-vs-helm-chart', title: 'Operator vs Helm Chart' },
      { id: 'operator-capability-levels', title: 'Operator Capability Levels' },
    ],
  },
  {
    id: 'operator-frameworks',
    title: 'Operator Frameworks',
    parentId: 'operators-pattern',
    children: [
      { id: 'kubebuilder', title: 'Kubebuilder' },
      { id: 'operator-sdk', title: 'Operator SDK' },
      { id: 'controller-runtime', title: 'controller-runtime (sigs)' },
      { id: 'kopf-python', title: 'Kopf (Python)' },
      { id: 'metacontroller', title: 'Metacontroller' },
      { id: 'shell-operator', title: 'shell-operator' },
      { id: 'helm-operator-framework', title: 'Helm Operator (OSDK)' },
      { id: 'ansible-operator-framework', title: 'Ansible Operator (OSDK)' },
      { id: 'kosmos-and-others', title: 'Kosmos & Others' },
    ],
  },
  {
    id: 'operator-development',
    title: 'Operator Development',
    parentId: 'operators-pattern',
    children: [
      { id: 'scaffolding-with-kubebuilder', title: 'Scaffolding with Kubebuilder' },
      { id: 'reconciler-implementation', title: 'Reconciler Implementation' },
      { id: 'predicates-and-event-filtering', title: 'Predicates & Event Filtering' },
      { id: 'workqueues-and-rate-limiters', title: 'Workqueues & Rate Limiters' },
      { id: 'finalizers-in-operators', title: 'Finalizers in Operators' },
      { id: 'conditions-and-status-reporting', title: 'Conditions & Status Reporting' },
      { id: 'owner-references-and-gc', title: 'OwnerReferences & Garbage Collection' },
      { id: 'leader-election-in-operators', title: 'Leader Election in Operators' },
      { id: 'multi-cluster-controllers', title: 'Multi-Cluster Controllers' },
      { id: 'webhooks-with-operators', title: 'Bundled Webhooks with Operators' },
    ],
  },
  {
    id: 'operator-testing',
    title: 'Operator Testing',
    parentId: 'operators-pattern',
    children: [
      { id: 'envtest', title: 'envtest' },
      { id: 'kind-for-integration-tests', title: 'kind for Integration Tests' },
      { id: 'controller-runtime-test-utilities', title: 'controller-runtime Test Utilities' },
      { id: 'e2e-tests-with-ginkgo-and-gomega', title: 'E2E with Ginkgo & Gomega' },
      { id: 'kuttl', title: 'KUTTL' },
      { id: 'operator-tdd-patterns', title: 'Operator TDD Patterns' },
    ],
  },
  {
    id: 'operator-lifecycle-manager',
    title: 'Operator Lifecycle Manager (OLM)',
    parentId: 'operators-pattern',
    children: [
      { id: 'olm-overview', title: 'OLM Overview' },
      { id: 'subscription-resource', title: 'Subscription Resource' },
      { id: 'clusterserviceversion-resource', title: 'ClusterServiceVersion Resource' },
      { id: 'operatorgroup-resource', title: 'OperatorGroup Resource' },
      { id: 'catalogsource-resource', title: 'CatalogSource Resource' },
      { id: 'olm-bundles-and-bundle-format', title: 'Bundles & Bundle Format' },
      { id: 'olm-v1', title: 'OLM v1' },
    ],
  },
  {
    id: 'operatorhub-and-distribution',
    title: 'OperatorHub & Distribution',
    parentId: 'operators-pattern',
    children: [
      { id: 'operatorhub-io', title: 'OperatorHub.io' },
      { id: 'redhat-marketplace', title: 'Red Hat Marketplace' },
      { id: 'community-operators', title: 'Community Operators' },
      { id: 'private-catalog-distribution', title: 'Private Catalog Distribution' },
    ],
  },
  {
    id: 'operator-best-practices',
    title: 'Operator Best Practices',
    parentId: 'operators-pattern',
    children: [
      { id: 'minimize-rbac', title: 'Minimize RBAC' },
      { id: 'idempotency-and-error-handling', title: 'Idempotency & Error Handling' },
      { id: 'graceful-deletion', title: 'Graceful Deletion' },
      { id: 'observability-from-operators', title: 'Operator Observability' },
      { id: 'operator-upgrade-strategies', title: 'Operator Upgrade Strategies' },
      { id: 'operator-versioning-and-compatibility', title: 'Versioning & Compatibility' },
    ],
  },

  /* ---------- api-extensions ---------- */
  {
    id: 'aggregated-apiserver',
    title: 'Aggregated API Server',
    parentId: 'api-extensions',
    children: [
      { id: 'apiservice-resource', title: 'APIService Resource' },
      { id: 'sample-apiserver', title: 'sample-apiserver' },
      { id: 'building-aggregated-apiservers', title: 'Building Aggregated API Servers' },
      { id: 'aggregated-apiserver-tls', title: 'Aggregated API Server TLS' },
      { id: 'aggregated-discovery', title: 'Aggregated Discovery' },
      { id: 'kube-aggregator', title: 'kube-aggregator Component' },
    ],
  },
  {
    id: 'cel-language-deep',
    title: 'CEL Language Deep Dive',
    parentId: 'api-extensions',
    children: [
      { id: 'cel-overview', title: 'CEL Overview' },
      { id: 'cel-types', title: 'CEL Types' },
      { id: 'cel-functions', title: 'CEL Functions' },
      { id: 'cel-cost-budget', title: 'CEL Cost Budget' },
      { id: 'cel-libraries', title: 'CEL Libraries' },
      { id: 'cel-where-used', title: 'Where CEL Is Used (CRD validation, VAP, MAP, AuthN/AuthZ config)' },
    ],
  },
  {
    id: 'admission-webhooks-deep-pointer',
    title: 'Admission Webhooks Deep (Pointer)',
    parentId: 'api-extensions',
    children: [
      { id: 'admission-webhooks-recap', title: 'Admission Webhooks Recap (Stage 10)' },
      { id: 'webhook-failure-policies-deep', title: 'Failure Policies (Deep)' },
      { id: 'webhook-bypass-and-emergency-access', title: 'Webhook Bypass & Emergency Access' },
    ],
  },
  {
    id: 'service-account-issuer-discovery',
    title: 'ServiceAccount Issuer Discovery',
    parentId: 'api-extensions',
    children: [
      { id: 'oidc-discovery-endpoint', title: 'OIDC Discovery Endpoint' },
      { id: 'service-account-issuer-flag', title: '--service-account-issuer Flag' },
      { id: 'public-jwks-keys', title: 'Public JWKS Keys' },
      { id: 'workload-identity-via-discovery', title: 'Workload Identity via Discovery' },
    ],
  },
  {
    id: 'openapi-and-discovery',
    title: 'OpenAPI & Discovery',
    parentId: 'api-extensions',
    children: [
      { id: 'openapi-v2-vs-v3', title: 'OpenAPI v2 vs v3' },
      { id: 'aggregated-discovery-deep', title: 'Aggregated Discovery (Deep)' },
      { id: 'protobuf-schema', title: 'Protobuf Schema' },
      { id: 'kubectl-explain-source', title: 'Source for kubectl explain' },
    ],
  },
  {
    id: 'field-and-label-selectors',
    title: 'Field & Label Selectors',
    parentId: 'api-extensions',
    children: [
      { id: 'label-selectors-deep', title: 'Label Selectors Deep' },
      { id: 'field-selectors-deep', title: 'Field Selectors Deep' },
      { id: 'set-based-vs-equality', title: 'Set-Based vs Equality' },
      { id: 'selectable-fields-on-crds-pointer', title: 'Selectable Fields on CRDs (Pointer)' },
    ],
  },
  {
    id: 'watch-api-deep',
    title: 'Watch API Deep Dive',
    parentId: 'api-extensions',
    children: [
      { id: 'watch-protocol-detail', title: 'Watch Protocol Detail' },
      { id: 'bookmark-events', title: 'Bookmark Events' },
      { id: 'streaming-list-api', title: 'Streaming List API (KEP-3157)' },
      { id: 'watch-cache-deep', title: 'Watch Cache Deep' },
      { id: 'consistent-list-from-cache', title: 'Consistent Reads from Cache (KEP-2340)' },
    ],
  },
  {
    id: 'structured-merge-and-managed-fields',
    title: 'Structured Merge & Managed Fields',
    parentId: 'api-extensions',
    children: [
      { id: 'server-side-apply-deep', title: 'Server-Side Apply Deep' },
      { id: 'managed-fields-deep', title: 'Managed Fields Deep' },
      { id: 'field-ownership', title: 'Field Ownership & Conflicts' },
      { id: 'apply-vs-update', title: 'Apply vs Update' },
    ],
  },
  {
    id: 'finalizers-and-gc-deep',
    title: 'Finalizers & Garbage Collection (Deep)',
    parentId: 'api-extensions',
    children: [
      { id: 'finalizers-deep', title: 'Finalizers Deep' },
      { id: 'garbage-collection-deep', title: 'Garbage Collection Deep' },
      { id: 'foreground-vs-background-vs-orphan-deep', title: 'Foreground vs Background vs Orphan (Deep)' },
      { id: 'cascade-deletion-controllers', title: 'Cascade Deletion Controllers' },
    ],
  },
  {
    id: 'extension-types-comparison',
    title: 'Extension Types Comparison',
    parentId: 'api-extensions',
    children: [
      { id: 'crd-vs-aggregated-api-deep', title: 'CRD vs Aggregated API (Deep)' },
      { id: 'webhook-vs-policy-engine', title: 'Webhook vs Policy Engine' },
      { id: 'controllers-vs-operators', title: 'Controllers vs Operators' },
      { id: 'choosing-the-right-extension', title: 'Choosing the Right Extension' },
    ],
  },
])
