import { addTopics } from './addTopics.mjs'

// Stage 17 — GitOps & CI/CD
// gitops-fundamentals refocused on K8s-specific GitOps patterns
// (generic GitOps theory lives in the DevOps subject).
addTopics([
  /* ---------- gitops-fundamentals (K8s-focused) ---------- */
  {
    id: 'gitops-on-k8s-overview',
    title: 'GitOps on Kubernetes Overview',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'why-gitops-fits-k8s', title: 'Why GitOps Fits Kubernetes' },
      { id: 'declarative-and-reconciliation-on-k8s', title: 'Declarative Model & Reconciliation on K8s' },
      { id: 'pull-based-vs-push-based-on-k8s', title: 'Pull-Based vs Push-Based on K8s' },
      { id: 'cluster-state-vs-app-state-on-k8s', title: 'Cluster State vs App State on K8s' },
      { id: 'opengitops-principles-pointer', title: 'OpenGitOps Principles (Pointer)' },
    ],
  },
  {
    id: 'repository-patterns-for-k8s',
    title: 'Repository Patterns for Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'monorepo-vs-polyrepo-on-k8s', title: 'Monorepo vs Polyrepo on K8s' },
      { id: 'app-of-apps-pattern', title: 'App-of-Apps Pattern' },
      { id: 'team-and-tenant-repos', title: 'Team / Tenant Repos' },
      { id: 'environment-branches-vs-overlays', title: 'Environment Branches vs Overlays' },
      { id: 'tenancy-folders-and-paths', title: 'Tenancy Folders & Paths' },
      { id: 'mirroring-charts-and-helm-repos', title: 'Mirroring Charts & Helm Repos' },
    ],
  },
  {
    id: 'environment-promotion-on-k8s',
    title: 'Environment Promotion on Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'dev-staging-prod-overlays', title: 'Dev / Staging / Prod Overlays' },
      { id: 'kustomize-overlays-for-environments', title: 'Kustomize Overlays per Environment' },
      { id: 'helm-values-per-environment', title: 'Helm Values per Environment' },
      { id: 'manual-vs-automated-promotion', title: 'Manual vs Automated Promotion' },
      { id: 'environment-pinning-strategies', title: 'Environment Pinning Strategies' },
      { id: 'pull-request-based-promotion', title: 'Pull-Request-Based Promotion' },
    ],
  },
  {
    id: 'secrets-on-gitops-clusters',
    title: 'Secrets on GitOps Clusters',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'sealed-secrets-on-gitops', title: 'Sealed Secrets on GitOps' },
      { id: 'external-secrets-on-gitops', title: 'External Secrets on GitOps' },
      { id: 'sops-on-gitops', title: 'SOPS on GitOps' },
      { id: 'vault-agent-injector-on-gitops', title: 'Vault Agent Injector' },
      { id: 'argocd-vault-plugin-pointer', title: 'argocd-vault-plugin (Pointer)' },
    ],
  },
  {
    id: 'drift-and-self-healing-on-k8s',
    title: 'Drift Detection & Self-Healing on K8s',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'drift-detection-mechanisms', title: 'Drift Detection Mechanisms' },
      { id: 'automated-self-heal-on-k8s', title: 'Automated Self-Heal' },
      { id: 'prune-orphan-resources', title: 'Prune Orphan Resources' },
      { id: 'sync-windows-and-blackouts', title: 'Sync Windows & Blackouts' },
      { id: 'last-applied-vs-server-side-apply-on-gitops', title: 'last-applied vs Server-Side Apply' },
    ],
  },
  {
    id: 'gitops-multi-cluster-on-k8s',
    title: 'GitOps Multi-Cluster on Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'gitops-multi-cluster-pointer', title: 'GitOps Multi-Cluster (Pointer to Stage 16)' },
      { id: 'fleet-shaped-repositories', title: 'Fleet-Shaped Repositories' },
      { id: 'cross-cluster-promotion', title: 'Cross-Cluster Promotion' },
    ],
  },
  {
    id: 'gitops-bootstrap-patterns',
    title: 'GitOps Bootstrap Patterns',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'bootstrap-cluster-with-gitops-agent', title: 'Bootstrap Cluster With GitOps Agent' },
      { id: 'cluster-bootstrap-via-flux', title: 'Cluster Bootstrap via Flux' },
      { id: 'cluster-bootstrap-via-argocd', title: 'Cluster Bootstrap via Argo CD' },
      { id: 'bootstrap-via-clusterapi-pointer', title: 'Bootstrap via Cluster API (Pointer)' },
      { id: 'self-managing-clusters', title: 'Self-Managing Clusters' },
    ],
  },
  {
    id: 'gitops-rbac-on-clusters',
    title: 'GitOps RBAC on Clusters',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'gitops-agent-rbac', title: 'GitOps Agent RBAC' },
      { id: 'tenant-isolation-via-rbac', title: 'Tenant Isolation via RBAC' },
      { id: 'restricting-cluster-scoped-resources', title: 'Restricting Cluster-Scoped Resources' },
    ],
  },
  {
    id: 'gitops-and-helm-on-k8s',
    title: 'GitOps + Helm on Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'helm-charts-via-gitops', title: 'Helm Charts via GitOps' },
      { id: 'helm-values-files-in-git', title: 'Helm Values Files in Git' },
      { id: 'helm-vs-rendered-manifests-debate', title: 'Helm vs Rendered-Manifests Debate' },
    ],
  },
  {
    id: 'gitops-and-kustomize-on-k8s',
    title: 'GitOps + Kustomize on Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'kustomize-via-gitops', title: 'Kustomize via GitOps' },
      { id: 'overlays-in-gitops-repos', title: 'Overlays in GitOps Repos' },
      { id: 'pre-rendering-strategies', title: 'Pre-Rendering Strategies' },
    ],
  },
  {
    id: 'gitops-policy-as-code-on-k8s',
    title: 'GitOps Policy-as-Code on Kubernetes',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'kyverno-policies-via-gitops', title: 'Kyverno Policies via GitOps' },
      { id: 'gatekeeper-policies-via-gitops', title: 'Gatekeeper Policies via GitOps' },
      { id: 'policy-bundles-and-versioning', title: 'Policy Bundles & Versioning' },
    ],
  },
  {
    id: 'gitops-disaster-recovery',
    title: 'GitOps for Disaster Recovery',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'rebuild-cluster-from-git', title: 'Rebuild Cluster From Git' },
      { id: 'gitops-as-source-of-truth', title: 'GitOps as Source of Truth' },
      { id: 'state-not-in-git-pointer', title: 'State Not in Git (Pointer)' },
    ],
  },
  {
    id: 'gitops-and-progressive-delivery',
    title: 'GitOps & Progressive Delivery',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'progressive-delivery-on-gitops', title: 'Progressive Delivery on GitOps' },
      { id: 'argo-rollouts-with-gitops-pointer', title: 'Argo Rollouts with GitOps (Pointer)' },
      { id: 'flagger-with-gitops-pointer', title: 'Flagger with GitOps (Pointer)' },
    ],
  },
  {
    id: 'gitops-tooling-comparison-on-k8s',
    title: 'GitOps Tooling Comparison on K8s',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'argocd-vs-flux', title: 'Argo CD vs Flux' },
      { id: 'rancher-fleet-pointer-stage17', title: 'Rancher Fleet (Pointer)' },
      { id: 'jenkins-x-pointer-stage17', title: 'Jenkins X (Pointer)' },
      { id: 'spinnaker-pointer-stage17', title: 'Spinnaker (Pointer)' },
    ],
  },
  {
    id: 'compliance-and-audit-via-gitops',
    title: 'Compliance & Audit via GitOps',
    parentId: 'gitops-fundamentals',
    children: [
      { id: 'audit-trail-via-git-history', title: 'Audit Trail via Git History' },
      { id: 'signed-commits-and-tags', title: 'Signed Commits & Tags' },
      { id: 'sigstore-and-gitops-pointer', title: 'Sigstore & GitOps (Pointer)' },
    ],
  },

  /* ---------- argo-cd-and-rollouts ---------- */
  {
    id: 'argo-cd',
    title: 'Argo CD',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'argocd-overview', title: 'Argo CD Overview' },
      { id: 'argocd-architecture', title: 'Argo CD Architecture' },
      { id: 'argocd-server', title: 'argocd-server' },
      { id: 'argocd-application-controller', title: 'argocd-application-controller' },
      { id: 'argocd-repo-server', title: 'argocd-repo-server' },
      { id: 'argocd-redis', title: 'argocd Redis' },
      { id: 'argocd-dex', title: 'argocd Dex (SSO)' },
      { id: 'argocd-cli', title: 'argocd CLI' },
      { id: 'argocd-installation-options', title: 'Installation Options' },
    ],
  },
  {
    id: 'argo-cd-applications',
    title: 'Argo CD Applications',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'application-resource', title: 'Application Resource' },
      { id: 'application-source-types', title: 'Source Types (helm, kustomize, plain, plugin)' },
      { id: 'multi-source-applications', title: 'Multi-Source Applications' },
      { id: 'sync-policy', title: 'Sync Policy' },
      { id: 'sync-options', title: 'Sync Options' },
      { id: 'sync-waves-and-sync-hooks', title: 'Sync Waves & Sync Hooks' },
      { id: 'sync-windows-on-argo', title: 'Sync Windows' },
      { id: 'automated-sync-and-self-heal-argo', title: 'Automated Sync & Self-Heal' },
      { id: 'cascade-deletion-and-finalizers-argo', title: 'Cascade Deletion & Finalizers' },
      { id: 'health-and-sync-status', title: 'Health & Sync Status' },
    ],
  },
  {
    id: 'argo-cd-projects',
    title: 'Argo CD Projects',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'appproject-resource', title: 'AppProject Resource' },
      { id: 'project-roles', title: 'Project Roles' },
      { id: 'source-and-destination-restrictions', title: 'Source & Destination Restrictions' },
      { id: 'jwt-tokens-for-projects', title: 'JWT Tokens for Projects' },
      { id: 'cluster-resource-allow-deny-lists', title: 'Cluster Resource Allow / Deny Lists' },
    ],
  },
  {
    id: 'argo-cd-applicationsets-deep',
    title: 'Argo CD ApplicationSets (Deep)',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'applicationset-controller', title: 'ApplicationSet Controller' },
      { id: 'applicationset-templates', title: 'ApplicationSet Templates' },
      { id: 'progressive-syncs-on-argo', title: 'Progressive Syncs' },
      { id: 'applicationset-rollback', title: 'ApplicationSet Rollback Patterns' },
    ],
  },
  {
    id: 'argo-cd-config-management-plugins',
    title: 'Argo CD Config Management Plugins',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'argocd-cmp-overview', title: 'CMP Overview' },
      { id: 'kustomize-and-helm-customization', title: 'Kustomize & Helm Customisation' },
      { id: 'external-tools-jsonnet-tanka', title: 'External Tools (Jsonnet, Tanka)' },
      { id: 'cmp-sidecar-pattern', title: 'CMP Sidecar Pattern' },
    ],
  },
  {
    id: 'argo-cd-multi-tenant',
    title: 'Argo CD Multi-Tenant',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'rbac-for-argo', title: 'RBAC for Argo' },
      { id: 'sso-and-oidc-on-argo', title: 'SSO & OIDC on Argo' },
      { id: 'argo-with-multiple-clusters', title: 'Argo With Multiple Clusters' },
      { id: 'cluster-secrets-and-decryption', title: 'Cluster Secrets & Decryption' },
    ],
  },
  {
    id: 'argo-cd-image-updater',
    title: 'Argo CD Image Updater',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'image-updater-overview', title: 'Image Updater Overview' },
      { id: 'image-updater-write-back-methods', title: 'Write-Back Methods' },
      { id: 'image-update-strategies', title: 'Image Update Strategies (semver, latest, digest, name)' },
    ],
  },
  {
    id: 'argo-cd-notifications-controller',
    title: 'Argo CD Notifications Controller',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'notifications-overview', title: 'Notifications Overview' },
      { id: 'notification-templates', title: 'Notification Templates' },
      { id: 'notification-services', title: 'Notification Services (Slack, Email, etc.)' },
    ],
  },
  {
    id: 'argo-cd-observability-and-secrets',
    title: 'Argo CD Observability & Secrets',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'argocd-metrics', title: 'Argo CD Metrics' },
      { id: 'argocd-logs', title: 'Argo CD Logs' },
      { id: 'argocd-vault-plugin', title: 'argocd-vault-plugin' },
      { id: 'sealed-secrets-with-argo', title: 'Sealed Secrets with Argo' },
    ],
  },
  {
    id: 'argo-rollouts',
    title: 'Argo Rollouts',
    parentId: 'argo-cd-and-rollouts',
    children: [
      { id: 'argo-rollouts-overview', title: 'Argo Rollouts Overview' },
      { id: 'rollout-resource', title: 'Rollout Resource' },
      { id: 'canary-strategy-rollouts', title: 'Canary Strategy' },
      { id: 'blue-green-strategy-rollouts', title: 'Blue-Green Strategy' },
      { id: 'traffic-routing-providers', title: 'Traffic Routing Providers (Istio, Nginx, ALB, SMI, APISIX, Gateway API)' },
      { id: 'analysis-templates-and-runs', title: 'AnalysisTemplate & AnalysisRun' },
      { id: 'experiments-rollouts', title: 'Experiments' },
      { id: 'rollout-controller-mechanics', title: 'Rollout Controller Mechanics' },
      { id: 'rollout-rollback-and-pause', title: 'Rollback & Pause' },
      { id: 'rollouts-with-helm-charts', title: 'Rollouts With Helm Charts' },
      { id: 'rollouts-with-kustomize', title: 'Rollouts With Kustomize' },
      { id: 'rollouts-cli-and-dashboard', title: 'kubectl-argo-rollouts CLI & Dashboard' },
    ],
  },

  /* ---------- flux-and-other-cd ---------- */
  {
    id: 'flux',
    title: 'Flux (FluxCD)',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'flux-overview', title: 'Flux Overview' },
      { id: 'flux-architecture', title: 'Flux Architecture' },
      { id: 'flux-source-controller', title: 'source-controller' },
      { id: 'flux-kustomize-controller', title: 'kustomize-controller' },
      { id: 'flux-helm-controller', title: 'helm-controller' },
      { id: 'flux-notification-controller', title: 'notification-controller' },
      { id: 'flux-image-reflector-controller', title: 'image-reflector-controller' },
      { id: 'flux-image-automation-controller', title: 'image-automation-controller' },
      { id: 'flux-source-types', title: 'Source Types (Git, Helm, OCI, Bucket)' },
      { id: 'flux-cluster-bootstrap', title: 'Flux Cluster Bootstrap' },
      { id: 'flux-multi-tenant-pointer-stage17', title: 'Flux Multi-Tenant (Pointer)' },
      { id: 'flux-cli-and-flux-bootstrap', title: 'flux CLI & flux bootstrap' },
      { id: 'flux-vs-argocd-comparison', title: 'Flux vs Argo CD Comparison' },
      { id: 'flux-d2-architecture-pointer', title: 'Flux D2 Architecture (Pointer)' },
    ],
  },
  {
    id: 'jenkins-x',
    title: 'Jenkins X',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'jx-overview', title: 'Jenkins X Overview' },
      { id: 'jx-architecture', title: 'Jenkins X Architecture' },
      { id: 'jx-pipeline-and-environments', title: 'Pipelines & Environments' },
      { id: 'jx-quickstart', title: 'Jenkins X Quickstarts' },
    ],
  },
  {
    id: 'tekton-on-k8s',
    title: 'Tekton on Kubernetes',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'tekton-pipelines-architecture', title: 'Tekton Pipelines Architecture' },
      { id: 'tekton-task-and-pipeline-resources', title: 'Task, Pipeline, PipelineRun, TaskRun' },
      { id: 'tekton-triggers', title: 'Tekton Triggers' },
      { id: 'tekton-results', title: 'Tekton Results' },
      { id: 'tekton-chains-pointer', title: 'Tekton Chains (Pointer)' },
      { id: 'tekton-catalog', title: 'Tekton Catalog' },
      { id: 'tekton-dashboard', title: 'Tekton Dashboard' },
    ],
  },
  {
    id: 'spinnaker-on-k8s',
    title: 'Spinnaker on Kubernetes',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'spinnaker-architecture-on-k8s', title: 'Spinnaker Architecture' },
      { id: 'spinnaker-kubernetes-provider', title: 'Spinnaker Kubernetes Provider' },
      { id: 'spinnaker-pipelines', title: 'Spinnaker Pipelines' },
    ],
  },
  {
    id: 'keptn-on-k8s',
    title: 'Keptn on Kubernetes',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'keptn-overview', title: 'Keptn Overview' },
      { id: 'keptn-lifecycle-toolkit', title: 'Keptn Lifecycle Toolkit' },
      { id: 'keptn-evaluations-and-metrics', title: 'Keptn Evaluations & Metrics' },
    ],
  },
  {
    id: 'werf',
    title: 'werf',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'werf-overview', title: 'werf Overview' },
      { id: 'werf-image-builds', title: 'werf Image Builds' },
      { id: 'werf-deploy', title: 'werf Deploy' },
    ],
  },
  {
    id: 'dev-loops-on-k8s',
    title: 'Dev Loops on Kubernetes',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'skaffold-overview', title: 'Skaffold Overview' },
      { id: 'skaffold-dev-loop', title: 'Skaffold Dev Loop' },
      { id: 'devspace', title: 'DevSpace' },
      { id: 'tilt', title: 'Tilt' },
      { id: 'okteto-pointer', title: 'Okteto (Pointer)' },
      { id: 'garden-io', title: 'Garden.io' },
    ],
  },
  {
    id: 'k8s-cd-tooling-comparison',
    title: 'K8s CD Tooling Comparison',
    parentId: 'flux-and-other-cd',
    children: [
      { id: 'argocd-vs-flux-vs-fleet', title: 'Argo CD vs Flux vs Fleet' },
      { id: 'tekton-vs-argo-workflows-pointer', title: 'Tekton vs Argo Workflows (Pointer)' },
      { id: 'pipekit-and-others-pointer', title: 'Pipekit & Others (Pointer)' },
    ],
  },
])
