import { addTopics } from './addTopics.mjs'

// Stage 6 — Services & Networking
addTopics([
  /* ---------- services ---------- */
  {
    id: 'service-fundamentals',
    title: 'Service Fundamentals',
    parentId: 'services',
    children: [
      { id: 'service-purpose', title: 'Service Purpose' },
      { id: 'service-discovery-via-dns', title: 'Service Discovery via DNS' },
      { id: 'service-discovery-via-env-vars', title: 'Service Discovery via Env Vars' },
      { id: 'virtual-ip-vs-real-ip', title: 'Virtual IP vs Real IP' },
      { id: 'service-vs-endpoints', title: 'Service vs Endpoints' },
      { id: 'service-without-selector', title: 'Services Without Selectors' },
    ],
  },
  {
    id: 'service-types',
    title: 'Service Types',
    parentId: 'services',
    children: [
      { id: 'clusterip-service', title: 'ClusterIP Service' },
      { id: 'nodeport-service', title: 'NodePort Service' },
      { id: 'loadbalancer-service', title: 'LoadBalancer Service' },
      { id: 'externalname-service', title: 'ExternalName Service' },
      { id: 'headless-service', title: 'Headless Service (clusterIP: None)' },
    ],
  },
  {
    id: 'endpoints-and-endpointslices',
    title: 'Endpoints & EndpointSlices',
    parentId: 'services',
    children: [
      { id: 'endpoints-resource-legacy', title: 'Endpoints Resource (Legacy)' },
      { id: 'endpointslices-resource', title: 'EndpointSlices Resource' },
      { id: 'endpointslice-mirroring', title: 'EndpointSlice Mirroring' },
      { id: 'endpointslice-controller', title: 'EndpointSlice Controller' },
      { id: 'manual-endpoints-and-endpointslices', title: 'Manual Endpoints & EndpointSlices' },
    ],
  },
  {
    id: 'service-selectors',
    title: 'Service Selectors',
    parentId: 'services',
    children: [
      { id: 'label-selectors-on-services', title: 'Label Selectors on Services' },
      { id: 'multi-label-selectors', title: 'Multi-Label Selectors' },
      { id: 'set-based-vs-equality-selectors', title: 'Set-Based vs Equality Selectors (Services Only Support Equality)' },
    ],
  },
  {
    id: 'service-ports',
    title: 'Service Ports',
    parentId: 'services',
    children: [
      { id: 'port-vs-targetport-vs-nodeport', title: 'port vs targetPort vs nodePort' },
      { id: 'named-ports', title: 'Named Ports' },
      { id: 'service-protocols', title: 'Protocols (TCP, UDP, SCTP)' },
      { id: 'multiport-services', title: 'Multi-Port Services' },
      { id: 'app-protocol-field', title: 'appProtocol Field' },
    ],
  },
  {
    id: 'session-affinity',
    title: 'Session Affinity',
    parentId: 'services',
    children: [
      { id: 'sessionaffinity-clientip', title: 'sessionAffinity: ClientIP' },
      { id: 'session-affinity-config-timeout', title: 'sessionAffinityConfig timeoutSeconds' },
      { id: 'session-affinity-vs-sticky-sessions', title: 'Session Affinity vs L7 Sticky Sessions' },
    ],
  },
  {
    id: 'traffic-policies',
    title: 'Traffic Policies',
    parentId: 'services',
    children: [
      { id: 'internal-traffic-policy-cluster-vs-local', title: 'internalTrafficPolicy (Cluster vs Local)' },
      { id: 'external-traffic-policy-cluster-vs-local', title: 'externalTrafficPolicy (Cluster vs Local)' },
      { id: 'preserving-source-ip', title: 'Preserving Source IP' },
    ],
  },
  {
    id: 'topology-aware-routing',
    title: 'Topology-Aware Routing',
    parentId: 'services',
    children: [
      { id: 'topology-aware-hints', title: 'Topology-Aware Hints (Legacy)' },
      { id: 'traffic-distribution-field', title: 'trafficDistribution Field (KEP-4444)' },
      { id: 'preferclose-routing', title: 'PreferClose Routing' },
      { id: 'topology-aware-routing-tradeoffs', title: 'Trade-offs (Skew, Hot Spots)' },
    ],
  },
  {
    id: 'dual-stack-and-ip-families',
    title: 'Dual-Stack & IP Families',
    parentId: 'services',
    children: [
      { id: 'ipfamilypolicy', title: 'ipFamilyPolicy (SingleStack, PreferDualStack, RequireDualStack)' },
      { id: 'ipfamilies-list', title: 'ipFamilies List' },
      { id: 'dual-stack-services', title: 'Dual-Stack Services' },
    ],
  },
  {
    id: 'loadbalancer-services-deep',
    title: 'LoadBalancer Services Deep Dive',
    parentId: 'services',
    children: [
      { id: 'loadbalancer-class', title: 'loadBalancerClass Field' },
      { id: 'cloud-provider-load-balancers', title: 'Cloud-Provider Load Balancers' },
      { id: 'metallb', title: 'MetalLB' },
      { id: 'kube-vip', title: 'kube-vip' },
      { id: 'openelb', title: 'OpenELB' },
      { id: 'purelb', title: 'PureLB' },
      { id: 'cilium-loadbalancer-ipam', title: 'Cilium LoadBalancer IPAM' },
      { id: 'allocate-load-balancer-node-ports', title: 'allocateLoadBalancerNodePorts' },
      { id: 'load-balancer-source-ranges', title: 'loadBalancerSourceRanges' },
    ],
  },
  {
    id: 'multi-network-and-secondary-interfaces',
    title: 'Multi-Network & Secondary Interfaces',
    parentId: 'services',
    children: [
      { id: 'multus-cni', title: 'Multus CNI' },
      { id: 'pod-multiple-networks', title: 'Pods with Multiple Networks' },
      { id: 'sriov-and-dpdk-interfaces', title: 'SR-IOV & DPDK Interfaces' },
      { id: 'multi-network-services-kep', title: 'Multi-Network Services KEP' },
    ],
  },

  /* ---------- ingress-gateway-api ---------- */
  {
    id: 'ingress-resource',
    title: 'Ingress Resource',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'ingress-spec', title: 'Ingress Spec' },
      { id: 'ingress-rules-and-paths', title: 'Rules & Paths' },
      { id: 'default-backend', title: 'Default Backend' },
      { id: 'tls-on-ingress', title: 'TLS on Ingress' },
      { id: 'ingressclassname', title: 'ingressClassName' },
      { id: 'ingress-path-types', title: 'Path Types (Exact / Prefix / ImplementationSpecific)' },
      { id: 'ingress-host-rules', title: 'Host-Based Rules' },
      { id: 'ingress-annotations-extensibility', title: 'Annotations as Extensibility (Pre-Gateway API)' },
    ],
  },
  {
    id: 'ingress-controllers',
    title: 'Ingress Controllers',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'ingress-nginx', title: 'ingress-nginx (Kubernetes Project)' },
      { id: 'nginx-inc-ingress', title: 'NGINX Inc Ingress' },
      { id: 'traefik-ingress', title: 'Traefik' },
      { id: 'haproxy-ingress', title: 'HAProxy Ingress' },
      { id: 'contour-ingress', title: 'Contour' },
      { id: 'envoy-gateway-ingress', title: 'Envoy Gateway' },
      { id: 'kong-ingress', title: 'Kong Ingress Controller' },
      { id: 'apisix-ingress', title: 'Apache APISIX Ingress' },
      { id: 'cilium-ingress', title: 'Cilium Ingress' },
      { id: 'aws-load-balancer-controller', title: 'AWS Load Balancer Controller (Pointer)' },
      { id: 'azure-application-gateway-ingress', title: 'Azure Application Gateway Ingress (Pointer)' },
      { id: 'gke-ingress', title: 'GKE Ingress / GLBC (Pointer)' },
    ],
  },
  {
    id: 'gateway-api',
    title: 'Gateway API',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'gateway-api-overview', title: 'Gateway API Overview' },
      { id: 'gateway-api-ga-status', title: 'Gateway API GA & Versions' },
      { id: 'gateway-api-roles-model', title: 'Roles Model (Infra / Cluster Operator / App Dev)' },
      { id: 'gatewayclass-resource', title: 'GatewayClass Resource' },
      { id: 'gateway-resource', title: 'Gateway Resource' },
      { id: 'listeners', title: 'Listeners' },
      { id: 'httproute-resource', title: 'HTTPRoute Resource' },
      { id: 'tcproute-resource', title: 'TCPRoute Resource' },
      { id: 'tlsroute-resource', title: 'TLSRoute Resource' },
      { id: 'udproute-resource', title: 'UDPRoute Resource' },
      { id: 'grpcroute-resource', title: 'GRPCRoute Resource' },
      { id: 'referencegrant-resource', title: 'ReferenceGrant Resource' },
      { id: 'parametersref', title: 'parametersRef on GatewayClass' },
      { id: 'gateway-api-conformance', title: 'Gateway API Conformance' },
    ],
  },
  {
    id: 'gateway-api-traffic-features',
    title: 'Gateway API Traffic Features',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'header-based-routing', title: 'Header-Based Routing' },
      { id: 'path-based-routing', title: 'Path-Based Routing' },
      { id: 'method-based-routing', title: 'Method-Based Routing' },
      { id: 'query-param-routing', title: 'Query-Parameter Routing' },
      { id: 'weighted-traffic-splitting', title: 'Weighted Traffic Splitting' },
      { id: 'request-mirroring', title: 'Request Mirroring' },
      { id: 'request-redirects', title: 'Request Redirects' },
      { id: 'request-and-response-header-modification', title: 'Request/Response Header Modification' },
      { id: 'url-rewrites', title: 'URL Rewrites' },
      { id: 'timeouts-and-retries', title: 'Timeouts & Retries' },
      { id: 'session-persistence-policy', title: 'Session Persistence Policy' },
    ],
  },
  {
    id: 'gateway-api-implementations',
    title: 'Gateway API Implementations',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'envoy-gateway-impl', title: 'Envoy Gateway' },
      { id: 'istio-gateway-api-impl', title: 'Istio Gateway API (Pointer)' },
      { id: 'cilium-gateway-api-impl', title: 'Cilium Gateway API' },
      { id: 'nginx-gateway-fabric', title: 'NGINX Gateway Fabric' },
      { id: 'kong-gateway-api-impl', title: 'Kong Gateway API' },
      { id: 'kgateway', title: 'kgateway' },
      { id: 'haproxy-gateway-api', title: 'HAProxy Gateway API' },
      { id: 'gke-gateway-api-impl', title: 'GKE Gateway API (Pointer)' },
      { id: 'aws-gateway-api-controller', title: 'AWS Gateway API Controller (Pointer)' },
    ],
  },
  {
    id: 'gateway-api-extensions',
    title: 'Gateway API Extensions',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'gateway-api-inference-extension', title: 'Gateway API Inference Extension' },
      { id: 'inferencepool-resource', title: 'InferencePool Resource' },
      { id: 'inferencemodel-resource', title: 'InferenceModel Resource' },
      { id: 'gateway-api-tls-routes', title: 'TLS Routes Extension' },
      { id: 'gateway-api-policy-attachment', title: 'Policy Attachment Pattern' },
      { id: 'gamma-mesh-initiative', title: 'GAMMA (Mesh Initiative)' },
    ],
  },
  {
    id: 'migrating-ingress-to-gateway-api',
    title: 'Migrating from Ingress to Gateway API',
    parentId: 'ingress-gateway-api',
    children: [
      { id: 'migration-strategies', title: 'Migration Strategies' },
      { id: 'dual-running-ingress-gateway', title: 'Dual-Running Ingress + Gateway' },
      { id: 'ingress2gateway-tool', title: 'ingress2gateway Tool' },
      { id: 'feature-mapping', title: 'Feature Mapping (Annotations → Policies)' },
    ],
  },

  /* ---------- network-policies ---------- */
  {
    id: 'networkpolicy-fundamentals',
    title: 'NetworkPolicy Fundamentals',
    parentId: 'network-policies',
    children: [
      { id: 'networkpolicy-resource', title: 'NetworkPolicy Resource' },
      { id: 'default-deny-vs-default-allow', title: 'Default Deny vs Default Allow' },
      { id: 'pod-selectors-in-networkpolicy', title: 'Pod Selectors' },
      { id: 'namespace-selectors-in-networkpolicy', title: 'Namespace Selectors' },
      { id: 'ingress-rules', title: 'Ingress Rules' },
      { id: 'egress-rules', title: 'Egress Rules' },
      { id: 'rule-precedence', title: 'Rule Precedence' },
      { id: 'policytypes-field', title: 'policyTypes Field' },
      { id: 'ipblock-cidrs', title: 'ipBlock CIDRs & except' },
    ],
  },
  {
    id: 'networkpolicy-cni-support',
    title: 'NetworkPolicy CNI Support',
    parentId: 'network-policies',
    children: [
      { id: 'calico-networkpolicy-support', title: 'Calico NetworkPolicy Support' },
      { id: 'cilium-networkpolicy-support', title: 'Cilium NetworkPolicy Support' },
      { id: 'weave-networkpolicy-support', title: 'Weave NetworkPolicy Support' },
      { id: 'flannel-no-policy-support', title: 'Flannel: No Built-In Policy Support' },
      { id: 'antrea-networkpolicy-support', title: 'Antrea NetworkPolicy Support' },
    ],
  },
  {
    id: 'admin-network-policy',
    title: 'AdminNetworkPolicy',
    parentId: 'network-policies',
    children: [
      { id: 'anp-overview', title: 'AdminNetworkPolicy Overview (KEP-2091)' },
      { id: 'anp-vs-networkpolicy', title: 'AdminNetworkPolicy vs NetworkPolicy' },
      { id: 'anp-priorities', title: 'AdminNetworkPolicy Priorities' },
      { id: 'baseline-admin-network-policy', title: 'BaselineAdminNetworkPolicy' },
      { id: 'cluster-scope-policy-targets', title: 'Cluster-Scope Policy Targets' },
    ],
  },
  {
    id: 'cilium-networkpolicy-extensions',
    title: 'Cilium NetworkPolicy Extensions',
    parentId: 'network-policies',
    children: [
      { id: 'ciliumnetworkpolicy-crd', title: 'CiliumNetworkPolicy CRD' },
      { id: 'ciliumclusterwidenetworkpolicy', title: 'CiliumClusterwideNetworkPolicy' },
      { id: 'l7-aware-policies', title: 'L7-Aware Policies (HTTP, gRPC, Kafka)' },
      { id: 'dns-aware-policies', title: 'DNS-Aware Policies (FQDN)' },
      { id: 'service-account-based-policies', title: 'ServiceAccount-Based Policies' },
    ],
  },
  {
    id: 'calico-networkpolicy-extensions',
    title: 'Calico NetworkPolicy Extensions',
    parentId: 'network-policies',
    children: [
      { id: 'calico-globalnetworkpolicy', title: 'GlobalNetworkPolicy' },
      { id: 'calico-networkset', title: 'NetworkSet' },
      { id: 'calico-tier-system', title: 'Tier System' },
      { id: 'calico-application-layer-policy', title: 'Application Layer Policy' },
    ],
  },
  {
    id: 'networkpolicy-tooling',
    title: 'NetworkPolicy Tooling',
    parentId: 'network-policies',
    children: [
      { id: 'np-viewer-and-editors', title: 'Policy Viewer / Editor Tools' },
      { id: 'np-recommender', title: 'Policy Recommenders (kube-iptables-tailer, etc.)' },
      { id: 'cilium-hubble-flow-tracing', title: 'Hubble for Flow Tracing' },
      { id: 'cyclonus-and-conformance-tests', title: 'Cyclonus & Conformance Tests' },
    ],
  },
  {
    id: 'networkpolicy-best-practices',
    title: 'NetworkPolicy Best Practices',
    parentId: 'network-policies',
    children: [
      { id: 'starting-with-default-deny', title: 'Starting with Default Deny' },
      { id: 'namespace-segmentation', title: 'Namespace Segmentation' },
      { id: 'tiered-policies', title: 'Tiered Policies' },
      { id: 'testing-and-staging-policies', title: 'Testing & Staging Policies' },
      { id: 'policy-as-code-pointer', title: 'Policy-as-Code Tooling (Pointer)' },
    ],
  },
])
