import { addTopics } from './addTopics.mjs'

// Stage 22 — Certifications & Career
addTopics([
  /* ---------- kubernetes-certifications ---------- */
  {
    id: 'cncf-certifications-overview',
    title: 'CNCF Certifications Overview',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'cncf-overview', title: 'CNCF Overview' },
      { id: 'cncf-certification-roadmap', title: 'CNCF Certification Roadmap' },
      { id: 'exam-policies-and-environment', title: 'Exam Policies & Environment' },
      { id: 'remote-proctored-exam-flow', title: 'Remote-Proctored Exam Flow' },
      { id: 'exam-recertification-policy', title: 'Recertification Policy' },
    ],
  },
  {
    id: 'kcna',
    title: 'KCNA — Kubernetes & Cloud Native Associate',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'kcna-domains', title: 'KCNA Domains' },
      { id: 'kcna-prerequisites', title: 'KCNA Prerequisites' },
      { id: 'kcna-vs-cka', title: 'KCNA vs CKA' },
      { id: 'kcna-curriculum-2026', title: 'KCNA Curriculum (2026)' },
    ],
  },
  {
    id: 'kcsa',
    title: 'KCSA — Kubernetes & Cloud Native Security Associate',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'kcsa-domains', title: 'KCSA Domains' },
      { id: 'kcsa-prerequisites', title: 'KCSA Prerequisites' },
      { id: 'kcsa-vs-cks', title: 'KCSA vs CKS' },
      { id: 'kcsa-curriculum-2026', title: 'KCSA Curriculum (2026)' },
    ],
  },
  {
    id: 'ckad',
    title: 'CKAD — Certified Kubernetes Application Developer',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'ckad-domains', title: 'CKAD Domains' },
      { id: 'ckad-exam-format', title: 'CKAD Exam Format' },
      { id: 'ckad-tips', title: 'CKAD Tips' },
      { id: 'ckad-curriculum-2026', title: 'CKAD Curriculum (2026)' },
      { id: 'ckad-time-management', title: 'CKAD Time Management' },
    ],
  },
  {
    id: 'cka',
    title: 'CKA — Certified Kubernetes Administrator',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'cka-domains', title: 'CKA Domains' },
      { id: 'cka-exam-format', title: 'CKA Exam Format' },
      { id: 'cka-tips', title: 'CKA Tips' },
      { id: 'cka-curriculum-2026', title: 'CKA Curriculum (2026)' },
      { id: 'cka-time-management', title: 'CKA Time Management' },
    ],
  },
  {
    id: 'cks',
    title: 'CKS — Certified Kubernetes Security Specialist',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'cks-domains', title: 'CKS Domains' },
      { id: 'cks-prerequisites', title: 'CKS Prerequisites (CKA)' },
      { id: 'cks-exam-format', title: 'CKS Exam Format' },
      { id: 'cks-tips', title: 'CKS Tips' },
      { id: 'cks-curriculum-2026', title: 'CKS Curriculum (2026)' },
      { id: 'cks-tools-allowed', title: 'CKS Allowed Tools' },
    ],
  },
  {
    id: 'kubestronaut-program',
    title: 'Kubestronaut Program',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'kubestronaut-requirements', title: 'Kubestronaut Requirements' },
      { id: 'kubestronaut-benefits', title: 'Kubestronaut Benefits' },
      { id: 'golden-kubestronaut-pointer', title: 'Golden Kubestronaut (Pointer)' },
    ],
  },
  {
    id: 'service-mesh-certifications',
    title: 'Service Mesh Certifications',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'hashicorp-consul-cert-pointer', title: 'HashiCorp Consul Cert (Pointer)' },
      { id: 'istio-certified-associate', title: 'Istio Certified Associate (ICA)' },
      { id: 'linkerd-certifications', title: 'Linkerd Certifications' },
    ],
  },
  {
    id: 'argo-and-cd-certifications',
    title: 'Argo & CD Certifications',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'argo-cd-certifications', title: 'Argo CD Certifications' },
      { id: 'tekton-and-flux-certifications-pointer', title: 'Tekton & Flux Certifications (Pointer)' },
    ],
  },
  {
    id: 'observability-and-platform-certifications',
    title: 'Observability & Platform Certifications',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'prometheus-certified-associate-pca', title: 'Prometheus Certified Associate (PCA)' },
      { id: 'opentelemetry-certifications-pointer', title: 'OpenTelemetry Certifications (Pointer)' },
      { id: 'cnpa-cloud-native-platform-associate', title: 'CNPA — Cloud Native Platform Associate' },
    ],
  },
  {
    id: 'vendor-certifications-on-k8s',
    title: 'Vendor Certifications on K8s',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'red-hat-do180-do280-and-others', title: 'Red Hat DO180 / DO280 / EX280' },
      { id: 'rancher-certifications', title: 'Rancher Certifications' },
      { id: 'aws-eks-certifications-pointer', title: 'AWS EKS Certifications (Pointer)' },
      { id: 'gke-certifications-pointer', title: 'GKE Certifications (Pointer)' },
      { id: 'aks-certifications-pointer', title: 'AKS Certifications (Pointer)' },
      { id: 'vmware-tanzu-certifications', title: 'VMware Tanzu Certifications' },
    ],
  },
  {
    id: 'exam-resources-overview',
    title: 'Exam Resources Overview',
    parentId: 'kubernetes-certifications',
    children: [
      { id: 'cncf-curriculum-repos', title: 'CNCF Curriculum Repositories' },
      { id: 'official-exam-pdf-and-policies', title: 'Official Exam PDF & Policies' },
      { id: 'kubernetes-docs-as-resource', title: 'Kubernetes Docs as Resource' },
    ],
  },

  /* ---------- exam-preparation ---------- */
  {
    id: 'learning-paths-overview',
    title: 'Learning Paths Overview',
    parentId: 'exam-preparation',
    children: [
      { id: 'self-paced-vs-instructor-led', title: 'Self-Paced vs Instructor-Led' },
      { id: 'free-vs-paid-resources', title: 'Free vs Paid Resources' },
      { id: 'study-plan-templates', title: 'Study Plan Templates' },
    ],
  },
  {
    id: 'killer-sh-and-killercoda',
    title: 'killer.sh & Killercoda',
    parentId: 'exam-preparation',
    children: [
      { id: 'killer-sh-simulator', title: 'killer.sh Simulator' },
      { id: 'killercoda-scenarios', title: 'Killercoda Scenarios' },
      { id: 'killer-sh-tips', title: 'killer.sh Tips' },
    ],
  },
  {
    id: 'paid-courses-pointer',
    title: 'Paid Courses (Pointer)',
    parentId: 'exam-preparation',
    children: [
      { id: 'udemy-and-kodekloud-courses-pointer', title: 'Udemy & KodeKloud (Pointer)' },
      { id: 'pluralsight-acloudguru-pointer', title: 'Pluralsight & A Cloud Guru (Pointer)' },
      { id: 'linux-foundation-training', title: 'Linux Foundation Training' },
    ],
  },
  {
    id: 'free-resources-and-blogs',
    title: 'Free Resources & Blogs',
    parentId: 'exam-preparation',
    children: [
      { id: 'youtube-channels', title: 'YouTube Channels' },
      { id: 'official-blog-posts', title: 'Official Blog Posts' },
      { id: 'kubernetes-the-hard-way', title: 'Kubernetes the Hard Way' },
      { id: 'k8s-learning-roadmaps', title: 'K8s Learning Roadmaps' },
    ],
  },
  {
    id: 'official-docs-as-source',
    title: 'Official Docs as Source',
    parentId: 'exam-preparation',
    children: [
      { id: 'kubernetes-docs-deep', title: 'Kubernetes Docs (Deep)' },
      { id: 'kubernetes-tasks-section', title: 'Kubernetes Tasks Section' },
      { id: 'kubectl-bookmark-tips', title: 'kubectl Bookmark Tips' },
      { id: 'troubleshooting-section-on-docs', title: 'Troubleshooting Section on Docs' },
    ],
  },
  {
    id: 'hands-on-labs',
    title: 'Hands-On Labs',
    parentId: 'exam-preparation',
    children: [
      { id: 'kind-for-practice', title: 'kind for Practice' },
      { id: 'minikube-for-practice', title: 'Minikube for Practice' },
      { id: 'k3d-for-practice', title: 'k3d for Practice' },
      { id: 'katacoda-archive-pointer', title: 'Katacoda Archive (Pointer)' },
      { id: 'instruqt-and-others-pointer', title: 'Instruqt & Others (Pointer)' },
      { id: 'tgik-and-other-streams', title: 'TGIK & Other Streams' },
    ],
  },
  {
    id: 'mock-exam-strategies',
    title: 'Mock-Exam Strategies',
    parentId: 'exam-preparation',
    children: [
      { id: 'simulator-environments', title: 'Simulator Environments' },
      { id: 'timed-practice', title: 'Timed Practice' },
      { id: 'common-traps', title: 'Common Traps' },
      { id: 'self-grading-rubrics', title: 'Self-Grading Rubrics' },
    ],
  },
  {
    id: 'exam-day-tips',
    title: 'Exam Day Tips',
    parentId: 'exam-preparation',
    children: [
      { id: 'environment-setup', title: 'Environment Setup' },
      { id: 'browser-and-tool-tips', title: 'Browser & Tool Tips' },
      { id: 'terminal-shortcuts', title: 'Terminal Shortcuts' },
      { id: 'vim-and-tmux-on-exam', title: 'vim & tmux on Exam' },
      { id: 'bookmark-management', title: 'Bookmark Management' },
      { id: 'staying-calm-under-time-pressure', title: 'Staying Calm Under Time Pressure' },
    ],
  },
  {
    id: 'common-pitfalls-on-exams',
    title: 'Common Pitfalls on Exams',
    parentId: 'exam-preparation',
    children: [
      { id: 'context-and-namespace-mistakes', title: 'Context & Namespace Mistakes' },
      { id: 'misreading-question-requirements', title: 'Misreading Question Requirements' },
      { id: 'spending-too-long-on-one-question', title: 'Spending Too Long on One Question' },
      { id: 'cluster-version-skew-confusion', title: 'Cluster Version Skew Confusion' },
    ],
  },
  {
    id: 'post-exam-followup',
    title: 'Post-Exam Follow-Up',
    parentId: 'exam-preparation',
    children: [
      { id: 'reading-the-result-report', title: 'Reading the Result Report' },
      { id: 'retake-policy-and-strategy', title: 'Retake Policy & Strategy' },
      { id: 'sharing-the-credential', title: 'Sharing the Credential (Credly etc.)' },
    ],
  },

  /* ---------- career-community ---------- */
  {
    id: 'kubernetes-roles-overview',
    title: 'Kubernetes Roles Overview',
    parentId: 'career-community',
    children: [
      { id: 'kubernetes-engineer', title: 'Kubernetes Engineer' },
      { id: 'sre-on-k8s', title: 'SRE on Kubernetes' },
      { id: 'platform-engineer-on-k8s', title: 'Platform Engineer on K8s' },
      { id: 'cloud-engineer-on-k8s', title: 'Cloud Engineer on K8s' },
      { id: 'devops-engineer-on-k8s', title: 'DevOps Engineer on K8s' },
      { id: 'mlops-engineer-on-k8s', title: 'MLOps Engineer on K8s' },
      { id: 'security-engineer-on-k8s', title: 'Security Engineer on K8s' },
      { id: 'cloud-native-architect', title: 'Cloud-Native Architect' },
    ],
  },
  {
    id: 'preparing-a-k8s-portfolio',
    title: 'Preparing a Kubernetes Portfolio',
    parentId: 'career-community',
    children: [
      { id: 'github-presence', title: 'GitHub Presence' },
      { id: 'blogposts-and-talks', title: 'Blog Posts & Talks' },
      { id: 'homelab-projects', title: 'Homelab Projects' },
      { id: 'open-source-contributions', title: 'Open-Source Contributions' },
      { id: 'side-projects-on-k8s', title: 'Side Projects on K8s' },
    ],
  },
  {
    id: 'contributing-upstream-to-kubernetes',
    title: 'Contributing Upstream to Kubernetes',
    parentId: 'career-community',
    children: [
      { id: 'kubernetes-sigs-overview', title: 'Kubernetes SIGs Overview' },
      { id: 'kubernetes-contributor-paths', title: 'Contributor Paths' },
      { id: 'kep-process', title: 'KEP (Kubernetes Enhancement Proposal) Process' },
      { id: 'good-first-issues-and-help-wanted', title: 'good-first-issue & help-wanted' },
      { id: 'shadowing-rotations', title: 'Shadowing Rotations' },
      { id: 'sig-meetings', title: 'SIG Meetings' },
      { id: 'bug-triage-rotations', title: 'Bug Triage Rotations' },
      { id: 'test-grids-and-flaky-tests', title: 'Test Grids & Flaky Tests' },
      { id: 'release-team-roles', title: 'Release Team Roles' },
      { id: 'docs-contribution-via-website-repo', title: 'Docs Contribution (kubernetes/website)' },
    ],
  },
  {
    id: 'kubecon-and-events',
    title: 'KubeCon & Events',
    parentId: 'career-community',
    children: [
      { id: 'kubecon-eu', title: 'KubeCon EU' },
      { id: 'kubecon-na', title: 'KubeCon NA' },
      { id: 'kubecon-china', title: 'KubeCon China' },
      { id: 'kubecon-india', title: 'KubeCon India' },
      { id: 'kubecon-japan', title: 'KubeCon Japan' },
      { id: 'cloud-native-meetups', title: 'Cloud-Native Meetups' },
      { id: 'kcds-and-co-located-events', title: 'KCDs & Co-Located Events' },
      { id: 'cfp-and-conference-speaking', title: 'CFP & Conference Speaking' },
    ],
  },
  {
    id: 'staying-up-to-date-on-k8s',
    title: 'Staying Up-to-Date on Kubernetes',
    parentId: 'career-community',
    children: [
      { id: 'kubernetes-blog', title: 'Kubernetes Blog' },
      { id: 'cncf-newsletter', title: 'CNCF Newsletter' },
      { id: 'sig-mailing-lists', title: 'SIG Mailing Lists' },
      { id: 'tgik-pointer-stage22', title: 'TGIK (Pointer)' },
      { id: 'youtube-channels-stage22', title: 'YouTube Channels' },
      { id: 'twitter-x-and-mastodon', title: 'Twitter/X & Mastodon' },
      { id: 'last-week-in-kubernetes-development', title: 'Last Week in Kubernetes Development (LWKD)' },
      { id: 'kubernetes-podcast', title: 'Kubernetes Podcast (from Google)' },
    ],
  },
  {
    id: 'community-membership',
    title: 'Community Membership',
    parentId: 'career-community',
    children: [
      { id: 'kubernetes-community-org', title: 'kubernetes/community Org' },
      { id: 'cncf-membership', title: 'CNCF Membership' },
      { id: 'tag-membership-and-tocs', title: 'TAGs, TOCs & Working Groups' },
      { id: 'becoming-a-kubernetes-org-member', title: 'Becoming a kubernetes Org Member' },
    ],
  },
  {
    id: 'mentorship-and-rotations',
    title: 'Mentorship & Rotations',
    parentId: 'career-community',
    children: [
      { id: 'lfx-mentorship', title: 'LFX Mentorship' },
      { id: 'kubernetes-shadow-program', title: 'Kubernetes Shadow Program' },
      { id: 'women-and-non-binary-in-cncf-pointer', title: 'Women & Non-Binary in CNCF (Pointer)' },
      { id: 'newcomer-pathways', title: 'Newcomer Pathways' },
    ],
  },
  {
    id: 'thought-leadership-and-public-speaking',
    title: 'Thought Leadership & Public Speaking',
    parentId: 'career-community',
    children: [
      { id: 'writing-technical-blogposts', title: 'Writing Technical Blog Posts' },
      { id: 'submitting-to-kubernetes-blog', title: 'Submitting to the Kubernetes Blog' },
      { id: 'cncf-ambassadors', title: 'CNCF Ambassadors' },
      { id: 'building-a-personal-brand-on-k8s', title: 'Building a Personal Brand on K8s' },
    ],
  },
])
