import { addTopics } from './addTopics.mjs'

// Stage 20 — Specialized Workloads
addTopics([
  /* ---------- ai-ml-on-kubernetes ---------- */
  {
    id: 'gpu-on-kubernetes',
    title: 'GPUs on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'nvidia-device-plugin', title: 'NVIDIA Device Plugin' },
      { id: 'amd-rocm-device-plugin', title: 'AMD ROCm Device Plugin' },
      { id: 'intel-gpu-device-plugin', title: 'Intel GPU Device Plugin' },
      { id: 'nvidia-gpu-operator', title: 'NVIDIA GPU Operator' },
      { id: 'mig-multi-instance-gpu', title: 'MIG (Multi-Instance GPU)' },
      { id: 'mps-multi-process-service', title: 'MPS (Multi-Process Service)' },
      { id: 'time-slicing-gpus', title: 'Time-Slicing GPUs' },
      { id: 'gpu-feature-discovery', title: 'GPU Feature Discovery' },
      { id: 'dra-for-gpus-pointer', title: 'DRA for GPUs (Pointer to Stage 8)' },
      { id: 'gpu-monitoring-dcgm-exporter', title: 'DCGM Exporter (GPU Monitoring)' },
      { id: 'gpu-driver-management-on-nodes', title: 'GPU Driver Management on Nodes' },
    ],
  },
  {
    id: 'accelerators-on-k8s',
    title: 'Accelerators on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'tpu-on-gke', title: 'TPU on GKE' },
      { id: 'aws-trainium-and-inferentia', title: 'AWS Trainium & Inferentia' },
      { id: 'habana-gaudi', title: 'Habana Gaudi' },
      { id: 'aws-neuron-sdk-pointer', title: 'AWS Neuron SDK (Pointer)' },
      { id: 'rdma-and-infiniband', title: 'RDMA & InfiniBand' },
      { id: 'rdma-shared-device-plugin', title: 'RDMA Shared Device Plugin' },
      { id: 'sriov-for-gpus-and-nics', title: 'SR-IOV for GPUs & NICs' },
    ],
  },
  {
    id: 'kubeflow',
    title: 'Kubeflow',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'kubeflow-overview', title: 'Kubeflow Overview' },
      { id: 'kubeflow-pipelines', title: 'Kubeflow Pipelines' },
      { id: 'kubeflow-notebooks', title: 'Kubeflow Notebooks' },
      { id: 'kubeflow-katib', title: 'Kubeflow Katib (HPO)' },
      { id: 'kubeflow-training-operator', title: 'Kubeflow Training Operator' },
      { id: 'kubeflow-tfjob', title: 'TFJob' },
      { id: 'kubeflow-pytorchjob', title: 'PyTorchJob' },
      { id: 'kubeflow-mpijob', title: 'MPIJob' },
      { id: 'kubeflow-paddlejob', title: 'PaddleJob' },
      { id: 'kubeflow-xgboostjob', title: 'XGBoostJob' },
      { id: 'kubeflow-jaxjob', title: 'JAXJob' },
      { id: 'kubeflow-spark-operator-pointer', title: 'Kubeflow Spark Operator (Pointer)' },
      { id: 'kubeflow-istio-integration', title: 'Kubeflow Istio Integration' },
      { id: 'kubeflow-multi-tenancy', title: 'Kubeflow Multi-Tenancy' },
    ],
  },
  {
    id: 'kserve',
    title: 'KServe',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'kserve-overview', title: 'KServe Overview' },
      { id: 'kserve-inferenceservice-resource', title: 'InferenceService Resource' },
      { id: 'kserve-control-plane', title: 'KServe Control Plane' },
      { id: 'kserve-data-plane', title: 'KServe Data Plane' },
      { id: 'kserve-predictors-and-explainers', title: 'Predictors & Explainers' },
      { id: 'kserve-modelmesh', title: 'KServe ModelMesh' },
      { id: 'kserve-canary', title: 'KServe Canary' },
      { id: 'kserve-llm-runtime', title: 'KServe LLM Runtime' },
    ],
  },
  {
    id: 'seldon-core',
    title: 'Seldon Core',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'seldon-core-overview', title: 'Seldon Core Overview' },
      { id: 'seldon-core-v2', title: 'Seldon Core v2' },
      { id: 'seldon-deployments', title: 'Seldon Deployments' },
      { id: 'seldon-mlflow-and-others', title: 'MLflow & Other Servers' },
    ],
  },
  {
    id: 'mlops-tools-on-k8s',
    title: 'MLOps Tools on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'bentoml-on-k8s', title: 'BentoML on K8s' },
      { id: 'mlflow-on-k8s', title: 'MLflow on K8s' },
      { id: 'clearml-on-k8s', title: 'ClearML on K8s' },
      { id: 'metaflow-on-k8s', title: 'Metaflow on K8s' },
      { id: 'flyte-on-k8s', title: 'Flyte on K8s' },
      { id: 'zenml-on-k8s', title: 'ZenML on K8s' },
    ],
  },
  {
    id: 'ray-on-kubernetes',
    title: 'Ray on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'kuberay-operator', title: 'KubeRay Operator' },
      { id: 'rayservice-resource', title: 'RayService' },
      { id: 'raycluster-resource', title: 'RayCluster' },
      { id: 'rayjob-resource', title: 'RayJob' },
      { id: 'ray-autoscaling', title: 'Ray Autoscaling' },
      { id: 'ray-gpu-and-multi-node', title: 'Ray GPU & Multi-Node' },
    ],
  },
  {
    id: 'distributed-training-on-k8s',
    title: 'Distributed Training on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'data-parallel-training', title: 'Data-Parallel Training' },
      { id: 'model-parallel-training', title: 'Model-Parallel Training' },
      { id: 'pipeline-parallel-training', title: 'Pipeline-Parallel Training' },
      { id: 'fsdp-and-deepspeed-on-k8s', title: 'FSDP & DeepSpeed on K8s' },
      { id: 'mpi-jobs-on-k8s', title: 'MPI Jobs on K8s' },
      { id: 'nccl-and-rdma-on-k8s', title: 'NCCL & RDMA on K8s' },
      { id: 'large-model-training-patterns', title: 'Large-Model Training Patterns' },
      { id: 'checkpointing-and-fault-tolerance-training', title: 'Checkpointing & Fault Tolerance' },
    ],
  },
  {
    id: 'llm-serving-on-kubernetes',
    title: 'LLM Serving on Kubernetes',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'vllm-on-k8s', title: 'vLLM on K8s' },
      { id: 'tgi-on-k8s', title: 'TGI on K8s' },
      { id: 'tensorrt-llm-on-k8s', title: 'TensorRT-LLM on K8s' },
      { id: 'llm-inference-gateway', title: 'LLM Inference Gateway (Gateway API extension)' },
      { id: 'kv-cache-on-k8s', title: 'KV Cache on K8s' },
      { id: 'autoscaling-llms-on-k8s', title: 'Autoscaling LLMs on K8s' },
      { id: 'llm-multi-tenancy', title: 'LLM Multi-Tenancy' },
    ],
  },
  {
    id: 'model-storage-and-registries',
    title: 'Model Storage & Registries',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'model-volume-strategies', title: 'Model Volume Strategies' },
      { id: 'oci-artifacts-for-models', title: 'OCI Artifacts for Models' },
      { id: 'huggingface-on-k8s-pointer', title: 'Hugging Face on K8s (Pointer)' },
      { id: 'cloud-model-registries-pointer', title: 'Cloud Model Registries (Pointer)' },
    ],
  },
  {
    id: 'ai-data-platforms-on-k8s',
    title: 'AI Data Platforms on K8s',
    parentId: 'ai-ml-on-kubernetes',
    children: [
      { id: 'feature-stores-on-k8s', title: 'Feature Stores on K8s' },
      { id: 'feast-on-k8s', title: 'Feast on K8s' },
      { id: 'vector-databases-on-k8s-pointer-stage20', title: 'Vector DBs on K8s (Pointer to Stage 14)' },
    ],
  },

  /* ---------- batch-hpc-workloads ---------- */
  {
    id: 'batch-on-k8s-overview',
    title: 'Batch on Kubernetes Overview',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'batch-vs-online-workloads', title: 'Batch vs Online Workloads' },
      { id: 'native-job-and-cronjob-pointer-stage20', title: 'Native Job & CronJob (Pointer to Stage 4)' },
      { id: 'batch-system-personas', title: 'Batch System Personas' },
      { id: 'why-k8s-for-batch', title: 'Why K8s for Batch?' },
    ],
  },
  {
    id: 'jobset-for-batch',
    title: 'JobSet for Batch',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'jobset-resource', title: 'JobSet Resource' },
      { id: 'jobset-operator', title: 'JobSet Operator' },
      { id: 'jobset-success-and-failure-policies', title: 'Success & Failure Policies' },
      { id: 'jobset-with-distributed-training', title: 'JobSet for Distributed Training' },
      { id: 'jobset-pointer-stage4', title: 'JobSet Basics (Pointer to Stage 4)' },
    ],
  },
  {
    id: 'kueue',
    title: 'Kueue',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'kueue-overview', title: 'Kueue Overview' },
      { id: 'kueue-architecture', title: 'Kueue Architecture' },
      { id: 'clusterqueue', title: 'ClusterQueue' },
      { id: 'localqueue', title: 'LocalQueue' },
      { id: 'resourceflavor', title: 'ResourceFlavor' },
      { id: 'workload-objects', title: 'Workload Objects' },
      { id: 'kueue-priority-and-preemption', title: 'Kueue Priority & Preemption' },
      { id: 'kueue-cohorts-and-borrowing', title: 'Cohorts & Borrowing' },
      { id: 'kueue-multi-tenancy', title: 'Kueue Multi-Tenancy' },
      { id: 'kueue-and-jobset-integration', title: 'Kueue + JobSet Integration' },
      { id: 'kueue-and-rayjob-integration', title: 'Kueue + RayJob Integration' },
      { id: 'kueue-fair-sharing', title: 'Kueue Fair Sharing' },
    ],
  },
  {
    id: 'volcano',
    title: 'Volcano',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'volcano-overview', title: 'Volcano Overview' },
      { id: 'volcano-scheduler-plugins', title: 'Volcano Scheduler Plugins' },
      { id: 'vc-job-resource', title: 'vc Job Resource' },
      { id: 'volcano-queue-and-podgroup', title: 'Queue & PodGroup' },
      { id: 'gang-scheduling-volcano', title: 'Gang Scheduling' },
      { id: 'fair-share-and-drf-volcano', title: 'Fair-Share & DRF' },
      { id: 'volcano-vs-kueue', title: 'Volcano vs Kueue' },
    ],
  },
  {
    id: 'yunikorn',
    title: 'YuniKorn',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'yunikorn-overview', title: 'YuniKorn Overview' },
      { id: 'yunikorn-architecture', title: 'YuniKorn Architecture' },
      { id: 'yunikorn-queues-and-policies', title: 'Queues & Policies' },
    ],
  },
  {
    id: 'workflow-engines-on-k8s',
    title: 'Workflow Engines on Kubernetes',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'argo-workflows', title: 'Argo Workflows' },
      { id: 'argo-workflows-overview', title: 'Argo Workflows Overview' },
      { id: 'workflow-resource', title: 'Workflow Resource' },
      { id: 'cronworkflow-resource', title: 'CronWorkflow Resource' },
      { id: 'dag-vs-steps-templates', title: 'DAG vs Steps Templates' },
      { id: 'argo-artifact-management', title: 'Artifact Management' },
      { id: 'workflow-of-workflows', title: 'Workflow of Workflows' },
      { id: 'argo-events', title: 'Argo Events' },
      { id: 'tekton-pipelines-pointer-stage20', title: 'Tekton Pipelines (Pointer)' },
      { id: 'prefect-on-k8s', title: 'Prefect on K8s' },
      { id: 'dagster-on-k8s-pointer', title: 'Dagster on K8s (Pointer)' },
    ],
  },
  {
    id: 'hpc-on-k8s',
    title: 'HPC on Kubernetes',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'mpi-jobs-on-k8s-pointer-stage20', title: 'MPI Jobs (Pointer)' },
      { id: 'slurm-on-k8s-bridges', title: 'Slurm-on-K8s Bridges' },
      { id: 'hpc-network-considerations', title: 'HPC Network Considerations' },
      { id: 'rdma-on-k8s', title: 'RDMA on K8s' },
      { id: 'openmpi-on-k8s', title: 'OpenMPI on K8s' },
      { id: 'gpudirect-and-nvlink-on-k8s', title: 'GPUDirect & NVLink on K8s' },
    ],
  },
  {
    id: 'batch-storage-patterns',
    title: 'Batch Storage Patterns',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'shared-filesystem-strategies', title: 'Shared Filesystem Strategies' },
      { id: 'object-storage-strategies', title: 'Object Storage Strategies' },
      { id: 'scratch-volumes', title: 'Scratch Volumes' },
      { id: 'data-locality-considerations-batch', title: 'Data Locality Considerations' },
    ],
  },
  {
    id: 'batch-cost-optimization',
    title: 'Batch Cost Optimization',
    parentId: 'batch-hpc-workloads',
    children: [
      { id: 'spot-instances-for-batch', title: 'Spot Instances for Batch' },
      { id: 'bin-packing-for-batch', title: 'Bin Packing for Batch' },
      { id: 'autoscaling-for-batch', title: 'Autoscaling for Batch' },
    ],
  },

  /* ---------- edge-iot-virtualization ---------- */
  {
    id: 'kubevirt',
    title: 'KubeVirt',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'kubevirt-overview', title: 'KubeVirt Overview' },
      { id: 'kubevirt-architecture', title: 'KubeVirt Architecture' },
      { id: 'virtualmachine-resource', title: 'VirtualMachine Resource' },
      { id: 'virtualmachineinstance-resource', title: 'VirtualMachineInstance Resource' },
      { id: 'kubevirt-vm-disks-and-storage', title: 'VM Disks & Storage' },
      { id: 'kubevirt-vm-networking', title: 'VM Networking' },
      { id: 'cdi-containerized-data-importer', title: 'CDI (Containerized Data Importer)' },
      { id: 'kubevirt-live-migration', title: 'Live Migration' },
      { id: 'kubevirt-hot-plug', title: 'Hot-Plug Resources' },
      { id: 'kubevirt-gpu-passthrough', title: 'GPU Passthrough' },
      { id: 'kubevirt-vs-vmware-pointer', title: 'KubeVirt vs VMware (Pointer)' },
    ],
  },
  {
    id: 'kata-containers',
    title: 'Kata Containers',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'kata-overview', title: 'Kata Overview' },
      { id: 'kata-architecture', title: 'Kata Architecture' },
      { id: 'kata-runtime-class', title: 'Kata RuntimeClass' },
      { id: 'kata-with-cri', title: 'Kata With CRI' },
      { id: 'kata-on-firecracker', title: 'Kata on Firecracker' },
      { id: 'kata-vs-runc', title: 'Kata vs runc' },
      { id: 'confidential-containers-with-kata', title: 'Confidential Containers with Kata' },
    ],
  },
  {
    id: 'gvisor',
    title: 'gVisor',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'gvisor-overview', title: 'gVisor Overview' },
      { id: 'gvisor-architecture', title: 'gVisor Architecture' },
      { id: 'gvisor-runtime-class', title: 'gVisor RuntimeClass' },
      { id: 'gvisor-vs-kata', title: 'gVisor vs Kata' },
    ],
  },
  {
    id: 'wasm-on-kubernetes',
    title: 'WebAssembly (Wasm) on Kubernetes',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'wasm-runtimes-on-k8s', title: 'Wasm Runtimes on K8s' },
      { id: 'runwasi-shim', title: 'runwasi Shim' },
      { id: 'spin-on-kubernetes', title: 'Spin on Kubernetes' },
      { id: 'wasmedge-on-k8s', title: 'WasmEdge on K8s' },
      { id: 'wasmtime-on-k8s', title: 'Wasmtime on K8s' },
      { id: 'wasm-runtime-class', title: 'Wasm RuntimeClass' },
      { id: 'wasm-vs-containers-tradeoffs', title: 'Wasm vs Containers Trade-offs' },
      { id: 'spinkube-pointer', title: 'SpinKube (Pointer)' },
    ],
  },
  {
    id: 'firecracker-and-microvms',
    title: 'Firecracker & MicroVMs',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'firecracker-on-k8s', title: 'Firecracker on K8s' },
      { id: 'microvm-runtime-classes', title: 'MicroVM RuntimeClasses' },
      { id: 'cloud-hypervisor-on-k8s', title: 'Cloud-Hypervisor on K8s' },
    ],
  },
  {
    id: 'iot-on-kubernetes',
    title: 'IoT on Kubernetes',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'iot-device-management-pointer', title: 'IoT Device Management (Pointer)' },
      { id: 'akri-pointer-stage20', title: 'Akri (Pointer to Stage 16)' },
      { id: 'kubeedge-iot-patterns-pointer', title: 'KubeEdge IoT Patterns (Pointer)' },
      { id: 'mqtt-brokers-on-k8s', title: 'MQTT Brokers on K8s' },
    ],
  },
  {
    id: 'specialised-runtimes-comparison',
    title: 'Specialised Runtimes Comparison',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'runc-vs-kata-vs-gvisor-vs-wasm', title: 'runc vs Kata vs gVisor vs Wasm' },
      { id: 'choosing-a-runtime', title: 'Choosing a Runtime' },
      { id: 'multiple-runtimes-on-one-cluster', title: 'Multiple Runtimes on One Cluster' },
    ],
  },
  {
    id: 'harvester-and-virt-platforms',
    title: 'Harvester & Virtualization Platforms',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'harvester-overview', title: 'Harvester Overview' },
      { id: 'harvester-vs-kubevirt', title: 'Harvester vs KubeVirt' },
      { id: 'rancher-virtualization-pointer', title: 'Rancher Virtualization (Pointer)' },
    ],
  },
  {
    id: 'confidential-containers',
    title: 'Confidential Containers',
    parentId: 'edge-iot-virtualization',
    children: [
      { id: 'coco-overview', title: 'CoCo Overview' },
      { id: 'tee-attestation-on-k8s', title: 'TEE Attestation on K8s' },
      { id: 'amd-sev-snp-and-intel-tdx-on-k8s', title: 'AMD SEV-SNP & Intel TDX on K8s' },
    ],
  },
])
