import { addTopics } from './addTopics.mjs'

// Stage 2 — Kubernetes Fundamentals
addTopics([
  /* ---------- what-is-kubernetes ---------- */
  {
    id: 'kubernetes-definition-goals',
    title: 'Kubernetes Definition & Goals',
    parentId: 'what-is-kubernetes',
    children: [
      { id: 'declarative-orchestration', title: 'Declarative Container Orchestration' },
      { id: 'desired-state-vs-actual-state', title: 'Desired State vs Actual State' },
      { id: 'portability-across-environments', title: 'Portability Across Environments' },
      { id: 'extensibility-as-a-platform', title: 'Extensibility as a Platform' },
    ],
  },
  {
    id: 'problems-kubernetes-solves',
    title: 'Problems Kubernetes Solves',
    parentId: 'what-is-kubernetes',
    children: [
      { id: 'service-discovery-load-balancing', title: 'Service Discovery & Load Balancing' },
      { id: 'automated-rollouts-rollbacks', title: 'Automated Rollouts & Rollbacks' },
      { id: 'self-healing', title: 'Self-Healing' },
      { id: 'storage-orchestration', title: 'Storage Orchestration' },
      { id: 'secret-and-config-management', title: 'Secret & Config Management' },
      { id: 'horizontal-scaling', title: 'Horizontal Scaling' },
      { id: 'resource-bin-packing', title: 'Resource Bin-Packing' },
      { id: 'workload-portability', title: 'Workload Portability' },
    ],
  },
  {
    id: 'what-kubernetes-is-not',
    title: 'What Kubernetes Is NOT',
    parentId: 'what-is-kubernetes',
    children: [
      { id: 'not-a-traditional-paas', title: 'Not a Traditional PaaS' },
      { id: 'not-a-ci-cd-system', title: 'Not a CI/CD System' },
      { id: 'not-a-monitoring-stack', title: 'Not a Monitoring Stack' },
      { id: 'no-built-in-app-services', title: 'No Built-In Application Services' },
      { id: 'no-source-of-truth-for-config', title: 'Not the Source of Truth for Config' },
    ],
  },
  {
    id: 'kubernetes-ecosystem-governance',
    title: 'Kubernetes Ecosystem & Governance',
    parentId: 'what-is-kubernetes',
    children: [
      { id: 'cncf-and-graduation', title: 'CNCF & Project Graduation' },
      { id: 'sig-and-wg-structure', title: 'SIGs & Working Groups' },
      { id: 'kep-process', title: 'Kubernetes Enhancement Proposals (KEPs)' },
      { id: 'release-team', title: 'The Release Team' },
      { id: 'steering-committee', title: 'Steering Committee' },
      { id: 'code-of-conduct', title: 'Code of Conduct & Community Norms' },
    ],
  },
  {
    id: 'alternatives-and-comparisons',
    title: 'Alternatives & Comparisons',
    parentId: 'what-is-kubernetes',
    children: [
      { id: 'nomad-compared', title: 'HashiCorp Nomad' },
      { id: 'docker-swarm-compared', title: 'Docker Swarm Compared' },
      { id: 'mesos-marathon-historical', title: 'Apache Mesos / Marathon (Historical)' },
      { id: 'aws-ecs-compared', title: 'AWS ECS Compared' },
      { id: 'serverless-platforms-compared', title: 'Serverless Platforms (Cloud Run, Fargate)' },
    ],
  },

  /* ---------- kubernetes-evolution ---------- */
  {
    id: 'kubernetes-history',
    title: 'Kubernetes History',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'borg-and-omega', title: 'Borg & Omega Origins' },
      { id: 'open-sourcing-2014', title: 'Open Sourcing in 2014' },
      { id: 'donation-to-cncf', title: 'Donation to CNCF (2015)' },
      { id: 'kubernetes-1-0', title: 'Kubernetes 1.0 (July 2015)' },
      { id: 'mesos-vs-swarm-vs-k8s-era', title: 'The Orchestration Wars' },
    ],
  },
  {
    id: 'release-cycle-cadence',
    title: 'Release Cycle & Cadence',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'three-releases-per-year', title: 'Three Releases per Year (KEP-3996)' },
      { id: 'release-team-roles', title: 'Release Team Roles' },
      { id: 'release-notes-changelog', title: 'Release Notes & CHANGELOG' },
      { id: 'patch-release-cadence', title: 'Patch Release Cadence' },
      { id: 'lts-discussions', title: 'LTS Discussions (Working Group)' },
    ],
  },
  {
    id: 'feature-lifecycle',
    title: 'Feature Lifecycle (Alpha → Beta → GA)',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'alpha-features', title: 'Alpha Features' },
      { id: 'beta-features', title: 'Beta Features' },
      { id: 'ga-stable-features', title: 'GA / Stable Features' },
      { id: 'feature-gates', title: 'Feature Gates' },
      { id: 'deprecation-policy', title: 'Deprecation Policy' },
      { id: 'opt-in-beta-policy', title: 'Opt-In Beta Policy (Post-1.24)' },
    ],
  },
  {
    id: 'version-skew-policy',
    title: 'Version Skew Policy',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'kube-apiserver-skew', title: 'kube-apiserver Skew Rules' },
      { id: 'kubelet-skew', title: 'kubelet Skew Rules' },
      { id: 'kube-controller-manager-skew', title: 'kube-controller-manager / scheduler Skew' },
      { id: 'kubectl-skew', title: 'kubectl Skew' },
      { id: 'control-plane-component-skew', title: 'Control-Plane Component Skew' },
    ],
  },
  {
    id: 'notable-versions',
    title: 'Notable Versions Through v1.36',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'v1-21-cronjob-ga', title: 'v1.21 — CronJob GA, PodDisruptionBudget GA' },
      { id: 'v1-22-api-removals', title: 'v1.22 — Major API Removals' },
      { id: 'v1-23-dual-stack-ga', title: 'v1.23 — IPv4/IPv6 Dual-Stack GA' },
      { id: 'v1-24-dockershim-removed', title: 'v1.24 — dockershim Removed' },
      { id: 'v1-25-pod-security-ga', title: 'v1.25 — PodSecurity GA, PSP Removed' },
      { id: 'v1-26-cri-v1-required', title: 'v1.26 — CRI v1 Required, DRA Alpha' },
      { id: 'v1-27-seccomp-default-ga', title: 'v1.27 — SeccompDefault GA' },
      { id: 'v1-28-sidecar-alpha', title: 'v1.28 — Sidecar Containers (Alpha)' },
      { id: 'v1-29-kms-v2-ga', title: 'v1.29 — KMS v2 GA' },
      { id: 'v1-30-vap-ga', title: 'v1.30 — ValidatingAdmissionPolicy GA, AppArmor GA' },
      { id: 'v1-31-nftables-beta', title: 'v1.31 — nftables Proxy (Beta), Image Volumes (Alpha)' },
      { id: 'v1-32-dra-redesign', title: 'v1.32 — DRA Redesign, Memory Manager GA' },
      { id: 'v1-33-sidecar-ga', title: 'v1.33 — Sidecar Containers GA' },
      { id: 'v1-34-features', title: 'v1.34 — Recent Stabilizations' },
      { id: 'v1-35-features', title: 'v1.35 — Recent Stabilizations' },
      { id: 'v1-36-features', title: 'v1.36 (April 2026) — Latest Stable' },
    ],
  },
  {
    id: 'supported-versions',
    title: 'Supported Versions',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'support-window', title: '~14-Month Support Window' },
      { id: 'patch-releases', title: 'Patch Releases' },
      { id: 'cve-and-security-patches', title: 'CVE & Security Patches' },
      { id: 'end-of-life-versions', title: 'End-of-Life Version Handling' },
    ],
  },
  {
    id: 'api-versioning',
    title: 'API Versioning',
    parentId: 'kubernetes-evolution',
    children: [
      { id: 'v1-vs-v1beta1-vs-v1alpha1', title: 'v1, v1beta1, v1alpha1 Conventions' },
      { id: 'api-deprecation-window', title: 'API Deprecation Window' },
      { id: 'api-removals', title: 'Notable API Group Removals' },
      { id: 'api-version-priority', title: 'API Version Priority' },
    ],
  },

  /* ---------- kubernetes-architecture ---------- */
  {
    id: 'declarative-model',
    title: 'Declarative Model',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'desired-state-spec', title: 'Desired State (.spec)' },
      { id: 'actual-state-status', title: 'Actual State (.status)' },
      { id: 'reconciliation-loops', title: 'Reconciliation Loops' },
      { id: 'level-triggered-design', title: 'Level-Triggered (vs Edge-Triggered) Design' },
      { id: 'imperative-vs-declarative', title: 'Imperative vs Declarative Commands' },
      { id: 'server-side-apply', title: 'Server-Side Apply' },
    ],
  },
  {
    id: 'control-plane-vs-data-plane',
    title: 'Control Plane vs Data Plane',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'control-plane-overview', title: 'Control Plane Overview' },
      { id: 'data-plane-overview', title: 'Data Plane (Worker Nodes) Overview' },
      { id: 'separation-of-concerns', title: 'Separation of Concerns' },
      { id: 'managed-control-plane-implications', title: 'Managed Control-Plane Implications' },
    ],
  },
  {
    id: 'master-and-worker-nodes',
    title: 'Master & Worker Nodes',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'master-node-historical-term', title: 'Master Node (Historical Term)' },
      { id: 'control-plane-nodes', title: 'Control Plane Nodes' },
      { id: 'worker-nodes', title: 'Worker Nodes' },
      { id: 'node-roles-and-labels', title: 'Node Roles & Labels' },
      { id: 'mixed-control-plane-data-plane', title: 'Mixed Control/Data Plane Nodes' },
    ],
  },
  {
    id: 'api-server-as-hub',
    title: 'API Server as the Hub',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'everything-talks-to-api-server', title: 'Everything Talks to API Server' },
      { id: 'api-server-as-watch-source', title: 'API Server as Watch Source' },
      { id: 'api-server-as-resource-store', title: 'API Server as Resource Store' },
      { id: 'kubernetes-api-as-contract', title: 'Kubernetes API as the Contract' },
    ],
  },
  {
    id: 'objects-and-resources',
    title: 'Kubernetes Objects & Resources',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'resource-vs-kind', title: 'Resource vs Kind' },
      { id: 'api-groups', title: 'API Groups' },
      { id: 'core-resources-overview', title: 'Core Resources at a Glance' },
      { id: 'object-metadata', title: 'Object Metadata (name, namespace, labels)' },
      { id: 'gvk-and-gvr', title: 'GVK and GVR Notation' },
      { id: 'short-names', title: 'Short Names (po, svc, deploy, ...)' },
    ],
  },
  {
    id: 'namespaces-overview',
    title: 'Namespaces Overview',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'default-system-namespaces', title: 'default, kube-system, kube-public, kube-node-lease' },
      { id: 'namespaced-vs-cluster-scoped', title: 'Namespaced vs Cluster-Scoped Resources' },
      { id: 'what-namespaces-isolate', title: "What Namespaces Do & Don't Isolate" },
      { id: 'namespace-templates-and-projects', title: 'Namespace Templates & Projects (Distributions)' },
    ],
  },
  {
    id: 'watch-and-informer-model',
    title: 'Watch & Informer Model',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'watch-api', title: 'Watch API' },
      { id: 'informer-and-cache', title: 'Informer & Local Cache' },
      { id: 'shared-informer-pattern', title: 'Shared Informer Pattern' },
      { id: 'list-watch-resync', title: 'List → Watch → Resync Pattern' },
      { id: 'resource-version-semantics', title: 'resourceVersion Semantics' },
    ],
  },
  {
    id: 'pod-creation-flow',
    title: 'End-to-End Pod Creation Flow',
    parentId: 'kubernetes-architecture',
    children: [
      { id: 'kubectl-apply-to-api-server', title: 'kubectl apply to API Server' },
      { id: 'admission-and-validation', title: 'Admission & Validation' },
      { id: 'persist-to-etcd', title: 'Persist to etcd' },
      { id: 'scheduler-watches-and-binds', title: 'Scheduler Watches & Binds' },
      { id: 'kubelet-picks-up-pod', title: 'kubelet Picks Up Pod' },
      { id: 'cri-creates-container', title: 'CRI Creates Container' },
      { id: 'cni-attaches-network', title: 'CNI Attaches Network' },
      { id: 'csi-mounts-volumes', title: 'CSI Mounts Volumes' },
      { id: 'status-reports-back', title: 'Status Reports Back via kubelet' },
    ],
  },
])
