import { addTopics } from './addTopics.mjs'

// Stage 9 — Control Plane & Cluster Internals
addTopics([
  /* ---------- control-plane-components ---------- */
  {
    id: 'kube-apiserver',
    title: 'kube-apiserver',
    parentId: 'control-plane-components',
    children: [
      { id: 'apiserver-overview', title: 'API Server Overview' },
      { id: 'apiserver-flags-and-config', title: 'API Server Flags & Config' },
      { id: 'apiserver-request-flow', title: 'Request Flow (Auth → Admission → Storage)' },
      { id: 'apiserver-storage-interface', title: 'Storage Interface (etcd)' },
      { id: 'apiserver-watch-cache', title: 'Watch Cache' },
      { id: 'apiserver-tls-and-certs', title: 'API Server TLS & Certificates' },
      { id: 'apiserver-priority-and-fairness', title: 'API Priority & Fairness (Pointer)' },
      { id: 'apiserver-audit-log', title: 'Audit Logging (Pointer)' },
      { id: 'apiserver-feature-gates', title: 'Feature Gates' },
      { id: 'apiserver-aggregation-layer', title: 'Aggregation Layer' },
      { id: 'apiserver-encryption-config', title: 'Encryption Config Wiring' },
      { id: 'apiserver-streaming-and-spdy', title: 'Streaming, SPDY & WebSocket' },
    ],
  },
  {
    id: 'kube-controller-manager',
    title: 'kube-controller-manager',
    parentId: 'control-plane-components',
    children: [
      { id: 'kcm-overview', title: 'kube-controller-manager Overview' },
      { id: 'kcm-built-in-controllers', title: 'Built-In Controllers' },
      { id: 'kcm-controller-list', title: 'Controller List (Node, Endpoint, Namespace, ...)' },
      { id: 'kcm-leader-election', title: 'Leader Election' },
      { id: 'kcm-feature-gates', title: 'Feature Gates' },
      { id: 'kcm-cloud-controller-separation', title: 'Cloud Controller Separation' },
    ],
  },
  {
    id: 'cloud-controller-manager',
    title: 'cloud-controller-manager',
    parentId: 'control-plane-components',
    children: [
      { id: 'ccm-overview', title: 'CCM Overview' },
      { id: 'ccm-node-controller', title: 'Cloud Node Controller' },
      { id: 'ccm-route-controller', title: 'Cloud Route Controller' },
      { id: 'ccm-service-controller', title: 'Cloud Service Controller' },
      { id: 'in-tree-cloud-provider-removal', title: 'In-Tree Cloud Provider Removal' },
      { id: 'cloud-providers-list', title: 'Cloud Provider Implementations' },
    ],
  },
  {
    id: 'kube-scheduler-component',
    title: 'kube-scheduler (Component View)',
    parentId: 'control-plane-components',
    children: [
      { id: 'scheduler-component-overview', title: 'Scheduler Component Overview (Pointer)' },
      { id: 'scheduler-leader-election', title: 'Scheduler Leader Election' },
      { id: 'scheduler-extenders-legacy', title: 'Scheduler Extenders (Legacy)' },
    ],
  },
  {
    id: 'coordinated-leader-election',
    title: 'Coordinated Leader Election',
    parentId: 'control-plane-components',
    children: [
      { id: 'leader-election-evolution', title: 'Leader Election Evolution' },
      { id: 'lease-resource', title: 'Lease Resource' },
      { id: 'coordinated-leader-election-kep', title: 'Coordinated Leader Election (KEP-4188)' },
    ],
  },
  {
    id: 'control-plane-ha',
    title: 'Control Plane High Availability',
    parentId: 'control-plane-components',
    children: [
      { id: 'stacked-vs-external-etcd', title: 'Stacked vs External etcd' },
      { id: 'control-plane-replication', title: 'Control Plane Replication' },
      { id: 'quorum-requirements', title: 'Quorum Requirements' },
      { id: 'control-plane-load-balancer', title: 'Control Plane Load Balancer' },
      { id: 'multi-zone-control-plane', title: 'Multi-Zone Control Plane' },
      { id: 'apiserver-bootstrap-and-recovery', title: 'API Server Bootstrap & Recovery' },
    ],
  },
  {
    id: 'konnectivity-server',
    title: 'Konnectivity',
    parentId: 'control-plane-components',
    children: [
      { id: 'konnectivity-overview', title: 'Konnectivity Overview' },
      { id: 'konnectivity-tunneling', title: 'Tunneling Control Plane → Nodes' },
      { id: 'konnectivity-vs-ssh-tunnels', title: 'Konnectivity vs Legacy SSH Tunnels' },
    ],
  },
  {
    id: 'metrics-server-and-resource-metrics',
    title: 'Metrics Server & Resource Metrics API',
    parentId: 'control-plane-components',
    children: [
      { id: 'metrics-server-overview', title: 'Metrics Server Overview' },
      { id: 'resource-metrics-api', title: 'Resource Metrics API' },
      { id: 'custom-metrics-api', title: 'Custom Metrics API' },
      { id: 'external-metrics-api', title: 'External Metrics API' },
    ],
  },

  /* ---------- node-internals ---------- */
  {
    id: 'kubelet-architecture',
    title: 'kubelet Architecture',
    parentId: 'node-internals',
    children: [
      { id: 'kubelet-overview', title: 'kubelet Overview' },
      { id: 'kubelet-config-resource', title: 'KubeletConfiguration Resource' },
      { id: 'kubelet-flags-vs-config', title: 'Flags vs Config File' },
      { id: 'kubelet-drop-in-config', title: 'Drop-In Config Files' },
      { id: 'kubelet-graceful-shutdown', title: 'kubelet Graceful Shutdown' },
      { id: 'kubelet-priority-shutdown', title: 'Priority-Based Shutdown' },
      { id: 'kubelet-pleg', title: 'PLEG (Pod Lifecycle Event Generator)' },
      { id: 'kubelet-evented-pleg', title: 'Evented PLEG' },
    ],
  },
  {
    id: 'pod-lifecycle-on-node',
    title: 'Pod Lifecycle on Node',
    parentId: 'node-internals',
    children: [
      { id: 'pod-sandbox-creation', title: 'Pod Sandbox Creation' },
      { id: 'cni-call-on-pod-network', title: 'CNI Call on Pod Network' },
      { id: 'csi-call-on-volume-mounts', title: 'CSI Call on Volume Mounts' },
      { id: 'container-creation-via-cri', title: 'Container Creation via CRI' },
      { id: 'container-start-stop', title: 'Container Start/Stop' },
      { id: 'status-reporting', title: 'Status Reporting Back to API Server' },
      { id: 'pod-cleanup-on-deletion', title: 'Pod Cleanup on Deletion' },
    ],
  },
  {
    id: 'cri-runtime-side',
    title: 'CRI (Runtime-Side View)',
    parentId: 'node-internals',
    children: [
      { id: 'cri-grpc-streams', title: 'CRI gRPC Streams' },
      { id: 'container-and-podsandbox', title: 'Container vs PodSandbox APIs' },
      { id: 'cri-streaming-server', title: 'CRI Streaming Server (exec, attach, port-forward)' },
      { id: 'cri-stats-api', title: 'CRI Stats API' },
    ],
  },
  {
    id: 'kubelet-storage',
    title: 'kubelet Storage',
    parentId: 'node-internals',
    children: [
      { id: 'volume-manager-component', title: 'Volume Manager Component' },
      { id: 'mount-and-attach-controllers', title: 'Mount & Attach Controllers' },
      { id: 'subpath-handling', title: 'subPath Handling' },
      { id: 'volume-reconstruction-on-restart', title: 'Volume Reconstruction on Restart' },
    ],
  },
  {
    id: 'kubelet-networking',
    title: 'kubelet Networking',
    parentId: 'node-internals',
    children: [
      { id: 'cni-bin-and-conf-dirs', title: 'CNI bin & conf Directories' },
      { id: 'cni-plugin-execution', title: 'CNI Plugin Execution' },
      { id: 'kubelet-and-network-namespaces', title: 'kubelet & Network Namespaces' },
      { id: 'kubelet-iptables-rules', title: 'kubelet iptables Rules' },
    ],
  },
  {
    id: 'kube-proxy-component',
    title: 'kube-proxy (Component View)',
    parentId: 'node-internals',
    children: [
      { id: 'kube-proxy-overview-component', title: 'kube-proxy Overview' },
      { id: 'kube-proxy-modes-pointer', title: 'kube-proxy Modes (Pointer)' },
      { id: 'kube-proxy-as-daemonset-pointer', title: 'kube-proxy as DaemonSet (Pointer)' },
      { id: 'kube-proxy-watchers', title: 'Service & EndpointSlice Watchers' },
    ],
  },
  {
    id: 'node-status',
    title: 'Node Status',
    parentId: 'node-internals',
    children: [
      { id: 'node-conditions', title: 'Node Conditions' },
      { id: 'node-heartbeats', title: 'Node Heartbeats' },
      { id: 'node-lease', title: 'Node Lease' },
      { id: 'node-readiness', title: 'Node Readiness' },
      { id: 'node-allocatable', title: 'Node Allocatable' },
      { id: 'node-system-info', title: 'Node System Info Fields' },
    ],
  },
  {
    id: 'node-shutdown-handling',
    title: 'Node Shutdown Handling',
    parentId: 'node-internals',
    children: [
      { id: 'graceful-node-shutdown', title: 'Graceful Node Shutdown' },
      { id: 'non-graceful-node-shutdown', title: 'Non-Graceful Node Shutdown' },
      { id: 'shutdown-grace-period', title: 'Shutdown Grace Period' },
      { id: 'critical-pods-priority-on-shutdown', title: 'Critical Pods Priority on Shutdown' },
    ],
  },
  {
    id: 'node-garbage-collection',
    title: 'Node Garbage Collection',
    parentId: 'node-internals',
    children: [
      { id: 'image-garbage-collection-deep', title: 'Image Garbage Collection (Deep)' },
      { id: 'container-garbage-collection', title: 'Container Garbage Collection' },
      { id: 'log-rotation', title: 'Log Rotation' },
      { id: 'gc-thresholds', title: 'GC Thresholds' },
    ],
  },
  {
    id: 'kubelet-authn-authz',
    title: 'kubelet Authentication & Authorization',
    parentId: 'node-internals',
    children: [
      { id: 'kubelet-x509-client-cert', title: 'X.509 Client Cert Auth' },
      { id: 'kubelet-bearer-token', title: 'Bearer Token Auth' },
      { id: 'kubelet-anonymous-requests', title: 'Anonymous Requests' },
      { id: 'kubelet-authz-modes', title: 'Authorization Modes (AlwaysAllow, Webhook)' },
      { id: 'kubelet-csr-bootstrap', title: 'CSR Bootstrap' },
    ],
  },
  {
    id: 'kubelet-credential-providers',
    title: 'kubelet Credential Providers',
    parentId: 'node-internals',
    children: [
      { id: 'credential-provider-config', title: 'CredentialProviderConfig' },
      { id: 'exec-credential-providers', title: 'Exec Credential Providers' },
      { id: 'cloud-provider-image-creds', title: 'Cloud Provider Image Credentials' },
    ],
  },
  {
    id: 'kubelet-metrics-and-stats',
    title: 'kubelet Metrics & Stats',
    parentId: 'node-internals',
    children: [
      { id: 'kubelet-stats-summary-api', title: 'Kubelet /stats/summary API' },
      { id: 'cadvisor-integration', title: 'cAdvisor Integration' },
      { id: 'kubelet-prometheus-metrics', title: 'kubelet Prometheus Metrics' },
    ],
  },

  /* ---------- etcd-internals ---------- */
  {
    id: 'etcd-overview',
    title: 'etcd Overview',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-purpose-in-k8s', title: 'etcd Purpose in Kubernetes' },
      { id: 'etcd-data-model', title: 'etcd Data Model' },
      { id: 'etcd-vs-other-kv-stores', title: 'etcd vs Other KV Stores' },
      { id: 'etcd-deployment-shapes', title: 'Deployment Shapes (Embedded, External)' },
    ],
  },
  {
    id: 'etcd-architecture',
    title: 'etcd Architecture',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-cluster-topology', title: 'Cluster Topology' },
      { id: 'quorum-and-odd-numbers', title: 'Quorum & Odd Numbers' },
      { id: 'voting-vs-learner-members', title: 'Voting vs Learner Members' },
      { id: 'etcd-grpc-api', title: 'etcd gRPC API' },
    ],
  },
  {
    id: 'raft-consensus',
    title: 'Raft Consensus',
    parentId: 'etcd-internals',
    children: [
      { id: 'raft-leader-election', title: 'Raft Leader Election' },
      { id: 'raft-log-replication', title: 'Raft Log Replication' },
      { id: 'raft-membership-changes', title: 'Membership Changes' },
      { id: 'raft-vs-paxos', title: 'Raft vs Paxos' },
      { id: 'raft-safety-and-liveness', title: 'Safety & Liveness Properties' },
    ],
  },
  {
    id: 'etcd-data-storage',
    title: 'etcd Data Storage',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-storage-engine-bbolt', title: 'Storage Engine (bbolt)' },
      { id: 'revisions-and-mvcc', title: 'Revisions & MVCC' },
      { id: 'compaction', title: 'Compaction' },
      { id: 'defragmentation', title: 'Defragmentation' },
      { id: 'quota-backend-bytes', title: 'quota-backend-bytes' },
    ],
  },
  {
    id: 'etcd-watch',
    title: 'etcd Watch',
    parentId: 'etcd-internals',
    children: [
      { id: 'watch-stream', title: 'Watch Stream' },
      { id: 'watch-progress-notifications', title: 'Watch Progress Notifications' },
      { id: 'watch-fragmentation', title: 'Watch Fragmentation' },
      { id: 'watch-cache-vs-direct-watch', title: 'Watch Cache vs Direct Watch' },
    ],
  },
  {
    id: 'etcd-performance',
    title: 'etcd Performance',
    parentId: 'etcd-internals',
    children: [
      { id: 'disk-iops-requirements', title: 'Disk IOPS Requirements' },
      { id: 'latency-considerations', title: 'Latency Considerations' },
      { id: 'fio-benchmarks', title: 'fio Benchmarks for etcd' },
      { id: 'sized-cluster-recommendations', title: 'Sized Cluster Recommendations' },
    ],
  },
  {
    id: 'etcd-security',
    title: 'etcd Security',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-tls-server-certs', title: 'etcd Server TLS Certs' },
      { id: 'etcd-peer-tls', title: 'Peer TLS' },
      { id: 'etcd-client-auth', title: 'Client Authentication' },
      { id: 'etcd-rbac-internal', title: 'etcd Role-Based Access (Internal)' },
      { id: 'etcd-encryption-at-rest', title: 'etcd Encryption at Rest' },
    ],
  },
  {
    id: 'etcd-backup-restore',
    title: 'etcd Backup & Restore',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcdctl-snapshot-save', title: 'etcdctl snapshot save' },
      { id: 'etcdctl-snapshot-restore', title: 'etcdctl snapshot restore' },
      { id: 'point-in-time-snapshots', title: 'Point-in-Time Snapshots' },
      { id: 'automated-backup-strategies-etcd', title: 'Automated Backup Strategies' },
      { id: 'velero-vs-etcd-snapshot', title: 'Velero vs etcd Snapshot' },
      { id: 'restoring-after-quorum-loss', title: 'Restoring After Quorum Loss' },
    ],
  },
  {
    id: 'etcd-upgrades',
    title: 'etcd Upgrades',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-upgrade-paths', title: 'Upgrade Paths' },
      { id: 'rolling-etcd-upgrades', title: 'Rolling etcd Upgrades' },
      { id: 'rollback-considerations-etcd', title: 'Rollback Considerations' },
    ],
  },
  {
    id: 'etcd-observability',
    title: 'etcd Observability',
    parentId: 'etcd-internals',
    children: [
      { id: 'etcd-metrics', title: 'etcd Metrics' },
      { id: 'etcd-events-stream', title: 'etcd Events Stream' },
      { id: 'prometheus-scraping-etcd', title: 'Prometheus Scraping etcd' },
      { id: 'etcd-alerts', title: 'etcd Alerts' },
    ],
  },
  {
    id: 'external-vs-stacked-etcd',
    title: 'External vs Stacked etcd',
    parentId: 'etcd-internals',
    children: [
      { id: 'external-etcd-cluster', title: 'External etcd Cluster' },
      { id: 'stacked-etcd-with-kubeadm', title: 'Stacked etcd with kubeadm' },
      { id: 'migrating-stacked-to-external', title: 'Migrating Stacked → External' },
    ],
  },
  {
    id: 'etcd-tuning',
    title: 'etcd Tuning',
    parentId: 'etcd-internals',
    children: [
      { id: 'heartbeat-and-election-timeouts', title: 'Heartbeat & Election Timeouts' },
      { id: 'storage-quota-tuning', title: 'Storage Quota Tuning' },
      { id: 'auto-compaction', title: 'Auto-Compaction' },
      { id: 'separating-events-etcd', title: 'Separate events etcd Cluster' },
    ],
  },
])
