import { addTopics } from './addTopics.mjs'

// Stage 8 — Scheduling & Resource Management
addTopics([
  /* ---------- scheduling-fundamentals ---------- */
  {
    id: 'scheduler-overview',
    title: 'Scheduler Overview',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'kube-scheduler-purpose', title: 'kube-scheduler Purpose' },
      { id: 'scheduling-cycle', title: 'Scheduling Cycle' },
      { id: 'binding-cycle', title: 'Binding Cycle' },
      { id: 'scheduling-vs-preemption', title: 'Scheduling vs Preemption' },
      { id: 'scheduler-as-controller', title: 'Scheduler as a Controller' },
    ],
  },
  {
    id: 'nodeselector',
    title: 'nodeSelector',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'nodeselector-basics', title: 'nodeSelector Basics' },
      { id: 'well-known-node-labels', title: 'Well-Known Node Labels' },
      { id: 'nodeselector-vs-affinity', title: 'nodeSelector vs Node Affinity' },
    ],
  },
  {
    id: 'node-affinity-basics',
    title: 'Node Affinity (Basics)',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'required-during-scheduling', title: 'requiredDuringSchedulingIgnoredDuringExecution' },
      { id: 'preferred-during-scheduling', title: 'preferredDuringSchedulingIgnoredDuringExecution' },
      { id: 'node-affinity-anti-affinity', title: 'Node Affinity vs Anti-Affinity' },
    ],
  },
  {
    id: 'pod-affinity-basics',
    title: 'Pod Affinity (Basics)',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'co-locating-pods', title: 'Co-Locating Pods' },
      { id: 'spreading-pods-with-anti-affinity', title: 'Spreading with Anti-Affinity' },
      { id: 'topology-key', title: 'topologyKey' },
      { id: 'mismatchlabelkeys', title: 'mismatchLabelKeys (KEP-3633)' },
    ],
  },
  {
    id: 'taints-and-tolerations-basics',
    title: 'Taints & Tolerations (Basics)',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'taint-effect-noschedule', title: 'Effect: NoSchedule' },
      { id: 'taint-effect-prefernoschedule', title: 'Effect: PreferNoSchedule' },
      { id: 'taint-effect-noexecute', title: 'Effect: NoExecute' },
      { id: 'toleration-operator-equal-exists', title: 'Toleration Operator: Equal vs Exists' },
      { id: 'well-known-taints', title: 'Well-Known Taints' },
    ],
  },
  {
    id: 'scheduling-flow',
    title: 'Scheduling Flow',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'filter-phase', title: 'Filter Phase' },
      { id: 'score-phase', title: 'Score Phase' },
      { id: 'reserve-phase', title: 'Reserve Phase' },
      { id: 'permit-phase', title: 'Permit Phase' },
      { id: 'prebind-phase', title: 'PreBind Phase' },
      { id: 'bind-phase', title: 'Bind Phase' },
      { id: 'assume-and-cache-update', title: 'Assume & Cache Update' },
      { id: 'fit-error-handling', title: 'Fit Error Handling' },
    ],
  },
  {
    id: 'priorityclass-and-preemption',
    title: 'PriorityClass & Preemption',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'priorityclass-resource', title: 'PriorityClass Resource' },
      { id: 'system-priorityclasses', title: 'System PriorityClasses' },
      { id: 'non-preempting-priorityclass', title: 'Non-Preempting PriorityClass' },
      { id: 'preemption-process', title: 'Preemption Process' },
      { id: 'graceful-termination-on-preemption', title: 'Graceful Termination on Preemption' },
      { id: 'preemption-policy-field', title: 'preemptionPolicy Field' },
    ],
  },
  {
    id: 'nominatednodename',
    title: 'nominatedNodeName',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'nominatednodename-purpose', title: 'nominatedNodeName Purpose' },
      { id: 'nnn-and-preemption', title: 'NNN & Preemption Flow' },
    ],
  },
  {
    id: 'scheduler-configuration',
    title: 'Scheduler Configuration',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'kubeschedulerconfiguration', title: 'KubeSchedulerConfiguration' },
      { id: 'scheduler-profiles', title: 'Scheduler Profiles' },
      { id: 'scheduling-plugins-config', title: 'Scheduling Plugins Configuration' },
      { id: 'default-plugins-list', title: 'Default Plugins List' },
      { id: 'multiple-profiles-per-scheduler', title: 'Multiple Profiles per Scheduler' },
    ],
  },
  {
    id: 'pod-scheduling-readiness',
    title: 'Pod Scheduling Readiness',
    parentId: 'scheduling-fundamentals',
    children: [
      { id: 'scheduling-gates-field', title: 'schedulingGates Field' },
      { id: 'scheduling-gate-controllers', title: 'Scheduling Gate Controllers' },
      { id: 'workload-batching-via-gates', title: 'Workload Batching via Gates' },
    ],
  },

  /* ---------- resource-management ---------- */
  {
    id: 'requests-and-limits',
    title: 'Requests & Limits',
    parentId: 'resource-management',
    children: [
      { id: 'cpu-requests-limits', title: 'CPU Requests & Limits' },
      { id: 'memory-requests-limits', title: 'Memory Requests & Limits' },
      { id: 'hugepages-as-resource', title: 'HugePages as a Resource' },
      { id: 'ephemeral-storage-requests-limits', title: 'Ephemeral Storage Requests & Limits' },
      { id: 'requests-without-limits-pattern', title: 'Requests-Without-Limits Pattern' },
      { id: 'cpu-units-and-millicores', title: 'CPU Units & Millicores' },
      { id: 'memory-units', title: 'Memory Units (Mi, Gi)' },
    ],
  },
  {
    id: 'qos-classes',
    title: 'QoS Classes',
    parentId: 'resource-management',
    children: [
      { id: 'qos-guaranteed', title: 'Guaranteed' },
      { id: 'qos-burstable', title: 'Burstable' },
      { id: 'qos-besteffort', title: 'BestEffort' },
      { id: 'qos-impact-on-eviction', title: 'QoS Impact on Eviction' },
      { id: 'qos-impact-on-oom-score', title: 'QoS Impact on OOM Score' },
    ],
  },
  {
    id: 'cpu-and-memory-runtime-behaviour',
    title: 'CPU & Memory Runtime Behaviour',
    parentId: 'resource-management',
    children: [
      { id: 'cpu-throttling', title: 'CPU Throttling' },
      { id: 'memory-oom-killer', title: 'Memory & OOM Killer' },
      { id: 'memory-pressure-conditions', title: 'Memory Pressure Conditions' },
      { id: 'pid-limits-on-pods', title: 'PID Limits on Pods' },
    ],
  },
  {
    id: 'resource-quotas',
    title: 'ResourceQuotas',
    parentId: 'resource-management',
    children: [
      { id: 'resourcequota-overview', title: 'ResourceQuota Overview' },
      { id: 'compute-resource-quotas', title: 'Compute Resource Quotas' },
      { id: 'storage-resource-quotas', title: 'Storage Resource Quotas' },
      { id: 'object-count-quotas', title: 'Object Count Quotas' },
      { id: 'extended-resource-quotas', title: 'Extended Resource Quotas' },
      { id: 'quota-scopes', title: 'Quota Scopes (Terminating, BestEffort, etc.)' },
      { id: 'quota-scope-selectors', title: 'Scope Selectors' },
      { id: 'cross-namespace-pod-affinity-quota', title: 'CrossNamespacePodAffinity Quota' },
    ],
  },
  {
    id: 'limit-ranges',
    title: 'LimitRanges',
    parentId: 'resource-management',
    children: [
      { id: 'limitrange-overview', title: 'LimitRange Overview' },
      { id: 'default-requests-limits', title: 'Default Requests & Limits' },
      { id: 'min-max-limits', title: 'Min / Max Limits' },
      { id: 'maxLimitRequestRatio', title: 'maxLimitRequestRatio' },
      { id: 'limit-range-types', title: 'LimitRange Types (Container, Pod, PVC)' },
    ],
  },
  {
    id: 'extended-resources',
    title: 'Extended Resources',
    parentId: 'resource-management',
    children: [
      { id: 'extended-resource-overview', title: 'Extended Resource Overview' },
      { id: 'node-level-extended-resources', title: 'Node-Level Extended Resources' },
      { id: 'cluster-level-extended-resources', title: 'Cluster-Level Extended Resources' },
      { id: 'device-plugins-and-extended-resources', title: 'Device Plugins & Extended Resources' },
    ],
  },
  {
    id: 'pod-overhead',
    title: 'Pod Overhead',
    parentId: 'resource-management',
    children: [
      { id: 'overhead-from-runtimeclass', title: 'Overhead from RuntimeClass' },
      { id: 'overhead-and-quotas', title: 'Overhead & Quotas' },
      { id: 'overhead-and-scheduling', title: 'Overhead & Scheduling' },
    ],
  },
  {
    id: 'eviction-and-pressure',
    title: 'Eviction & Pressure',
    parentId: 'resource-management',
    children: [
      { id: 'soft-eviction-thresholds', title: 'Soft Eviction Thresholds' },
      { id: 'hard-eviction-thresholds', title: 'Hard Eviction Thresholds' },
      { id: 'kubelet-eviction-flow', title: 'Kubelet Eviction Flow' },
      { id: 'eviction-signals', title: 'Eviction Signals' },
      { id: 'eviction-vs-preemption', title: 'Eviction vs Preemption' },
      { id: 'api-initiated-eviction', title: 'API-Initiated Eviction' },
    ],
  },
  {
    id: 'in-place-resize-resource-aspect',
    title: 'In-Place Resize (Resource Aspect)',
    parentId: 'resource-management',
    children: [
      { id: 'in-place-resize-resource-overview', title: 'Resource View of In-Place Resize' },
      { id: 'in-place-resize-allocatable', title: 'Allocatable Tracking on Resize' },
    ],
  },

  /* ---------- advanced-scheduling ---------- */
  {
    id: 'topology-spread-constraints',
    title: 'Topology Spread Constraints',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'topology-spread-mechanics', title: 'Topology Spread Mechanics' },
      { id: 'whenunsatisfiable', title: 'whenUnsatisfiable' },
      { id: 'matchlabelkeys-tsc', title: 'matchLabelKeys' },
      { id: 'nodeaffinitypolicy-tsc', title: 'nodeAffinityPolicy' },
      { id: 'nodetaintspolicy-tsc', title: 'nodeTaintsPolicy' },
      { id: 'mindomains', title: 'minDomains' },
      { id: 'cluster-default-tsc', title: 'Cluster-Default Constraints' },
    ],
  },
  {
    id: 'node-affinity-deep',
    title: 'Node Affinity Deep Dive',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'node-affinity-weighting', title: 'Node Affinity Weighting' },
      { id: 'matchexpressions-vs-matchfields', title: 'matchExpressions vs matchFields' },
      { id: 'multiple-node-affinity-rules', title: 'Multiple Node Affinity Rules' },
      { id: 'node-affinity-with-anti-affinity-combinations', title: 'Affinity + Anti-Affinity Combinations' },
    ],
  },
  {
    id: 'inter-pod-affinity-deep',
    title: 'Inter-Pod Affinity Deep Dive',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'co-located-services-deep', title: 'Co-Located Services' },
      { id: 'anti-affinity-spread-deep', title: 'Anti-Affinity Spread' },
      { id: 'pod-affinity-performance', title: 'Pod-Affinity Performance Considerations' },
      { id: 'namespaceselector-pod-affinity', title: 'namespaceSelector on Pod Affinity' },
    ],
  },
  {
    id: 'taints-tolerations-advanced',
    title: 'Taints & Tolerations Advanced',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'noexecute-with-tolerationseconds', title: 'NoExecute with tolerationSeconds' },
      { id: 'taint-based-evictions', title: 'Taint-Based Evictions' },
      { id: 'condition-based-taints', title: 'Condition-Based Taints' },
      { id: 'taints-from-cloud-provider', title: 'Cloud-Provider Taints' },
    ],
  },
  {
    id: 'multiple-schedulers',
    title: 'Multiple Schedulers',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'schedulername-field', title: 'schedulerName Field on Pods' },
      { id: 'running-multiple-schedulers', title: 'Running Multiple Schedulers' },
      { id: 'scheduler-leader-election', title: 'Scheduler Leader Election' },
    ],
  },
  {
    id: 'custom-schedulers',
    title: 'Custom Schedulers',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'building-a-custom-scheduler', title: 'Building a Custom Scheduler' },
      { id: 'scheduling-framework', title: 'Scheduling Framework' },
      { id: 'extension-points', title: 'Extension Points (PreFilter, Filter, Score, ...)' },
      { id: 'using-scheduler-plugins-sdk', title: 'Using Scheduler Plugins SDK' },
    ],
  },
  {
    id: 'kubernetes-sigs-scheduler-plugins',
    title: 'kubernetes-sigs/scheduler-plugins',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'coscheduling-plugin', title: 'Coscheduling Plugin' },
      { id: 'capacity-scheduling-plugin', title: 'Capacity Scheduling' },
      { id: 'node-resource-topology-plugin', title: 'Node Resource Topology' },
      { id: 'real-load-aware-scheduling', title: 'Real Load Aware Scheduling (Trimaran)' },
      { id: 'network-aware-scheduling', title: 'Network-Aware Scheduling' },
      { id: 'sysched-plugin', title: 'SySched (Syscall-Aware) Plugin' },
    ],
  },
  {
    id: 'gang-scheduling',
    title: 'Gang Scheduling',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'gang-scheduling-need', title: 'Why Gang Scheduling?' },
      { id: 'volcano-gang-scheduling-pointer', title: 'Volcano Gang Scheduling (Pointer)' },
      { id: 'kueue-gang-scheduling-pointer', title: 'Kueue Gang Scheduling (Pointer)' },
      { id: 'coscheduling-vs-gang', title: 'Coscheduling vs Gang Scheduling' },
    ],
  },
  {
    id: 'descheduler',
    title: 'Descheduler',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'descheduler-overview', title: 'Descheduler Overview' },
      { id: 'descheduler-strategies', title: 'Descheduler Strategies' },
      { id: 'remove-duplicates', title: 'RemoveDuplicates' },
      { id: 'low-node-utilization', title: 'LowNodeUtilization' },
      { id: 'high-node-utilization', title: 'HighNodeUtilization' },
      { id: 'remove-pods-violating-node-affinity', title: 'RemovePodsViolatingNodeAffinity' },
      { id: 'remove-pods-violating-interpod-anti-affinity', title: 'RemovePodsViolatingInterPodAntiAffinity' },
      { id: 'remove-pods-violating-topology-spread', title: 'RemovePodsViolatingTopologySpreadConstraint' },
      { id: 'remove-pods-having-too-many-restarts', title: 'RemovePodsHavingTooManyRestarts' },
      { id: 'descheduler-as-controller', title: 'Descheduler as Controller (Continuous Mode)' },
    ],
  },
  {
    id: 'node-resource-management-advanced',
    title: 'Node Resource Management (Advanced)',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'cpu-manager-policies', title: 'CPU Manager Policies (none, static)' },
      { id: 'memory-manager', title: 'Memory Manager' },
      { id: 'topology-manager', title: 'Topology Manager' },
      { id: 'topology-manager-policies', title: 'Topology Manager Policies' },
      { id: 'device-manager', title: 'Device Manager' },
      { id: 'cpu-pinning', title: 'CPU Pinning' },
      { id: 'reserved-cpus', title: 'Reserved CPUs' },
    ],
  },
  {
    id: 'dynamic-resource-allocation',
    title: 'Dynamic Resource Allocation (DRA)',
    parentId: 'advanced-scheduling',
    children: [
      { id: 'dra-overview', title: 'DRA Overview (KEP-3063)' },
      { id: 'resourceclaim-resource', title: 'ResourceClaim Resource' },
      { id: 'resourceclaimtemplate', title: 'ResourceClaimTemplate' },
      { id: 'deviceclass-resource', title: 'DeviceClass Resource' },
      { id: 'resourceslice-resource', title: 'ResourceSlice Resource' },
      { id: 'dra-driver-development', title: 'DRA Driver Development' },
      { id: 'dra-vs-extended-resources', title: 'DRA vs Extended Resources' },
      { id: 'dra-vs-device-plugins', title: 'DRA vs Device Plugins' },
      { id: 'structured-parameters-dra', title: 'Structured Parameters in DRA' },
      { id: 'partitionable-devices', title: 'Partitionable Devices' },
    ],
  },
])
