import { addTopics } from './addTopics.mjs'

// Stage 4 — Workloads & Pods
addTopics([
  /* ---------- pod-fundamentals ---------- */
  {
    id: 'pod-basics',
    title: 'Pod Basics',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'pod-definition', title: 'Pod Definition' },
      { id: 'pod-vs-container', title: 'Pod vs Container' },
      { id: 'one-process-per-container', title: 'One Process per Container Convention' },
      { id: 'pod-as-atomic-unit', title: 'Pod as Atomic Scheduling Unit' },
      { id: 'static-pods', title: 'Static Pods' },
      { id: 'mirror-pods', title: 'Mirror Pods' },
    ],
  },
  {
    id: 'pod-lifecycle',
    title: 'Pod Lifecycle',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'pod-phases', title: 'Pod Phases (Pending, Running, Succeeded, Failed, Unknown)' },
      { id: 'pod-conditions', title: 'Pod Conditions (PodScheduled, Initialized, ContainersReady, Ready)' },
      { id: 'container-states', title: 'Container States (Waiting, Running, Terminated)' },
      { id: 'pod-termination-flow', title: 'Pod Termination Flow' },
      { id: 'pod-restart-policy', title: 'restartPolicy (Always, OnFailure, Never)' },
      { id: 'restart-policy-per-container', title: 'restartPolicy per Container (KEP-3676)' },
      { id: 'graceful-termination-period', title: 'Graceful Termination Period' },
      { id: 'pod-readiness-gates', title: 'Pod Readiness Gates' },
    ],
  },
  {
    id: 'multi-container-pods',
    title: 'Multi-Container Pods',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'sidecar-pattern', title: 'Sidecar Pattern' },
      { id: 'native-sidecar-containers', title: 'Native Sidecar Containers (KEP-753, GA v1.33)' },
      { id: 'ambassador-pattern', title: 'Ambassador Pattern' },
      { id: 'adapter-pattern', title: 'Adapter Pattern' },
      { id: 'shared-volumes-between-containers', title: 'Shared Volumes Between Containers' },
      { id: 'shared-process-namespace', title: 'Shared Process Namespace' },
      { id: 'shared-network-namespace', title: 'Shared Network Namespace' },
    ],
  },
  {
    id: 'init-containers',
    title: 'Init Containers',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'init-container-purpose', title: 'Init Container Purpose' },
      { id: 'init-container-execution-order', title: 'Execution Order' },
      { id: 'init-vs-sidecar', title: 'Init vs Native Sidecar' },
      { id: 'init-container-failures', title: 'Init Container Failures & Restarts' },
      { id: 'init-container-resource-handling', title: 'Init Container Resource Handling' },
    ],
  },
  {
    id: 'pod-probes',
    title: 'Pod Probes',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'liveness-probe', title: 'Liveness Probe' },
      { id: 'readiness-probe', title: 'Readiness Probe' },
      { id: 'startup-probe', title: 'Startup Probe' },
      { id: 'probe-action-httpget', title: 'httpGet Probe' },
      { id: 'probe-action-tcpsocket', title: 'tcpSocket Probe' },
      { id: 'probe-action-exec', title: 'exec Probe' },
      { id: 'probe-action-grpc', title: 'gRPC Probe (GA v1.27)' },
      { id: 'probe-tuning', title: 'Probe Tuning (delays, periods, thresholds)' },
      { id: 'probe-anti-patterns', title: 'Probe Anti-Patterns' },
    ],
  },
  {
    id: 'container-lifecycle-hooks',
    title: 'Container Lifecycle Hooks',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'poststart-hook', title: 'postStart Hook' },
      { id: 'prestop-hook', title: 'preStop Hook' },
      { id: 'hook-handler-exec', title: 'exec Handler' },
      { id: 'hook-handler-httpget', title: 'httpGet Handler' },
      { id: 'hook-handler-sleep', title: 'sleep Handler (KEP-3960)' },
      { id: 'hook-failure-handling', title: 'Hook Failure Handling' },
    ],
  },
  {
    id: 'pod-security-context',
    title: 'Pod Security Context',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'pod-level-securitycontext', title: 'Pod-Level securityContext' },
      { id: 'container-level-securitycontext', title: 'Container-Level securityContext' },
      { id: 'runasuser-runasgroup', title: 'runAsUser / runAsGroup' },
      { id: 'fsgroup-and-fsgroupchangepolicy', title: 'fsGroup & fsGroupChangePolicy' },
      { id: 'readonlyrootfilesystem', title: 'readOnlyRootFilesystem' },
      { id: 'privileged-vs-unprivileged', title: 'Privileged vs Unprivileged' },
      { id: 'capabilities-add-drop', title: 'Linux Capabilities Add/Drop' },
      { id: 'allow-privilege-escalation', title: 'allowPrivilegeEscalation' },
      { id: 'seccomp-profile', title: 'seccompProfile' },
      { id: 'apparmor-profile', title: 'AppArmor Profile (GA v1.30)' },
      { id: 'selinux-options', title: 'seLinuxOptions' },
      { id: 'sysctls-in-pods', title: 'sysctls in Pods' },
      { id: 'user-namespaces-in-pods', title: 'User Namespaces in Pods (KEP-127)' },
      { id: 'supplementalgroupspolicy', title: 'supplementalGroupsPolicy (KEP-3619)' },
    ],
  },
  {
    id: 'pod-spec-fields',
    title: 'Pod Spec Fields',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'command-and-args', title: 'command & args' },
      { id: 'env-and-envfrom', title: 'env & envFrom' },
      { id: 'working-directory', title: 'workingDir' },
      { id: 'host-network-pid-ipc', title: 'hostNetwork / hostPID / hostIPC' },
      { id: 'host-aliases', title: 'hostAliases' },
      { id: 'termination-grace-period-seconds', title: 'terminationGracePeriodSeconds' },
      { id: 'active-deadline-seconds', title: 'activeDeadlineSeconds' },
      { id: 'image-pull-secrets-field', title: 'imagePullSecrets' },
      { id: 'service-account-name', title: 'serviceAccountName & automountServiceAccountToken' },
      { id: 'subdomain-and-hostname', title: 'subdomain & hostname' },
      { id: 'os-field', title: 'os Field (linux / windows)' },
      { id: 'enableservicelinks', title: 'enableServiceLinks' },
      { id: 'preemption-policy', title: 'preemptionPolicy' },
      { id: 'topology-spread-constraints-pod-level', title: 'topologySpreadConstraints (Pod-Level)' },
    ],
  },
  {
    id: 'ephemeral-containers',
    title: 'Ephemeral Containers',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'ephemeral-container-purpose', title: 'Ephemeral Container Purpose' },
      { id: 'ephemeral-vs-regular-containers', title: 'Ephemeral vs Regular Containers' },
      { id: 'targeting-running-containers', title: 'Targeting Running Containers' },
      { id: 'ephemeral-debug-images', title: 'Debug Images (busybox, distroless-debug)' },
    ],
  },
  {
    id: 'pod-disruption-budgets-overview',
    title: 'Pod Disruption Budgets (Overview)',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'pdb-purpose', title: 'PDB Purpose' },
      { id: 'voluntary-vs-involuntary-disruption', title: 'Voluntary vs Involuntary Disruption' },
      { id: 'min-available', title: 'minAvailable' },
      { id: 'max-unavailable', title: 'maxUnavailable' },
      { id: 'pdb-unhealthy-pod-eviction-policy', title: 'unhealthyPodEvictionPolicy (GA v1.31)' },
    ],
  },
  {
    id: 'pod-resize-and-in-place-updates',
    title: 'In-Place Pod Resize',
    parentId: 'pod-fundamentals',
    children: [
      { id: 'in-place-resize-overview', title: 'In-Place Resize Overview (KEP-1287)' },
      { id: 'resize-policy', title: 'resizePolicy per Container' },
      { id: 'resize-restart-policy', title: 'restartPolicy on Resize' },
    ],
  },

  /* ---------- workload-controllers ---------- */
  {
    id: 'replicasets',
    title: 'ReplicaSets',
    parentId: 'workload-controllers',
    children: [
      { id: 'replicaset-purpose', title: 'ReplicaSet Purpose' },
      { id: 'replicaset-vs-replicationcontroller', title: 'ReplicaSet vs ReplicationController' },
      { id: 'replicaset-selectors', title: 'ReplicaSet Selectors' },
      { id: 'orphaning-and-adopting-pods', title: 'Orphaning & Adopting Pods' },
      { id: 'manual-replicaset-management', title: 'Manual ReplicaSet Management' },
    ],
  },
  {
    id: 'deployments',
    title: 'Deployments',
    parentId: 'workload-controllers',
    children: [
      { id: 'deployment-spec', title: 'Deployment Spec' },
      { id: 'rolling-update-strategy', title: 'RollingUpdate Strategy' },
      { id: 'recreate-strategy', title: 'Recreate Strategy' },
      { id: 'max-surge-and-max-unavailable', title: 'maxSurge & maxUnavailable' },
      { id: 'rollout-history', title: 'Rollout History' },
      { id: 'rollout-pause-and-resume', title: 'Rollout Pause & Resume' },
      { id: 'rollout-undo', title: 'Rollout Undo' },
      { id: 'revision-history-limit', title: 'revisionHistoryLimit' },
      { id: 'progress-deadline-seconds', title: 'progressDeadlineSeconds' },
      { id: 'min-ready-seconds', title: 'minReadySeconds' },
      { id: 'deployment-status-fields', title: 'Deployment Status Fields' },
    ],
  },
  {
    id: 'statefulsets',
    title: 'StatefulSets',
    parentId: 'workload-controllers',
    children: [
      { id: 'statefulset-purpose', title: 'StatefulSet Purpose' },
      { id: 'stable-network-identity', title: 'Stable Network Identity' },
      { id: 'stable-storage', title: 'Stable Storage' },
      { id: 'ordered-pod-management', title: 'Ordered Pod Management' },
      { id: 'parallel-pod-management', title: 'Parallel Pod Management' },
      { id: 'statefulset-update-strategies', title: 'StatefulSet Update Strategies' },
      { id: 'partition-rolling-update', title: 'Partition Rolling Update' },
      { id: 'volume-claim-templates', title: 'volumeClaimTemplates' },
      { id: 'pvc-retention-policy', title: 'persistentVolumeClaimRetentionPolicy' },
      { id: 'statefulset-headless-service', title: 'Headless Service Requirement' },
    ],
  },
  {
    id: 'daemonsets',
    title: 'DaemonSets',
    parentId: 'workload-controllers',
    children: [
      { id: 'daemonset-purpose', title: 'DaemonSet Purpose' },
      { id: 'one-pod-per-node', title: 'One Pod per Node' },
      { id: 'daemonset-node-selectors', title: 'Node Selectors & Affinity' },
      { id: 'daemonset-tolerations', title: 'Tolerations on DaemonSets' },
      { id: 'daemonset-rolling-update', title: 'RollingUpdate Strategy' },
      { id: 'daemonset-on-delete', title: 'OnDelete Strategy' },
      { id: 'daemonset-system-services', title: 'DaemonSets for System Services' },
    ],
  },
  {
    id: 'replicationcontroller-legacy',
    title: 'ReplicationController (Legacy)',
    parentId: 'workload-controllers',
    children: [
      { id: 'rc-purpose', title: 'ReplicationController Purpose' },
      { id: 'rc-vs-replicaset', title: 'ReplicationController vs ReplicaSet' },
      { id: 'migrating-rc-to-replicaset', title: 'Migrating to ReplicaSet' },
    ],
  },
  {
    id: 'workload-identity-and-ownership',
    title: 'Workload Identity & Ownership',
    parentId: 'workload-controllers',
    children: [
      { id: 'owner-references', title: 'ownerReferences' },
      { id: 'controller-revision', title: 'ControllerRevision' },
      { id: 'garbage-collection', title: 'Garbage Collection' },
      { id: 'foreground-vs-background-cascade', title: 'Foreground vs Background Cascade' },
      { id: 'orphan-cascade', title: 'Orphan Cascade' },
      { id: 'finalizers-overview', title: 'Finalizers (Overview)' },
    ],
  },

  /* ---------- jobs-and-cronjobs ---------- */
  {
    id: 'jobs',
    title: 'Jobs',
    parentId: 'jobs-and-cronjobs',
    children: [
      { id: 'job-purpose', title: 'Job Purpose' },
      { id: 'job-completion-modes', title: 'Job Completion Modes' },
      { id: 'parallelism-and-completions', title: 'parallelism & completions' },
      { id: 'indexed-jobs', title: 'Indexed Jobs' },
      { id: 'non-indexed-jobs', title: 'Non-Indexed Jobs' },
      { id: 'backoff-limit', title: 'backoffLimit' },
      { id: 'backoff-limit-per-index', title: 'backoffLimitPerIndex (KEP-3850)' },
      { id: 'job-active-deadline-seconds', title: 'activeDeadlineSeconds' },
      { id: 'ttl-after-finished', title: 'ttlSecondsAfterFinished' },
      { id: 'pod-failure-policy', title: 'podFailurePolicy' },
      { id: 'success-policy', title: 'successPolicy (KEP-3998)' },
      { id: 'managed-by-field', title: 'managedBy Field (KEP-4368)' },
      { id: 'pod-replacement-policy', title: 'podReplacementPolicy (KEP-3939)' },
      { id: 'job-suspend-resume', title: 'Suspend & Resume Jobs' },
    ],
  },
  {
    id: 'cronjobs',
    title: 'CronJobs',
    parentId: 'jobs-and-cronjobs',
    children: [
      { id: 'cronjob-spec', title: 'CronJob Spec' },
      { id: 'cron-schedule-syntax', title: 'Cron Schedule Syntax' },
      { id: 'timezones-in-cronjobs', title: 'Time Zones in CronJobs' },
      { id: 'concurrency-policy', title: 'concurrencyPolicy (Allow / Forbid / Replace)' },
      { id: 'starting-deadline-seconds', title: 'startingDeadlineSeconds' },
      { id: 'jobs-history-limits', title: 'successfulJobsHistoryLimit & failedJobsHistoryLimit' },
      { id: 'cronjob-suspend', title: 'Suspending a CronJob' },
    ],
  },
  {
    id: 'batch-job-patterns',
    title: 'Batch Job Patterns',
    parentId: 'jobs-and-cronjobs',
    children: [
      { id: 'work-queue-pattern', title: 'Work Queue Pattern' },
      { id: 'parallel-processing-pattern', title: 'Parallel Processing Pattern' },
      { id: 'fan-out-fan-in', title: 'Fan-Out / Fan-In' },
      { id: 'sequence-of-jobs', title: 'Sequence of Jobs' },
      { id: 'idempotent-job-design', title: 'Idempotent Job Design' },
    ],
  },
  {
    id: 'jobset',
    title: 'JobSet',
    parentId: 'jobs-and-cronjobs',
    children: [
      { id: 'jobset-overview', title: 'JobSet Overview (Working Group Batch)' },
      { id: 'jobset-replicated-jobs', title: 'Replicated Jobs' },
      { id: 'jobset-failure-policies', title: 'Failure Policies' },
      { id: 'jobset-startup-policy', title: 'Startup Policy' },
      { id: 'jobset-vs-job', title: 'JobSet vs Job' },
    ],
  },
])
