import { addTopics } from './addTopics.mjs'

// Stage 18 — Cluster Operations: Day-2
addTopics([
  /* ---------- cluster-upgrades-maintenance ---------- */
  {
    id: 'kubernetes-version-skew-policy',
    title: 'Kubernetes Version Skew Policy',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'apiserver-skew', title: 'API Server Skew' },
      { id: 'kubelet-skew', title: 'kubelet Skew' },
      { id: 'kube-proxy-skew', title: 'kube-proxy Skew' },
      { id: 'kube-controller-manager-skew', title: 'kube-controller-manager Skew' },
      { id: 'kube-scheduler-skew', title: 'kube-scheduler Skew' },
      { id: 'kubectl-skew', title: 'kubectl Skew' },
      { id: 'cloud-controller-manager-skew', title: 'cloud-controller-manager Skew' },
    ],
  },
  {
    id: 'release-and-deprecation-windows',
    title: 'Release & Deprecation Windows',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'release-cadence-stage18', title: 'Release Cadence' },
      { id: 'support-policy-and-eol', title: 'Support Policy & EOL' },
      { id: 'deprecation-policy', title: 'Deprecation Policy' },
      { id: 'api-deprecation-removal-windows', title: 'API Deprecation Removal Windows' },
      { id: 'feature-gate-graduation', title: 'Feature Gate Graduation' },
    ],
  },
  {
    id: 'pre-upgrade-checks',
    title: 'Pre-Upgrade Checks',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'deprecated-api-detection', title: 'Deprecated API Detection' },
      { id: 'kube-no-trouble', title: 'kube-no-trouble (kubent)' },
      { id: 'pluto', title: 'Pluto' },
      { id: 'apisnoop-and-discovery', title: 'APISnoop & Discovery' },
      { id: 'workload-compatibility-audits', title: 'Workload Compatibility Audits' },
      { id: 'storage-compatibility-checks', title: 'Storage Compatibility Checks' },
      { id: 'cni-compatibility-checks', title: 'CNI Compatibility Checks' },
      { id: 'addon-compatibility-matrix', title: 'Addon Compatibility Matrix' },
    ],
  },
  {
    id: 'control-plane-upgrades',
    title: 'Control Plane Upgrades',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'kubeadm-upgrade-flow', title: 'kubeadm Upgrade Flow' },
      { id: 'upgrade-etcd', title: 'Upgrade etcd' },
      { id: 'upgrade-apiserver-and-kcm', title: 'Upgrade kube-apiserver & KCM' },
      { id: 'upgrade-scheduler', title: 'Upgrade kube-scheduler' },
      { id: 'upgrade-cloud-controller-manager', title: 'Upgrade cloud-controller-manager' },
      { id: 'control-plane-ha-during-upgrades', title: 'Control Plane HA During Upgrades' },
      { id: 'rollback-control-plane-upgrades', title: 'Rolling Back Control Plane Upgrades' },
    ],
  },
  {
    id: 'node-upgrades',
    title: 'Node Upgrades',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'cordon-drain-and-upgrade', title: 'Cordon, Drain & Upgrade' },
      { id: 'kubelet-upgrade', title: 'kubelet Upgrade' },
      { id: 'container-runtime-upgrades', title: 'Container Runtime Upgrades' },
      { id: 'node-image-upgrades', title: 'Node Image Upgrades' },
      { id: 'rolling-node-replacement', title: 'Rolling Node Replacement' },
      { id: 'in-place-vs-replace-upgrades', title: 'In-Place vs Replace Upgrades' },
      { id: 'gpu-driver-upgrades-on-nodes', title: 'GPU Driver Upgrades on Nodes' },
    ],
  },
  {
    id: 'managed-cluster-upgrades-pointer',
    title: 'Managed Cluster Upgrades (Pointer)',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'managed-upgrades-overview', title: 'Managed Upgrades Overview' },
      { id: 'auto-upgrade-channels-pointer', title: 'Auto-Upgrade Channels (Pointer)' },
    ],
  },
  {
    id: 'post-upgrade-validation',
    title: 'Post-Upgrade Validation',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'apiserver-health-checks', title: 'API Server Health Checks' },
      { id: 'workload-smoke-tests', title: 'Workload Smoke Tests' },
      { id: 'api-deprecation-monitoring-after', title: 'API Deprecation Monitoring (Post-Upgrade)' },
      { id: 'control-plane-conformance-tests', title: 'Control Plane Conformance Tests' },
    ],
  },
  {
    id: 'automated-upgrade-tooling',
    title: 'Automated Upgrade Tooling',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'clusterapi-upgrade-controllers-pointer', title: 'Cluster API Upgrade Controllers (Pointer)' },
      { id: 'rancher-system-upgrade-controller', title: 'Rancher System Upgrade Controller' },
      { id: 'kured-reboot-daemon', title: 'kured Reboot Daemon' },
      { id: 'kpack-and-others', title: 'kpack & Others' },
    ],
  },
  {
    id: 'maintenance-windows-and-pdbs',
    title: 'Maintenance Windows & PDBs',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'planning-maintenance-windows', title: 'Planning Maintenance Windows' },
      { id: 'using-pod-disruption-budgets-stage18', title: 'Using Pod Disruption Budgets' },
      { id: 'draining-with-pdb', title: 'Draining With PDB' },
      { id: 'terminationgraceperiodseconds-tuning', title: 'terminationGracePeriodSeconds Tuning' },
    ],
  },
  {
    id: 'node-os-patching',
    title: 'Node OS Patching',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'immutable-os-flatcar-talos-pointer', title: 'Immutable OS — Flatcar / Talos / Bottlerocket (Pointer)' },
      { id: 'rolling-os-updates', title: 'Rolling OS Updates' },
      { id: 'kured-os-reboot', title: 'kured for OS Reboot' },
      { id: 'live-kernel-patching-on-k8s-nodes', title: 'Live Kernel Patching on K8s Nodes' },
    ],
  },
  {
    id: 'addon-upgrades',
    title: 'Addon Upgrades',
    parentId: 'cluster-upgrades-maintenance',
    children: [
      { id: 'cni-upgrades', title: 'CNI Upgrades' },
      { id: 'coredns-upgrades', title: 'CoreDNS Upgrades' },
      { id: 'csi-driver-upgrades', title: 'CSI Driver Upgrades' },
      { id: 'metrics-server-upgrade', title: 'Metrics Server Upgrade' },
      { id: 'ingress-controller-upgrades', title: 'Ingress Controller Upgrades' },
      { id: 'gateway-controller-upgrades', title: 'Gateway Controller Upgrades' },
    ],
  },

  /* ---------- disaster-recovery ---------- */
  {
    id: 'disaster-recovery-on-k8s-overview',
    title: 'Disaster Recovery on Kubernetes Overview',
    parentId: 'disaster-recovery',
    children: [
      { id: 'rpo-rto-on-k8s-deep', title: 'RPO / RTO on Kubernetes' },
      { id: 'failure-modes-on-k8s', title: 'Failure Modes on Kubernetes' },
      { id: 'dr-vs-ha-on-k8s', title: 'DR vs HA on Kubernetes' },
      { id: 'blast-radius-on-k8s', title: 'Blast Radius on Kubernetes' },
    ],
  },
  {
    id: 'etcd-backup-and-restore',
    title: 'etcd Backup & Restore',
    parentId: 'disaster-recovery',
    children: [
      { id: 'etcdctl-snapshot-save', title: 'etcdctl snapshot save' },
      { id: 'etcdctl-snapshot-restore', title: 'etcdctl snapshot restore' },
      { id: 'etcd-backup-strategies', title: 'etcd Backup Strategies' },
      { id: 'cross-region-etcd-backups', title: 'Cross-Region etcd Backups' },
      { id: 'encrypted-etcd-backups', title: 'Encrypted etcd Backups' },
      { id: 'etcd-corruption-recovery', title: 'etcd Corruption Recovery' },
      { id: 'etcd-defrag-and-compaction-on-recovery', title: 'Defrag & Compaction on Recovery' },
    ],
  },
  {
    id: 'cluster-state-recovery',
    title: 'Cluster State Recovery',
    parentId: 'disaster-recovery',
    children: [
      { id: 'rebuild-from-velero', title: 'Rebuild From Velero' },
      { id: 'rebuild-from-gitops-stage18', title: 'Rebuild From GitOps' },
      { id: 'manifest-replay', title: 'Manifest Replay' },
      { id: 'partial-resource-restore', title: 'Partial Resource Restore' },
    ],
  },
  {
    id: 'control-plane-rebuild',
    title: 'Control Plane Rebuild',
    parentId: 'disaster-recovery',
    children: [
      { id: 'bare-metal-control-plane-rebuild', title: 'Bare-Metal Control Plane Rebuild' },
      { id: 'kubeadm-cluster-rebuild', title: 'kubeadm Cluster Rebuild' },
      { id: 'external-vs-stacked-etcd-recovery', title: 'External vs Stacked etcd Recovery' },
      { id: 'reissuing-cluster-certificates', title: 'Reissuing Cluster Certificates' },
    ],
  },
  {
    id: 'node-recovery',
    title: 'Node Recovery',
    parentId: 'disaster-recovery',
    children: [
      { id: 'node-replacement-flow', title: 'Node Replacement Flow' },
      { id: 'daemonset-recovery', title: 'DaemonSet Recovery' },
      { id: 'persistent-data-recovery', title: 'Persistent Data Recovery' },
      { id: 'recovering-stranded-pods', title: 'Recovering Stranded Pods' },
    ],
  },
  {
    id: 'network-and-cni-recovery',
    title: 'Network & CNI Recovery',
    parentId: 'disaster-recovery',
    children: [
      { id: 'cni-state-loss', title: 'CNI State Loss' },
      { id: 'service-vip-recovery', title: 'Service VIP Recovery' },
      { id: 'dns-recovery', title: 'DNS Recovery' },
      { id: 'kube-proxy-state-recovery', title: 'kube-proxy State Recovery' },
    ],
  },
  {
    id: 'multi-region-dr-on-k8s',
    title: 'Multi-Region DR on Kubernetes',
    parentId: 'disaster-recovery',
    children: [
      { id: 'active-active-on-k8s', title: 'Active-Active on K8s' },
      { id: 'active-passive-on-k8s', title: 'Active-Passive on K8s' },
      { id: 'pilot-light-and-warm-standby', title: 'Pilot Light & Warm Standby' },
      { id: 'cross-region-failover', title: 'Cross-Region Failover' },
      { id: 'data-replication-considerations-stage18', title: 'Data Replication Considerations' },
    ],
  },
  {
    id: 'application-level-dr',
    title: 'Application-Level DR',
    parentId: 'disaster-recovery',
    children: [
      { id: 'stateful-app-failover-pointer', title: 'Stateful App Failover (Pointer)' },
      { id: 'queue-replay-and-idempotency', title: 'Queue Replay & Idempotency' },
      { id: 'cross-region-replication-of-data', title: 'Cross-Region Replication of Data' },
    ],
  },
  {
    id: 'chaos-and-dr-testing',
    title: 'Chaos & DR Testing',
    parentId: 'disaster-recovery',
    children: [
      { id: 'chaos-engineering-on-k8s-pointer', title: 'Chaos Engineering on K8s (Pointer)' },
      { id: 'chaos-mesh-pointer', title: 'Chaos Mesh (Pointer)' },
      { id: 'litmus-chaos-pointer', title: 'LitmusChaos (Pointer)' },
      { id: 'dr-game-days', title: 'DR Game Days' },
      { id: 'tabletop-exercises', title: 'Tabletop Exercises' },
    ],
  },
  {
    id: 'dr-runbooks-and-documentation',
    title: 'DR Runbooks & Documentation',
    parentId: 'disaster-recovery',
    children: [
      { id: 'dr-runbook-template', title: 'DR Runbook Template' },
      { id: 'oncall-rotation-and-escalation', title: 'On-Call Rotation & Escalation' },
      { id: 'communication-during-incidents', title: 'Communication During Incidents' },
    ],
  },

  /* ---------- troubleshooting-debugging ---------- */
  {
    id: 'troubleshooting-mindset-on-k8s',
    title: 'Troubleshooting Mindset on K8s',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'cluster-vs-app-vs-infra-issues', title: 'Cluster vs App vs Infra Issues' },
      { id: 'reproducing-issues-on-k8s', title: 'Reproducing Issues on K8s' },
      { id: 'escalation-paths', title: 'Escalation Paths' },
      { id: 'four-golden-signals-on-k8s', title: 'Four Golden Signals on K8s' },
    ],
  },
  {
    id: 'debugging-pods',
    title: 'Debugging Pods',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'kubectl-describe-deep', title: 'kubectl describe (Deep)' },
      { id: 'kubectl-logs-deep', title: 'kubectl logs (Deep)' },
      { id: 'kubectl-exec-deep', title: 'kubectl exec (Deep)' },
      { id: 'kubectl-debug-deep', title: 'kubectl debug (Deep)' },
      { id: 'ephemeral-containers-deep', title: 'Ephemeral Containers (Deep)' },
      { id: 'debug-with-pid-namespace-share', title: 'Debug With Process-Namespace Share' },
      { id: 'debug-distroless-and-scratch-images', title: 'Debug Distroless & Scratch Images' },
      { id: 'sidecar-debugging-patterns', title: 'Sidecar Debugging Patterns' },
    ],
  },
  {
    id: 'debugging-pod-startup',
    title: 'Debugging Pod Startup',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'imagepullbackoff', title: 'ImagePullBackOff' },
      { id: 'errimagepull', title: 'ErrImagePull' },
      { id: 'crashloopbackoff', title: 'CrashLoopBackOff' },
      { id: 'oom-killed', title: 'OOMKilled' },
      { id: 'pending-and-unschedulable', title: 'Pending / Unschedulable' },
      { id: 'failedscheduling-events', title: 'FailedScheduling Events' },
      { id: 'kubelet-rejected-pod', title: 'kubelet-Rejected Pods' },
      { id: 'image-architecture-mismatches', title: 'Image Architecture Mismatches' },
    ],
  },
  {
    id: 'debugging-services-and-networking',
    title: 'Debugging Services & Networking',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'service-not-resolving', title: 'Service Not Resolving' },
      { id: 'dns-issues-and-coredns-debugging', title: 'DNS Issues & CoreDNS Debugging' },
      { id: 'kube-proxy-issues', title: 'kube-proxy Issues' },
      { id: 'endpoints-and-endpointslices-debug', title: 'Endpoints & EndpointSlices Debug' },
      { id: 'networkpolicy-debugging', title: 'NetworkPolicy Debugging' },
      { id: 'ingress-debugging', title: 'Ingress Debugging' },
      { id: 'gateway-api-debugging', title: 'Gateway API Debugging' },
      { id: 'mtu-mismatch-issues', title: 'MTU Mismatch Issues' },
      { id: 'mss-clamp-issues', title: 'MSS Clamp Issues' },
      { id: 'session-affinity-issues', title: 'Session Affinity Issues' },
    ],
  },
  {
    id: 'debugging-ingress-and-loadbalancer',
    title: 'Debugging Ingress & LoadBalancer',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'ingress-controller-logs', title: 'Ingress Controller Logs' },
      { id: 'cloud-loadbalancer-debugging', title: 'Cloud LoadBalancer Debugging' },
      { id: 'metallb-and-kube-vip-debugging', title: 'MetalLB & kube-vip Debugging' },
      { id: 'cert-manager-issues', title: 'cert-manager Issues' },
    ],
  },
  {
    id: 'debugging-storage-on-k8s',
    title: 'Debugging Storage on K8s',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'pv-pvc-binding-issues', title: 'PV / PVC Binding Issues' },
      { id: 'csi-driver-issues', title: 'CSI Driver Issues' },
      { id: 'mount-and-attach-failures', title: 'Mount & Attach Failures' },
      { id: 'readonly-filesystem-issues', title: 'Read-Only Filesystem Issues' },
      { id: 'volume-resize-failures', title: 'Volume Resize Failures' },
      { id: 'snapshot-restore-issues', title: 'Snapshot / Restore Issues' },
    ],
  },
  {
    id: 'debugging-nodes',
    title: 'Debugging Nodes',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'notready-node-conditions', title: 'NotReady Node Conditions' },
      { id: 'kubelet-not-running', title: 'kubelet Not Running' },
      { id: 'container-runtime-issues', title: 'Container Runtime Issues' },
      { id: 'disk-pressure-and-eviction', title: 'Disk Pressure & Eviction' },
      { id: 'memory-pressure-debug', title: 'Memory Pressure' },
      { id: 'pid-pressure', title: 'PID Pressure' },
      { id: 'node-shutdown-and-recovery-debug', title: 'Node Shutdown & Recovery' },
    ],
  },
  {
    id: 'debugging-control-plane',
    title: 'Debugging Control Plane',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'apiserver-not-responding', title: 'apiserver Not Responding' },
      { id: 'etcd-quorum-issues', title: 'etcd Quorum Issues' },
      { id: 'kcm-not-reconciling', title: 'KCM Not Reconciling' },
      { id: 'scheduler-issues', title: 'Scheduler Issues' },
      { id: 'leader-election-flapping', title: 'Leader Election Flapping' },
    ],
  },
  {
    id: 'debugging-rbac-and-auth',
    title: 'Debugging RBAC & Auth',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'permission-denied', title: 'Permission Denied' },
      { id: 'sa-token-issues', title: 'ServiceAccount Token Issues' },
      { id: 'oidc-issues', title: 'OIDC Issues' },
      { id: 'certificate-issues-on-k8s', title: 'Certificate Issues' },
      { id: 'subjectaccessreview-debugging', title: 'SubjectAccessReview Debugging' },
    ],
  },
  {
    id: 'audit-logs-and-events-for-debug',
    title: 'Audit Logs & Events for Debug',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'reading-audit-logs-effectively', title: 'Reading Audit Logs Effectively' },
      { id: 'event-correlation', title: 'Event Correlation' },
      { id: 'kubectl-events-deep', title: 'kubectl events (Deep)' },
    ],
  },
  {
    id: 'debugging-tools-on-k8s',
    title: 'Debugging Tools on Kubernetes',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'k9s-and-lens-pointer-stage18', title: 'k9s & Lens (Pointer)' },
      { id: 'stern-debug', title: 'Stern' },
      { id: 'kubectx-kubens', title: 'kubectx / kubens' },
      { id: 'popeye', title: 'Popeye' },
      { id: 'kube-bench-pointer', title: 'kube-bench (Pointer)' },
      { id: 'kube-hunter-pointer', title: 'kube-hunter (Pointer)' },
      { id: 'krew-pointer-stage18', title: 'Krew Plugins (Pointer)' },
      { id: 'inspektor-gadget', title: 'Inspektor Gadget' },
      { id: 'tcpdump-and-tshark-in-pods', title: 'tcpdump & tshark in Pods' },
      { id: 'nsenter-and-debug-images', title: 'nsenter & Debug Images' },
    ],
  },
  {
    id: 'network-debugging-tools',
    title: 'Network Debugging Tools',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'kubectl-trace', title: 'kubectl trace' },
      { id: 'cilium-debug-tools', title: 'Cilium Debug Tools (Hubble)' },
      { id: 'calico-debug-tools', title: 'Calico Debug Tools (calicoctl)' },
      { id: 'istioctl-and-meshctl', title: 'istioctl & meshctl' },
      { id: 'mesh-debug-via-envoy-admin', title: 'Mesh Debug via Envoy Admin Interface' },
    ],
  },
  {
    id: 'distributed-tracing-for-debug-pointer',
    title: 'Distributed Tracing for Debug (Pointer)',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'tracing-pointer-stage11', title: 'Tracing Pointer (Stage 11)' },
      { id: 'profiling-during-incidents', title: 'Profiling During Incidents' },
    ],
  },
  {
    id: 'post-mortems-and-rca',
    title: 'Post-Mortems & Root Cause Analysis',
    parentId: 'troubleshooting-debugging',
    children: [
      { id: 'blameless-post-mortems', title: 'Blameless Post-Mortems' },
      { id: 'rca-on-k8s-incidents', title: 'RCA on K8s Incidents' },
      { id: 'action-items-and-follow-up', title: 'Action Items & Follow-Up' },
    ],
  },
])
