import { addTopics } from './addTopics.mjs'

// Stage 3 — Cluster Setup & First Steps
addTopics([
  /* ---------- local-development-clusters ---------- */
  {
    id: 'minikube',
    title: 'Minikube',
    parentId: 'local-development-clusters',
    children: [
      { id: 'minikube-installation', title: 'Minikube Installation' },
      { id: 'minikube-drivers', title: 'Minikube Drivers (Docker, hyperkit, KVM, podman, qemu)' },
      { id: 'minikube-addons', title: 'Minikube Addons' },
      { id: 'minikube-multi-node', title: 'Minikube Multi-Node Clusters' },
      { id: 'minikube-profiles', title: 'Minikube Profiles' },
    ],
  },
  {
    id: 'kind',
    title: 'kind (Kubernetes IN Docker)',
    parentId: 'local-development-clusters',
    children: [
      { id: 'kind-installation', title: 'kind Installation' },
      { id: 'kind-cluster-config', title: 'kind Cluster Config' },
      { id: 'kind-multi-node', title: 'kind Multi-Node Clusters' },
      { id: 'kind-load-images', title: 'Loading Images into kind' },
      { id: 'kind-extra-mounts-and-port-mappings', title: 'Extra Mounts & Port Mappings' },
    ],
  },
  {
    id: 'k3d',
    title: 'k3d (k3s in Docker)',
    parentId: 'local-development-clusters',
    children: [
      { id: 'k3d-installation', title: 'k3d Installation' },
      { id: 'k3d-cluster-config', title: 'k3d Cluster Config' },
      { id: 'k3d-multi-server', title: 'k3d Multi-Server Clusters' },
      { id: 'k3d-image-import', title: 'k3d Image Import' },
      { id: 'k3d-registries', title: 'k3d Local Registries' },
    ],
  },
  {
    id: 'docker-desktop-kubernetes-cluster',
    title: 'Docker Desktop Kubernetes',
    parentId: 'local-development-clusters',
    children: [
      { id: 'enabling-kubernetes-in-desktop', title: 'Enabling Kubernetes in Docker Desktop' },
      { id: 'docker-desktop-resource-allocation', title: 'Resource Allocation' },
      { id: 'docker-desktop-cluster-reset', title: 'Cluster Reset' },
    ],
  },
  {
    id: 'microk8s',
    title: 'MicroK8s',
    parentId: 'local-development-clusters',
    children: [
      { id: 'microk8s-installation', title: 'MicroK8s Installation' },
      { id: 'microk8s-addons', title: 'MicroK8s Addons' },
      { id: 'microk8s-channels', title: 'Channels & Tracks' },
      { id: 'microk8s-ha-clustering', title: 'HA Clustering' },
    ],
  },
  {
    id: 'rancher-desktop-k8s',
    title: 'Rancher Desktop (K8s Side)',
    parentId: 'local-development-clusters',
    children: [
      { id: 'rancher-desktop-k8s-overview', title: 'Rancher Desktop K8s Overview' },
      { id: 'rancher-desktop-runtime-choice', title: 'Runtime Choice (containerd vs Moby)' },
      { id: 'rancher-desktop-traefik', title: 'Traefik Built-In Ingress' },
    ],
  },
  {
    id: 'colima-k8s',
    title: 'Colima (K8s Mode)',
    parentId: 'local-development-clusters',
    children: [
      { id: 'colima-k8s-overview', title: 'Colima K8s Overview' },
      { id: 'colima-k3s-mode', title: 'k3s Mode in Colima' },
    ],
  },
  {
    id: 'orbstack-k8s',
    title: 'OrbStack (K8s Mode)',
    parentId: 'local-development-clusters',
    children: [
      { id: 'orbstack-k8s-overview', title: 'OrbStack K8s Overview' },
    ],
  },
  {
    id: 'wsl2-and-vms-for-k8s',
    title: 'WSL2 & VMs for Kubernetes',
    parentId: 'local-development-clusters',
    children: [
      { id: 'wsl2-kubernetes-setup', title: 'WSL2 Kubernetes Setup' },
      { id: 'multipass-for-k8s', title: 'Multipass for K8s' },
      { id: 'lima-for-k8s', title: 'Lima for K8s' },
    ],
  },

  /* ---------- cluster-installation ---------- */
  {
    id: 'kubeadm',
    title: 'kubeadm',
    parentId: 'cluster-installation',
    children: [
      { id: 'kubeadm-overview', title: 'kubeadm Overview' },
      { id: 'kubeadm-init', title: 'kubeadm init' },
      { id: 'kubeadm-join', title: 'kubeadm join' },
      { id: 'kubeadm-config', title: 'kubeadm Configuration File' },
      { id: 'kubeadm-upgrade', title: 'kubeadm Upgrade Workflow' },
      { id: 'kubeadm-certs', title: 'kubeadm Certificate Management' },
      { id: 'kubeadm-ha-clusters', title: 'kubeadm HA Clusters' },
      { id: 'kubeadm-reset', title: 'kubeadm Reset' },
      { id: 'kubeadm-phases', title: 'kubeadm Phases' },
    ],
  },
  {
    id: 'kops',
    title: 'kops (Kubernetes Operations)',
    parentId: 'cluster-installation',
    children: [
      { id: 'kops-overview', title: 'kops Overview' },
      { id: 'kops-cluster-spec', title: 'kops Cluster Spec' },
      { id: 'kops-state-store', title: 'kops State Store' },
      { id: 'kops-on-aws', title: 'kops on AWS' },
      { id: 'kops-on-gce', title: 'kops on GCE' },
      { id: 'kops-rolling-updates', title: 'kops Rolling Updates' },
    ],
  },
  {
    id: 'kubespray',
    title: 'Kubespray (Ansible)',
    parentId: 'cluster-installation',
    children: [
      { id: 'kubespray-overview', title: 'Kubespray Overview' },
      { id: 'kubespray-inventory', title: 'Kubespray Inventory' },
      { id: 'kubespray-playbooks', title: 'Kubespray Playbooks' },
      { id: 'kubespray-customization', title: 'Customization (CNI, addons, container runtime)' },
      { id: 'kubespray-upgrades', title: 'Kubespray Upgrades' },
    ],
  },
  {
    id: 'cluster-api',
    title: 'Cluster API (CAPI)',
    parentId: 'cluster-installation',
    children: [
      { id: 'cluster-api-overview', title: 'Cluster API Overview' },
      { id: 'capi-providers', title: 'CAPI Infrastructure Providers' },
      { id: 'capi-bootstrap-providers', title: 'CAPI Bootstrap Providers' },
      { id: 'capi-control-plane-providers', title: 'CAPI Control Plane Providers' },
      { id: 'capi-management-cluster', title: 'Management Cluster' },
      { id: 'capi-machine-and-machinedeployment', title: 'Machine & MachineDeployment' },
      { id: 'capi-machinepool', title: 'MachinePool' },
      { id: 'capi-clusterclass', title: 'ClusterClass' },
    ],
  },
  {
    id: 'bare-metal-installations',
    title: 'Bare-Metal Installations',
    parentId: 'cluster-installation',
    children: [
      { id: 'kubernetes-the-hard-way', title: 'Kubernetes The Hard Way' },
      { id: 'typhoon', title: 'Typhoon' },
      { id: 'rke-and-rke2', title: 'RKE & RKE2' },
      { id: 'k3s-installation', title: 'k3s Installation' },
      { id: 'talos-installation', title: 'Talos Installation' },
      { id: 'metal3', title: 'Metal³ (CAPI for Bare Metal)' },
      { id: 'tinkerbell', title: 'Tinkerbell' },
    ],
  },
  {
    id: 'managed-cluster-creation',
    title: 'Managed Cluster Creation Flow',
    summary: 'How clusters are created on managed services (AWS EKS, Azure AKS, Google GKE deep-dives live in their own subjects).',
    parentId: 'cluster-installation',
    children: [
      { id: 'managed-vs-self-managed', title: 'Managed vs Self-Managed Trade-offs' },
      { id: 'managed-control-plane-model', title: 'Managed Control-Plane Model' },
      { id: 'node-pools-and-node-groups', title: 'Node Pools & Node Groups' },
      { id: 'serverless-node-modes', title: 'Serverless Node Modes (Fargate, Autopilot)' },
      { id: 'regional-vs-zonal-clusters', title: 'Regional vs Zonal Clusters' },
      { id: 'private-clusters', title: 'Private Clusters' },
    ],
  },
  {
    id: 'cluster-bootstrap-tooling',
    title: 'Cluster Bootstrap Tooling',
    parentId: 'cluster-installation',
    children: [
      { id: 'cloud-init-and-ignition', title: 'cloud-init & Ignition' },
      { id: 'sealed-os-images', title: 'Sealed OS Images' },
      { id: 'cluster-bootstrap-secrets', title: 'Cluster Bootstrap Secrets' },
      { id: 'tls-bootstrapping', title: 'kubelet TLS Bootstrapping' },
    ],
  },

  /* ---------- kubectl-and-access ---------- */
  {
    id: 'kubectl-fundamentals',
    title: 'kubectl Fundamentals',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'kubectl-installation', title: 'kubectl Installation' },
      { id: 'kubectl-syntax', title: 'kubectl Syntax' },
      { id: 'imperative-vs-declarative-commands', title: 'Imperative vs Declarative Commands' },
      { id: 'common-verbs', title: 'Common Verbs (get, describe, create, apply, delete)' },
      { id: 'resource-shortnames', title: 'Resource Short Names' },
      { id: 'all-resources-and-api-resources', title: 'kubectl api-resources & api-versions' },
    ],
  },
  {
    id: 'kubeconfig',
    title: 'kubeconfig',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'kubeconfig-structure', title: 'kubeconfig File Structure' },
      { id: 'clusters-users-contexts', title: 'Clusters, Users & Contexts' },
      { id: 'kubeconfig-merging', title: 'Kubeconfig Merging via KUBECONFIG' },
      { id: 'exec-credential-plugins', title: 'Exec Credential Plugins' },
      { id: 'in-cluster-config', title: 'In-Cluster Config (Pods)' },
      { id: 'kubeconfig-best-practices', title: 'Kubeconfig Best Practices' },
    ],
  },
  {
    id: 'contexts-and-namespaces',
    title: 'Contexts & Namespaces',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'context-switching', title: 'Context Switching' },
      { id: 'kubectx-and-kubens', title: 'kubectx & kubens' },
      { id: 'per-shell-contexts', title: 'Per-Shell Contexts (kubie, direnv)' },
      { id: 'default-namespace-handling', title: 'Default Namespace Handling' },
    ],
  },
  {
    id: 'kubectl-output-formats',
    title: 'kubectl Output Formats',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'default-output', title: 'Default Output' },
      { id: 'wide-output', title: 'Wide Output (-o wide)' },
      { id: 'jsonpath-output', title: 'JSONPath Output' },
      { id: 'go-template-output', title: 'Go Template Output' },
      { id: 'custom-columns', title: 'Custom Columns' },
      { id: 'kyaml-output', title: 'KYAML Output' },
      { id: 'name-output', title: 'Name Output (-o name)' },
    ],
  },
  {
    id: 'kubectl-apply-and-edit',
    title: 'kubectl apply & edit',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'apply-vs-create', title: 'apply vs create' },
      { id: 'kubectl-edit', title: 'kubectl edit' },
      { id: 'kubectl-patch', title: 'kubectl patch (strategic, JSON, merge)' },
      { id: 'kubectl-replace', title: 'kubectl replace' },
      { id: 'last-applied-configuration', title: 'last-applied-configuration Annotation' },
      { id: 'server-side-apply-with-kubectl', title: 'Server-Side Apply with kubectl' },
      { id: 'force-conflicts', title: '--force-conflicts on SSA' },
    ],
  },
  {
    id: 'kubectl-debugging-commands',
    title: 'kubectl Debugging Commands',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'kubectl-describe', title: 'kubectl describe' },
      { id: 'kubectl-logs', title: 'kubectl logs' },
      { id: 'kubectl-exec', title: 'kubectl exec' },
      { id: 'kubectl-port-forward', title: 'kubectl port-forward' },
      { id: 'kubectl-cp', title: 'kubectl cp' },
      { id: 'kubectl-debug', title: 'kubectl debug' },
      { id: 'kubectl-attach', title: 'kubectl attach' },
      { id: 'kubectl-events', title: 'kubectl events' },
      { id: 'kubectl-top', title: 'kubectl top' },
      { id: 'kubectl-explain', title: 'kubectl explain' },
    ],
  },
  {
    id: 'kubectl-plugins',
    title: 'kubectl Plugins',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'krew', title: 'Krew Plugin Manager' },
      { id: 'plugin-discovery', title: 'Plugin Discovery (kubectl-* binaries)' },
      { id: 'plugin-kubectl-tree', title: 'kubectl-tree' },
      { id: 'plugin-kubectl-stern', title: 'kubectl-stern' },
      { id: 'plugin-kubectl-neat', title: 'kubectl-neat' },
      { id: 'plugin-kubectl-view-secret', title: 'kubectl-view-secret' },
      { id: 'plugin-kubectl-ctx-ns', title: 'kubectl-ctx & kubectl-ns' },
      { id: 'writing-plugins', title: 'Writing kubectl Plugins' },
    ],
  },
  {
    id: 'alternative-cli-and-tui-tools',
    title: 'Alternative CLI & TUI Tools',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'k9s', title: 'k9s' },
      { id: 'kubie', title: 'kubie' },
      { id: 'stern', title: 'stern' },
      { id: 'lens-openlens', title: 'Lens / OpenLens' },
      { id: 'headlamp', title: 'Headlamp' },
      { id: 'kubernetes-dashboard', title: 'Kubernetes Dashboard' },
      { id: 'kui', title: 'Kui' },
    ],
  },
  {
    id: 'accessing-the-api-directly',
    title: 'Accessing the API Directly',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'kubectl-proxy', title: 'kubectl proxy' },
      { id: 'kubectl-raw', title: 'kubectl --raw' },
      { id: 'curl-with-bearer-tokens', title: 'curl with Bearer Tokens' },
      { id: 'openapi-and-swagger-spec', title: 'OpenAPI & Swagger Spec' },
      { id: 'discovery-api', title: 'Discovery API' },
      { id: 'aggregated-discovery', title: 'Aggregated Discovery' },
    ],
  },
  {
    id: 'kubectl-completion-and-aliases',
    title: 'kubectl Completion & Aliases',
    parentId: 'kubectl-and-access',
    children: [
      { id: 'shell-completion', title: 'Shell Completion (bash, zsh, fish, PowerShell)' },
      { id: 'kubectl-aliases', title: 'kubectl Aliases (k, kgp, kgs, kaf)' },
      { id: 'kubectl-config-current-context', title: 'Showing Current Context in Prompt' },
    ],
  },
])
