import { addTopics } from './addTopics.mjs'

// Stage 10 — Security & Authorization
addTopics([
  /* ---------- cluster-authentication ---------- */
  {
    id: 'authentication-overview',
    title: 'Authentication Overview',
    parentId: 'cluster-authentication',
    children: [
      { id: 'authn-vs-authz-vs-admission', title: 'AuthN vs AuthZ vs Admission' },
      { id: 'authentication-strategies', title: 'Authentication Strategies' },
      { id: 'authentication-flow', title: 'Authentication Flow' },
      { id: 'users-vs-serviceaccounts', title: 'Users vs ServiceAccounts' },
      { id: 'groups-and-system-groups', title: 'Groups & system: Prefix' },
    ],
  },
  {
    id: 'x509-client-certificates',
    title: 'X.509 Client Certificates',
    parentId: 'cluster-authentication',
    children: [
      { id: 'x509-cert-flow', title: 'X.509 Cert Flow' },
      { id: 'cn-and-organization-mapping', title: 'CN & Organization Mapping' },
      { id: 'certificate-signing-request', title: 'CertificateSigningRequest Resource' },
      { id: 'csr-signers', title: 'CSR Signers' },
      { id: 'certificate-rotation', title: 'Certificate Rotation' },
    ],
  },
  {
    id: 'bearer-tokens',
    title: 'Bearer Tokens',
    parentId: 'cluster-authentication',
    children: [
      { id: 'static-token-file', title: 'Static Token File' },
      { id: 'bootstrap-tokens', title: 'Bootstrap Tokens' },
      { id: 'serviceaccount-tokens-overview', title: 'ServiceAccount Tokens (Overview)' },
    ],
  },
  {
    id: 'service-account-tokens',
    title: 'ServiceAccount Tokens',
    parentId: 'cluster-authentication',
    children: [
      { id: 'legacy-secret-tokens', title: 'Legacy Secret-Based Tokens' },
      { id: 'bound-service-account-tokens', title: 'Bound ServiceAccount Tokens' },
      { id: 'token-request-api', title: 'TokenRequest API' },
      { id: 'projected-token-audience', title: 'Projected Token Audience' },
      { id: 'serviceaccount-token-cleaner', title: 'Token Cleaner Controller' },
      { id: 'kubelet-pod-bound-tokens', title: 'kubelet Pod-Bound Tokens' },
    ],
  },
  {
    id: 'oidc-authentication',
    title: 'OIDC Authentication',
    parentId: 'cluster-authentication',
    children: [
      { id: 'oidc-issuer-and-client', title: 'OIDC Issuer & Client' },
      { id: 'oidc-claims-mapping', title: 'OIDC Claims Mapping' },
      { id: 'oidc-id-token-flow', title: 'OIDC ID Token Flow' },
      { id: 'oidc-providers-keycloak-okta', title: 'External Providers (Keycloak, Okta, Auth0, Dex)' },
      { id: 'oidc-refresh-tokens', title: 'OIDC Refresh Tokens' },
    ],
  },
  {
    id: 'structured-authentication-config',
    title: 'Structured Authentication Config',
    parentId: 'cluster-authentication',
    children: [
      { id: 'authenticationconfiguration-resource', title: 'AuthenticationConfiguration Resource (KEP-3331)' },
      { id: 'jwt-authenticator', title: 'JWT Authenticator' },
      { id: 'multiple-authenticators', title: 'Multiple Authenticators' },
      { id: 'cel-claim-mappings', title: 'CEL-Based Claim Mappings' },
    ],
  },
  {
    id: 'webhook-token-authentication',
    title: 'Webhook Token Authentication',
    parentId: 'cluster-authentication',
    children: [
      { id: 'webhook-token-overview', title: 'Webhook Token Overview' },
      { id: 'tokenreview-resource', title: 'TokenReview Resource' },
      { id: 'webhook-config-format', title: 'Webhook Config Format' },
    ],
  },
  {
    id: 'impersonation',
    title: 'Impersonation',
    parentId: 'cluster-authentication',
    children: [
      { id: 'kubectl-as-flag', title: 'kubectl --as Flag' },
      { id: 'user-impersonation', title: 'User Impersonation' },
      { id: 'group-impersonation', title: 'Group Impersonation' },
      { id: 'serviceaccount-impersonation', title: 'ServiceAccount Impersonation' },
      { id: 'impersonate-userextra', title: 'UserExtra Headers' },
      { id: 'impersonate-uid', title: 'UID Impersonation (KEP-3614)' },
    ],
  },
  {
    id: 'proxy-authentication',
    title: 'Authenticating Proxy',
    parentId: 'cluster-authentication',
    children: [
      { id: 'authenticating-proxy-overview', title: 'Authenticating Proxy Overview' },
      { id: 'x-remote-user-headers', title: 'X-Remote-* Headers' },
      { id: 'requestheader-client-ca', title: 'requestheader-client-ca' },
    ],
  },
  {
    id: 'workload-identity-on-k8s',
    title: 'Workload Identity on Kubernetes',
    parentId: 'cluster-authentication',
    children: [
      { id: 'workload-identity-concept', title: 'Workload Identity Concept' },
      { id: 'irsa-pointer', title: 'AWS IAM Roles for ServiceAccounts (Pointer)' },
      { id: 'eks-pod-identity-pointer', title: 'EKS Pod Identity (Pointer)' },
      { id: 'azure-workload-identity-pointer', title: 'Azure Workload Identity (Pointer)' },
      { id: 'gke-workload-identity-pointer', title: 'GKE Workload Identity (Pointer)' },
      { id: 'spire-and-spiffe-on-k8s', title: 'SPIRE & SPIFFE on Kubernetes' },
    ],
  },
  {
    id: 'anonymous-authentication',
    title: 'Anonymous Authentication',
    parentId: 'cluster-authentication',
    children: [
      { id: 'anonymous-auth-flag', title: 'anonymous-auth Flag' },
      { id: 'anonymous-restrictions', title: 'AnonymousAuthConfigurableEndpoints (KEP-4633)' },
    ],
  },

  /* ---------- rbac-authorization ---------- */
  {
    id: 'authorization-modes',
    title: 'Authorization Modes',
    parentId: 'rbac-authorization',
    children: [
      { id: 'rbac-mode', title: 'RBAC Mode' },
      { id: 'abac-mode', title: 'ABAC Mode (Legacy)' },
      { id: 'node-mode', title: 'Node Authorizer Mode' },
      { id: 'webhook-mode', title: 'Webhook Authorizer Mode' },
      { id: 'alwaysallow-alwaysdeny', title: 'AlwaysAllow / AlwaysDeny Modes' },
      { id: 'authorization-config-file', title: 'Structured Authorization Config (KEP-3221)' },
    ],
  },
  {
    id: 'rbac-fundamentals',
    title: 'RBAC Fundamentals',
    parentId: 'rbac-authorization',
    children: [
      { id: 'role-resource', title: 'Role Resource' },
      { id: 'clusterrole-resource', title: 'ClusterRole Resource' },
      { id: 'rolebinding-resource', title: 'RoleBinding Resource' },
      { id: 'clusterrolebinding-resource', title: 'ClusterRoleBinding Resource' },
      { id: 'rbac-subjects-types', title: 'Subject Types (User, Group, ServiceAccount)' },
      { id: 'apigroups-resources-verbs', title: 'apiGroups, resources, verbs' },
      { id: 'resource-names-restriction', title: 'resourceNames Restriction' },
      { id: 'non-resource-urls-rbac', title: 'nonResourceURLs' },
      { id: 'aggregated-clusterroles', title: 'Aggregated ClusterRoles' },
      { id: 'system-built-in-clusterroles', title: 'System: Built-In ClusterRoles' },
    ],
  },
  {
    id: 'rbac-best-practices',
    title: 'RBAC Best Practices',
    parentId: 'rbac-authorization',
    children: [
      { id: 'rbac-least-privilege', title: 'Least Privilege' },
      { id: 'role-aggregation-pattern', title: 'Role Aggregation Pattern' },
      { id: 'avoiding-cluster-admin', title: 'Avoiding cluster-admin' },
      { id: 'rbac-auditing', title: 'RBAC Auditing' },
      { id: 'rbac-policy-tools', title: 'RBAC Policy Tools (rbac-tool, can-i, rakkess)' },
      { id: 'rbac-namespace-scope-vs-cluster-scope', title: 'Namespace-Scope vs Cluster-Scope Choice' },
    ],
  },
  {
    id: 'subject-access-review-apis',
    title: 'SubjectAccessReview APIs',
    parentId: 'rbac-authorization',
    children: [
      { id: 'subjectaccessreview', title: 'SubjectAccessReview' },
      { id: 'selfsubjectaccessreview', title: 'SelfSubjectAccessReview' },
      { id: 'localsubjectaccessreview', title: 'LocalSubjectAccessReview' },
      { id: 'kubectl-auth-can-i', title: 'kubectl auth can-i' },
    ],
  },
  {
    id: 'node-authorizer-deep',
    title: 'Node Authorizer Deep Dive',
    parentId: 'rbac-authorization',
    children: [
      { id: 'node-authorizer-overview', title: 'Node Authorizer Overview' },
      { id: 'node-restriction-admission', title: 'NodeRestriction Admission' },
      { id: 'node-bound-service-tokens', title: 'Node-Bound ServiceAccount Tokens' },
    ],
  },
  {
    id: 'webhook-authorization',
    title: 'Webhook Authorization',
    parentId: 'rbac-authorization',
    children: [
      { id: 'webhook-authz-overview', title: 'Webhook Authorization Overview' },
      { id: 'authorization-webhook-config', title: 'Authorization Webhook Config' },
      { id: 'subjectaccessreview-webhook-payload', title: 'SubjectAccessReview Webhook Payload' },
    ],
  },

  /* ---------- pod-security-and-admission ---------- */
  {
    id: 'admission-controllers',
    title: 'Admission Controllers',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'admission-controllers-overview', title: 'Admission Controllers Overview' },
      { id: 'built-in-admission-controllers', title: 'Built-In Admission Controllers' },
      { id: 'admission-controller-pipeline', title: 'Admission Pipeline (Mutate → Validate)' },
      { id: 'enabling-disabling-admission-plugins', title: 'Enabling / Disabling Admission Plugins' },
      { id: 'admission-controller-ordering', title: 'Admission Controller Ordering' },
    ],
  },
  {
    id: 'mutating-admission-webhooks',
    title: 'Mutating Admission Webhooks',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'mutatingadmissionwebhook-resource', title: 'MutatingWebhookConfiguration Resource' },
      { id: 'webhook-server-design', title: 'Webhook Server Design' },
      { id: 'json-patch-vs-strategic-merge', title: 'JSON Patch vs Strategic Merge' },
      { id: 'mutating-webhook-side-effects', title: 'Mutating Webhook Side Effects' },
      { id: 'mutating-webhook-failure-policy', title: 'Failure Policy' },
      { id: 'mutating-webhook-reinvocation-policy', title: 'reinvocationPolicy' },
    ],
  },
  {
    id: 'validating-admission-webhooks',
    title: 'Validating Admission Webhooks',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'validatingadmissionwebhook-resource', title: 'ValidatingWebhookConfiguration Resource' },
      { id: 'validating-webhook-failure-policy', title: 'Failure Policy' },
      { id: 'validating-webhook-side-effects', title: 'Side Effects' },
      { id: 'validating-webhook-match-conditions', title: 'matchConditions' },
      { id: 'webhook-namespace-and-object-selectors', title: 'Namespace & Object Selectors' },
      { id: 'webhook-timeoutseconds', title: 'timeoutSeconds' },
    ],
  },
  {
    id: 'validatingadmissionpolicy',
    title: 'ValidatingAdmissionPolicy',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'vap-overview', title: 'VAP Overview (GA v1.30)' },
      { id: 'cel-language-for-vap', title: 'CEL Language for VAP' },
      { id: 'validatingadmissionpolicybinding', title: 'ValidatingAdmissionPolicyBinding' },
      { id: 'param-resources-vap', title: 'paramKind & Param Resources' },
      { id: 'matchconditions-vap', title: 'matchConditions' },
      { id: 'auditannotations-vap', title: 'auditAnnotations' },
      { id: 'validations-and-failure-policies-vap', title: 'Validations & Failure Policies' },
    ],
  },
  {
    id: 'mutatingadmissionpolicy',
    title: 'MutatingAdmissionPolicy',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'map-overview', title: 'MAP Overview (KEP-3962)' },
      { id: 'cel-for-mutation', title: 'CEL for Mutation' },
      { id: 'mutatingadmissionpolicybinding', title: 'MutatingAdmissionPolicyBinding' },
      { id: 'apply-configuration-vs-patch', title: 'ApplyConfiguration vs JSON Patch' },
    ],
  },
  {
    id: 'pod-security-standards',
    title: 'Pod Security Standards',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'pss-privileged', title: 'Privileged' },
      { id: 'pss-baseline', title: 'Baseline' },
      { id: 'pss-restricted', title: 'Restricted' },
      { id: 'pss-changes-by-version', title: 'PSS Changes by Version' },
    ],
  },
  {
    id: 'pod-security-admission',
    title: 'Pod Security Admission',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'psa-overview', title: 'PSA Overview' },
      { id: 'psa-modes-enforce-warn-audit', title: 'Modes: enforce / warn / audit' },
      { id: 'psa-version-pinning', title: 'Version Pinning' },
      { id: 'namespace-labels-for-psa', title: 'Namespace Labels for PSA' },
      { id: 'psa-exemptions', title: 'Exemptions (Usernames, RuntimeClasses, Namespaces)' },
      { id: 'psa-monitoring-violations', title: 'Monitoring PSA Violations' },
    ],
  },
  {
    id: 'podsecuritypolicy-removed',
    title: 'PodSecurityPolicy (Removed)',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'psp-deprecation-history', title: 'PSP Deprecation History (1.21 → 1.25)' },
      { id: 'migrating-from-psp', title: 'Migrating from PSP' },
    ],
  },
  {
    id: 'third-party-policy-engines',
    title: 'Third-Party Policy Engines',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'opa-gatekeeper', title: 'OPA / Gatekeeper' },
      { id: 'kyverno', title: 'Kyverno' },
      { id: 'kubewarden', title: 'Kubewarden' },
      { id: 'jspolicy', title: 'jsPolicy' },
      { id: 'polaris', title: 'Polaris' },
      { id: 'vap-vs-policy-engines', title: 'VAP vs Policy Engines' },
    ],
  },
  {
    id: 'runtime-security-on-k8s',
    title: 'Runtime Security on Kubernetes',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'falco-pointer', title: 'Falco (Pointer)' },
      { id: 'tetragon-pointer', title: 'Cilium Tetragon (Pointer)' },
      { id: 'tracee-pointer', title: 'Tracee (Pointer)' },
      { id: 'kubescape-pointer', title: 'Kubescape (Pointer)' },
      { id: 'audit-and-detect-vs-prevent', title: 'Audit-and-Detect vs Prevent' },
    ],
  },
  {
    id: 'audit-logging-deep',
    title: 'Audit Logging',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'audit-policy-resource', title: 'Audit Policy Resource' },
      { id: 'audit-stages', title: 'Audit Stages (RequestReceived → ResponseComplete)' },
      { id: 'audit-levels', title: 'Audit Levels (None, Metadata, Request, RequestResponse)' },
      { id: 'audit-backends-log-webhook', title: 'Audit Backends (log, webhook)' },
      { id: 'audit-id-tracking', title: 'Audit ID Tracking' },
      { id: 'audit-log-rotation', title: 'Audit Log Rotation' },
    ],
  },
  {
    id: 'api-priority-and-fairness',
    title: 'API Priority & Fairness',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'apf-overview', title: 'APF Overview' },
      { id: 'flowschema', title: 'FlowSchema Resource' },
      { id: 'prioritylevelconfiguration', title: 'PriorityLevelConfiguration Resource' },
      { id: 'apf-defaults', title: 'APF Defaults' },
      { id: 'apf-monitoring', title: 'APF Monitoring & Metrics' },
    ],
  },
  {
    id: 'certificate-management-cluster',
    title: 'Cluster Certificate Management',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'csr-resource-deep', title: 'CertificateSigningRequest Deep Dive' },
      { id: 'kcm-csr-signers', title: 'kube-controller-manager CSR Signers' },
      { id: 'cluster-trust-bundle', title: 'ClusterTrustBundle (KEP-3257)' },
      { id: 'cab-projection', title: 'ClusterTrustBundle Projection' },
      { id: 'cert-manager-pointer', title: 'cert-manager (Pointer)' },
    ],
  },
  {
    id: 'cluster-hardening',
    title: 'Cluster Hardening',
    parentId: 'pod-security-and-admission',
    children: [
      { id: 'cis-kubernetes-benchmark', title: 'CIS Kubernetes Benchmark' },
      { id: 'kube-bench', title: 'kube-bench' },
      { id: 'kube-hunter', title: 'kube-hunter' },
      { id: 'nsa-cisa-hardening-guidance', title: 'NSA / CISA Hardening Guidance' },
      { id: 'restrict-anonymous-and-system-anonymous', title: 'Restrict Anonymous / system:anonymous' },
      { id: 'minimize-host-namespace-sharing', title: 'Minimize Host Namespace Sharing' },
    ],
  },
])
