import { addTopics } from './addTopics.mjs'

// Stage 21 — Distributions & Platforms
// platform-engineering refocused on K8s-specific platform engineering
// (generic platform-engineering topics live in the DevOps subject).
addTopics([
  /* ---------- managed-distributions (K8s perspective only) ---------- */
  {
    id: 'managed-k8s-on-clouds-overview',
    title: 'Managed Kubernetes on Clouds Overview',
    parentId: 'managed-distributions',
    children: [
      { id: 'what-managed-k8s-provides', title: 'What Managed K8s Provides' },
      { id: 'managed-control-plane-vs-data-plane', title: 'Managed Control Plane vs Data Plane' },
      { id: 'managed-vs-self-managed-tradeoffs', title: 'Managed vs Self-Managed Trade-offs' },
      { id: 'cloud-native-vs-managed-on-prem', title: 'Cloud-Native vs Managed On-Prem' },
      { id: 'sla-and-control-plane-availability', title: 'SLA & Control-Plane Availability' },
    ],
  },
  {
    id: 'aws-eks-on-k8s-perspective',
    title: 'AWS EKS (K8s Perspective)',
    parentId: 'managed-distributions',
    children: [
      { id: 'eks-pointer-to-aws-subject', title: 'EKS (Pointer to AWS Subject)' },
      { id: 'eks-addons-from-k8s-angle', title: 'EKS Add-ons (K8s Angle)' },
      { id: 'eks-iam-and-irsa-on-k8s', title: 'EKS IAM & IRSA on K8s' },
      { id: 'eks-pod-identity-on-k8s', title: 'EKS Pod Identity on K8s' },
      { id: 'eks-vpc-cni-on-k8s', title: 'EKS VPC CNI on K8s' },
      { id: 'eks-fargate-on-k8s', title: 'EKS Fargate (K8s Angle)' },
      { id: 'eks-anywhere-and-eks-distro', title: 'EKS Anywhere & EKS Distro' },
      { id: 'eks-hybrid-nodes-pointer', title: 'EKS Hybrid Nodes (Pointer)' },
    ],
  },
  {
    id: 'gke-on-k8s',
    title: 'Google GKE on Kubernetes',
    parentId: 'managed-distributions',
    children: [
      { id: 'gke-control-plane', title: 'GKE Control Plane' },
      { id: 'gke-standard-vs-autopilot', title: 'Standard vs Autopilot' },
      { id: 'gke-version-release-channels', title: 'GKE Release Channels' },
      { id: 'gke-fleet-and-config-sync-pointer-stage21', title: 'GKE Fleet & Config Sync (Pointer)' },
      { id: 'gke-image-streaming-and-bin-packing', title: 'Image Streaming & Bin Packing' },
      { id: 'gke-workload-identity-on-k8s', title: 'GKE Workload Identity on K8s' },
      { id: 'gke-multi-cluster-services', title: 'GKE Multi-Cluster Services' },
      { id: 'anthos-on-k8s-pointer', title: 'Anthos (Pointer)' },
    ],
  },
  {
    id: 'aks-on-k8s-perspective',
    title: 'Azure AKS (K8s Perspective)',
    parentId: 'managed-distributions',
    children: [
      { id: 'aks-pointer-to-azure-subject', title: 'AKS (Pointer to Azure Subject)' },
      { id: 'aks-system-and-user-node-pools', title: 'System & User Node Pools' },
      { id: 'aks-virtual-nodes-on-k8s', title: 'AKS Virtual Nodes (K8s Angle)' },
      { id: 'aks-node-image-options', title: 'AKS Node Image Options' },
      { id: 'aks-workload-identity-on-k8s', title: 'AKS Workload Identity on K8s' },
      { id: 'aks-arc-pointer', title: 'Azure Arc-enabled K8s (Pointer)' },
      { id: 'aks-fleet-manager-pointer-stage21', title: 'AKS Fleet Manager (Pointer)' },
    ],
  },
  {
    id: 'ibm-cloud-kubernetes-service',
    title: 'IBM Cloud Kubernetes Service',
    parentId: 'managed-distributions',
    children: [
      { id: 'iks-overview', title: 'IKS Overview' },
      { id: 'iks-vs-openshift-on-ibm-cloud', title: 'IKS vs OpenShift on IBM Cloud' },
    ],
  },
  {
    id: 'oracle-oke',
    title: 'Oracle Kubernetes Engine (OKE)',
    parentId: 'managed-distributions',
    children: [
      { id: 'oke-overview', title: 'OKE Overview' },
      { id: 'oke-distribution-features', title: 'OKE Distribution Features' },
    ],
  },
  {
    id: 'other-managed-k8s-providers',
    title: 'Other Managed K8s Providers',
    parentId: 'managed-distributions',
    children: [
      { id: 'digitalocean-doks', title: 'DigitalOcean DOKS' },
      { id: 'linode-lke', title: 'Linode LKE' },
      { id: 'vultr-vke', title: 'Vultr VKE' },
      { id: 'alibaba-ack', title: 'Alibaba ACK' },
      { id: 'huawei-cce', title: 'Huawei CCE' },
      { id: 'tencent-tke', title: 'Tencent TKE' },
      { id: 'yandex-managed-k8s', title: 'Yandex Managed K8s' },
      { id: 'ovh-managed-k8s', title: 'OVH Managed K8s' },
      { id: 'civo-kubernetes', title: 'Civo Kubernetes' },
      { id: 'scaleway-kapsule', title: 'Scaleway Kapsule' },
    ],
  },
  {
    id: 'specialised-managed-clusters',
    title: 'Specialised Managed Clusters',
    parentId: 'managed-distributions',
    children: [
      { id: 'managed-arm-clusters', title: 'Managed ARM Clusters' },
      { id: 'managed-gpu-clusters', title: 'Managed GPU Clusters' },
      { id: 'managed-multi-cluster-control-planes-pointer', title: 'Managed Multi-Cluster Control Planes (Pointer)' },
    ],
  },
  {
    id: 'choosing-a-managed-distribution',
    title: 'Choosing a Managed Distribution',
    parentId: 'managed-distributions',
    children: [
      { id: 'managed-feature-comparison', title: 'Feature Comparison' },
      { id: 'managed-cost-comparison', title: 'Cost Comparison' },
      { id: 'managed-region-and-data-sovereignty', title: 'Region & Data Sovereignty' },
      { id: 'managed-vendor-lock-in', title: 'Vendor Lock-In' },
    ],
  },

  /* ---------- self-managed-distributions ---------- */
  {
    id: 'openshift-and-okd',
    title: 'OpenShift & OKD',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'openshift-overview', title: 'OpenShift Overview' },
      { id: 'okd-vs-openshift', title: 'OKD vs OpenShift' },
      { id: 'openshift-operators-ecosystem', title: 'OpenShift Operators Ecosystem' },
      { id: 'openshift-routes-and-ingress', title: 'OpenShift Routes & Ingress' },
      { id: 'openshift-security-context-constraints', title: 'Security Context Constraints (SCC)' },
      { id: 'openshift-builds-and-s2i', title: 'Builds & Source-to-Image (S2I)' },
      { id: 'openshift-pipelines-tekton', title: 'OpenShift Pipelines (Tekton)' },
      { id: 'openshift-gitops-argo', title: 'OpenShift GitOps (Argo)' },
      { id: 'openshift-virtualization-kubevirt', title: 'OpenShift Virtualization (KubeVirt)' },
      { id: 'openshift-on-public-cloud', title: 'OpenShift on Public Cloud' },
      { id: 'rosa-and-aro-pointer', title: 'ROSA & ARO (Pointer)' },
    ],
  },
  {
    id: 'rancher',
    title: 'Rancher',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'rancher-architecture', title: 'Rancher Architecture' },
      { id: 'rancher-rke', title: 'Rancher RKE' },
      { id: 'rancher-rke2', title: 'Rancher RKE2' },
      { id: 'rancher-k3s-pointer', title: 'Rancher k3s (Pointer)' },
      { id: 'rancher-fleet-pointer-stage21', title: 'Rancher Fleet (Pointer)' },
      { id: 'rancher-cluster-management', title: 'Rancher Cluster Management' },
      { id: 'longhorn-pointer', title: 'Longhorn (Pointer)' },
      { id: 'rancher-vs-other-distributions', title: 'Rancher vs Other Distributions' },
    ],
  },
  {
    id: 'vmware-tanzu',
    title: 'VMware Tanzu',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'tanzu-kubernetes-grid-tkg', title: 'Tanzu Kubernetes Grid (TKG)' },
      { id: 'tanzu-application-platform', title: 'Tanzu Application Platform' },
      { id: 'tanzu-mission-control', title: 'Tanzu Mission Control' },
      { id: 'tanzu-on-vsphere', title: 'Tanzu on vSphere' },
    ],
  },
  {
    id: 'k3s',
    title: 'k3s',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'k3s-overview', title: 'k3s Overview' },
      { id: 'k3s-architecture', title: 'k3s Architecture' },
      { id: 'k3s-storage', title: 'k3s Storage' },
      { id: 'k3s-networking', title: 'k3s Networking' },
      { id: 'k3s-for-edge-and-iot', title: 'k3s for Edge & IoT' },
      { id: 'k3s-air-gapped-pointer', title: 'k3s Air-Gapped (Pointer)' },
      { id: 'k3sup-tool', title: 'k3sup' },
    ],
  },
  {
    id: 'microk8s-as-distribution',
    title: 'MicroK8s as a Distribution',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'microk8s-distribution-overview', title: 'MicroK8s Distribution Overview' },
      { id: 'microk8s-strict-confinement', title: 'Strict Confinement' },
      { id: 'microk8s-tracks-and-channels', title: 'Tracks & Channels' },
      { id: 'microk8s-pointer-stage3', title: 'MicroK8s Basics (Pointer to Stage 3)' },
    ],
  },
  {
    id: 'talos-linux',
    title: 'Talos Linux',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'talos-overview', title: 'Talos Overview' },
      { id: 'talos-os-design', title: 'Talos OS Design (Immutable)' },
      { id: 'talos-config', title: 'Talos Machine Config' },
      { id: 'talosctl', title: 'talosctl CLI' },
      { id: 'talos-on-bare-metal', title: 'Talos on Bare Metal' },
      { id: 'talos-with-clusterapi', title: 'Talos With Cluster API' },
      { id: 'sidero-omni-pointer', title: 'Sidero / Omni (Pointer)' },
    ],
  },
  {
    id: 'bottlerocket-and-flatcar',
    title: 'Bottlerocket & Flatcar',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'bottlerocket-os', title: 'Bottlerocket OS' },
      { id: 'flatcar-container-linux', title: 'Flatcar Container Linux' },
      { id: 'immutable-os-on-k8s-tradeoffs', title: 'Immutable OS Trade-offs' },
    ],
  },
  {
    id: 'k0s',
    title: 'k0s',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'k0s-overview', title: 'k0s Overview' },
      { id: 'k0s-cluster-bootstrap', title: 'k0s Cluster Bootstrap' },
      { id: 'k0smotron-pointer', title: 'k0smotron (Pointer)' },
    ],
  },
  {
    id: 'kubeadm-and-kubespray-pointers',
    title: 'kubeadm & Kubespray (Pointers)',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'kubeadm-pointer-stage21', title: 'kubeadm (Pointer to Stage 3)' },
      { id: 'kubespray-pointer-stage21', title: 'Kubespray (Pointer to Stage 3)' },
      { id: 'kops-pointer-stage21', title: 'kOps (Pointer to Stage 3)' },
    ],
  },
  {
    id: 'other-self-managed-distributions',
    title: 'Other Self-Managed Distributions',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'charmed-kubernetes', title: 'Charmed Kubernetes' },
      { id: 'mirantis-mke', title: 'Mirantis Kubernetes Engine (MKE)' },
      { id: 'ezmeral-runtime', title: 'HPE Ezmeral Runtime' },
      { id: 'spectro-cloud-palette', title: 'Spectro Cloud Palette' },
      { id: 'd2iq-konvoy-pointer', title: 'D2iQ Konvoy (Pointer)' },
    ],
  },
  {
    id: 'choosing-a-self-managed-distribution',
    title: 'Choosing a Self-Managed Distribution',
    parentId: 'self-managed-distributions',
    children: [
      { id: 'self-managed-feature-comparison', title: 'Feature Comparison' },
      { id: 'support-and-lifecycle-comparison', title: 'Support & Lifecycle Comparison' },
      { id: 'self-managed-on-bare-metal', title: 'Self-Managed on Bare Metal' },
      { id: 'self-managed-on-private-cloud', title: 'Self-Managed on Private Cloud' },
    ],
  },

  /* ---------- platform-engineering (K8s-focused) ---------- */
  {
    id: 'platform-engineering-on-k8s-overview',
    title: 'Platform Engineering on Kubernetes Overview',
    parentId: 'platform-engineering',
    children: [
      { id: 'k8s-as-an-internal-developer-platform', title: 'K8s as an Internal Developer Platform' },
      { id: 'golden-paths-on-k8s', title: 'Golden Paths on K8s' },
      { id: 'paved-roads-on-k8s', title: 'Paved Roads on K8s' },
      { id: 'team-topologies-on-k8s-platform-pointer', title: 'Team Topologies on K8s (Pointer)' },
      { id: 'platform-as-a-product', title: 'Platform as a Product' },
      { id: 'measuring-platform-success', title: 'Measuring Platform Success' },
    ],
  },
  {
    id: 'crossplane',
    title: 'Crossplane',
    parentId: 'platform-engineering',
    children: [
      { id: 'crossplane-overview', title: 'Crossplane Overview' },
      { id: 'crossplane-architecture', title: 'Crossplane Architecture' },
      { id: 'crossplane-providers', title: 'Crossplane Providers' },
      { id: 'crossplane-managed-resources', title: 'Managed Resources' },
      { id: 'crossplane-compositions-v1', title: 'Compositions (v1)' },
      { id: 'crossplane-compositions-v2-and-functions', title: 'Compositions v2 & Composition Functions' },
      { id: 'crossplane-compositionrevisions', title: 'CompositionRevisions' },
      { id: 'crossplane-claims-and-xrds', title: 'Claims & XRDs' },
      { id: 'crossplane-composite-resources-xr', title: 'Composite Resources (XR)' },
      { id: 'crossplane-vs-terraform', title: 'Crossplane vs Terraform' },
      { id: 'crossplane-as-control-plane', title: 'Crossplane as a Control Plane' },
      { id: 'upbound-marketplace-pointer', title: 'Upbound Marketplace (Pointer)' },
    ],
  },
  {
    id: 'backstage-on-k8s',
    title: 'Backstage on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'backstage-overview', title: 'Backstage Overview' },
      { id: 'backstage-software-catalog', title: 'Software Catalog' },
      { id: 'backstage-on-k8s-deployment', title: 'Backstage on K8s Deployment' },
      { id: 'backstage-kubernetes-plugin', title: 'Backstage Kubernetes Plugin' },
      { id: 'backstage-templates-and-scaffolder', title: 'Templates & Scaffolder' },
      { id: 'backstage-techdocs', title: 'TechDocs' },
      { id: 'backstage-and-argocd-plugin', title: 'Backstage + Argo CD Plugin' },
      { id: 'backstage-rbac-and-multi-tenancy', title: 'Backstage RBAC & Multi-Tenancy' },
    ],
  },
  {
    id: 'humanitec-and-score-on-k8s',
    title: 'Humanitec & Score on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'humanitec-overview-pointer', title: 'Humanitec Overview (Pointer)' },
      { id: 'score-spec-on-k8s', title: 'Score Spec on K8s' },
      { id: 'score-helm-and-compose', title: 'Score Helm & Compose' },
    ],
  },
  {
    id: 'kratix',
    title: 'Kratix',
    parentId: 'platform-engineering',
    children: [
      { id: 'kratix-overview', title: 'Kratix Overview' },
      { id: 'kratix-promises', title: 'Kratix Promises' },
      { id: 'kratix-marketplace', title: 'Kratix Marketplace' },
    ],
  },
  {
    id: 'portainer-on-k8s',
    title: 'Portainer on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'portainer-overview', title: 'Portainer Overview' },
      { id: 'portainer-multi-cluster', title: 'Portainer Multi-Cluster' },
    ],
  },
  {
    id: 'k8s-as-control-plane-pattern',
    title: 'Kubernetes as a Control Plane Pattern',
    parentId: 'platform-engineering',
    children: [
      { id: 'choreo-and-control-plane-patterns', title: 'Choreo & Control-Plane Patterns' },
      { id: 'kcp-pointer-stage21', title: 'kcp (Pointer)' },
      { id: 'config-connector-pointer', title: 'Config Connector (Pointer)' },
      { id: 'aws-controllers-for-k8s-ack-pointer', title: 'AWS Controllers for K8s (ACK) (Pointer)' },
      { id: 'azure-service-operator-pointer', title: 'Azure Service Operator (Pointer)' },
    ],
  },
  {
    id: 'self-service-namespaces-on-k8s',
    title: 'Self-Service Namespaces on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'capsule-on-k8s-platform', title: 'Capsule on K8s' },
      { id: 'kiosk-on-k8s-platform', title: 'Kiosk on K8s' },
      { id: 'hierarchical-namespace-controller-hnc', title: 'Hierarchical Namespace Controller (HNC)' },
    ],
  },
  {
    id: 'cluster-as-a-service-on-k8s',
    title: 'Cluster-as-a-Service on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'vcluster-as-a-service', title: 'vcluster as a Service' },
      { id: 'kamaji-as-a-service-pointer', title: 'Kamaji as a Service (Pointer)' },
      { id: 'capi-as-a-service', title: 'Cluster API as a Service' },
    ],
  },
  {
    id: 'developer-experience-on-k8s',
    title: 'Developer Experience on Kubernetes',
    parentId: 'platform-engineering',
    children: [
      { id: 'skaffold-tilt-devspace-pointer', title: 'Skaffold / Tilt / DevSpace (Pointer)' },
      { id: 'okteto-pointer-stage21', title: 'Okteto (Pointer)' },
      { id: 'garden-pointer-stage21', title: 'Garden.io (Pointer)' },
      { id: 'dapr-on-k8s', title: 'Dapr on Kubernetes' },
    ],
  },
  {
    id: 'scoring-and-policy-frameworks-on-k8s',
    title: 'Scoring & Policy Frameworks on K8s',
    parentId: 'platform-engineering',
    children: [
      { id: 'kyverno-policy-bundles-platform', title: 'Kyverno Policy Bundles' },
      { id: 'gatekeeper-libraries-platform', title: 'Gatekeeper Libraries' },
      { id: 'polaris-and-kube-score', title: 'Polaris & kube-score' },
      { id: 'datree-pointer', title: 'Datree (Pointer)' },
    ],
  },
  {
    id: 'idp-frameworks-and-platforms-comparison',
    title: 'IDP Frameworks & Platforms Comparison',
    parentId: 'platform-engineering',
    children: [
      { id: 'rafay-and-uxp-pointer', title: 'Rafay & UXP (Pointer)' },
      { id: 'idp-comparison-on-k8s', title: 'IDP Comparison on K8s' },
      { id: 'building-vs-buying-an-idp', title: 'Build vs Buy an IDP' },
    ],
  },
])
