import { addTopics } from './addTopics.mjs'

// Stage 19 — Performance & Scalability
addTopics([
  /* ---------- cluster-scaling ---------- */
  {
    id: 'cluster-autoscaler-on-k8s',
    title: 'Cluster Autoscaler',
    parentId: 'cluster-scaling',
    children: [
      { id: 'cluster-autoscaler-overview', title: 'Cluster Autoscaler Overview' },
      { id: 'ca-architecture', title: 'CA Architecture' },
      { id: 'ca-cloud-provider-integrations', title: 'Cloud Provider Integrations' },
      { id: 'node-groups-and-pools', title: 'Node Groups & Pools' },
      { id: 'scale-up-mechanics', title: 'Scale-Up Mechanics' },
      { id: 'scale-down-mechanics', title: 'Scale-Down Mechanics' },
      { id: 'expander-strategies', title: 'Expander Strategies (random, most-pods, least-waste, priority)' },
      { id: 'balance-similar-node-groups', title: 'balance-similar-node-groups' },
      { id: 'skip-nodes-with-system-pods', title: 'skip-nodes-with-system-pods' },
      { id: 'taints-and-labels-for-ca', title: 'Taints & Labels for CA' },
      { id: 'ca-with-spot-instances', title: 'CA with Spot Instances' },
      { id: 'ca-vs-managed-autoscaler', title: 'CA vs Managed Autoscaler' },
    ],
  },
  {
    id: 'karpenter',
    title: 'Karpenter',
    parentId: 'cluster-scaling',
    children: [
      { id: 'karpenter-overview', title: 'Karpenter Overview' },
      { id: 'karpenter-architecture', title: 'Karpenter Architecture' },
      { id: 'nodepool-resource', title: 'NodePool Resource (v1)' },
      { id: 'nodeclass-resource', title: 'NodeClass Resource' },
      { id: 'karpenter-disruption-controls', title: 'Disruption Controls' },
      { id: 'karpenter-consolidation', title: 'Consolidation' },
      { id: 'karpenter-drift-handling', title: 'Drift Handling' },
      { id: 'karpenter-and-spot', title: 'Karpenter & Spot' },
      { id: 'karpenter-vs-cluster-autoscaler', title: 'Karpenter vs Cluster Autoscaler' },
      { id: 'multi-cloud-karpenter', title: 'Multi-Cloud Karpenter' },
      { id: 'karpenter-and-gpu', title: 'Karpenter & GPU Nodes' },
    ],
  },
  {
    id: 'cloud-node-autoprovisioning-pointer',
    title: 'Cloud Node Auto-Provisioning (Pointer)',
    parentId: 'cluster-scaling',
    children: [
      { id: 'gke-node-auto-provisioning-pointer', title: 'GKE Node Auto-Provisioning (Pointer)' },
      { id: 'eks-managed-node-groups-pointer', title: 'EKS Managed Node Groups (Pointer)' },
      { id: 'aks-virtual-node-pointer', title: 'AKS Virtual Node (Pointer)' },
    ],
  },
  {
    id: 'large-cluster-considerations',
    title: 'Large-Cluster Considerations',
    parentId: 'cluster-scaling',
    children: [
      { id: 'kubernetes-scalability-limits', title: 'Kubernetes Scalability Limits' },
      { id: '5000-node-clusters', title: '5,000-Node Clusters' },
      { id: '15000-node-clusters', title: '15,000-Node Clusters' },
      { id: 'apiserver-scaling-strategies', title: 'API Server Scaling Strategies' },
      { id: 'etcd-scaling-considerations-stage19', title: 'etcd Scaling Considerations' },
      { id: 'kubelet-scalability', title: 'kubelet Scalability' },
      { id: 'kube-proxy-scalability', title: 'kube-proxy Scalability' },
      { id: 'cni-scalability', title: 'CNI Scalability' },
      { id: 'dns-scalability-nodelocal', title: 'DNS Scalability (NodeLocal DNSCache)' },
      { id: 'controller-scalability', title: 'Controller Scalability' },
    ],
  },
  {
    id: 'cluster-tuning-knobs',
    title: 'Cluster Tuning Knobs',
    parentId: 'cluster-scaling',
    children: [
      { id: 'apiserver-flags-for-scale', title: 'apiserver Flags for Scale' },
      { id: 'kcm-flags-for-scale', title: 'KCM Flags for Scale' },
      { id: 'scheduler-flags-for-scale', title: 'Scheduler Flags for Scale' },
      { id: 'kubelet-flags-for-scale', title: 'kubelet Flags for Scale' },
    ],
  },
  {
    id: 'managed-control-plane-scaling-pointer',
    title: 'Managed Control Plane Scaling (Pointer)',
    parentId: 'cluster-scaling',
    children: [
      { id: 'managed-cp-scaling-overview', title: 'Managed CP Scaling Overview' },
      { id: 'large-managed-cluster-options-pointer', title: 'Large Managed Cluster Options (Pointer)' },
    ],
  },
  {
    id: 'multi-az-and-region-scaling',
    title: 'Multi-AZ & Region Scaling',
    parentId: 'cluster-scaling',
    children: [
      { id: 'multi-az-cluster-scaling', title: 'Multi-AZ Cluster Scaling' },
      { id: 'multi-region-cluster-scaling-pointer', title: 'Multi-Region (Pointer to Stage 16)' },
    ],
  },
  {
    id: 'cost-optimization-on-k8s',
    title: 'Cost Optimization on Kubernetes',
    parentId: 'cluster-scaling',
    children: [
      { id: 'rightsizing-clusters', title: 'Rightsizing Clusters' },
      { id: 'spot-and-preemptible-strategies', title: 'Spot & Preemptible Strategies' },
      { id: 'bin-packing', title: 'Bin Packing' },
      { id: 'kubecost-pointer', title: 'Kubecost (Pointer)' },
      { id: 'opencost-pointer', title: 'OpenCost (Pointer)' },
      { id: 'finops-on-k8s', title: 'FinOps on Kubernetes' },
      { id: 'idle-resource-detection', title: 'Idle Resource Detection' },
    ],
  },

  /* ---------- workload-autoscaling ---------- */
  {
    id: 'horizontal-pod-autoscaler',
    title: 'Horizontal Pod Autoscaler (HPA)',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'hpa-overview', title: 'HPA Overview' },
      { id: 'hpa-resource-v2', title: 'HPA v2 Resource' },
      { id: 'cpu-and-memory-autoscaling', title: 'CPU & Memory Autoscaling' },
      { id: 'custom-metrics-autoscaling', title: 'Custom Metrics Autoscaling' },
      { id: 'external-metrics-autoscaling', title: 'External Metrics Autoscaling' },
      { id: 'object-metrics-autoscaling', title: 'Object Metrics Autoscaling' },
      { id: 'hpa-behavior-policies', title: 'HPA Behavior Policies' },
      { id: 'hpa-stabilization-window', title: 'HPA Stabilization Window' },
      { id: 'hpa-tolerance', title: 'HPA Tolerance' },
      { id: 'hpa-debugging', title: 'HPA Debugging' },
      { id: 'hpa-on-statefulset', title: 'HPA on StatefulSet' },
      { id: 'hpa-on-custom-resources', title: 'HPA on Custom Resources (scale subresource)' },
    ],
  },
  {
    id: 'vertical-pod-autoscaler',
    title: 'Vertical Pod Autoscaler (VPA)',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'vpa-overview', title: 'VPA Overview' },
      { id: 'vpa-architecture', title: 'VPA Architecture' },
      { id: 'vpa-recommender', title: 'VPA Recommender' },
      { id: 'vpa-updater', title: 'VPA Updater' },
      { id: 'vpa-admission-controller', title: 'VPA Admission Controller' },
      { id: 'vpa-update-modes', title: 'VPA Update Modes (Off, Initial, Recreate, Auto, InPlace)' },
      { id: 'vpa-with-in-place-resize', title: 'VPA + In-Place Pod Resize' },
      { id: 'vpa-vs-hpa-coexistence', title: 'VPA vs HPA Coexistence' },
    ],
  },
  {
    id: 'keda',
    title: 'KEDA',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'keda-overview', title: 'KEDA Overview' },
      { id: 'keda-architecture', title: 'KEDA Architecture' },
      { id: 'scaledobject-resource', title: 'ScaledObject Resource' },
      { id: 'scaledjob-resource', title: 'ScaledJob Resource' },
      { id: 'keda-triggers', title: 'KEDA Triggers (Kafka, Prometheus, Cron, SQS, Pub/Sub, RabbitMQ, Azure, etc.)' },
      { id: 'keda-authentication-providers', title: 'KEDA Authentication Providers' },
      { id: 'scale-to-zero-with-keda', title: 'Scale-to-Zero With KEDA' },
      { id: 'keda-with-hpa', title: 'KEDA With HPA' },
      { id: 'keda-and-event-driven-patterns', title: 'KEDA & Event-Driven Patterns' },
    ],
  },
  {
    id: 'predictive-and-multidim-autoscaling',
    title: 'Predictive & Multi-Dimensional Autoscaling',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'predictive-vs-reactive-autoscaling', title: 'Predictive vs Reactive Autoscaling' },
      { id: 'predictive-hpa-and-others', title: 'Predictive HPA & Others' },
      { id: 'multidim-pod-autoscaler-mpa', title: 'Multi-Dimensional Pod Autoscaler (MPA)' },
      { id: 'vertical-and-horizontal-together', title: 'Vertical + Horizontal Together' },
    ],
  },
  {
    id: 'in-place-resize-autoscaling-pointer',
    title: 'In-Place Pod Resize Autoscaling (Pointer)',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'in-place-resize-pointer-stage19', title: 'In-Place Resize (Pointer to Stage 4)' },
      { id: 'inplace-vs-recreate-autoscaling', title: 'In-Place vs Recreate Autoscaling' },
    ],
  },
  {
    id: 'application-and-runtime-autoscaling',
    title: 'Application & Runtime Autoscaling',
    parentId: 'workload-autoscaling',
    children: [
      { id: 'knative-autoscaler-pointer', title: 'Knative Autoscaler (Pointer)' },
      { id: 'openfaas-and-fission-pointer', title: 'OpenFaaS & Fission (Pointer)' },
      { id: 'application-resource-recommender-pointer', title: 'Application Resource Recommender (Pointer)' },
    ],
  },

  /* ---------- performance-tuning ---------- */
  {
    id: 'performance-baseline-on-k8s',
    title: 'Performance Baseline on K8s',
    parentId: 'performance-tuning',
    children: [
      { id: 'sli-slo-on-k8s', title: 'SLI / SLO on K8s' },
      { id: 'latency-throughput-budgets', title: 'Latency / Throughput Budgets' },
      { id: 'common-bottlenecks-on-k8s', title: 'Common Bottlenecks on K8s' },
      { id: 'observability-for-tuning-pointer', title: 'Observability for Tuning (Pointer)' },
    ],
  },
  {
    id: 'benchmarking-and-load-testing',
    title: 'Benchmarking & Load Testing',
    parentId: 'performance-tuning',
    children: [
      { id: 'kube-burner', title: 'kube-burner' },
      { id: 'clusterloader2', title: 'ClusterLoader2' },
      { id: 'perf-tests-repo', title: 'kubernetes/perf-tests Repo' },
      { id: 'vegeta-and-k6-on-k8s-pointer', title: 'Vegeta & k6 on K8s (Pointer)' },
      { id: 'locust-on-k8s-pointer', title: 'Locust on K8s (Pointer)' },
    ],
  },
  {
    id: 'node-tuning',
    title: 'Node Tuning',
    parentId: 'performance-tuning',
    children: [
      { id: 'kernel-tuning-for-k8s-pointer', title: 'Kernel Tuning (Pointer to Stage 1)' },
      { id: 'cpu-frequency-governor', title: 'CPU Frequency Governor' },
      { id: 'hugepages-on-k8s', title: 'HugePages on K8s' },
      { id: 'irq-affinity-tuning', title: 'IRQ Affinity' },
      { id: 'numa-tuning', title: 'NUMA Tuning' },
      { id: 'sysctl-tuning', title: 'sysctl Tuning' },
      { id: 'filesystem-tuning', title: 'Filesystem Tuning' },
      { id: 'block-io-and-elevator-tuning', title: 'Block I/O & Elevator Tuning' },
      { id: 'tuned-and-performance-profiles', title: 'tuned & Performance Profiles' },
    ],
  },
  {
    id: 'container-runtime-tuning',
    title: 'Container Runtime Tuning',
    parentId: 'performance-tuning',
    children: [
      { id: 'containerd-tuning', title: 'containerd Tuning' },
      { id: 'cri-o-tuning', title: 'CRI-O Tuning' },
      { id: 'shim-and-cgroup-driver-tuning', title: 'Shim & cgroup Driver Tuning' },
      { id: 'image-pull-tuning', title: 'Image Pull Tuning' },
    ],
  },
  {
    id: 'cpu-and-memory-tuning',
    title: 'CPU & Memory Tuning',
    parentId: 'performance-tuning',
    children: [
      { id: 'cpu-manager-static-policy-stage19', title: 'CPU Manager Static Policy' },
      { id: 'memory-manager-policy-stage19', title: 'Memory Manager Policy' },
      { id: 'topology-manager-policy-stage19', title: 'Topology Manager Policy' },
      { id: 'cpu-pinning-and-isolation', title: 'CPU Pinning & Isolation' },
      { id: 'hugepages-allocation-strategies', title: 'HugePages Allocation Strategies' },
      { id: 'cpu-throttling-detection', title: 'CPU Throttling Detection' },
    ],
  },
  {
    id: 'network-performance-tuning',
    title: 'Network Performance Tuning',
    parentId: 'performance-tuning',
    children: [
      { id: 'cilium-bpf-tuning', title: 'Cilium eBPF Tuning' },
      { id: 'calico-ebpf-tuning', title: 'Calico eBPF Tuning' },
      { id: 'kube-proxy-mode-comparison-perf', title: 'kube-proxy Mode Comparison (Perf)' },
      { id: 'mtu-tuning-perf', title: 'MTU Tuning' },
      { id: 'tcp-stack-tuning', title: 'TCP Stack Tuning' },
      { id: 'dns-perf-tuning', title: 'DNS Perf Tuning' },
      { id: 'service-mesh-overhead', title: 'Service Mesh Overhead' },
    ],
  },
  {
    id: 'storage-performance-tuning',
    title: 'Storage Performance Tuning',
    parentId: 'performance-tuning',
    children: [
      { id: 'csi-driver-tuning', title: 'CSI Driver Tuning' },
      { id: 'block-vs-filesystem-perf', title: 'Block vs Filesystem Perf' },
      { id: 'rwx-vs-rwo-perf', title: 'RWX vs RWO Perf' },
      { id: 'local-vs-network-storage-perf', title: 'Local vs Network Storage Perf' },
      { id: 'storage-iops-budgets', title: 'Storage IOPS Budgets' },
    ],
  },
  {
    id: 'apiserver-performance',
    title: 'API Server Performance',
    parentId: 'performance-tuning',
    children: [
      { id: 'apf-tuning', title: 'API Priority & Fairness Tuning' },
      { id: 'watch-cache-tuning', title: 'Watch Cache Tuning' },
      { id: 'request-flow-control', title: 'Request Flow Control' },
      { id: 'apiserver-protobuf-vs-json', title: 'protobuf vs JSON' },
      { id: 'large-list-vs-watch', title: 'Large LIST vs WATCH' },
    ],
  },
  {
    id: 'etcd-tuning-for-perf',
    title: 'etcd Tuning for Performance',
    parentId: 'performance-tuning',
    children: [
      { id: 'etcd-iops-and-latency-budgets', title: 'IOPS & Latency Budgets' },
      { id: 'etcd-defrag-and-compaction-tuning', title: 'Defrag & Compaction Tuning' },
      { id: 'etcd-mvcc-history-tuning', title: 'MVCC History Tuning' },
      { id: 'etcd-quota-backend-bytes', title: 'quota-backend-bytes' },
      { id: 'etcd-perf-pointer-stage9', title: 'etcd Performance (Pointer to Stage 9)' },
    ],
  },
  {
    id: 'scheduler-performance',
    title: 'Scheduler Performance',
    parentId: 'performance-tuning',
    children: [
      { id: 'scheduler-throughput-tuning', title: 'Scheduler Throughput Tuning' },
      { id: 'parallelism-and-percentage-of-nodes-to-score', title: 'Parallelism & percentageOfNodesToScore' },
      { id: 'scheduler-profiles-perf', title: 'Scheduler Profiles for Perf' },
    ],
  },
  {
    id: 'workload-tuning-on-k8s',
    title: 'Workload Tuning on Kubernetes',
    parentId: 'performance-tuning',
    children: [
      { id: 'jvm-on-k8s-pointer', title: 'JVM on K8s (Pointer)' },
      { id: 'golang-on-k8s-pointer', title: 'Go on K8s (Pointer)' },
      { id: 'python-on-k8s-pointer', title: 'Python on K8s (Pointer)' },
      { id: 'nodejs-on-k8s-pointer', title: 'Node.js on K8s (Pointer)' },
    ],
  },
  {
    id: 'profiling-on-k8s',
    title: 'Profiling on Kubernetes',
    parentId: 'performance-tuning',
    children: [
      { id: 'continuous-profiling-pointer-stage19', title: 'Continuous Profiling (Pointer to Stage 11)' },
      { id: 'pprof-on-k8s', title: 'pprof on K8s' },
      { id: 'parca-on-k8s', title: 'Parca on K8s' },
      { id: 'pyroscope-on-k8s', title: 'Pyroscope on K8s' },
    ],
  },
])
