import { addTopics } from './addTopics.mjs'

// Stage 7 — Storage & Volumes
addTopics([
  /* ---------- volumes-fundamentals ---------- */
  {
    id: 'volume-concept',
    title: 'Volume Concept',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'volume-purpose', title: 'Volume Purpose' },
      { id: 'volume-vs-mount', title: 'Volume vs Mount' },
      { id: 'volume-lifecycle-with-pod', title: 'Volume Lifecycle (Tied to Pod)' },
      { id: 'volume-vs-persistentvolume', title: 'Volume vs PersistentVolume' },
      { id: 'volume-source-vs-volume', title: 'volumes vs volumeSource Spec' },
    ],
  },
  {
    id: 'emptydir',
    title: 'emptyDir',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'emptydir-overview', title: 'emptyDir Overview' },
      { id: 'emptydir-medium-default', title: 'medium: "" (Default)' },
      { id: 'emptydir-medium-memory', title: 'medium: Memory (tmpfs)' },
      { id: 'emptydir-sizelimit', title: 'sizeLimit' },
      { id: 'emptydir-use-cases', title: 'Common Use Cases' },
    ],
  },
  {
    id: 'hostpath',
    title: 'hostPath',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'hostpath-overview', title: 'hostPath Overview' },
      { id: 'hostpath-types', title: 'hostPath Types (Directory, File, Socket, ...)' },
      { id: 'hostpath-security-risks', title: 'hostPath Security Risks' },
      { id: 'hostpath-vs-local-pv', title: 'hostPath vs Local PV' },
    ],
  },
  {
    id: 'ephemeral-volumes',
    title: 'Ephemeral Volumes',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'generic-ephemeral-volumes', title: 'Generic Ephemeral Volumes' },
      { id: 'csi-ephemeral-volumes', title: 'CSI Ephemeral Volumes' },
      { id: 'configmap-secret-downwardapi-as-ephemeral', title: 'ConfigMap / Secret / DownwardAPI as Ephemeral' },
      { id: 'image-volumes-ephemeral', title: 'Image Volumes (Pointer)' },
    ],
  },
  {
    id: 'volume-mounts',
    title: 'Volume Mounts',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'mountpath', title: 'mountPath' },
      { id: 'subpath-and-subpathexpr', title: 'subPath & subPathExpr' },
      { id: 'mount-propagation', title: 'Mount Propagation (None, HostToContainer, Bidirectional)' },
      { id: 'mount-readonly', title: 'readOnly' },
      { id: 'recursive-read-only-mounts', title: 'Recursive Read-Only Mounts (KEP-3857)' },
      { id: 'mount-options-from-pod', title: 'mountOptions From Pod' },
    ],
  },
  {
    id: 'in-tree-volume-types-legacy',
    title: 'In-Tree Volume Types (Legacy)',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'nfs-volume', title: 'NFS Volume' },
      { id: 'iscsi-volume', title: 'iSCSI Volume' },
      { id: 'fc-volume', title: 'Fibre Channel (FC) Volume' },
      { id: 'cifs-smb-volume', title: 'CIFS/SMB Volume' },
      { id: 'rbd-volume', title: 'Ceph RBD Volume' },
      { id: 'cephfs-volume', title: 'CephFS Volume' },
      { id: 'glusterfs-volume', title: 'GlusterFS Volume (Removed)' },
      { id: 'portworx-volume-in-tree', title: 'Portworx (Removed In-Tree)' },
    ],
  },
  {
    id: 'in-tree-vs-out-of-tree-drivers',
    title: 'In-Tree vs Out-of-Tree Drivers',
    parentId: 'volumes-fundamentals',
    children: [
      { id: 'in-tree-volume-plugins', title: 'In-Tree Volume Plugins' },
      { id: 'flexvolume-deprecated', title: 'FlexVolume (Deprecated)' },
      { id: 'csi-migration-overview', title: 'CSI Migration Overview' },
      { id: 'csi-migration-status', title: 'CSI Migration Status by Driver' },
    ],
  },

  /* ---------- persistent-volumes ---------- */
  {
    id: 'pv-pvc-fundamentals',
    title: 'PV & PVC Fundamentals',
    parentId: 'persistent-volumes',
    children: [
      { id: 'persistentvolume-resource', title: 'PersistentVolume Resource' },
      { id: 'persistentvolumeclaim-resource', title: 'PersistentVolumeClaim Resource' },
      { id: 'pv-pvc-lifecycle', title: 'PV/PVC Lifecycle' },
      { id: 'claim-binding-process', title: 'Claim Binding Process' },
      { id: 'static-vs-dynamic-provisioning', title: 'Static vs Dynamic Provisioning' },
    ],
  },
  {
    id: 'access-modes',
    title: 'Access Modes',
    parentId: 'persistent-volumes',
    children: [
      { id: 'readwriteonce', title: 'ReadWriteOnce' },
      { id: 'readonlymany', title: 'ReadOnlyMany' },
      { id: 'readwritemany', title: 'ReadWriteMany' },
      { id: 'readwriteoncepod', title: 'ReadWriteOncePod (GA v1.29)' },
      { id: 'access-mode-driver-support', title: 'Access Mode Support per Driver' },
    ],
  },
  {
    id: 'volume-modes',
    title: 'Volume Modes',
    parentId: 'persistent-volumes',
    children: [
      { id: 'filesystem-mode', title: 'Filesystem Mode' },
      { id: 'block-mode', title: 'Block Mode' },
      { id: 'block-mode-use-cases', title: 'Block Mode Use Cases' },
    ],
  },
  {
    id: 'reclaim-policies',
    title: 'Reclaim Policies',
    parentId: 'persistent-volumes',
    children: [
      { id: 'reclaim-retain', title: 'Retain' },
      { id: 'reclaim-delete', title: 'Delete' },
      { id: 'reclaim-recycle-deprecated', title: 'Recycle (Deprecated)' },
      { id: 'reclaim-policy-on-pv-vs-sc', title: 'Reclaim Policy: PV vs StorageClass' },
    ],
  },
  {
    id: 'pv-pvc-phases',
    title: 'PV / PVC Phases',
    parentId: 'persistent-volumes',
    children: [
      { id: 'pv-phase-available', title: 'Available' },
      { id: 'pv-phase-bound', title: 'Bound' },
      { id: 'pv-phase-released', title: 'Released' },
      { id: 'pv-phase-failed', title: 'Failed' },
      { id: 'pvc-pending-vs-bound', title: 'PVC Pending vs Bound' },
    ],
  },
  {
    id: 'pvc-resize',
    title: 'PVC Resize',
    parentId: 'persistent-volumes',
    children: [
      { id: 'allowvolumeexpansion', title: 'allowVolumeExpansion' },
      { id: 'online-volume-expansion', title: 'Online Volume Expansion' },
      { id: 'offline-volume-expansion', title: 'Offline Volume Expansion' },
      { id: 'recovery-from-resize-failure', title: 'Recovery from Resize Failure' },
    ],
  },
  {
    id: 'volumeattributesclass',
    title: 'VolumeAttributesClass',
    parentId: 'persistent-volumes',
    children: [
      { id: 'vac-resource', title: 'VolumeAttributesClass Resource (KEP-3751)' },
      { id: 'changing-vac-on-pvc', title: 'Changing VAC on PVC' },
      { id: 'vac-driver-support', title: 'VAC Driver Support' },
    ],
  },
  {
    id: 'volume-snapshot',
    title: 'Volume Snapshots',
    parentId: 'persistent-volumes',
    children: [
      { id: 'volumesnapshot-resource', title: 'VolumeSnapshot Resource' },
      { id: 'volumesnapshotcontent-resource', title: 'VolumeSnapshotContent Resource' },
      { id: 'volumesnapshotclass-resource', title: 'VolumeSnapshotClass Resource' },
      { id: 'snapshot-lifecycle', title: 'Snapshot Lifecycle' },
      { id: 'snapshot-controller', title: 'External Snapshot Controller' },
      { id: 'incremental-snapshots', title: 'Incremental Snapshots' },
    ],
  },
  {
    id: 'volume-cloning-and-data-sources',
    title: 'Volume Cloning & Data Sources',
    parentId: 'persistent-volumes',
    children: [
      { id: 'creating-pvc-from-snapshot', title: 'Creating PVC from Snapshot' },
      { id: 'creating-pvc-from-pvc-clone', title: 'Creating PVC from PVC (Clone)' },
      { id: 'data-source-vs-data-source-ref', title: 'dataSource vs dataSourceRef' },
      { id: 'any-volume-data-source', title: 'AnyVolumeDataSource' },
      { id: 'volume-populator-controller', title: 'Volume Populator Controller' },
      { id: 'volume-populator-from-image', title: 'Populating from Image' },
    ],
  },
  {
    id: 'volumegroupsnapshots',
    title: 'VolumeGroupSnapshots',
    parentId: 'persistent-volumes',
    children: [
      { id: 'vgs-overview', title: 'VolumeGroupSnapshot Overview (KEP-3476)' },
      { id: 'vgs-resource', title: 'VolumeGroupSnapshot Resource' },
      { id: 'vgs-content', title: 'VolumeGroupSnapshotContent' },
      { id: 'vgs-class', title: 'VolumeGroupSnapshotClass' },
      { id: 'vgs-driver-support', title: 'VGS Driver Support' },
    ],
  },

  /* ---------- storage-classes-csi ---------- */
  {
    id: 'storage-classes',
    title: 'StorageClasses',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'storageclass-resource', title: 'StorageClass Resource' },
      { id: 'default-storageclass', title: 'Default StorageClass' },
      { id: 'multiple-default-storageclass-handling', title: 'Multiple Default StorageClass Handling' },
      { id: 'reclaim-policy-from-storageclass', title: 'reclaimPolicy from StorageClass' },
      { id: 'volume-binding-mode', title: 'volumeBindingMode (Immediate vs WaitForFirstConsumer)' },
      { id: 'allowed-topologies', title: 'allowedTopologies' },
      { id: 'storageclass-parameters', title: 'parameters Field' },
      { id: 'storageclass-mountoptions', title: 'mountOptions' },
    ],
  },
  {
    id: 'csi-fundamentals',
    title: 'CSI Fundamentals',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csi-spec-overview', title: 'CSI Spec Overview' },
      { id: 'csi-controller-plugin', title: 'CSI Controller Plugin' },
      { id: 'csi-node-plugin', title: 'CSI Node Plugin' },
      { id: 'csi-identity-service', title: 'CSI Identity Service' },
      { id: 'csi-driver-installation', title: 'CSI Driver Installation' },
      { id: 'csidriver-resource', title: 'CSIDriver Resource' },
      { id: 'csinode-resource', title: 'CSINode Resource' },
      { id: 'external-provisioner-attacher-resizer-snapshotter', title: 'External Provisioner / Attacher / Resizer / Snapshotter Sidecars' },
      { id: 'node-driver-registrar', title: 'Node Driver Registrar' },
      { id: 'livenessprobe-sidecar', title: 'liveness-probe Sidecar' },
    ],
  },
  {
    id: 'csi-features',
    title: 'CSI Features',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csi-provisioning', title: 'Provisioning' },
      { id: 'csi-attach-detach', title: 'Attach / Detach' },
      { id: 'csi-mount-unmount', title: 'Mount / Unmount' },
      { id: 'csi-resize', title: 'Online Resize' },
      { id: 'csi-snapshot', title: 'Snapshots' },
      { id: 'csi-clone', title: 'Cloning' },
      { id: 'csi-volume-health', title: 'Volume Health' },
      { id: 'csi-volume-stats', title: 'Volume Stats' },
      { id: 'csi-ephemeral-volumes-feature', title: 'Ephemeral Volumes' },
      { id: 'csi-windows-support', title: 'Windows Support' },
      { id: 'csi-volume-attributes-class', title: 'VolumeAttributesClass Support' },
    ],
  },
  {
    id: 'csi-topology',
    title: 'CSI Topology',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csi-topology-keys', title: 'Topology Keys' },
      { id: 'waitforfirstconsumer-binding', title: 'WaitForFirstConsumer Binding' },
      { id: 'immediate-binding', title: 'Immediate Binding' },
      { id: 'topology-and-zone-awareness', title: 'Zone-Aware Provisioning' },
    ],
  },
  {
    id: 'csi-driver-ecosystem',
    title: 'CSI Driver Ecosystem',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'aws-ebs-csi', title: 'AWS EBS CSI Driver' },
      { id: 'aws-efs-csi', title: 'AWS EFS CSI Driver' },
      { id: 'aws-fsx-csi', title: 'AWS FSx CSI Driver' },
      { id: 'azure-disk-csi', title: 'Azure Disk CSI Driver' },
      { id: 'azure-file-csi', title: 'Azure File CSI Driver' },
      { id: 'azure-blob-csi', title: 'Azure Blob CSI Driver' },
      { id: 'gce-pd-csi', title: 'GCE PD CSI Driver' },
      { id: 'gcs-fuse-csi', title: 'GCS FUSE CSI Driver' },
      { id: 'vsphere-csi', title: 'vSphere CSI Driver' },
      { id: 'openstack-cinder-csi', title: 'OpenStack Cinder CSI' },
      { id: 'rook-ceph-csi', title: 'Rook / Ceph CSI' },
      { id: 'longhorn-csi', title: 'Longhorn CSI' },
      { id: 'openebs-csi', title: 'OpenEBS CSI' },
      { id: 'portworx-csi', title: 'Portworx CSI' },
      { id: 'linstor-csi', title: 'Linstor / DRBD CSI' },
      { id: 'hostpath-csi', title: 'HostPath CSI (Reference Driver)' },
      { id: 'smb-csi', title: 'SMB CSI' },
      { id: 'nfs-csi', title: 'NFS CSI' },
      { id: 's3-csi', title: 'S3 CSI (Mountpoint for S3)' },
      { id: 'juicefs-csi', title: 'JuiceFS CSI' },
    ],
  },
  {
    id: 'node-local-storage',
    title: 'Node-Local Storage',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'local-pv', title: 'Local PersistentVolume' },
      { id: 'local-volume-static-provisioner', title: 'Local Volume Static Provisioner' },
      { id: 'openebs-local-pv', title: 'OpenEBS Local PV' },
      { id: 'topolvm', title: 'TopoLVM' },
    ],
  },
  {
    id: 'raw-block-volumes',
    title: 'Raw Block Volumes',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'block-volume-mode-recap', title: 'Block VolumeMode Recap' },
      { id: 'using-raw-block-in-pods', title: 'Using Raw Block in Pods' },
      { id: 'block-volume-use-cases', title: 'Block Volume Use Cases (DBs, Custom FS)' },
    ],
  },
  {
    id: 'csi-secrets-and-credentials',
    title: 'CSI Secrets & Credentials',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csi-publish-secrets', title: 'controllerPublishSecret / nodePublishSecret' },
      { id: 'csi-provision-secrets', title: 'provisionerSecret' },
      { id: 'per-volume-credentials', title: 'Per-Volume Credentials' },
    ],
  },
  {
    id: 'storage-capacity-tracking',
    title: 'Storage Capacity Tracking',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csistoragecapacity-resource', title: 'CSIStorageCapacity Resource' },
      { id: 'capacity-aware-scheduling', title: 'Capacity-Aware Scheduling' },
    ],
  },
  {
    id: 'volume-migration',
    title: 'In-Tree → CSI Migration',
    parentId: 'storage-classes-csi',
    children: [
      { id: 'csi-migration-overview-deep', title: 'CSI Migration Process' },
      { id: 'feature-gates-for-migration', title: 'Feature Gates for Migration' },
      { id: 'compatibility-shims', title: 'Compatibility Shims' },
      { id: 'csi-migration-final-status', title: 'Migration Status & Removed Drivers' },
    ],
  },
])
