import { addTopics } from './addTopics.mjs'

// Stage 15 — Service Mesh & Advanced Networking
// service-mesh-fundamentals is refocused: K8s-integration angle only
// (generic service-mesh theory lives in the DevOps subject).
addTopics([
  /* ---------- service-mesh-fundamentals (K8s-focused) ---------- */
  {
    id: 'service-mesh-on-k8s-overview',
    title: 'Service Mesh on Kubernetes Overview',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'what-mesh-adds-on-top-of-k8s', title: 'What a Mesh Adds on Top of Kubernetes' },
      { id: 'sidecar-vs-sidecarless-on-k8s', title: 'Sidecar vs Sidecarless on K8s' },
      { id: 'mesh-vs-ingress-vs-gateway-api', title: 'Mesh vs Ingress vs Gateway API' },
      { id: 'mesh-vs-network-policies-on-k8s', title: 'Mesh vs NetworkPolicies' },
      { id: 'mesh-control-plane-vs-data-plane-on-k8s', title: 'Mesh Control Plane vs Data Plane on K8s' },
      { id: 'when-not-to-use-a-mesh', title: 'When Not to Use a Mesh' },
    ],
  },
  {
    id: 'istio-on-kubernetes',
    title: 'Istio on Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'istio-architecture-on-k8s', title: 'Istio Architecture on K8s' },
      { id: 'istiod-deployment', title: 'istiod Deployment' },
      { id: 'istio-sidecar-injection', title: 'Sidecar Injection' },
      { id: 'istio-ambient-mode', title: 'Istio Ambient Mode' },
      { id: 'istio-ztunnel-and-waypoints', title: 'ztunnel & Waypoint Proxies' },
      { id: 'istio-crds', title: 'Istio CRD Suite' },
      { id: 'istio-virtualservice', title: 'VirtualService' },
      { id: 'istio-destinationrule', title: 'DestinationRule' },
      { id: 'istio-gateway', title: 'Istio Gateway Resource' },
      { id: 'istio-peerauthentication', title: 'PeerAuthentication' },
      { id: 'istio-authorizationpolicy', title: 'AuthorizationPolicy' },
      { id: 'istio-installation-options', title: 'Installation: istioctl, Helm, Operator' },
      { id: 'istio-multi-cluster-on-k8s', title: 'Istio Multi-Cluster' },
      { id: 'istio-upgrades', title: 'Istio Upgrades & Revisions' },
      { id: 'istio-gateway-api-support', title: 'Istio + Gateway API Support' },
    ],
  },
  {
    id: 'linkerd-on-kubernetes',
    title: 'Linkerd on Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'linkerd-architecture', title: 'Linkerd Architecture' },
      { id: 'linkerd-control-plane', title: 'Linkerd Control Plane' },
      { id: 'linkerd2-proxy-data-plane', title: 'linkerd2-proxy Data Plane' },
      { id: 'linkerd-injection', title: 'Linkerd Injection' },
      { id: 'linkerd-policies-and-extensions', title: 'Policies & Extensions' },
      { id: 'linkerd-multicluster', title: 'Linkerd Multicluster' },
      { id: 'linkerd-viz-and-jaeger-extensions', title: 'linkerd-viz & Jaeger Extensions' },
    ],
  },
  {
    id: 'cilium-service-mesh',
    title: 'Cilium Service Mesh',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'cilium-sidecarless-mesh', title: 'Cilium Sidecarless Mesh' },
      { id: 'cilium-envoy-integration', title: 'Cilium + Envoy Integration' },
      { id: 'cilium-mesh-policies', title: 'Cilium Mesh Policies' },
      { id: 'cilium-mtls-on-k8s', title: 'Cilium mTLS' },
      { id: 'cilium-clustermesh-pointer', title: 'ClusterMesh (Pointer)' },
    ],
  },
  {
    id: 'consul-on-kubernetes',
    title: 'Consul on Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'consul-helm-chart', title: 'Consul Helm Chart' },
      { id: 'consul-control-plane-on-k8s', title: 'Consul Control Plane on K8s' },
      { id: 'consul-connect-injector', title: 'Consul Connect Injector' },
      { id: 'consul-api-gateway-on-k8s', title: 'Consul API Gateway on K8s' },
      { id: 'consul-cluster-peering', title: 'Consul Cluster Peering' },
    ],
  },
  {
    id: 'kuma-on-kubernetes',
    title: 'Kuma on Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'kuma-control-plane-on-k8s', title: 'Kuma Control Plane on K8s' },
      { id: 'kuma-policies-on-k8s', title: 'Kuma Policies on K8s' },
      { id: 'kuma-multi-zone', title: 'Kuma Multi-Zone' },
    ],
  },
  {
    id: 'mesh-features-on-k8s',
    title: 'Mesh Features on Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'mtls-and-spiffe-identity', title: 'mTLS & SPIFFE Identity' },
      { id: 'traffic-policy-and-routing', title: 'Traffic Policy & Routing' },
      { id: 'retries-timeouts-circuit-breakers', title: 'Retries, Timeouts, Circuit Breakers' },
      { id: 'rate-limiting-and-quotas', title: 'Rate Limiting & Quotas' },
      { id: 'request-authn-and-authz-on-mesh', title: 'Request AuthN & AuthZ on Mesh' },
      { id: 'mesh-observability-on-k8s-pointer', title: 'Mesh Observability (Pointer to Stage 11)' },
      { id: 'canary-and-traffic-splitting-on-mesh', title: 'Canary & Traffic Splitting on Mesh' },
      { id: 'fault-injection', title: 'Fault Injection' },
      { id: 'egress-traffic-control', title: 'Egress Traffic Control' },
    ],
  },
  {
    id: 'gateway-api-and-mesh',
    title: 'Gateway API & Mesh (GAMMA)',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'gamma-initiative', title: 'GAMMA Initiative' },
      { id: 'service-as-parentref', title: 'Service as parentRef' },
      { id: 'mesh-policy-attachment', title: 'Mesh Policy Attachment' },
    ],
  },
  {
    id: 'choosing-a-mesh-for-k8s',
    title: 'Choosing a Mesh for Kubernetes',
    parentId: 'service-mesh-fundamentals',
    children: [
      { id: 'feature-comparison-meshes', title: 'Feature Comparison' },
      { id: 'operational-overhead-meshes', title: 'Operational Overhead' },
      { id: 'sidecar-vs-ambient-tradeoffs', title: 'Sidecar vs Ambient Trade-offs' },
      { id: 'mesh-and-multi-tenancy', title: 'Mesh & Multi-Tenancy' },
    ],
  },

  /* ---------- cni-deep-dive ---------- */
  {
    id: 'cni-spec-deep',
    title: 'CNI Specification Deep Dive',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'cni-versions', title: 'CNI Versions' },
      { id: 'cni-config-and-conflist', title: 'CNI Config & conflist' },
      { id: 'cni-plugin-chain', title: 'Plugin Chain' },
      { id: 'cni-result-types', title: 'CNI Result Types' },
      { id: 'cni-binary-locations', title: 'CNI Binary & Config Locations' },
      { id: 'cni-add-del-check-version', title: 'ADD / DEL / CHECK / VERSION' },
      { id: 'cni-status-verb', title: 'STATUS Verb (CNI 1.1)' },
      { id: 'cni-gc-verb', title: 'GC Verb (CNI 1.1)' },
    ],
  },
  {
    id: 'cni-runtime-flow',
    title: 'CNI Runtime Flow',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'kubelet-and-cri-handoff', title: 'kubelet ↔ CRI Handoff' },
      { id: 'container-runtime-cni-invocation', title: 'Container Runtime CNI Invocation' },
      { id: 'sandbox-and-network-namespace', title: 'Sandbox & Network Namespace Setup' },
      { id: 'pod-ip-allocation-flow', title: 'Pod IP Allocation Flow' },
    ],
  },
  {
    id: 'ipam-plugins',
    title: 'IPAM Plugins',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'host-local-ipam', title: 'host-local IPAM' },
      { id: 'dhcp-ipam', title: 'dhcp IPAM' },
      { id: 'static-ipam', title: 'static IPAM' },
      { id: 'whereabouts-ipam', title: 'Whereabouts' },
      { id: 'aws-vpc-cni-ipam', title: 'AWS VPC CNI IPAM' },
      { id: 'calico-ipam', title: 'Calico IPAM' },
      { id: 'cilium-ipam', title: 'Cilium IPAM' },
    ],
  },
  {
    id: 'meta-and-chained-plugins',
    title: 'Meta & Chained Plugins',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'portmap-plugin', title: 'portmap' },
      { id: 'bandwidth-plugin', title: 'bandwidth' },
      { id: 'tuning-plugin', title: 'tuning' },
      { id: 'firewall-plugin', title: 'firewall' },
      { id: 'sbr-plugin', title: 'sbr' },
      { id: 'vrf-plugin', title: 'vrf' },
    ],
  },
  {
    id: 'cilium-cni-deep',
    title: 'Cilium (CNI Deep)',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'cilium-architecture', title: 'Cilium Architecture' },
      { id: 'cilium-ebpf-data-path', title: 'eBPF Data Path' },
      { id: 'cilium-identity-model', title: 'Cilium Identity Model' },
      { id: 'cilium-network-policy-model-pointer', title: 'NetworkPolicy Model (Pointer)' },
      { id: 'cilium-host-firewall', title: 'Cilium Host Firewall' },
      { id: 'cilium-bpf-masquerade', title: 'eBPF Masquerade' },
      { id: 'cilium-kube-proxy-replacement', title: 'kube-proxy Replacement' },
      { id: 'cilium-bgp-control-plane', title: 'Cilium BGP Control Plane' },
      { id: 'cilium-egress-gateway', title: 'Cilium Egress Gateway' },
      { id: 'hubble-pointer-stage15', title: 'Hubble (Pointer)' },
    ],
  },
  {
    id: 'calico-cni-deep',
    title: 'Calico (CNI Deep)',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'calico-architecture', title: 'Calico Architecture' },
      { id: 'calico-bgp-mode', title: 'Calico BGP Mode' },
      { id: 'calico-vxlan-mode', title: 'Calico VXLAN Mode' },
      { id: 'calico-ipip-mode', title: 'Calico IPIP Mode' },
      { id: 'calico-data-plane-options', title: 'Data Plane Options (iptables, eBPF, nftables, VPP)' },
      { id: 'calico-typha', title: 'Typha' },
      { id: 'calico-felix', title: 'Felix' },
      { id: 'calico-network-policy-model-pointer', title: 'NetworkPolicy Model (Pointer)' },
      { id: 'calico-egress-gateway', title: 'Calico Egress Gateway' },
    ],
  },
  {
    id: 'flannel-and-other-overlay-cnis',
    title: 'Flannel & Other Overlay CNIs',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'flannel-vxlan-backend', title: 'Flannel VXLAN Backend' },
      { id: 'flannel-host-gw-backend', title: 'Flannel host-gw Backend' },
      { id: 'flannel-wireguard-backend', title: 'Flannel WireGuard Backend' },
      { id: 'weave-net', title: 'Weave Net' },
      { id: 'kube-router', title: 'kube-router' },
    ],
  },
  {
    id: 'antrea-cni',
    title: 'Antrea',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'antrea-architecture', title: 'Antrea Architecture' },
      { id: 'antrea-flow-visibility', title: 'Antrea Flow Visibility' },
      { id: 'antrea-multi-cluster', title: 'Antrea Multi-Cluster' },
      { id: 'antrea-network-policy', title: 'Antrea NetworkPolicy Extensions' },
    ],
  },
  {
    id: 'kube-ovn-cni',
    title: 'Kube-OVN',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'kube-ovn-architecture', title: 'Kube-OVN Architecture' },
      { id: 'kube-ovn-subnet-and-vpc', title: 'Subnet & VPC Model' },
      { id: 'kube-ovn-underlay', title: 'Kube-OVN Underlay' },
    ],
  },
  {
    id: 'multi-network-on-pods',
    title: 'Multi-Network on Pods',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'multus-cni', title: 'Multus CNI' },
      { id: 'network-attachment-definitions', title: 'NetworkAttachmentDefinition CRD' },
      { id: 'kubernetes-multinetwork-kep', title: 'Multi-Network KEP' },
      { id: 'sriov-cni', title: 'SR-IOV CNI' },
      { id: 'bond-and-macvlan-cni', title: 'bond, macvlan, ipvlan CNI' },
    ],
  },
  {
    id: 'choosing-a-cni',
    title: 'Choosing a CNI',
    parentId: 'cni-deep-dive',
    children: [
      { id: 'cni-feature-comparison', title: 'CNI Feature Comparison' },
      { id: 'cni-performance-considerations', title: 'CNI Performance Considerations' },
      { id: 'cni-policy-support', title: 'NetworkPolicy Support per CNI' },
      { id: 'cni-on-managed-clusters', title: 'CNI on Managed Clusters' },
    ],
  },

  /* ---------- multi-cluster-networking ---------- */
  {
    id: 'multi-cluster-networking-overview',
    title: 'Multi-Cluster Networking Overview',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'cross-cluster-service-discovery', title: 'Cross-Cluster Service Discovery' },
      { id: 'cross-cluster-traffic-policy', title: 'Cross-Cluster Traffic Policy' },
      { id: 'flat-vs-non-flat-networks', title: 'Flat vs Non-Flat Networks' },
      { id: 'cluster-id-and-domain-separation', title: 'Cluster IDs & Domain Separation' },
      { id: 'cross-cluster-mtls-overview', title: 'Cross-Cluster mTLS Overview' },
    ],
  },
  {
    id: 'multicluster-services-api',
    title: 'Multicluster Services (MCS) API',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'mcs-api-overview', title: 'MCS API Overview' },
      { id: 'serviceexport-resource', title: 'ServiceExport Resource' },
      { id: 'serviceimport-resource', title: 'ServiceImport Resource' },
      { id: 'mcs-api-controllers', title: 'MCS API Controllers' },
      { id: 'mcs-api-implementations', title: 'MCS API Implementations' },
    ],
  },
  {
    id: 'submariner',
    title: 'Submariner',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'submariner-architecture', title: 'Submariner Architecture' },
      { id: 'submariner-broker', title: 'Submariner Broker' },
      { id: 'submariner-gateway', title: 'Submariner Gateway' },
      { id: 'submariner-globalnet', title: 'Globalnet' },
      { id: 'lighthouse-discovery', title: 'Lighthouse Discovery' },
    ],
  },
  {
    id: 'cilium-clustermesh',
    title: 'Cilium ClusterMesh',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'clustermesh-architecture', title: 'ClusterMesh Architecture' },
      { id: 'clustermesh-service-affinity', title: 'Service Affinity' },
      { id: 'clustermesh-shared-services', title: 'Shared Services' },
      { id: 'clustermesh-mtls-and-identities', title: 'mTLS & Identities Across Clusters' },
    ],
  },
  {
    id: 'istio-multi-cluster-deep',
    title: 'Istio Multi-Cluster (Deep)',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'primary-remote-vs-multi-primary', title: 'Primary-Remote vs Multi-Primary' },
      { id: 'east-west-gateway', title: 'East-West Gateway' },
      { id: 'cross-cluster-mtls-istio', title: 'Cross-Cluster mTLS' },
      { id: 'service-discovery-across-clusters-istio', title: 'Service Discovery Across Clusters' },
    ],
  },
  {
    id: 'linkerd-multicluster-deep',
    title: 'Linkerd Multicluster (Deep)',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'linkerd-service-mirror-controller', title: 'Service Mirror Controller' },
      { id: 'linkerd-gateway-load-balancer', title: 'Gateway Load Balancer' },
    ],
  },
  {
    id: 'skupper',
    title: 'Skupper',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'skupper-overview', title: 'Skupper Overview' },
      { id: 'skupper-vans', title: 'Virtual Application Networks' },
    ],
  },
  {
    id: 'consul-cluster-peering-multi-cluster',
    title: 'Consul Cluster Peering (Multi-Cluster)',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'consul-peering-architecture', title: 'Peering Architecture' },
      { id: 'consul-cross-cluster-services', title: 'Cross-Cluster Services' },
    ],
  },
  {
    id: 'liqo',
    title: 'Liqo',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'liqo-peering-model', title: 'Liqo Peering Model' },
      { id: 'liqo-virtual-node', title: 'Liqo Virtual Node' },
      { id: 'liqo-resource-reflection', title: 'Resource Reflection' },
    ],
  },
  {
    id: 'kuma-and-other-multi-zone-meshes',
    title: 'Kuma & Other Multi-Zone Meshes',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'kuma-multi-zone-deep', title: 'Kuma Multi-Zone (Deep)' },
      { id: 'kilo-and-wireguard-mesh', title: 'Kilo & WireGuard Mesh' },
    ],
  },
  {
    id: 'multi-cluster-dns',
    title: 'Multi-Cluster DNS',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'external-dns-multi-cluster', title: 'ExternalDNS Across Clusters' },
      { id: 'dns-discovery-across-clusters', title: 'DNS Discovery Across Clusters' },
      { id: 'mcs-dns-spec', title: 'MCS DNS Spec' },
    ],
  },
  {
    id: 'multi-cluster-load-balancing',
    title: 'Multi-Cluster Load Balancing',
    parentId: 'multi-cluster-networking',
    children: [
      { id: 'global-server-load-balancing', title: 'Global Server Load Balancing' },
      { id: 'geo-anycast-pointer', title: 'Geo-Anycast (Pointer)' },
      { id: 'k8gb-multi-cluster-gslb', title: 'K8GB Multi-Cluster GSLB' },
    ],
  },
])
